### ISSUE TITLE
Python version policy

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#10103]
In response to #10097, I think we should pick what Python versions we want to support for running mach and other scripts. (Python 2.7.11 and 2.7.0 can be considered the same in terms of language/stdlib features, but 3.5.x and 3.4.x are different.)

If we want to support more than one (especially 2.x vs 3.x) we should have CI for each of them, since it’s very easy to regress. This introduce non-negligible CI complexity, and IMO brings very little value.

If we pick one I’d be ok with 3.x, but some things may still need porting. 2.7 on the other hand is not going away. https://caremad.io/2015/04/a-year-of-pypi-downloads/ is almost one year old now, but shows only 5~6% of PyPI download made with Python 3. ["End of life" for 2.7](http://legacy.python.org/dev/peps/pep-0373/) has been moved 5 years to 2020, but I’m skeptical that it will not still be widely used then.

**Comment by SimonSapin** [comment]
CC @larsbergstrom @Ms2ger @jdm @frewsxcv

**Comment by Ms2ger** [comment]
We depend on a lot of mozbase/wpt stuff that's py2 only. I've been poking at making those py3-compatible every now and then, but that's not a small task. For now I'd stick to requiring py2.7. (We could try to ensure we use the `__future__` imports that are available, though.)

**Comment by frewsxcv** [comment]
If I were to start a project today, I'd use Python 3. That said, I'd vote to stick with Python 2.7. It's supported until 2020 and moving to Python 3 will result in virtually no benefits to Servo itself.

**Comment by KiChjang** [comment]
Thing is, wer're going to eventually need to migrate over to Python by 2020, so it's just a matter of time that we need to rewrite our Python code to be 3.x compliant.

**Comment by aneeshusa** [comment]
I'd vote to support Python2.7 for all existing scripts, but require both Python2.7 and Python3 support for all new scripts.

In terms of CI, the buildbot machines all currently have Python 3.4 for their Python3 since they're on Ubuntu 14.04 Trusty; I believe that newer Ubuntu releases have Python 3.5, which is scheduled to become the default system Python in 16.04, the next LTS.

The increased CI complexity IMO is just another reason to start migrating existing code to Python 3.x now; since it's going to take a lot of time, it's better to start now than sometime in 2019 and try to rush everything through. I don't think rewriting everything in another language would be easier or take less effort.

**Comment by mdboom** [comment]
Having looked at the code through `python-modernize`, this doesn't look like too much of a large project.  Though as noted above, a number of the dependencies are also not Python 3.x compatible.  Would this still be welcome as a pull request?  I'm looking for an easy first project.

I'd suggest converting to cross-compatible 2 and 3 code first rather than leaping straight to 3 only, even though testing multiple CI configurations does add complexity.  I think if you plan to sunset 2.x within a reasonable time, though, hopefully some of the complexity can be contained.

**Comment by SimonSapin** [comment]
I opened this issue in order to have a somewhere to discuss and to point people to, but I don’t think it’s worth spending much time on this, at least until all dependencies support Python 3 themselves.

**Comment by nox** [comment]
@SimonSapin Is there anything to do here?

**Comment by SimonSapin** [comment]
Not really. The status quo for us is 2.7 (which is not going away, even in 2020), and I think we should not spent too much time worrying about Python 3.
