### ISSUE TITLE
embedding shared lib no longer linkable

### ISSUE THREAD

**Issue by zmike** [servo/servo#10130]
```
undefined reference to `eglDestroyImageKHR'
undefined reference to `eglCreateImageKHR'
```

cc @larsbergstrom @pcwalton @glennw @jdm

**Comment by larsbergstrom** [comment]
It looks like this is because in https://github.com/servo/rust-egl/tree/master/src, somebody checked in the results of rust-bindgen code output from running over EGL, with settings to statically link against these functions, rather than checking and attempting to load them dynamically.

**Comment by larsbergstrom** [comment]
It looks like these stubs are unused by any of the calling modules in Servo (glutin-app, layers, servo-skia, or azure). It doesn't cause a problem on other platforms without these functions because the linker is probably discarding the bindings before attempting to do the final resolution.

I don't want to push a breaking semver revision through by removing them, so I'll just change them to use `eglGetProcAddress` and bump it.
