### ISSUE TITLE
Jumpiness involving transitions on border, inline-block, and whitespace (affects Twitter)

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#10200]
Minimal test case:
```html
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8">
    <style>
    #a {
        border: 0 solid;
    }
    #a:hover {
        border-bottom-width: 4px !important;
    }
    </style>
    </head>
    <body>
    <div style="display: inline-block; width: 33.3333%;"></div>
    <div style="display: inline-block; width: 66.66%;">
        <div id=a style="transition: all .15s ease-out;">Move your mouse here</div>
    </div>
    </body>
    </html>
```
This causes jumpiness on Twitter.

It's related to the whitespace. Seems that we aren't calling `strip_leading_whitespace_if_necessary` sometimes when we should be.

cc @mbrubeck since you've been chasing down inline incremental reflow bugs

**Comment by mbrubeck** [comment]
On initial layout, the whitespace between the first two divs is correctly compressed to a single space character.  But then because it is the last fragment on its line, `strip_trailing_whitespace_from_pending_line_if_necessary` strips it down to an empty string.  If a subsequent reflow happens that does not rebuild flows, the stripped whitespace is never restored.  (The code to restore it is in `Fragment::merge_with`, which is never called because this fragment doesn't have any compatible neighbors to merge with.)
