### ISSUE TITLE
Remove CompositorThread struct?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10261]
This now unconditionally wraps `IOCompositor`. (\o/)

**Comment by mbrubeck** [comment]
CC #11339

**Comment by mbrubeck** [comment]
This code can be removed:  https://github.com/mbrubeck/servo/blob/master/components/compositing/compositor_thread.rs#L286-L296

and the [code that calls it][1] can call `IOCompositor::create` instead, and store an `IOCompositor` directly instead of as a boxed trait object.

[1]: https://github.com/mbrubeck/servo/blob/e0addae51c6ecacd474e501da06f647ca9d96dc0/components/servo/lib.rs#L171-L185

**Comment by talklittle** [comment]
I will take a shot at this issue!

**Comment by ConnorGBrewster** [comment]
@talklittle have at it!

**Comment by ConnorGBrewster** [comment]
@talklittle also #11443 took care of removing the boxed trait object, so you do not need to worry about that.
