### ISSUE TITLE
Implement support in Servo for all standardized CSS properties that Gecko supports

### ISSUE THREAD

**Issue by bholley** [servo/servo#10408]
For the Stylo project, we're trying to integrate Servo's next-generation CSS engine into Gecko. One requirement for this project is to add support for all the style properties that Gecko supports and Servo does not.

This is a meta-bug. There's a lot of work to do here, so we don't expect support for every CSS property to land in the same PR or be authored by the same person.

The current master-list of all the properties supported by both engines is at [1].

Gecko supports some non-standard properties - specifically the properties with the |-moz| prefix, along with the ones in the "XUL" style-struct. We'll need to do something about these properties eventually, but let's not worry about them for now.

The CSS property implementation in servo is located at components/style/properties.mako.rs. This file is Mako template, which means that it gets run through a python program first. This spits out a bunch of Rust code, which then gets compiled. You can find the generated rust code in somewhere like: target/debug/build/style-5f35851704bc359e/out/properties.rs (the hash will generally differ, and |debug| will be |release| for release-builds).

Once you get the hang of this file, there should be enough examples to figure out how to add new properties. The easiest ones are probably keyword properties, which are labeled with PARSE_VALUE and H | K in [1].

When you start working on a property, mark it in the spreadsheet so that nobody duplicates work. One support for that property lands, mark it in the spreadsheet, rinse, and repeat! 

[1] https://docs.google.com/spreadsheets/d/1pSw2SjNxXZAQ19SAuNKcs5u4S7Zkc1ebEOkSP4oITUQ/edit#gid=257952899

**Comment by bholley** [comment]
CC @mauricioc, who was interested in helping out on Stylo. This would be a fantastic way to help. :-)

**Comment by bholley** [comment]
CC @larsbergstrom for suggestions on how to make this more contributor-friendly.

CC @SimonSapin for a heads-up on the incoming PR-storm. :-)

**Comment by SimonSapin** [comment]
I think you mean “support” in the `style` crate: parsing, serializing, computed values, etc. Let’s call this style-system support.

But usually talking about “supporting” a CSS property means implementing it all the way: doing all the layout and painting and other things that it involves. Let’s call this full support. In that sense, yes we want Servo to fully support everything but that’s a much bigger scope than I think you had in mind :)

A important aspect of CSS is fallback:

```css
body {
  background-image: url(gradient.png);
  background-image: conic-gradient(...);
}
```

If both declarations are parsed in a particular browser, the latter wins and "hides" the former. But if `conic-gradient(...)` is a parse error, that declaration is considered invalid and ignored, and the earlier one applies. It’s to enable this kind of fallback that it’s important to not parse properties or values that are not supported. It’s even more important with [`@supports` conditional rules](https://drafts.csswg.org/css-conditional/#at-supports) where "is this declaration parsed" is literally a test for "is this feature supported".

https://drafts.csswg.org/css2/syndata.html#unsupported-values
https://drafts.csswg.org/css-cascade/#conform-partial

What this means to us is that we want a different set of properties *and values* to be parsed for Servo and for Stylo/Gecko.

It’s possible (and we often do it for new / incomplete stuff) to have style-system support for a property or value but inhibit parsing with a feature flag. But then the rest of the browser (e.g. layout code) still has to deal with the corresponding data structures like new variants in an `enum`.

Maybe it would be better to completely separate the properties and values definitions for Servo and Stylo/Gecko? And split them from the rest of the style crate: cascade, tree traversal, etc could stay shared/generic.

**Comment by bholley** [comment]
That's a great point. I'll investigate possible solutions here tomorrow.

**Comment by SimonSapin** [comment]
Gecko has a `layout/style/test/property_database.js` file that contains a lot of data about each CSS supported property, in particular some strings that should and should not parse as valid values for a given property. Some of the Mochitest-based tests in `layout/style/test/*.html` are based on that file.

@bholley and I discussed importing some of these tests into Servo. We’d make it so that we can track what is passing or failing per property, which would give us a way to see what’s left to implement and distribute that work between potentially many contributors.

This would be either either:

* Tests mostly in their current form, maybe with testharness.js instead of Mochitest.
* Or as unit tests in the style crate. This may require rewriting `property_database.json` in JSON format or similar.

The latter would allow significantly shorter build times (not rebuilding the `script` crate) for every code change in the usual [change, recompile, test] cycle, but make it harder to merge changes when `property_database.js` is updated on the Gecko side.

Thoughts?

CC @cpeterso

**Comment by Ms2ger** [comment]
Unfortunately `property_database.js` is very much code, not just data. We'd need to rewrite it quite significantly to fix that. I do think it would be valuable to try to do that, though, and update Gecko's tests to use the plain data file.

**Comment by SimonSapin** [comment]
testharness.js tests could use the JS file as code-more-than-data, right?

**Comment by Ms2ger** [comment]
Yeah, but having a unit test would be great too

**Comment by bholley** [comment]
I think it would be valuable to move as much testing we can into style unit tests. This will help long-term with sharing the style system, because it will keep the testing of this functionality close to the implementation, rather than further away in the different consumers.

If it would really be easier to just have all of this information in a rust file, it might be fine to just fork property_database.js for now, and just have somebody manually watch it for changes in the near term. If Stylo succeeds, we can just make the rust file the canonical properties database and delete property_database.js.

I'm fine with doing a data file too though - whatever's less work overall.

**Comment by SimonSapin** [comment]
Just to make this info more discoverable:

In Rust’s default test harness, normally one test is created for one Rust function with a `#[test]` attribute. But for html5ever (Servo’s HTML parser) we’ve already used it to dynamically generate thousands of tests based data files. This is discussed in https://internals.rust-lang.org/t/test-and-external-test-harnesses/3145

If we’re doing this here (as opposed to using wptrunner like for Servo’s reftests and testharness.js tests) we’ll need some *other* data file to track which tests are known to fail (because something is not implemented yet).

**Comment by nox** [comment]
I think we can say this has been done.
