### ISSUE TITLE
Implement Blob URLs

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10539]
*This is not an easy bug.*

This will need integration with the URL parser.

**Comment by jdm** [comment]
Please note, this is part of a GSoC project and anyone who wants to work on this should talk to me before doing anything.

**Comment by bpowers** [comment]
hi @jdm, did this end up as part of an accepted GSoC project?

**Comment by jdm** [comment]
It did!

**Comment by izgzhen** [comment]
Just about to file an issue and found this one :D. Can someone help me to label it as assigned?

And some other related info:

* Spec: https://w3c.github.io/FileAPI/#url
* GSoC project home: https://github.com/izgzhen/gsoc-file-support, issue #10778 and issue #11131
* Ping the mentor @Manishearth

**Comment by izgzhen** [comment]
I found a problem regarding the implementation: https://w3c.github.io/FileAPI/#requestResponseModel. Here it mentions the model of "request". However, first it sounds a pretty counterintuitive thing to think about how to handle request in a browser; second, as I observed, in current implementation we will somehow *intercept* the `LoadData` message in `resource_thread.rs`'s `CoreResourceManager::load` based on the url scheme and dispatch to some special loaders like `about_loader` and `file_loader`.

I am proposing to handle `blob:` in a similar  way, however, we still don't fix the GET method problem (as specified in the spec). That is to say, our model is more like somehow internalize the "request" (which has headers, method as protocol says) into a "load" one.

**Comment by Manishearth** [comment]
> somehow intercept the

Well, there's already a switch on a scheme in both http_loader and fetch, we just add an entry to that. It's possible to filter on GET, and I think XHR does this for us anyway.

**Comment by izgzhen** [comment]
Some experimental code:

https://github.com/izgzhen/servo/tree/blob-loader and https://github.com/izgzhen/servo/tree/url-interface-mock (the latest commit)

Some problems:

1. Where to put Blob URL Store? Currently I prefer to manage it under `CoreResourceManager`, and accessible through message interface from script thread.
2. And the above question will determine how loader will communicate with the Blob Store. Since the loader is called directly in `core_resource_thread`, so we can directly call it with load requests if we choose the example impl above.
3. URL origin check (currently I `unicode_serialization` the origin and do a simple comparison, I thought we have already better checking logics for this somewhere but I have not yet try to find it for now).

And finally the `GET` method problem,  I inspected some *dispatch on `scheme`* code (in `http_loader` etc.), but not yet found anything particular interesting. Will track more in coming days.

**Comment by jdm** [comment]
I think @Manishearth meant switching on the scheme in `resource_thread.rs`, not `http_loader.rs`.

**Comment by Manishearth** [comment]
Yeah, basically.

> Where to put Blob URL Store? Currently I prefer to manage it under CoreResourceManager,

CRM seems fine for now. FileManager is also okay with me

>  and accessible through message interface from script thread.

Does script ever need to directly fetch a blob URI? I thought we'd only have to think about HTTP and XHR loads on blob: uris, and switching in resource_thread will fix that (for XHR, you can add a similar switch in fetch, this is already specced)

> so we can directly call it with load requests if we choose the example impl above.

yep. _might_ need to be spawned in a temporary thread or loaded in the file manager thread event loop to avoid the resource task getting clogged, since there's an IPC copy involved.

> URL origin check (currently I unicode_serialization the origin and do a simple comparison,

Fetch currently checks if `o.ascii_serialization()` is equal. XHR does the same with "as_str". I'm not sure why a simple PartialEq check on the `url::Origin` won't work, though.

**Comment by Manishearth** [comment]
It depends which of these two you need. https://html.spec.whatwg.org/multipage/browsers.html#same-origin . "same origin-domain" is something you'd have to implement manually.

**Comment by Manishearth** [comment]
We should really start using typed origins everywhere

**Comment by izgzhen** [comment]
I think it would be convenient to implement the same-origin check inside `Origin`. Also, derive serialize/deserialize for it. (Oddly `url` doesn't derive it now, and does't use `#[derive(Ser...)]` feature either)

**Comment by Manishearth** [comment]
the same-origin check is already inside Origin :smile:

**Comment by Manishearth** [comment]
Why are we using strings at all though? You can obtain typed origins from typed URLs, and we have typed URLs.

**Comment by izgzhen** [comment]
> Does script ever need to directly fetch a blob URI? 

No, the communication between script thread and store the `creation` and `revocation` api.

**Comment by Manishearth** [comment]
Well, the file thread will handle creation. We only need a revocation message.

**Comment by izgzhen** [comment]
Check just by `urlA.origin() == urlB.origin()`?! It looks more like structural equivalence to me (though it looks like that the spec version "same-origin" is a structural one in a typed, or normalized context).

And for the "creation", it is to create a URL from existing `Blob`, so it looks like not really related to current file manager thread (although put the store under its management would leverage clogging problem you mentioned).

**Comment by Manishearth** [comment]
same-origin _is_ structural :smile: . 

Well, the existing blob is probably in the file manager thread anyway. But yeah, that depends on your caching strategy, and which in-memory data goes where. The file manager thread will be creating _some_ blob URIs at any rate.
