### ISSUE TITLE
Implement the :placeholder-shown pseudo class

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10561]
At the moment, it's plain black.

It needs to be `opacity: 0.54`.

Relevant:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1069012
- https://bugzilla.mozilla.org/show_bug.cgi?id=556145
- https://lists.w3.org/Archives/Public/www-style/2013Jan/0283.html

(browserhtml P2 as I think we can work around this for now)

**Comment by SimonSapin** [comment]
Selectors 4 defines a `:placeholder-shown` pseudo class.

https://drafts.csswg.org/selectors/#placeholder
https://github.com/whatwg/html/pull/1354

Note that it applies to the entire `input` or `textarea` element (when a placeholder exists and is being shown), not just the placeholder, so you may want to use the `color` property rather than `opacity` (since the latter would also affect borders).
