### ISSUE TITLE
Use the document base url when resolving script URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10578]
According to [the specification](https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-script) (step 17.4), we need to be [using the base URL](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-url). This means calling `document.base_url()` instead of `window.get_url()` as the code currently does.

Code: `components/script/dom/htmlscriptelement.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element/fetch-src/alpha/base.html`

**Comment by Liamsi** [comment]
If I do `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element/fetch-src/alpha/base.html` the existing test fails in the rendered servo window (`expected "beta" but got "alpha"`) in both cases (using either `document.base_url()` or, like before, `window.get_url()` in `components/script/dom/htmlimageelement.rs`), is this the expected behaviour (on the command-line I see `1 ran as expected. 0 tests skipped.`)? Shouldn't the code be  `components/script/dom/htmlscriptelement.rs`? (I'm completely new to servo)

**Comment by Liamsi** [comment]
If I change the code in `htmlscriptelement.rs` instead, i get a failing test. Do I need to update the [expected outcome](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) [here](https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/semantics/scripting-1/the-script-element/fetch-src/alpha/base.html.ini)?

**Comment by jdm** [comment]
Yes, you were right and I made a mistake in the original issue description. It looks like you've figured it out though :)

**Comment by Liamsi** [comment]
Cool, thanks for the feedback. You can assign me the other open and not assigned issues which are very similar to resolve (currently #10577, #10576).
