### ISSUE TITLE
Implement the :valid and :invalid pseudo-classes

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10781]
Blocks #2185, #2968.
- Spec: https://html.spec.whatwg.org/multipage/#selector-invalid.
- Code: `components/style/selector_impl.rs`, `components/layout/wrapper.rs`, `components/script/dom/element.rs`.
- Test: `html/semantics/selectors/pseudo-classes/valid-invalid.html`, `dom/nodes/Element-closest.html`.

**Comment by shssoichiro** [comment]
I'd like to claim this one.

**Comment by shssoichiro** [comment]
Do we have existing methods for checking the validity of an input, e.g. for form submission?

**Comment by jdm** [comment]
Hmm, the problem here is that there is a student group currently working on implementing form input validation. The work to implement the pseudo-class is separate from that, but difficult to test without the actual validation present. I'd like to hold off on this until the necessary pieces are in place.

**Comment by tipowol** [comment]
@highfive assign me
