### ISSUE TITLE
[regression] hittest issue - iframe in the background take precedence over foreground elements

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11108]
```html
<style>
  iframe, div {
    display: block;
    top: 0;
    left: 0;
    position: absolute;
  }
  iframe {
    border-width: 0;
    width: 100%;
    height: 100%;
  }
  div {
    width: 100px;
    height: 100px;
    background: red;
  }
</style>
<iframe src="http://example.com"></iframe>
<div onclick="console.log(42)"></div>
```

**Comment by paulrouget** [comment]
I thought we could work around that, but it's messing up with the overlay code we use in browserhtml.

If this is too hard to solve, I can try harder to work around this.

/cc @pcwalton

**Comment by pcwalton** [comment]
Grrrrrrrr. I think I'm going to put up a whiteboard next to my desk counting the number of times this has regressed.

**Comment by paulrouget** [comment]
I think it's also related to the overflow:scroll PR.

**Comment by metajack** [comment]
Will @asajeffrey's new webdriver stuff allow us to make a test for this?

**Comment by asajeffrey** [comment]
At the moment, I'm afraid not, because the relevant bit of webdriver is https://www.w3.org/TR/webdriver/#actions, which is currently not implemented in https://github.com/jgraham/webdriver-rust/blob/master/src/command.rs#L52. @jgraham would know if there's a deep reason for this.

**Comment by jgraham** [comment]
The deep reason is "this stuff is hard and, for some odd reason, I have ended up writing the spec for it (which is not yet done) despite having very little relevant domain experience". Since there is no spec there is also no implementation yet (although I have a branch of the protocol library which matches the current spec pre-drafts, so one *could* start implementing the semantics in servo, if one really wanted).

**Comment by asajeffrey** [comment]
I added an issue for adding webdriver action support: #11254. We can decide whether to push forward on this, or wait until the spec stabilizes.

**Comment by metajack** [comment]
I suspect this is a case where our implementation would help push the spec forward, no? This is obviously not immediately critical, but we should get this done in Q3 if possible.

**Comment by pcwalton** [comment]
So per your test case this doesn't seem to be a regression (although it may well have been exposed by some enhancement to WR)—rather, it's a design issue. The problem is that WebRender iterates through *scroll layer* trees to do hit testing, whereas it really should be iterating through *display items*. There are two ways to fix this: (a) move the display item-based hit testing code to WebRender; (b) move the layer-to-point-translation code to Servo.

After experimenting with (a), I'm more inclined to pursue strategy (b). That's because we would have to duplicate the hit testing code into WR to keep both paths working, and we'd have to involve WebRender for hit tests even when those hit tests are not done on rendered content (e.g. when initiated by script). The way to make this work is to replace `TranslatePointToLayerSpace` with a function like `GetLayerTreeForHitTest()`. This would return the scroll offsets and transforms applied to every layer. That tree would be sent from the compositor to the constellation, and the mouse events would be routed (unconditionally) to the script task for the root pipeline. If they hit an iframe, they would be forwarded per the event forwarding logic we already have, and the constellation would be able to consult the stored layer tree information to be able to translate points appropriately through iframe layers.

How does this sound, @glennw?

**Comment by glennw** [comment]
@pcwalton That suggestion sounds good to me. Long term, I think it makes sense to have it in WR and take advantage of the culling trees for performance reasons, but that's certainly something we could consider later - let's just get it working correctly for now.

**Comment by pcwalton** [comment]
OK, cool. I'll do it that way then.

**Comment by paulrouget** [comment]
Again - if this is too much work, we can work around that in browserhtml.
