### ISSUE TITLE
codegen-units causes performance problems

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#11102]
See rust-lang/rust#33522, for example. codegen-units is well known to cause performance problems due to missed IPO such as inlining.

Can we enable this only on bots?

**Comment by pcwalton** [comment]
I've seen `mem::forget` not being inlined, and gw has seen performance problems in euclid suspected to be caused by this.

**Comment by mbrubeck** [comment]
Now that Cargo supports `$RUSTFLAGS`, we could add `-C codegen-units=4` to RUSTFLAGS in the buildbot environment, instead of putting it in the Cargo manifests.

**Comment by mbrubeck** [comment]
cc #9987

**Comment by metajack** [comment]
If this really causes big performance issues, this is likely going to inflate our test times even as it saves our build times. The only way to know whether this is worth it in automation is to try it and see.

**Comment by mbrubeck** [comment]
https://github.com/servo/servo/pull/9987#issuecomment-196411825 found no major change to test times.  However, Servo performance may not be the dominating factor in our test runs.

**Comment by larsbergstrom** [comment]
I'm OK with disabling `codegen-units`. As I mentioned on IRC, though, if we do that then I'd like to do so consistently so that what we're developing on is what we're testing and what we're (eventually) shipping. I would be really iffy about "just using `codegen-units`" in CI to cut down the build time, as we've had concurrency issues and even crashes that were specific to the optimization level.

**Comment by glennw** [comment]
I tested the mean frame time in the backend WR2 prototype thread on one of the stress tests I profile with:

codegen-units: 8.9ms
without: 6.2ms

So it does cause a dramatic performance issue in the WR2 prototype - which is unfortunate, since the build times are very noticeably faster with codegen-units :(
