### ISSUE TITLE
Webrender: WebGL fast path does not work on Mac

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#11138]
On mac webrender uses OpenGL 3.2 Core.
The WebGL spec conforms to the OpenGL ES 2.0 API.
This causes an incompatibility and breaks webgl on mac when using webrender.

**Comment by metajack** [comment]
cc @glennw @pcwalton

**Comment by emilio** [comment]
This is a dupe of https://github.com/servo/servo/issues/10376, so one of them should be closed.

**Comment by ConnorGBrewster** [comment]
Can we close this after #11744?

**Comment by emilio** [comment]
Sort of, I'd prefer to leave this open until we make the fast path work.

**Comment by nox** [comment]
@emilio Can we close this now?

**Comment by jdm** [comment]
I'm pretty sure we still don't use a fast path on macOS.

**Comment by nox** [comment]
@emilio Could you describe what needs to be done to get this?

**Comment by emilio** [comment]
https://github.com/emilio/rust-offscreen-rendering-context/issues/82 contains most of the details, I think we need to emulate a compat context (what WebGL wants) but using a core context, so that resources can be shared with WR.

The alternative, I think, is using shared textures (using `IOSurface` on Mac) as the backing storage for the WebGL stuff, and teach WR about those. WR probably knows or has a hook to interact with these for Gecko I suspect.

I'm not sure which of the two solutions is the right long-term architecture (maybe none?), I'd probably talk with @jdashg (`jgilbert` on IRC), about that, I don't know all the trade-offs and pitfalls, and I don't know if WebGL 2 would change those.

**Comment by jdm** [comment]
This was fixed by #24482.
