### ISSUE TITLE
Add a tidy check for &Root arguments

### ISSUE THREAD

**Issue by jdm** [servo/servo#11137]
There's no benefit to using `&Root<T>` as a function argument instead of `&T`, and it's slightly more inefficient because of the extra dereferencing. We should have `tidy.py` report instances of this pattern.

Code: `python/tidy/servo_tidy/tidy.py`
Test: `python/tidy/servo_tidy_tests/rust_tidy.rs`, run `./mach test-tidy --self-test`

**Comment by mrmiywj** [comment]
@jdm 
I'll pick this up.

**Comment by KiChjang** [comment]
Go for it!

**Comment by mrmiywj** [comment]
Hi, I'm not sure how to continue on this issue.
Actually `tidy.py` is a python script to check whether the code is tidy. But check whether a argument of a function is `&Root<T>` is a compiler work, I think.
May the solution is like [check use](https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L438) here.
But I have no idea on how to determine whether this line is a function header, since it can be splited into several lines.
Any suggests?

**Comment by jdm** [comment]
I would suggest looking for `: &Root<`, which would limit the possible places that the syntax could be found.

**Comment by mrmiywj** [comment]
Sorry for that I've not read through `Root`'s source code. But, will `: &Root<` appear when one tries to declare a variable? If not, I do think it's a good solution.

**Comment by jdm** [comment]
It could, but it would be very rare and it would be inefficient for the same reason that we are warning about it here. Therefore, I don't think it's a problem :)

**Comment by Wafflespeanut** [comment]
As a sidenote, tidy already complains about the usage of `&Vec` and `&String`

**Comment by mrmiywj** [comment]
@Wafflespeanut Thx!
