### ISSUE TITLE
Update EventHandler.webidl

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#11158]
The WebIDL has more events defined on it now. Also, there is a new `DocumentAndElementEventHandlers` interface that is supposed to be defined on `Document` and `HTMLElement`.

Spec: https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers, https://html.spec.whatwg.org/multipage/webappapis.html#windoweventhandlers, https://html.spec.whatwg.org/multipage/webappapis.html#documentandelementeventhandlers
Code: `components/script/dom/webidls/EventHandler.webidl`, `components/script/dom/webidls/HTMLElement.webidl`, `components/script/dom/webidls/Document.webidl`

**Comment by s-baldrick** [comment]
@KiChjang 
I'd like to have a go at this (though I'm unlikely to get started before Saturday).

Greetings,
Piotr

**Comment by jdm** [comment]
Great!

**Comment by Ms2ger** [comment]
Should we implement `onfoo` attributes where we never dispatch a `foo` event?

**Comment by jdm** [comment]
On one hand it's not great for feature detection. On the other hand, it's _really_ easy to forget to add them when implementing code that dispatches the appropriate event, and it leads to frustrating and confusing debugging sessions. I lean towards adding the handlers for that reason.

**Comment by s-baldrick** [comment]
Hi, I've done a couple patches for this - https://github.com/s-baldrick/servo/tree/11158, and now I am trying to come up with some tests, although I am not sure what will be a sensible way of going about it since not all of these events will be triggered. I guess asserting if setting an event handler does not fail could be one way, but then they all get set in the same way, so testing for this might not bring much to the table. Do you have some suggestions about this?

**Comment by KiChjang** [comment]
You can actually open a PR right now, and I'll do a try run and see which tests it'll break. Some of our WPT tests are marked as FAILING, but after defining these events, I'd expect plenty of them to PASS.

**Comment by s-baldrick** [comment]
Cool, I'll open it this evening, as I am at work right now.
