### ISSUE TITLE
Create a test for #11264

### ISSUE THREAD

**Issue by jdm** [servo/servo#11281]
It's not clear to me why it's difficult to test. We had a reproducible test case, and the code changes seem to be working around a particular situation that can occur. Why can't we reverse-engineer the conditions that make that code be executed?

cc @KiChjang

**Comment by KiChjang** [comment]
I'm really not sure why the logs show that there was a `.borrow()` call from `update_href` before. I double-scanned and triple-scanned `htmlanchorelement.rs` before #11264 was merged, and I still don't see any `borrow()` at all in `update_href`.

I wasn't able to reproduce it on my computer since I'm using Linux and I hit a `FontCache` panic.

**Comment by jdm** [comment]
I have not been able to reproduce #11261 yet from 904e9ea17ce56976cd2e94a130dff916c6746b8f. The panic backtrace reported by @paulrouget doesn't make sense at all, any @KiChjang wasn't able to reproduce the failure so the fix was produced on faith. I would like to properly figure out the actual problem we solved; @paulrouget can you revert to the revision in which you observed the panic and get a proper backtrace on a debug build?

**Comment by nox** [comment]
Was this done?

**Comment by jdm** [comment]
It was not done.

**Comment by jdm** [comment]
This will never be done.
