### ISSUE TITLE
Add GPOS and GSUB support to the Latin text shaping fast path

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#11310]
#11273 added a fast path but it only supports the TrueType 'kern' table.  Add support for fonts that include basic kerning and ligation of Latin script using the OpenType GPOS and GSUB tables.

https://www.microsoft.com/typography/OTSPEC/GPOS.htm
https://www.microsoft.com/typography/OTSPEC/GSUB.htm

**Comment by mrobinson** [comment]
Hrm. I'm going to close this one, I think. GPOS and GSUB are part of OpenType shaping. If a font needs OpenType shaping we should likely be using HarfBuzz to do that instead of trying to roll our own approach. There's probably many speedups we can make to HarfBuzz shaping though! For now, let's just stick with our existing fast path.
