### ISSUE TITLE
Update referrer policy code to include new options

### ISSUE THREAD

**Issue by rebstar6** [servo/servo#11384]
**this issue should not be completed until the web platform tests are updated to include the new policies

See https://w3c.github.io/webappsec-referrer-policy/
Policy options in Servo currently are:
- No-Referrer
- No-Referrer-When-Downgrade
- Origin-Only
- Origin-When-Cross-Origin
- Unsafe-Url
- None (undefined)

(these are defined in components/msg/constellation_msg ReferrerPolicy enum)

These need to be updated to include "Origin" and "Same-Origin" instead of "Origin-Only". 

This is a followup to https://github.com/servo/servo/issues/10311 and associated PRs.

**Comment by rebstar6** [comment]
Test updates requested at:
https://github.com/w3c/webappsec-referrer-policy/pull/42#issuecomment-221373530
https://github.com/w3c/webappsec-referrer-policy/pull/19#issuecomment-221373347

**Comment by jdm** [comment]
According to https://github.com/w3c/webappsec-referrer-policy/pull/42#issuecomment-221558477, the fact that the specification ever said `origin-only` was a mistake and the value should be `origin`.

**Comment by nox** [comment]
Upstream PRs landed AFAICT, but given origin-only was wrong, is that ticket still relevant?

**Comment by rebstar6** [comment]
https://github.com/w3c/web-platform-tests/pull/3153 should make this issue do-able.

**Comment by aravind-pg** [comment]
I'd like to take this on. Looks like I essentially have to update the [ReferrerPolicy enum](https://github.com/servo/servo/blob/master/components/msg/constellation_msg.rs#L362), update the referrer logic [here](https://github.com/servo/servo/blob/master/components/net/http_loader.rs#L460-464), and finally update [these tests](https://github.com/servo/servo/blob/master/tests/unit/net/http_loader.rs#L1628-1832) appropriately?

**Comment by jdm** [comment]
That is correct!

**Comment by rebstar6** [comment]
@aravind-pg - forgot to mention, for this, and the other referrer policy stuff, there are wpt in 2 places. The ones referenced above should be pulled into servo, and will be at tests/wpt/web-platform-tests/referrer-policy. There are also what are basically copies of the iframe tests within these folders at tests/wpt/mozilla/tests/mozilla/referrer-policy because servo doesn't support pieces of how those tests were working. @jdm knows more of the run details, but those should be updated as well.

May be worth looking into updating the spec.src.json file in the mozilla folder to only include iframe tests, and regenerating rather than copy/pasting the test files, but I'll leave that up to you :)

Anyway, just occurred to me, so wanted to call it out. Thanks for taking over the referrer policy work!

**Comment by jdm** [comment]
That's a very good point! We should definitely look into generating the tests properly.

**Comment by aravind-pg** [comment]
All right! Took me a little while to figure out the concrete details but here's what I did:
- Updated the spec.src.json file (only in the main folder, not mozilla yet) to add the new "orirgin" and "same-origin" sections as present in W3C master's copy of spec.src.json.
- Generated the new test files, updated the manifest etc.
- Built servo in release mode and then ran the new tests in release mode, logging the output.
- Observed a bunch of timeouts (despite release mode, unless I did it wrong) and failures.
- Used the log output to update test expectations using `mach update-wpt`.

Does this sound OK? I was a bit surprised there were test failures, at least for "origin", because it's exactly the same thing as "origin-only". But then again those tests do look like they've changed a bit so I guess that shouldn't be so surprising.

If this all sounds good then I can push the commit that does this, and similarly another commit for the mozilla folder (separately to keep things easy to review).

Also, I'm not too sure what it means to include just the iframe tests in the [spec.src.json file in mozilla](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/referrer-policy/spec.src.json). Isn't it already just the iframe tests? All the worker tests etc. seem to be excluded afaict. Would appreciate clarification.

**Comment by jdm** [comment]
We should remove everything from https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/referrer-policy/spec.src.json#L372 except iframe-tag, which will avoid generating tests for any other types of requests.

**Comment by jdm** [comment]
And yeah, those steps do sound correct. Thanks!

**Comment by aravind-pg** [comment]
Great, thanks for the clairification :)

**Comment by aravind-pg** [comment]
I've been having some difficulty updating the test expectations in the mozilla folder. It looks like `mach update-wpt` does not really understand tests in those folder, which is not surprising since they don't completely follow the wpt file layout. To work around this I tried a dumb common-sense approach: just make a backup of the main `referrer-policy` folder, then use the original folder to update `spec.src.json` (i.e. add the new options and remove everything but iframe tests) and run `update-wpt`, copy the resulting updated folder to the mozilla folder, and finally restore the backup. 

There are two issues I'm running into here. First of all, it doesn't work, for some very weird reason -- I'm supposed to be seeing only 30 tests (those are the only iframe tests), yet I see all 1400+ tests, even with the updated `spec.src.json`. In other words `./generic/tools/generate.py` just doesn't seem to be working. Obviously I'm doing something wrong, but I'm not sure what. Second of all, if I'm doing this, then what even is the point of the mozilla folder? Won't it just contain a complete and redundant copy of (a subset of) the main tests? There won't be any differences at all, IIUC. @rebstar6, would dearly appreciate a description of your workflow around the mozilla folder, as well as a little more explanation about why it exists.

**Comment by jdm** [comment]
The tests in the mozilla folder are modifications of the original tests from referrer-policy, because the originals rely on features that Servo doesn't support yet.

**Comment by jdm** [comment]
What do you mean by `mach update-wpt does not really understand tests in those folder`, exactly? As long as the tests are present in the MANIFEST.json in tests/wpt/mozilla/meta, update-wpt should be able to update the metadata ini files as appropriate.

**Comment by aravind-pg** [comment]
Well I never. I just reset to a clean state and tried it again and it worked. Clearly messed something up the first time 😛 Oh well.

Anyway, I updated my PR (#11968) with the test updates and it should be ready for review now :)
