### ISSUE TITLE
body.style.overflow set/get doubles attribute's value

### ISSUE THREAD

**Issue by broesamle** [servo/servo#11448]
When setting `document.body.style.overflow = "hidden"`its value is doubled (`hidden hidden`) but should be a single `hidden`.

At first glance, it does, by contrast, not occur with `document.body.style.height`.

Minimal Example:
```
<!doctype html>
<html>
<body id="thebody">
</body>
<script>
    console.log("A: "+document.body.style.overflow);
    document.body.style.overflow = "hidden";
    console.log("B1: "+document.body.style.overflow);
    console.log("B2: "+document.body.getAttribute('style'));
    document.body.setAttribute('style','height:30px');
    console.log("C : "+document.body.getAttribute('style'));
    document.body.style.height = "40px";
    console.log("D1: "+document.body.style.height);
    console.log("D2: "+document.body.getAttribute('style'));
</script>
</html>
```
Output servo: 
```
A: 
B1: hidden hidden
B2: overflow: hidden hidden;
C : height:30px
D1: 40px
D2: height: 40px;
```
Output Firefox:
```
A: 
B1: hidden
B2: overflow: hidden;
C : height:30px
D1: 40px
D2: height: 40px;
```

**Comment by broesamle** [comment]
I'd be happy to have a look at it (since #10947 somehow depends on it) but I think it would be good, if somebody else could confirm the issue.

**Comment by jdm** [comment]
cc @SimonSapin for confirmation

**Comment by craftytrickster** [comment]
Just an educated guess, but I think this is due to the fact that https://github.com/servo/servo/issues/10933 hasn't been implemented yet. 

Even though I do not see `overflow` on the list of [shorthands](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties) at MDN, overflow does behave in a similar fashion, as it is a property that represents more than one value when set. (overflow-x and overflow-y). In fact, `overflow` is set inline, the following property declarations are sent in as parameters:

```
[OverflowX(Value(visible)), OverflowY(Value(T(visible)))]
```

When the aformentioned issue is implemented, maybe overflow has to be considered as "shorthand-like" as well.

**Comment by SimonSapin** [comment]
@craftytrickster is correct: `hidden hidden` is the generic serialization of the `overflow` shorthand (which expands to `overflow-x` and `overflow-y`). The solution is to have serialization code that’s specific to each shorthand (similar to how parsing code is specific).

**Comment by broesamle** [comment]
thank you for the clarification!

so this should fail
```
    document.body.style.overflow = "hidden";
    assert_equals(document.body.style.overflow,"hidden");
```

and this should pass:
```
    document.body.style.overflow = "hidden";
    assert_equals(document.body.style.overflow,"hidden hidden");
```
(and firefox is acually wrong with my minimal console output example above.

**Comment by SimonSapin** [comment]
@broesamle That’s what happens currently in Servo, but it’s a bug. So it’s not what *should* happen. Fixing the bug means implementing shorthand-specific serialization code.

**Comment by craftytrickster** [comment]
Looks like this can probably be closed
