### ISSUE TITLE
Make DOM methods taking a `*mut JSContext` unsafe

### ISSUE THREAD

**Issue by nox** [servo/servo#11485]
For example, `HTMLCanvasElement::GetContext`.

Files:
- components/script/dom/bindings/codegen/CodegenRust.py

**Comment by metajack** [comment]
The generated code should add "unsafe" to the function signature. This can be easily done by searching for `*mut JSContext` in function declarations and then modifying them. In some cases you may have to inspect the generated code for them, and then figure out how they are built up by the code generator in order to know where to inject "unsafe".

After that step, there will probably be a bunch of compile errors where code that was calling these functions was not in an unsafe block. That code will need to be wrapped in unsafe now.

**Comment by ab22** [comment]
I'm up for this.

**Comment by jdm** [comment]
@ab22 Go for it :) Ask questions about anything that's unclear.

**Comment by KiChjang** [comment]
Previous attempt was stalled in #11595.

**Comment by fflorent** [comment]
May I take this one? I am currently learning Rust and I made my first PR to servo lately.
Or should I leave it to someone who has never contributed to Servo? (something I can easily understand)

Florent

**Comment by KiChjang** [comment]
@fflorent Nope, go right ahead!

**Comment by jdm** [comment]
@fflorent Have you made any progress on this issue?

**Comment by fflorent** [comment]
@jdm Not yet, busy these last days. Jeez, already one month and I did quite nothing, sorry. 

I'll keep you informed of my progress next week-end. Unless this is important for you and you need to have it quickly (I wouldn't mind if you unassign me from this issue, I would understand).

Cheers,
Florent

**Comment by fflorent** [comment]
@jdm here is my progress:
https://github.com/servo/servo/issues/14096

Cheers!
Florent
