### ISSUE TITLE
<tr> border is not displayed

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11527]
![tborder](https://cloud.githubusercontent.com/assets/10187350/15686529/17b447b2-2771-11e6-9021-d91ef227213b.png)
```html
<!doctype html>
<html><body>
	<style>
		table{
			border-collapse: collapse;
		}
		tr{
			border: 1px solid black;
		}
	</style>
	<table>
		<tr><td>Lorem</td></tr>
		<tr><td>ipsum</td></tr>
	</table>
</body></html>
```

**Comment by gpoesia** [comment]
I'm taking a look at this.

**Comment by jdm** [comment]
@gpoesia Great! Please ask questions about anything that's unclear!

**Comment by gpoesia** [comment]
@jdm Alright, thanks! I managed to reproduce it and found the code in components/layout/table_row.rs which handles the "collapse" logic (if border-collapse is not "collapse" it works). Will keep investigating and ask if I get stuck :)

**Comment by metajack** [comment]
Border collapse is pretty difficult to figure out. You will probably want to have both Chrome and Firefox involved in testing, since the behavior across mainstream browsers does not always agree.

@pcwalton wrote the border collapse code, so if you have specific questions feel free to ping him.

**Comment by gpoesia** [comment]
Just giving some update on this. I found out that in the end of `TableFlow::bubble_inline_sizes`, all inline and `block_{start,end}` borders have their style set to `none`. If I manually set them to solid (all `block_start`, `block_end`, and the first inline borders, which correspond to the left and right extremities,) it works, so I assume the bug is indeed during the flow tree construction.

I think it's related to #8586, and the fix would be to correctly implement `CollapsedBorderProvenance::FromTableRow`, so that row borders descend to `<td>`s. If the borders are placed in `<td>`'s instead, it mostly works (aside from the left and upper edges of the table: that may be related, but collapsing inside the table works). @pcwalton does this make sense to you? Any tips on this from the top of your head? I'll try that this week.
