### ISSUE TITLE
Default font-size in <input> is not correct.

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11529]
Default font-size in Input like `<input type="text" value="123" style="font-family: Arial">` is smaller in Servo compared to Firefox and other browsers.
![fsize](https://cloud.githubusercontent.com/assets/10187350/15689836/1dd0caac-2781-11e6-966e-8fa66b11a491.png)

**Comment by KiChjang** [comment]
It looks to me that this can easily be fixed by changing `resources/user-agent.css` to use a bigger font on input elements, but I'm not 100% sure.

**Comment by mbrubeck** [comment]
We explicitly set the font size for inputs here:

https://github.com/servo/servo/blob/55b0bb027caba9ca4f3fb091c55a53c24380dccb/resources/servo.css#L11

The servo.css file contains "internal" styles for rendering things like form controls, since we don't have any support for native form widget.  I think these styles are arbitrary, not specified by any standard.

We currently use 0.7em for inputs, which computes to 11.2px by default.  Firefox renders at 13.333px by default, which might correspond to 0.8333em.

**Comment by Coder206** [comment]
I would love to as soon as I complete #11450

**Comment by jdm** [comment]
We'll leave this unassigned until someone says they're ready to start working on it :)

**Comment by taravancil** [comment]
I'll work on this! I'll let y'all know if I have questions along the way.

**Comment by jdm** [comment]
It's yours!
