### ISSUE TITLE
Image with height defined in % is not resized properly

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11723]
```
<!doctype html>
<html><body>
	<div style="height: 100px;">
		<img style="height: 100%" src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Skoda130Rally.jpg/256px-Skoda130Rally.jpg">
	</div>
</body></html>
```
![img](https://cloud.githubusercontent.com/assets/10187350/15985926/22906600-2ffc-11e6-9467-3e9fdc5d7337.png)

**Comment by metajack** [comment]
This is probably E-Easy, but marking it less easy until some guidance gets posted.

It looks like the width isn't been locked to the original aspect ratio, and perhaps it should be?

**Comment by jdm** [comment]
Sorry, the easy and less-easy tags don't belong until someone's actually verified that's the case and provided helpful guidance.

**Comment by mbrubeck** [comment]
[`ReplacedImageFragmentInfo::calculate_replaced_inline_size`][1] calculates the wrong width (“inline size”), because the image width depends on the container’s height (“block size”), but this function doesn’t know the container height so it just passes [`None`][2].

The container height, if available, is stored in the `block_container_explicit_block_size` of the [Flow][3] that contains the image fragment.

`Fragment::assign_replaced_inline_size_if_necessary` should be changed to take an additional argument, `container_block_size: Option<Au>` and pass this argument on to `ReplacedImageFragmentInfo::calculate_replaced_inline_size`.  Any code that calls this function should pass `block.explicit_block_containing_size()` as the value of this argument if the fragment is in a BlockFlow, or `flow.base.block_container_explicit_block_size` if the fragment is in some other type of flow.

[1]: https://github.com/servo/servo/blob/0cfae3a3e756c5719b5ab58dde9d0eacc7f197be/components/layout/fragment.rs#L487-L493
[2]: https://github.com/servo/servo/blob/0cfae3a3e756c5719b5ab58dde9d0eacc7f197be/components/layout/fragment.rs#L516-L518
[3]: http://doc.servo.org/layout/flow/struct.BaseFlow.html
[4]: https://github.com/servo/servo/blob/0cfae3a3e756c5719b5ab58dde9d0eacc7f197be/components/layout/inline.rs#L1371

**Comment by DarinM223** [comment]
Hi, can I work on this? Thanks!

**Comment by mbrubeck** [comment]
Sure!
