### ISSUE TITLE
Support new "armv7-android-linuxeabi" target triple

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#11921]
rust-lang/rust#33278 added a new Android target, `armv7-android-linuxeabi`.

In the near future, the existing `arm-android-linuxeabi` target (which Servo uses by default when building for Android) will be changed to use the ARMv5TE instruction set instead of ARMv7.  We will need to switch to the new target if we want to continue generating ARMv7 code (and linking to standard libraries built for ARMv7).

This will require finding and fixing any packages whose build scripts that assume the `$TARGET` used by Cargo and rustc is the same as the `$TARGET` needed for the C toolchain, for example [harfbuzz-sys](https://github.com/servo/rust-harfbuzz/blob/764f3e5a56a9557c13a7ac8c3c846ece884e3727/harfbuzz-sys/makefile.cargo) and probably most of our other crates that can build their own C libraries.

**Comment by aneeshusa** [comment]
cc me, need to see how this affects servo/saltfs#355 and ARM triple naming

**Comment by larsbergstrom** [comment]
This has become newly important, as Rust just landed:
https://github.com/rust-lang/rust/pull/41656

I'd expect that to significantly regress Android performance unless we switch to the new target.

cc @fabricedesre @MortimerGoro

**Comment by MortimerGoro** [comment]
I have some wip code in Servo python scripts to add armv7 and aarch64 target compilation parameters. The biggest blocker are some makefile based crates/dependencies which fail to compile

An easier way to fix this may be using make-standalone-toolchain.sh script to generate a preconfigured ndk toolchain. At least, with some tests I did, preconfigured NDKs worked almost on first try, while using the full ndk produced with CXX params produced tons of errors.

**Comment by larsbergstrom** [comment]
My only worry about that is that we used to use `make-standalone-toolchain.sh`, but when we had to move to the LLVM C++ stdlib (due to Gecko native dep requirements, especially SM), the script did not properly create a standalone toolchain across ~5 different releases of the NDK that I tried.

It was also a *huge* failure point for people building for Android. They'd forget to do it or not do it quite right or not get the two env variables correct (you have to install the SDK and NDK and set env vars to the SDK and the made toolchain).

I'd loop with @froydnj, who I believe pointed me at the original gecko code that I cribbed for picking up the right NDK folders. I think it's all here:
https://dxr.mozilla.org/mozilla-central/source/build/autoconf/android.m4#91

**Comment by MortimerGoro** [comment]
@larsbergstrom Yes, I agree that standalone toolchains add more complexity to the users. It's better if we assume the complexity and make users happier ;)

I pushed https://github.com/servo/servo/issues/16769 for armv7 and aarch64 target triples support in python build scripts (build + packaging). 

arm-linux-androideabi is still the default, we can change it when all armv7 compilation errors are fixed in dependencies.

We still need to fix the crates failing to compile form arm-v7 and aarch64.

I fixed armv7 and aarch64 compilation for mozjs in this PR:
https://github.com/servo/mozjs/issues/118

Mio libray fails to compile in aarch64, but a PR is  already in progress: https://github.com/carllerche/mio/pull/599

Other libraries found that still need to be fixed: libfontconfig, skia.
