### ISSUE TITLE
Authentication request for all page resources behind nginx auth_basic

### ISSUE THREAD

**Issue by rmfitzpatrick** [servo/servo#12095]
When accessing a personal page set up w/ basic nginx authentication, the username and password prompts were displayed for all referenced site contents.  This resulted in a barrage of prompts that don't stop despite providing the correct credentials for any given one.

It's also a little distracting to have separate prompts for username and password but understandably this isn't in scope for the issue at hand.

Servo 0.0.1
OSX 10.11.5 (15F34)

**Comment by aneeshusa** [comment]
How did you get the Servo version number? Is that the full output of `./servo --version`? The version number should have a git revision associated with it; if it doesn't we've got a bug somewhere.

**Comment by rmfitzpatrick** [comment]
Sorry I just used the nightly build (haven't tried building myself) and went with what the UI told me.

`Servo 0.0.1-4f81384`

**Comment by aneeshusa** [comment]
OK, version number is all good them; just wanted to confirm our nightlies were getting the git revision embedded.

**Comment by jdm** [comment]
Our http with cache is keyed on the precise URL; we might need to change that to the origin instead.

**Comment by jdm** [comment]
Auth, not with.

**Comment by mpaolini** [comment]
same issue here with `Servo 0.0.1-589c6ee`

**Comment by jdm** [comment]
Let's change `AuthCache.entries` to be a hashmap using [Origin](http://doc.servo.org/url/enum.Origin.html) keys instead of `Url`. We can obtain an origin value by calling the [origin](http://doc.servo.org/url/struct.Url.html#method.origin) method of `Url`.

Code: `components/net/resource_thread.rs`
Test: We should [write a reference test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) that contains two images that reference a [python handler](http://wptserve.readthedocs.io/en/latest/handlers.html#python-file-handlers) - the first one should pass a username and password as part of the URL, and the second one should not. The handler should return a valid image response body if the correct `Authorization` HTTP header is present, and a `401` response if not. The reference file should contain two instances of the valid image.

**Comment by marinintim** [comment]
I'd like to try to tackle this issue

**Comment by jdm** [comment]
@marinintim Please do! Ask questions if anything is unclear.

**Comment by marinintim** [comment]
I'm trying to tackle test infrastructure.

@jdm, should I put new tests under tests/wpt/web-platform-tests/http/basic_auth.html?

**Comment by jdm** [comment]
Sure!

**Comment by marinintim** [comment]
Sorry, didn't have the time to actually do something yet about this issue, and compiling is not an easy challenge on my underpowered machine. I hope to tackle it somewhere around this weekend.

**Comment by jdm** [comment]
Thanks for letting us know!

**Comment by jdm** [comment]
@marinintim Any progress, or should someone else take a shot at this?

**Comment by KiChjang** [comment]
Unassigning due to inactivity. This issue is open for grabs!

**Comment by gilbertw1** [comment]
Seems pretty straight forward, I'd like to tackle this issue and get my feet wet with this code base.

**Comment by jdm** [comment]
@gilbertw1 Please do! Ask questions if anything is unclear.

**Comment by gilbertw1** [comment]
@jdm: I've got this a fix for this issue completed, and I've tested + verified it against a remove server I setup running nginx. However, I am having a tough time figuring out where to get started on creating the reference test and the corresponding python handler. Could you point me to an existing test that uses a python handler (along with the handler location)?

Thanks!

**Comment by jdm** [comment]
The python handlers are invoked by any URL that references them, like in [this test](https://dxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/XMLHttpRequest/getallresponseheaders-status.htm#33). That corresponds to [this handler](https://dxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/XMLHttpRequest/resources/headers.py).

**Comment by gilbertw1** [comment]
Just submitted a PR for this issue, may have err'ed a little on the side of over explaining. Thanks for your help!
