### ISSUE TITLE
Window borders aren't clean on macOS

### ISSUE THREAD

**Issue by Haroenv** [servo/servo#12114]
OS: OS X 10.11

Issue: the border doesn't follow the window size and rounds to the nearest pixels (not physical pixels, but the ones that the display says are pixels on a retina display)

<img width="92" alt="screen shot 2016-07-01 at 21 04 12" src="https://cloud.githubusercontent.com/assets/6270048/16532000/838ff6e0-3fcf-11e6-92a5-f7b1a5668aaa.png">

**Comment by pcwalton** [comment]
This is because we use the private `CGSSetSurfaceShape` to optimize alpha blending. It improves our frame rate a lot, but the downside is that the corners aren't rounded. You can actually see this in Interface Builder apps if you make an NSOpenGLView overlap the bottom corners—they become non-Retina.

Safari gets away with this because it outsources all of its compositing to Core Animation, but we can't do that because we use WebRender.

Unfortunately we can't do much until Apple gives us a better API for this. We could try to smooth over the borders ourselves, but I don't know how good that'd look.

**Comment by tigercosmos** [comment]
<img width="132" alt="2017-12-22 4 55 43" src="https://user-images.githubusercontent.com/18013815/34291842-2fa913d2-e739-11e7-82db-47a914b8deb9.png">
Seems no longer an issue?

**Comment by Haroenv** [comment]
I guess they now use regular window borders, as seen in your screenshot. I haven’t followed up on this issue, so if someone wants to close it, it’s probably fine

**Comment by tigercosmos** [comment]
I thought we can close it.
