### ISSUE TITLE
Incorrect rendering of overflown box

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12144]
Here is an example code https://jsbin.com/xovoyu/edit?html,css,output

You can run following url from servo to an output https://gozala.jsbin.com/xovoyu

You're supposed to see red box but instead you see blue one on servo.

**Comment by paulrouget** [comment]
@Gozala, can you clarify a bit what is actually blocking browserhtml?

The example is indeed not rendered the same way in servo and gecko, but I'd like to understand what exactly is the bug that needs to be fixed here to unblock browserhtml (there are multiple layout issues here).

Is it important that the inner element be inline? Because an absolute positioned inline has a specific behaviour that apparently Servo doesn't support well. Does using inline-block or block work around this issue?

Does the left value matters? I think it's irrelevant here.

Does the transform value matter? Does overflowing matter? If so (and I think this is the bug you're hitting), the overflowing content is cut too early. It looks like another instance of #10559 and #10431.

If so, here is a reduced test case:

```html
<div class="red">
  <div class="blue"></div>
</div>

<style>

  div {
    position: absolute;
    overflow: hidden;
  }

  .red {
    width: 400px;
    height: 400px;
    top: 0px;

    background: red;
  }

  .blue {
    width: 600px;
    height: 200px;
    top: 100px;

    transform: translateX(-100px);

    background: blue;
  }

</style>
```

**Comment by Gozala** [comment]
> @Gozala, can you clarify a bit what is actually blocking browserhtml?

I'm not actually blocked, as I was able to workaround issues. It's just what the issue was was not obvious and once I figured it out I have created issue so it can be fixed.

This is simplification of the following view (which already has workarounds in place if I recall correctly) https://github.com/browserhtml/browserhtml/pull/1015/files#diff-ffe8bca512bec3902f7acb2a95a47644R363 and is basically provides timeline in the bottom you can see in the gif below (that did not render on servo at all):

![](https://cloud.githubusercontent.com/assets/21236/15052403/5ea96112-12b2-11e6-960c-ab71493cea7a.gif)

`left` is there to center timeline itself and `translateX` are to place those event dots in the timeline. 

I don't want to spend too much time bisecting to figure what issue are more important, mainly due to it was possible to workaround them. I think making things `inline-block` was used in the workaround to make it work.

**Comment by notriddle** [comment]
![s](https://cloud.githubusercontent.com/assets/1593513/19697254/84cbfb50-9a9f-11e6-8ecb-93a4a2a8256b.png)

I think this issue is fixed. Can anyone else reproduce it?

**Comment by Gozala** [comment]
Indeed, it seems to be fixed on master 🍾
