### ISSUE TITLE
`referrer_url` argument to `modify_request_headers` is unused

### ISSUE THREAD

**Issue by jdm** [servo/servo#12398]
We assign a value to it, but the value is never read by the caller. We should be able to remove the argument entirely and use a local variable inside the function instead.

Code: `components/net/http_loader.rs`

No need for automated tests; if it builds, it's good enough for a PR.

**Comment by aravind-pg** [comment]
Based on the comment [here](https://dxr.mozilla.org/servo/source/components/net/fetch/methods.rs#791), I would think that fixing #11860 would mean this argument will actually find a use, right? Because I do have a fix for that issue that I can make a PR for, it's just blocked on #11978 landing (as well as a Hyper version bump and upgrade).

**Comment by jdm** [comment]
...Oh, yeah. Durr.

**Comment by jdm** [comment]
Rather, I don't think that #11860 is related to this at all. However, the argument can actually be used by #12389, since we need to extract it in order to store it in the Document that results from the network response.

**Comment by aravind-pg** [comment]
Ah, interesting, hmm. So you're saying we'll want to call `modify_request_headers` to obtain the right `referrer_url` to then pass to the Document constructor (addressing #12389)? But to do that won't we also need the ReferrerPolicy too, since for one thing `modify_request_headers` takes it as an argument? And that seems like it needs to come from the header, i.e. it needs #11860. But then again it seems strange that we're determining the right referrer url this early, because related logic also shows up later in the Fetch algorithm, so maybe this is not what is intended for #12389. Hmm I'm clearly very confused about it all.

**Comment by jdm** [comment]
Document A might have a Referrer-Policy header present in its HTTP response which would give it a custom default referrer policy. When navigating to a link contained in A, that policy would be used along with A's URL to form a referrer. For #12389, that referrer would then be propagated along with the resulting response for the new document B, which might have a different policy included in the same response. Does that make sense?

**Comment by aravind-pg** [comment]
Hmm, still confused tbh. This is best left to IRC I think, will find you there sometime. Just one small question in the meantime:

> Document A might have a Referrer-Policy header present in its HTTP response

HTTP response to what exactly?

**Comment by jdm** [comment]
The response for the original HTTP request for document A.
