### ISSUE TITLE
./mach test-tidy not checking .html files

### ISSUE THREAD

**Issue by simartin** [servo/servo#12421]
Even though "./mach test-tidy" was successful for the patch in https://github.com/servo/servo/pull/12365, it was introducing several \t characters; as spotted in the code review.

That's because test-tidy does not consider .html files, while I believe it should. This is trivially fixed by adding *.html in FILE_PATTERNS_TO_CHECK, however this also requires to fix a bunch of existing files to keep "./mach test-tidy --all" clean.

I propose to do it via this issue.

**Comment by simartin** [comment]
I'm happy to work on this myself.

**Comment by notriddle** [comment]
Alright.

I think `tests/unit/net/parsable_mime/text` should be excluded, because these files need to be kept exactly how they are to make sure they're triggering the right paths in the parser.

Also, `tests/wpt/mozilla/tests/css/fonts`, `tests/jquery`, and `tests/dromaeo` should probably be excluded because they're coming from external projects with different coding guidelines.

The list of excluded directories is right below the file patterns.

**Comment by Ms2ger** [comment]
We should perhaps run the wpt lint on our wpt-style tests.
