### ISSUE TITLE
Cursor doesn't update at scrolling

### ISSUE THREAD

**Issue by est31** [servo/servo#12604]
Tested with browserhtml and my own release build of commit b41bf4f1f30b8f4eec92909c8971bc02d5422b50 .
1. go to a page
2. hover your cursor over some text
3. scroll down or up, so that the cursor is not under text anymore

You will see the cursor not updating, still showing the cursor icon it has over text.

Expected behaviour is that the cursor updates when you scroll.

My OS is linux, but I suspect the bug is present on other OS as well.

I've also tried the css cursor [MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor), it is reproducible for other cursors than the text cursors as well.

**Comment by nox** [comment]
This is still an issue.

**Comment by paulrouget** [comment]
In compositor.rs, where ever `waiting_for_results_of_scroll` is set to `false` (in `composite_specific_target` and `NewScrollFrameReady`) we should compute the new cursor. To do so, we just need to reproduce what `IOCompositor::dispatch_mouse_window_move_event_class` does.

**Comment by reesmichael1** [comment]
@highfive: assign me

**Comment by reesmichael1** [comment]
I have a simple potential fix over on [my fork](https://github.com/reesmichael1/servo/commit/68469ec3cfffc5ef12a5a3e3ff360013fbcf0eb9), but I wanted to ask a few questions about it here before opening a PR if that's ok.

As far as I can see, we need to have some way of keeping track of the cursor location, since any mouse movements are sent in from outside (for example, in `ports/glutin/headed_window::winit_event_to_servo_event`). To handle this, I've added a new field `cursor_pos: DevicePoint` to `IOCompositor`. Is it ok to add this field, or is there a better way? 

Second, I'm not sure how to test this change. In this case, will it be ok to open a PR that doesn't have a test attached, or is there a way to write one for this?

Thanks!

**Comment by paulrouget** [comment]
> Is it ok to add this field

Yes

> I'm not sure how to test this change

I can't think of a way to do that. @jdm do you think there is a way to test the cursor type?

**Comment by jdm** [comment]
Nope. Cursor data isn't exposed to the web.

**Comment by jdm** [comment]
#23313 was an attempt to fix this that had some review comments that needed to be addressed.

**Comment by moonlightdrive** [comment]
I'd like to try fixing this one

**Comment by jdm** [comment]
@moonlightdrive Please do :)

**Comment by matharumanpreet00** [comment]
Hi, I tried to fix this and submitted a PR #23770. It follows the work from https://github.com/servo/servo/pull/23313.

**Comment by moonlightdrive** [comment]
oops, looks like I was too slow. Thanks for your response @jdm. If you happen to have any suggestions of a good first bug, I'd love to know :) otherwise I'll poke for something else to fix
