### ISSUE TITLE
Should we opt for removing old nightlies?

### ISSUE THREAD

**Issue by wafflespeanut** [servo/servo#12611]
Every time we do a rustup, we download new nightlies into `.servo/`. Is there any good reason to keep the old nightlies? If not, we can use `mach` to remove them (in two ways)...
- Once we do a rustup and download new nightlies, we can check `.servo` and remove the old ones.
- Or, we can put this check in `./mach clean`. Currently, the command only calls `cargo clean`, which only cleans up the build directory.

**Comment by Ms2ger** [comment]
In general I don't want to download nightlies more than once when jumping back and forth across a (single) rustup, especially because they're in `~/.servo` for me.

Perhaps overengineered idea: touch a file in the nightly's folder whenever we build with it, and occasionally prompt to delete ones that haven't been used in two months or so.

**Comment by nox** [comment]
We have `./mach clean-nightlies` now.
