### ISSUE TITLE
Android fails at startup with IllegalArgumentException

### ISSUE THREAD

**Issue by glennw** [servo/servo#12647]
I suspect we're hitting something similar to https://github.com/servo/servo/issues/6432 with the SpiderMonkey upgrade?

**Comment by glennw** [comment]
cc @larsbergstrom

**Comment by larsbergstrom** [comment]
Yes, I'm sorry about that! We had to disable the Android build verification:
https://github.com/servo/saltfs/pull/450

Until the SM upgrade landed: https://github.com/servo/servo/pull/12255 (done)
*and* the MSVC transition lands: https://github.com/servo/servo/pull/11756 (in progress)

The reason is that SM moved to a new libc++ (stlport to llvm), which requires sweeping build changes, but the build changes for the MSVC transition had half-landed in dependencies but had not made it to master, so there was no way to land the Android fixes.

It's top on my list as soon as MSVC lands, and I have most of the patch written & ready to go.

**Comment by nox** [comment]
@larsbergstrom Was this done?

**Comment by paulrouget** [comment]
I can start Servo on Android here. Assuming it's fixed.
