### ISSUE TITLE
Is CSS transition on font-size property implemented?

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12745]
Unsure if CSS  transitioning on the `font-size` property is implemented yet?

Applying the transition does not have any effect  - the below example 'toggles' between a large font size and back again.  In Servo, there is no transition but just a 'jump' between the two font sizes.

```
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
body {
    margin: 0;
    padding: 0;
    font-family: helvetica;
}
div {
    transition: 1.5s font-size ease-in-out;    
}
</style>

<script>
window.addEventListener('load', function() {
    var d = document.querySelector('div');
    var large = false;
    var interval = 1000; // Rest time inbetween transitions
    toggle();
    function toggle() {
        large = !large;
        d.style.fontSize = large ? '500%' : '100%';
        setTimeout(toggle, 1500 + interval);
    };
});
</script>

<body>
<div>
I should be transitioning between large font size and back repeatedly.
</div>
</body>
</html>
```

Online test case [here](https://samuknet.github.io/test_cases/fontSizeTransition/).

**Comment by jdm** [comment]
I believe the problem here is that animating any property that requires [reconstructing flows](https://dxr.mozilla.org/servo/rev/ef2bd42494c445dbfabe9acf3704299b340359f2/components/script_layout_interface/restyle_damage.rs#181) is broken, since the layout code that responds to the TickAnimation message [only performs style recalculation](https://dxr.mozilla.org/servo/rev/ef2bd42494c445dbfabe9acf3704299b340359f2/components/layout_thread/lib.rs#1341), not flow construction. @pcwalton What's the right thing to do here?

**Comment by pcwalton** [comment]
Oh, how annoying. I guess we should round trip to script for those so we can reconstruct flows while the DOM is locked.

**Comment by nox** [comment]
This is still not implemented.

**Comment by mrobinson** [comment]
This seems to be working now, probably as a result of #26407 and #26331.
