### ISSUE TITLE
Change usage of ffmpeg?

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12769]
We're having trouble on all of our Nightly builds (linux, mac, and Windows) with the distribution or installation of dependencies required by ffmpeg on those platforms. Should we:

1) Feature flag off the ffmpeg support until we can figure out what we're supposed to do here? 

2) List all the things we need to do to package/distribute bits and get this fixed ASAP?

@metajack mentioned that Gecko does some custom packaging on some platforms, combined with fallbacks for things (mp3) we're not allowed to redistributed.

cc @GuillaumeGomez

**Comment by larsbergstrom** [comment]
One idea that came up in IRC is, for linux, to instead distribute in a few distro-friendly formats (e.g., .deb & .rpm) and request that others build from source, in order to clearly express the package dependencies.

**Comment by metajack** [comment]
We need runtime dylib loading to enable sensible fallback strategies, or else we need to build a distributable ffmpeg ourselves and bundle the output with servo (this will lose us H.264 and MP3 support if we have this now).

I don't think building deb and rpm packages is viable without massively expanding our nightly builders. We'd need one for each distro we want to include, otherwise we'll have the same problem that libraries will be missing or have different names/versions.

I think the correct path forward is ffmpeg-free-sys, but unless someone is willing to start doing that work in the very near future, I think we need to pref it off in nightlyly until it exists.

**Comment by GuillaumeGomez** [comment]
I also think we should put it behind a feature if it's so much trouble.

**Comment by larsbergstrom** [comment]
@glennw says:
```
If we're considering .deb, .rpm etc you might want to consider using OBS (http://openbuildservice.org/). Using the public instance at https://build.opensuse.org/ we wouldn't need to host anything ourselves.
```

**Comment by larsbergstrom** [comment]
@vvuk Noticed that http://mediaarea.net/tr/MediaInfo exists, and might be a good alternative (licensing and build-wise) to ffmpeg.

@rillian Do you have any guidance / ideas here? Or pointers to people we should chat with on working with our video/audio dependencies?

**Comment by larsbergstrom** [comment]
Alternatively, if all we need is MP4 support, we could always use the awesome:
https://github.com/mozilla/mp4parse-rust

:-)

**Comment by tdaede** [comment]
On my machine, the build system finds static ffmpeg libraries and tries to link to them (which fails):

    /usr/bin/ld.gold: error: /usr/local/lib/libswresample.a(resample.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC

Servo really should not be statically linking ffmpeg.

**Comment by larsbergstrom** [comment]
@tdaede Yes, that will need to be fixed ASAP.

Thanks for pointing that out!

**Comment by est31** [comment]
Adding to what @larsbergstrom said, I'm doing a shameless promotion of my library for reading ogg/ogv metadata: https://github.com/est31/ogg-metadata

**Comment by est31** [comment]
(pure rust, no wrapper to an already existing c/c++ library, and no use of unsafe)

**Comment by GuillaumeGomez** [comment]
@est31: Nice! Now we just need a MP4 and a MKV parsers. :)

**Comment by est31** [comment]
@GuillaumeGomez as @larsbergstrom noted above there is already one for mp4: https://github.com/mozilla/mp4parse-rust . With my ogg-metadata crate, this would give support for ogg/ogv, and mp4. MKV/Webm is certainly doable in pure rust as well, although maybe one would have to write a container decoder for mkv (The rust compiler even uses a similar data format as EBML, which MKV bases on, maybe it can be copied and modified back to follow EBML again).

**Comment by GuillaumeGomez** [comment]
@est31: That's because the mkv one is very complicated that I didn't do it and used ffmpeg instead. However I can modify my crate to make it uses yours and the mp4 one instead. If someone could confirm it?

**Comment by rillian** [comment]
From my perspective:

- Servo shouldn't link ffmpeg. At best you should dlopen() it the way gecko does, like @metajack and @tdaede said.
- Gecko includes a stripped down build of ffmpeg so we can use its demuxers. Codec licensing prevents our shipping its decoders for mpeg formats.
- You can use mp4parse-rust as an mp4 parser, but sample extraction isn't completely implemented. Someone adding that would be great!
- For Gecko we want a rust webm parser with an interface which supports the MediaSource Extensions api better than the current nestegg library. See https://bugzilla.mozilla.org/show_bug.cgi?id=1267492
- No help in the short term, but there's been some mumbling about porting the entire gecko media playback subsystem to servo, since this stuff is hard, and we can converge to a rustier implementation over time. I don't know if anyone's seriously tried though.

**Comment by GuillaumeGomez** [comment]
Ok, i'll update to use dlopen in the next days then.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/GuillaumeGomez/video-metadata-rs/issues/22

**Comment by est31** [comment]
@GuillaumeGomez if you got confirmation from someone in the servo team to do this step, I'd really like that and would try to support you from the `ogg-metadata` side as much as I can.

**Comment by GuillaumeGomez** [comment]
@est31: I end the dlopen update and then I'd be glad to do it! :)

**Comment by DemiMarie** [comment]
Note that OpenH264 allows for anyone to do H264 decoding, IF we were willing to use Cisco's precompiled binaries (Cisco has said that it will pay the licensing fees in that case).  If OpenH264 has deterministic builds, we might be able to check that these binaries are the same as ones built from source.

**Comment by metajack** [comment]
I suspect we will eventually use OpenH264 probably by using the same sandbox solution that Firefox uses and downloading at runtime.

**Comment by est31** [comment]
OpenH264 is mostly useful for webrtc like things, but not for youtube etc: https://github.com/cisco/openh264/issues/1407

Firefox still uses gstreamer on linux and OS provided decoders on windows and mac for youtube use cases.

**Comment by metajack** [comment]
@est31 That is certainly true now, but there has been a lot of talk about high profile getting added eventually which would make it work for YouTube. 

Unfortunately, none of this solves the problem of AAC audio, which has no similar workaround.

**Comment by jdm** [comment]
ffmpeg is gone.
