### ISSUE TITLE
'dblclick' event and ondblclick attribute

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12767]
Are these currently implemented in Servo?  

For example:
```
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Double Click Event Handling</title>
<script>
window.addEventListener('load', function() {
	window.addEventListener('dblclick', function() {
        console.log('A double click happened!');
    })
});
</script>
</head>
<body>
<div ondblclick="console.log('A double click happened!');
">
Hello World
</div>
</body>
</html>
```

**Comment by jdm** [comment]
Not yet.

**Comment by jdm** [comment]
We'll want to do the following:
* store the timestamp and position of the last click event in Document
* when dispatching `click` in `Document::handle_mouse_event`, if the time since the last click is less than a certain threshold, and the distance between the clicks is less than a certain threshold, dispatch a `dblclick` event afterwards and reset the timestamp to zero
* otherwise, reset the timestamp and position to the current click that is being dispatched

**Comment by samuknet** [comment]
Thanks @jdm. Do you reckon I could have a go at this?

**Comment by jdm** [comment]
@samuknet Yeah, I think this would be a good place to start!

**Comment by nox** [comment]
> when dispatching click in Document::handle_mouse_event, if the time since the last click is less than a certain threshold, and the distance between the clicks is less than a certain threshold, dispatch a dblclick event afterwards and reset the timestamp to zero

Shouldn't the system tell us about the threshold actually?

**Comment by jdm** [comment]
Sure, but that's harder and requires platform-specific code. Definitely followup material.

**Comment by KiChjang** [comment]
@samuknet Need any help? Any questions?

**Comment by samuknet** [comment]
@KiChjang think I am nearing completion - I've implemented 'double click' and the behavior mirrors other browsers when testing on a page.  The double click timeout and distnace  threshold constants are pulled in from prefs.json.

 Could you take a quick look? This is the bulk of it really https://github.com/samuknet/servo/blob/dblclick/components/script/dom/document.rs#L791-L833
