### ISSUE TITLE
Create a `mach update` command to update everything needed to build

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12775]
Name open to bikeshed (`offline`?).

The idea is that this would:
 - (Optionally?) Do a git pull to update the branch
 - `./mach bootstrap-rust`
 - `./mach bootstrap-cargo`
 - For EACH of the Cargo.lock directories, `./mach cargo fetch`

I *think* that's everything we would need to have a good offline experience. This should just be a new `mach` command and some reuse of calls that exist in other files in the `python/servo` directory.

**Comment by Wafflespeanut** [comment]
Suggestion:  (**command:** `./mach fetch` since we already have some commands with the `update` prefix, and since our subprocesses have `fetch` in their subcommands)

Regarding sync'ing with the remote repo, maybe we should just `git fetch` from `git@github.com:servo/servo` and try to `git merge` it **if** the current branch is `master` (or it can switch to `master` if the `diff` contains no changes). If it's not, then display a message (something like, `"This doesn't look like 'master' branch. Please merge the remote changes into master branch and run this command later"`).

I'm okay with the bootstrapping. As for the `cargo fetch`ing, we could simply hardcode the lockfile paths into the script.

**Comment by Wafflespeanut** [comment]
Even though this is E-easy, it's not exactly a "good first bug" - maybe a good second/third bug :)

**Comment by aneeshusa** [comment]
+1 for `cargo fetch` or `cargo fetch-deps`. I'd rather not try to do any `git merge`ing, in case you're in the middle of working on something, but rather just fetch rust, cargo, and deps based on your current checkout. Having `./mach` commands change my git repo status is always surprising to me (e.g. #9666).

**Comment by Wafflespeanut** [comment]
In case my comment was unclear, we're merging only if `git diff` contains no changes. If the current branch is master, then we'll go ahead and merge it. If it's another branch, we can `checkout` to master and merge it. This happens **only** when there are no changes. If there's a change, we'll quit with the message above. We're not staging/committing anything. So, I don't see how this is going to be disturbing.

**Comment by aneeshusa** [comment]
I am surprised whenever `mach` does merging, pulling, checkout-ing, any git operations at all. For example, if you are in the middle of a bisect or rebase `git diff` might not show changes but merging into master would not be the right thing to do. Furthermore, I don't see why we would want to checkout master or merge the current branch into master - I see this command as useful to pre-fetch build dependencies, not fetching new code.

**Comment by Wafflespeanut** [comment]
Fair enough. I'm convinced.

**Comment by UK992** [comment]
I would like to work on that

**Comment by larsbergstrom** [comment]
@UK992 It's all yours! Thanks for working on this and all your other work that you've been doing for Servo lately :-)

**Comment by UK992** [comment]
I'm glad i can help :)
one question, where put update command, in bootstrap or devenv?

**Comment by jdm** [comment]
I think devenv is appropriate.
