### ISSUE TITLE
How to build from MSVC branch?

### ISSUE THREAD

**Issue by SaschaNaz** [servo/servo#12917]
Hi Servo team,

I downloaded #12916 and am trying building servo with `mach build --release` but it results too small `servo.exe` with 36 MiB size. Running it does not throw any error but just displays white screen. What should be done here?

**Comment by vvuk** [comment]
No need to use msvc branch -- it should be deleted.  The master branch has support for msvc.  You need an environment set up; this will soon be bootstrapped, but in the meantime the bat file and zip files in http://people.mozilla.org/~vladimir/misc/servo/ will provide some hints (call the bat file with "call", since it needs to modify your environment).  Better instructions are forthcoming.

**Comment by aochagavia** [comment]
See https://github.com/servo/servo/issues/13206 for current instructions on building with MSVC and https://github.com/servo/servo/issues/13257 for the white screen issue.
