### ISSUE TITLE
The offsetWidth of a span element is 0.

### ISSUE THREAD

**Issue by veer66** [servo/servo#12939]
offsetWidth obtained by script is 0. 

For example, this html page prints 0 to the console.

``` html
<!DOCTYPE html>
<html lang="en">
<body>
  <div id="main">
    <span id="span1">Test</span>
  </div>
  <script>
    console.log(document.getElementById("span1").offsetWidth);
  </script>
</body>
</html>
```

I used Servo commit 9415252 on Ubuntu 16.04.

**Comment by Permutatrix** [comment]
The other offset properties are wrong, too:

```html
<!DOCTYPE html>
<html>
  <body>
    <div id="main">
      <span id="span1">Test 1</span>
    </div>
    <p id="not-main" style="position: relative"></p>
    <script>
      var span1 = document.getElementById("span1");
      console.log(span1.offsetParent); // [object HTMLParagraphElement]
      console.log(span1.offsetLeft); // -8
      console.log(span1.offsetTop); // -27
      console.log(span1.offsetWidth); // 0
      console.log(span1.offsetHeight); // 0
    </script>
  </body>
</html>
```

This seems to be because the iteration initiated [here](https://github.com/servo/servo/blob/78344754826e938c004a83a21c898552a8e77b17/components/layout/query.rs#L779) doesn't actually find the node it's looking for if said node is set to `display: inline`. There's no assertion or anything there, so it just keeps going with its invalid state and produces the bizarre results above.

I'd like to take this. I've already made it my first foray into the Servo codebase by investigating it this far, and it doesn't seem all too involved.

**Comment by jdm** [comment]
Fantastic; thanks!

**Comment by jdm** [comment]
@Permutatrix Did you make any progress here?

**Comment by Permutatrix** [comment]
@jdm [Some.](https://github.com/Permutatrix/servo/commits/258b1c700912b2372e652e0186931d888f56a7df) I found after taking it that fixing this bug would actually require implementing the offset properties for inline elements from scratch, so I looked into what that would entail, and Firefox and Chrome's implementations are inconsistent with each other. They behave very strangely when it comes to replaced and inline-block children&mdash;for instance, take this mess:

```html
<!DOCTYPE html>
<html>
  <body>
    <span id="span1">
      Test 3
      <img src="100px-square.png" />
    </span>
    <script>
      var span1 = document.getElementById("span1");
      console.log(span1.offsetParent); // <body>
      console.log(span1.offsetLeft);   // Fx:   8. Ch:  8.
      console.log(span1.offsetTop);    // Fx:  93. Ch:  8.
      console.log(span1.offsetWidth);  // Fx: 153. Ch: 42.
      console.log(span1.offsetHeight); // Fx:  19. Ch: 17.
    </script>
  </body>
</html>
```

I figured I should talk to someone about this, but I guess I didn't. For a month. Because I am very "independent", which means terrible at teamwork.

I believe I could write an implementation of the offset properties for inline elements easily enough if I didn't have to worry about the details as Firefox and Chrome seem to have done, though I don't like the way these queries are implemented, using stateful objects that have the same method called over and over to process a sequence of items. It's terribly inside-out, and any implementation of something as complicated as these properties under the system is bound to be extremely brittle.

**Comment by Permutatrix** [comment]
[Alright, I made something that seems to know what it's doing if you don't grill it too hard.](https://github.com/Permutatrix/servo/commit/85da4a9ddf87536111231bdc93c7cee42adffa8e) (It notably doesn't yet work on absolutely positioned inline elements.) But then it occurred to me that this `FragmentBorderBoxIterator` system as it is now has no way of addressing a few cases involving inline elements, because an _empty_ inline element is completely invisible to such an iterator.

Right now I'm thinking of solving this problem by getting rid of `ParentOffsetBorderBoxIterator` completely (yay!) and moving the logic into `process_offset_parent_query` so we can interrogate the `layout_root` Flow directly. I'll have to learn more about how Flows work. This issue is a lot more interesting than it looked.

**Comment by Manishearth** [comment]
Any updates on this? What work is left to be done to make https://github.com/Permutatrix/servo/commit/85da4a9ddf87536111231bdc93c7cee42adffa8e landable?

**Comment by Permutatrix** [comment]
@Manishearth I guess I was just too much of a chucklehead to realize that https://github.com/Permutatrix/servo/commit/85da4a9ddf87536111231bdc93c7cee42adffa8e mostly fixes this bug even with #13982 out there. (Never mind that that bug should be long fixed by now anyway.) I'll have to remove the `unwrap()`, because even in the absence of any other bugs, it'll fail if an element is queried that isn't in the document. Other than that, it's probably mostly fine. I'll run the tests and see if I need to change anything else.

**Comment by Manishearth** [comment]
Cool! Let me know if you need help! :smile:

**Comment by Permutatrix** [comment]
@Manishearth Thanks. You guys are too nice to me, eheh... I just need to learn to be more responsible...
