### ISSUE TITLE
upload_docs.sh is busted

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#12964]
http://build.servo.org/builders/doc/builds/1220/steps/shell/logs/stdio
```
make: Entering directory `/home/servo/buildbot/slave/doc/build/components/script'
make: makefile.cargo: No such file or directory
make: *** No rule to make target `makefile.cargo'.  Stop.
make: Leaving directory `/home/servo/buildbot/slave/doc/build/components/script'
```

CC @vvuk

**Comment by Ms2ger** [comment]
@vvuk helloooooooooooooooo anybody there?

**Comment by larsbergstrom** [comment]
So the lines that are failing are here:
https://github.com/servo/servo/blob/master/etc/ci/upload_docs.sh#L23-L25

Do you want those lines removed from the upload_docs stuff? Or is the idea that you want us to bring back the makefile.cargo (https://github.com/servo/servo/blob/fc7053e030999ed118c9cf2cac0835286d6dde06/components/script/makefile.cargo ) with just the `doc` target?If the

**Comment by Ms2ger** [comment]
I have no idea what that code is trying to do.

**Comment by larsbergstrom** [comment]
git blame says that it was originally written by @jdm : https://github.com/servo/servo/commit/3c2435a172b1b11335b34a9071e6530514aaca46

**Comment by jdm** [comment]
Porting that make target to python would be the most sensible choice.

**Comment by Ms2ger** [comment]
```
 Documenting servo v0.0.1 (file:///home/servo/buildbot/slave/doc/build/components/servo)
Copying Rust documentation.
Usage: components/style/properties/build.py [ servo | gecko ] [ style-crate | html ] [ testing | regular ]
```

**Comment by Ms2ger** [comment]
CC @Manishearth

**Comment by Manishearth** [comment]
```
cp: cannot create regular file 'target/doc/servo/': No such file or directory
```

**Comment by Ms2ger** [comment]
```
[100%] Built target supported-apis
fatal: could not read Password for 'https://f09c2dfe2e63ef3532fb979b90301c1638b73963@github.com': No such device or address
```

CC @aneeshusa @larsbergstrom @metajack ?

**Comment by larsbergstrom** [comment]
Welp, dunno what's causing the failure, but clearly we're leaking that token and I need to revoke it asap :-/

cc @edunham

**Comment by larsbergstrom** [comment]
@edunham @SimonSapin @metajack How was this set up? This token does not appear to be owned by bors-servo or myself, so I can't revoke it :-/

**Comment by aneeshusa** [comment]
I made #13507 to prevent this from happening again, although we should investigate a better way to pass the token to git.

**Comment by SimonSapin** [comment]
I was notified a few weeks ago that some rust-url builds on Travis had leaked a token, so I revoked it and switch to docs.rs instead of github pages (same for cssparser, which shared the token). I then realized that `upload_docs.sh` had the same issue (leaking tokens on network errors) and also revoked that token. The build had been failing for a while anyway.

The token was owned by https://github.com/rustdoc . I’ve added the password for that accounts to usual place.

I wrote about all this to a couple people by email but haven’t gotten around to fixing `upload_docs.sh` yet as I’ve been traveling.

One option is to redirect both stdout and stderr:

```sh
git push -qf https://$TOKEN@github.com/…/… gh-pages > /dev/null 2>&1
```

Another is to keep the token in a file, like in https://github.com/t0yv0/t0yv0.github.io/blob/de5f1ef772ced750b5fe29fcf8388bbf2af8955a/deploy.sh

**Comment by aneeshusa** [comment]
OK, looks like we aren't leaking the old token anymore (compare http://build.servo.org/builders/doc/builds/1525/steps/shell/logs/stdio with http://build.servo.org/builders/doc/builds/1526/steps/shell/logs/stdio), but it looks like we still need to get a new token and deploy it.

**Comment by larsbergstrom** [comment]
Fixed: http://build.servo.org/builders/doc/builds/1546
