### ISSUE TITLE
Merge most of gecko_bindings and geckolib into style

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13038]
When working on #12991 I kept stumbling against coherence and dependency issues.

The Servo types corresponding to the FFI types are not defined in gecko_bindings, so I can't refer to them there. This leads to awkwardness like `fn into_arc<U>(self) -> Arc<U> where U: HasArcFFI<FFIType = T>` (it's also awkward to call, you often have to use turbofish notation to explicitly specify the type `U`)

I also can't implement methods for those types, so I have to use things like `Foo::from_bar(bar)` instead of `bar.into_foo()`.

In general I keep coming up against the fact that they're different crates when writing stylo code, often when generics are involved.

Could we make them all one crate? Keep geckolib around, but move most of its contents to style (behind a cfg). Not sure if it's feasible.

cc @bholley @emilio @heycam

**Comment by bholley** [comment]
The original reason that gecko_bindings became a separate crate was because we needed to use it from our [replace]-ed string_cache (and also, at some points, from style/). IIRC @SimonSapin did some stuff to remove that requirement.

One thing that might be a problem is that the bindings are eventually going to be generated at gecko build time in mozilla-central - that is to say, they won't be checked into servo/servo at all. I guess we can just generate them with a build.rs script that will only run when being built in Gecko mode.

Barring that constraint, I'm fine with whatever @SimonSapin wants to do here. I built these abstractions to keep the gecko stuff more separate, but if others don't mind it living in-crate I certainly don't. It does seem like we might want to use subdirectories or something, given how many files are appearing in style/.

**Comment by Manishearth** [comment]
> One thing that might be a problem is that the bindings are eventually going to be generated at gecko build time in mozilla-central 

Ugh, I forgot about this. One thing I was hoping for servo-in-m-c would be that we'd be able to centrally generate a single set of bindings. Though that proposal has its own issues -- there may be cyclic dependencies introduced by it. So I'm not sure if I should be worried about that.

We don't need to check them in in servo/servo either, we can just use the same script with a different out directory.

**Comment by SimonSapin** [comment]
I’m slightly worried about build times. Incremental compilation is not here yet, so merging crates means they always have to be rebuilt when anything changes.

**Comment by Manishearth** [comment]
Agreed. I'm super happy with the current build-geckolib build times.

**Comment by SimonSapin** [comment]
Ok, given that:

* `gecko_bindings` is relatively quick to build (a dozen seconds on my laptop)
* `geckolib` depends on `style`, so it needs to be rebuilt anyway when `style` changes

This specific merge is probably OK.

Still, I’d like whoever does it to check that the `style` build times for Servo doesn’t increase too much. (That is, does rustc spend time parsing/checking modules disabled with `#[cfg(…)]`?)

**Comment by Manishearth** [comment]
Rust parsing is super fast. Shouldn't be an issue.
