### ISSUE TITLE
FormData shouldn't store datums in a HashMap

### ISSUE THREAD

**Issue by nox** [servo/servo#13105]
The [spec](https://xhr.spec.whatwg.org/#concept-formdata-entry) says:

> The FormData object represents an ordered list of entries. Each entry consists of a name and a value.

So we can't use a data type that doesn't preserve order. Instead we should just use a `Vec<(Atom, FormDatum)>`.

**Comment by nox** [comment]
This is still true.

**Comment by CYBAI** [comment]
While working on #22660 , I just what @nox proposed is the right way.

We cannot use `HashMap`, `BTreeMap` or `IndexMap` because we'll miss the order of keys for multiple keys case.

After using `Vec<(Atom, FormDatum)>`, we should pass this test case.

https://github.com/web-platform-tests/wpt/blob/d57cb918ef2b0fbc79c39cb48f6870d02040d4d3/xhr/formdata-foreach.html#L9-L35
