### ISSUE TITLE
Remove support for UTF-16 in TextEncoder

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13231]
Blocks #5601.

The specification was changed. This should allow us to remove the `encoder` field of the `TextEncoder` struct.

* Spec: <https://encoding.spec.whatwg.org/#textencoder>.
* Code: `components/script/dom/textencoder.rs`, `components/script/dom/webidls/TextEncoder.webidl`.
* Test: `/encoding/textencoder-constructor-non-utf.html`, (possibly) `/encoding/idlharness.html`.

**Comment by ashrko619** [comment]
I'd like to take this :)

**Comment by jdm** [comment]
@ashrko619 Did you make progress on this? Any questions?

**Comment by ashrko619** [comment]
@jdm I did not know whether to work on this without being assigned 🙈 
So here the methods ```Encode``` and ```Encoding``` use encoder.
What should we do here ?

**Comment by jdm** [comment]
The encoding specification [changed](https://github.com/whatwg/encoding/commit/8360f775c8df145f649047c7d59c5ff733ade112) so that TextEncoder only ever uses UTF-8 now. That means that we don't need an encoder variable in our implementation any more; we can use the UTF-8 encoder directly everywhere instead.
