### ISSUE TITLE
Implement streaming support for TextDecoder

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13234]
Blocks #5601.
- Spec: https://encoding.spec.whatwg.org/#dom-textdecoder-decode.
- Code: `components/script/dom/textdecoder.rs`, `components/script/dom/webidls/TextDecoder.webidl`.
- Test: `/encoding/textdecoder-fatal-streaming.html`, `/encoding/textdecoder-streaming.html`.

**Comment by yodalee** [comment]
I wanna make sure that my thought is correct. To implement the streaming support, I think we need to add a `RawDecoder`, which is provided by `encoding`, to the `TextDecoder`
Currently, the `decode` method will process the input buffer to the end by calling `encoding.decode()`, thus we are unable to do incremental decoding. To allow stream decode, we need to add a `RawDecoder` and use `raw_feed` method instead.

**Comment by jdm** [comment]
That looks right to me.

**Comment by yodalee** [comment]
I cannot get it to work in the end. Here is the branch I tried so far.
https://github.com/servo/servo/compare/master...yodalee:add-streaming-support-for-textdecoder
I add the `stream` options, `Box<RawDecoder>`, do not flush flag and BOMseen flags.
However I cannot get this work, since `Decode` method take `&self` instead of `&mut self` as arguments. So I cannot modify any flag or RawDecoder in `TextDecoder` since it is not mutable.
No idea how to implement this.

**Comment by jdm** [comment]
@yodalee You need to store mutable fields inside `Cell` or `DOMRefCell` in order to mutate them. Does that help?

**Comment by yodalee** [comment]
I dig into this problem for a while, here is my little conclusion:
Currently, `TextDecoder` own a `EncodingRef`, and let `EncodingRef` do all the decode job. The`EncodingRef` does not supporting stream decode, which always flush buffer in the end of `decode` method.
I firstly try to add a `RawDecoder` into `TextDecoder`, and copy the content of `decode` method in `EncodingRef` to `Decode` method in `TextDecoder`. However, due to some restriction of `TextDecoder`, I cannot get this right, which took me half month and cannot get it right.
Now I'm not sure how to do it. We need a place to store `unprocessed` buffer, which `decode` method in `EncodingRef` will not support. Maybe I can add another method into `EncodingRef` to make it?

**Comment by yodalee** [comment]
I got an idea that: I can add a `RawDecoder` into `TextDecoder` to support streaming. To achieve that, I need to make customized change to `Rust-Encoding`, adding a function to reset the unprocessed buffer in `RawDecoder`. However I cannot get it worked.
I download `rust-encoding` and modify `Cargo.toml` in component/script, changing encoding setting to
```
{path="localpath", version="0.2"}
```
However, the compiler error when compiling `dom/htmlformelement.rs`. Here is part of error message:
```
   --> /home/yodalee/mozilla/servo/components/script/dom/htmlformelement.rs:384:42
    |
384 |                  .encoding_override(Some(self.pick_encoding()))
    |                                          ^^^^^^^^^^^^^^^^^^^^ expected trait `html5ever::encoding::Encoding`, found trait `encoding::Encoding`
    |
    = note: expected type `&html5ever::encoding::Encoding + Send + Sync`
    = note:    found type `&'static encoding::Encoding + Send + Sync + 'static`
```
which I cannot understand how to fix it.

**Comment by jdm** [comment]
You should follow http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies or http://doc.crates.io/specifying-dependencies.html#overriding-dependencies instead.

**Comment by jdm** [comment]
This requires adding the TextDecodeOptions dictionary from the spec and implementing the steps of the `encode` method that relate to streaming.

**Comment by talklittle** [comment]
I'd like to give this a shot.
