### ISSUE TITLE
Implement Window::open.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13241]
Blocks #2968.
- Spec: https://html.spec.whatwg.org/multipage/#dom-open.
- Code: `components/script/dom/window.rs`, `components/script/dom/webidls/Window.webidl`, and more.
- Test: various.

**Comment by gterzian** [comment]
is anyone working on this one? If not, I am interested...

**Comment by jdm** [comment]
Nobody is working on it. I don't think anybody has wanted to tackle dealing with multiple toplevel windows and figuring out how that relates to things like the compositor and webrender.

**Comment by gterzian** [comment]
ouch, that sounds painful, well I guess I'm up for it, you can add the 'assigned' label 😄

**Comment by jdm** [comment]
Related discussion: https://github.com/servo/servo/issues/13338

**Comment by jdm** [comment]
Also: https://github.com/servo/servo/issues/13993, https://github.com/servo/servo/issues/13994, and a bunch of relevant stuff in the tracking issue for multiple windows: https://github.com/servo/servo/issues/13997

**Comment by paulrouget** [comment]
https://github.com/servo/servo/issues/13994 needs to happen first (if you have multiple compositors, you will need multiple top level frames). Also, @glennw might be working on something related.

This issue is about supporting `window.open` which might not require multiple compositors. Maybe the embedder could just open a new tab instead of a new window, which in this case would only require multiple root frames (not multiple compositors).

Do we support `WindowProxy` already? Is it necessary to support `window.open`?

Do we want to support window opener and referrer?

/cc @glennw @asajeffrey

**Comment by paulrouget** [comment]
A simple initial approach could be to just fire an event to the embedder and let the embedder create a new top level frame (see how that would work here https://github.com/servo/servo/issues/13994#issuecomment-294415932).

Maybe we could ignore opener and refererrer at first.

Considerations:

* `window.open` is synchronous
* the embedder might refuse to open the window
* look at the `MozBrowserEvent::OpenWindow` event

**Comment by gterzian** [comment]
@paulrouget yes I can first work on #13994 and perhaps others, it sounds like this one needs a bit more infrastructure in place to be completed, and it's nice way to break up the work. 

re the initial approach you mention, am I correct if I say that when you say "just fire an event to the embedder" you mean that `window.open` would fire something such as the ["BrowserEvent::HandleUrl"](https://github.com/paulrouget/servo/blob/204b267d9d9cc71c79954d444fcd63623bdbe8e0/ports/servo/main.rs#L336) in your example, and that the "embedder" [`Tabs`](https://github.com/paulrouget/servo/blob/204b267d9d9cc71c79954d444fcd63623bdbe8e0/ports/servo/main.rs#L57), would respond to that event by "asking" for a new browsing context from Servo through the constellation, in your example using [`new_browser`](https://github.com/paulrouget/servo/blob/204b267d9d9cc71c79954d444fcd63623bdbe8e0/components/servo/lib.rs#L277).

In this case we would also need to add such event handling ourselves in `ports/servo`, which as I understand it is basically sort of acting like an embedder would?

**Comment by paulrouget** [comment]
> @paulrouget yes I can first work on #13994 and #13993, it sounds like this one needs a bit more infrastructure in place to be completed, and it's nice way to break up the work.

@asajeffrey is already working on multi top level frames (#13994).

And if I'm not mistaken, @glennw is working on multiple WR instances. I'm not sure how this plays with multiple compositors. Supporting multiple compositors will also mean that we need to stop using exclusively the compositor channel to talk back to the embedder. We may need another communication channel (see #15934).

So you need to sync up with them (IRC is a good place for that) to understand where you can help.

> re the initial approach you mention, am I correct if I say that when you say "just fire an event to the embedder" you mean that window.open would fire something such as the "BrowserEvent::HandleUrl" in your example, and that the "embedder" Tabs, would respond to that event by "asking" for a new browsing context from Servo through the constellation, in your example using new_browser.

You're correct.

The payload of the event should include enough information for the embedder to be able to create a new frame with the proper context name, opener reference, referrer, etc.

Something like this:

```
WindowMethod::new_window(opener:FrameId (or PipelineId), disposition: WindowDisposition, load_data: LoadData, context_name: String);

// preferred disposition. Up to the embedder to follow this or not:
pub enum WindowDisposition {
  ForegroundTab,
  BackgroundTab,
  NewWindow,
}

```

(this event would also be used by target="_blank", not just window.open)

`window.open` is synchronous, so that means the script will need to wait on the constellation which will wait on the embedder. But I don't think we ever want the constellation to block on anything, so I don't know how this should be done. @asajeffrey might be able to help here.

> In this case we would also need to add such event handling ourselves in ports/servo, which as I understand it is acting like a default embedder to run servo?

Yes.

**Comment by paulrouget** [comment]
At this point, we can see that a lot of things are required before being able to fully support `window.open`.

In term of priorities, supporting multiple compositors is very important for us (more that supporting `window.open`), along with supporting multiple top frames.

I am not sure what would be best for you to start with.
@jdm - what do you think?

**Comment by jdm** [comment]
I don't know that I have a meaningful opinion here, since I haven't been following the existing work that's happening.

**Comment by gterzian** [comment]
@paulrouget Ok, thanks for the clarification, I think I have a pretty good overview of what we are trying to do from a high level perspective. I'll try to connect with @glennw and @asajeffrey here or on IRC to see if there is something I can work on to support "multiple compositors".

**Comment by asajeffrey** [comment]
I'd recommend ignoring opener and referrer for the moment, until we decide what to do about de-conflating "top-level browsing context" from "unit of similar-origin browsing contexts".

For sync `window.open()`, the messages via the constellation should all be async, and the constellation shouldn't block on script, but it's okay for script to block on the constellation, so the easiest thing to do is probably to pass around an ack channel to wake up the script once it's finished. The main concern I've got is that we'll end up blocking every script in the same script thread, but I don't see much else we can do.

**Comment by gterzian** [comment]
I propose to first work on #13993 and #15934 in parallel, ultimately culminating in an implementation of `window.open` within the context of this issue that would look somewhat like we sketched above.

I assume the actual implementation plan for `window.open` will become clearer as the other issues are resolved first, and I'll communicate some plan for both other issues after having looked more closely into the code.

**Comment by paulrouget** [comment]
> I propose to first work on #13993 and #15934

I think this is a good idea.

**Comment by gterzian** [comment]
Also, since 'multiple webrender' was mentioned a year back, I was looking into webrender and the concept of `webrender::api::DocumentId` caught my attention. It seems now we use one `DocumentId` for the entire constellation, and I'm wondering if we couldn't move to having one for each pipeline?

See https://github.com/servo/webrender/blob/eb9415a3b601451476c52be4f444c982a3ed8e0c/webrender/examples/document.rs#L27

**Comment by paulrouget** [comment]
WR can only render one top level browsing context at once, but that doesn't mean other contexts / pipeline are not running. Sending the frametree to WR has not impact in the main event loop or the pipelines (beside the visibility event iirc).

On `open()`, we can, like you said, create a new tab, select it, and that's it.

The user experience will be affected, but that's fine for now. We will eventually implement tab switching (that works already, but we don't save the list of browsers yet, and we didn't bind the shortcuts).

For tests, I don't think this will have any impact at all. Both pipelines will be running. The one that's on screen should not matter.

**Comment by gterzian** [comment]
Ok, I'll be moving on to this one, starting with https://github.com/servo/servo/pull/20678(which I guess doesn't make a lot of sense to merge on it's own with all those TODO's and test failures left?).

I propose somewhat clarifying the scope of this  issue, which includes a bunch of interrelated concepts such as:

1. https://html.spec.whatwg.org/multipage#auxiliary-browsing-contexts
2. https://html.spec.whatwg.org/multipage#navigating-auxiliary-browsing-contexts-in-the-dom
3. https://html.spec.whatwg.org/multipagel#familiar-with
4. https://html.spec.whatwg.org/multipage#the-rules-for-choosing-a-browsing-context-given-a-browsing-context-name
5. https://html.spec.whatwg.org/multipage#dom-open
6. https://html.spec.whatwg.org/multipage#groupings-of-browsing-contexts

@KiChjang I've seen you've recently worked in the same area with https://github.com/servo/serv/pull/20615, would you be interested in reviewing this one?
