### ISSUE TITLE
Scrolling to end of element should start scrolling the parent element.

### ISSUE THREAD

**Issue by samuknet** [servo/servo#13249]
In other browsers, if you carry on scrolling an element past the end then its parent element will begin to scroll, if possible.

In Servo, the parent element does not begin to scroll once the inner element has been scrolled all the way down.

Expected behaviour as shown in FF (identical in Chrome):
![expected](https://cloud.githubusercontent.com/assets/9294710/18441679/cd088246-7905-11e6-9650-8260fc1d19e9.gif)

However, in Servo the parent element does not begin to scroll once the user has scrolled to the very end of the inner element.

Page used for testing can be found online [here](https://samuknet.github.io/test_cases/nestedScroll/).

**Comment by gterzian** [comment]
Could I give this one a try?

**Comment by jdm** [comment]
@mrobinson Would you be able to provide any pointers here?

**Comment by gterzian** [comment]
the culprit seems to be right here https://github.com/servo/servo/blob/master/components/compositing/compositor_layer.rs#L356 
😄

**Comment by paulrouget** [comment]
scroll events lands in compositor.rs here: https://github.com/servo/servo/blob/master/components/compositing/compositor.rs#L1617 then WebRender performs scrolling here: https://github.com/servo/webrender/blob/master/webrender/src/frame.rs#L284 … there, a layer is picked (see `get_scroll_layer`). I guess the wrong layer is picked (if any). It probably has to do with the ScrollEventPhase.

**Comment by gterzian** [comment]
@paulrouget thanks

**Comment by gterzian** [comment]
removed my comment above which refered to older scroll code...

**Comment by gterzian** [comment]
Hi everyone, I'm trying to build Servo with my local fork of webrender, seeing this erro:
`error: Package `webrender_traits v0.6.0 (file:///Users/gregory/Projects/servo/../webrender)` does not have these features: `serde_macros`

**Comment by paulrouget** [comment]
It's because of: https://github.com/servo/webrender/pull/430

@nox what needs to done on Servo's side?

**Comment by nox** [comment]
@gterzian For now you can base your work on the `rustup` branch of this repository. It will get merged tomorrow.

**Comment by gterzian** [comment]
@nox thanks, builds fine now 👍

**Comment by gterzian** [comment]
Quick proof of concept here: https://github.com/servo/webrender/pull/436

It 'works', however not sure if it's right way to approach the problem. For example, if we had more levels of nesting, the scrolling would 'jump' to scrolling the root layer, as opposed to going up the chain of child layers...

**Comment by glennw** [comment]
Probably best to get @pcwalton to look at this - he did the overscroll implementation and is able to test on mac (overscroll is not implemented for linux yet).

**Comment by mstange** [comment]
Once we have overscroll in Firefox on macOS, we're going to enable it for all scrollable elements. If a new scroll gesture starts while you're already scrolled all the way to the edge of the scrollable element under the mouse, then the scroll will be handed off to the next outer scrollable element which is actually scrollable in that direction. We don't do handoff in the middle of a scroll gesture.

**Comment by paulrouget** [comment]
> We don't do handoff in the middle of a scroll gesture.

As per design? Or not implement yet?

**Comment by mstange** [comment]
By design. The element you scroll is selected at the start of the scroll gesture, and if you decide that you want to scroll a different element after reaching the end of the current element, you can just lift your fingers and start a new scroll gesture.
If you scroll using a traditional mouse wheel, you need to move your mouse or wait for a short time to start a new wheel transaction.

I don't have a good example for why not handing off scrolls to the outside is a good thing. But I do have an example for why retargeting scrolls to the scrollable element under the mouse all the time (which is what Chrome does) is not a good idea: If you scroll a long page, and somewhere on that page is a smaller scrollable element, you don't want that element to swallow the rest of your scroll gesture if it suddenly happens to move under your mouse. You want the current scroll gesture to keep scrolling the outer page.

**Comment by gterzian** [comment]
@mstange Thanks for the background info. So this sounds like there is no issue at this point? Please confirm and if so I can close my PR and we can close this issue as well 😄

**Comment by paulrouget** [comment]
@gterzian if B is inside A, and the mouse is hovering B, and B can't scroll anymore, when the user starts scrolling, A should scroll. This is not working today, and it needs to be fixed.

What @mstange talks about not doing "handoff" during the gesture, it means that while the user is scroll, if B reaches the end, we should not scroll A.

Pick A only if B can't scroll anymore, and if the user starts scrolling (when `phase == ScrollEventPhase::Start`).

**Comment by gterzian** [comment]
@paulrouget Ok, thanks for the explanation, let me take a look at it!

**Comment by gterzian** [comment]
@paulrouget @mstange 

Here is a problem I am encountering:

Currently, when you reach the end of the child layer B, you get the 'overscroll' behavior. At that point, which means that you can't scroll further down. So the behavior of the child layer is akin to 'getting to the bottom of the page'. 

At that point, if the user starts a new scroll gesture, we should start scrolling the parent layer A, allowing the user to continue scrolling the rest of the page, instead of getting stuck in layer B. 

My problem is that, when you start the scroll, `phase == ScrollEventPhase::Start` is true, however the moment you actually start scrolling, `phase == ScrollEventPhase::Move(true)`. 

So at that point, I can't make out the difference between a 'new' scroll gesture, which started after reaching the bottom of the child layer, and an 'old' scroll gesture, which should finish in an over scroll when reaching the bottom.

**Comment by gterzian** [comment]
To give a bit more context, I've pushed my debug code: https://github.com/servo/webrender/pull/436/files

and I also attach a screenshot of the corresponding debug statements.

![screen shot 2016-10-15 at 6 08 32 pm](https://cloud.githubusercontent.com/assets/2792687/19409243/774ad4f0-9302-11e6-9a99-cdf56045544f.png)

**Comment by paulrouget** [comment]
I'm not sure, but during a scroll gesture, can different layers scroll? If the answer is no, on `phase==start`, maybe you can pick a layer and store its id (I don't know where), and for next events, pick that layer?

**Comment by gterzian** [comment]
@paulrouget thanks, let me give this a try.

 Also, FYI, when `phase==start` it actually does switch layer, however, when the scroll starts moving, it goes back to the child layer, I guess because the scroll location still is on the child layer? So the switch only last for one event, when the phase is start.

**Comment by gterzian** [comment]
@paulrouget proof of concept at https://github.com/servo/webrender/pull/465/files  it 'works', once again just switching the scroll to the root layer, if we go forward with this we should probably grab the 'nearest parent' instead... Please let me know what you think

**Comment by gterzian** [comment]
UPDATE: now also getting the 'nearest parent' ;)

**Comment by gterzian** [comment]
By the way, I noticed that when you scroll and you encounter a scrollable child layer, the scroll switches to that layer, which is the opposite of the behaviour we want as per @mstange. This doesn't relate to my changes, yet we might want to try to tackle both at the same time?

**Comment by paulrouget** [comment]
> the scroll switches to that layer

That's because layer is picked in `fn scroll` no matter the phase.

>  This doesn't relate to my changes, yet we might want to try to tackle both at the same time?

I would say yes. It's very much related. Both problems are about which layer is chosen on scroll.

**Comment by gterzian** [comment]
Ok, added another commit, which implements 'keeping the currently scrolling layer, unless a new scroll gesture started'. Also keeping the other part which implements 'switching to the parent layer, when the child has scrolled to the end, and a new scroll is started, unless we're dealing with the root scroll layer'.  

Please have a look: https://github.com/servo/webrender/pull/465

**Comment by gterzian** [comment]
I have one question: Now that webrender has been updated to version 0.7, I'm having troubles building Servo with my local fork, since Servo expects webrender 0.6. 

How can I update my local Servo to use my local webrender 0.7?

**Comment by paulrouget** [comment]
Wait until @glennw updates servo, or try yourself by doing `./mach update-cargo -p webrender`.

**Comment by glennw** [comment]
@gterzian Servo should be all updated with latest WR now. You may find your local [replace] override in Cargo.toml needs to change the version number (to 0.8.0 I think) to select that local override when building.

**Comment by gterzian** [comment]
@glennw thank you, yes it all works fine now :)

**Comment by gterzian** [comment]
Wanted to point out that this issue has moved somewhat deeper then the stuff we initially discussed here, and there is more info in the PR itself(not sure if we should move that discussion in here btw) see https://github.com/servo/webrender/pull/599
