### ISSUE TITLE
Implement fallback when the float width speculation fails

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#13284]
During block size assignment, we need to place block formatting contexts next to floats and if the resulting inline size is different from the speculated inline size, then we need to call `assign_inline_sizes()` and `assign_block_sizes()` sequentially again.

**Comment by pcwalton** [comment]
See #13223 for a test case

**Comment by notriddle** [comment]
Working out an approach to how to do this (mentioning possibilities that I need to handle):

* When a float speculation failure is detected, by making an `available_rect` call on the float object, a flag is added to the block flow in question.

* During block assignment on the parent (unless I'm misunderstanding the code, this is also the point when inline flows are moved around to avoid floats), after a child with the "float speculation failed" flag is encountered, it will run the "did float speculation work" check on all children with block context. For any that are failed, it will perform a reflow on it. The reflow doesn't have to be sequential, but it needs to wait until it's done before it can go on.

The reason for doing it this particular way is because reflowing a block context can affect whether later ones impact blocks. This has the unfortunate side-effect of forcing all the block contexts after a speculation failure to be laid out in sequence, but the only alternative I know of is to re-do all the following speculation failures in parallel, and that ends up O(n^2) if they all fail (like on GitHub).
