### ISSUE TITLE
Have tidy ensure that the there are no extra files in the webidls folder

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13427]
We should probably lint that `components/script/dom/webidls` contains only `*.webidl` files.

Code: https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py

**Comment by gterzian** [comment]
@Manishearth could this be already implemented through https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L570 ?

**Comment by Wafflespeanut** [comment]
@gterzian No, that checks the contents of the `webidl` file. We probably need a new check.

**Comment by gterzian** [comment]
@Wafflespeanut ok thanks for clarifying. Allright I'll give this one a try

**Comment by Wafflespeanut** [comment]
Glad to hear :)

**Comment by gterzian** [comment]
@Wafflespeanut @Manishearth 

A question: 

do we want to check for any type of  file inside `components/script/dom/webidls` or limit ourselves to the subset of `FILE_PATTERNS_TO_CHECK` see https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L44

I'm mainly asking because if the former, I can just plug into the existing 'file checking' generator pipeline from https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L834, otherwise I think I'll have to do a completely separate check.

**Comment by Manishearth** [comment]
@gterzian We want to ensure that this folder has only `*.webidl` files. webidl files elsewhere in the tree are okay (usually meaningless). Since the webidl files in that folder are read by the bindings generator, any other kind of file there is probably a mistake.

This is a different kind of check from the rest, let it stay completely separate.

**Comment by gterzian** [comment]
@Manishearth ok, thanks for the extra background info, that's all I need to get started :)

so I'll just add another step, akin to the config error check, that is unrelated to the generator pipeline that checks all files individually.
