### ISSUE TITLE
Properly rethrow any exceptions from parsing JSON in Body mixin's `Json()`

### ISSUE THREAD

**Issue by jeenalee** [servo/servo#13464]
The [Fetch spec](https://fetch.spec.whatwg.org/#body) requires the `Json()` method in Body mixin to rethrow any exceptions from parsing the JSON object. 

Currently, #13345 clears pending exception instead of rethrowing exception from `js::jsapi::JS_ParseJSON()`.

**Comment by nox** [comment]
Still happens, see `run_json_data_algorithm`.

**Comment by jdm** [comment]
It should be enough to remove the exception clearing and return an `Err(Error::JSFailed)` instead. Running `./mach test-wpt tests/wpt/web-platform-tests/fetch` will show if there are any tests for this that already exist.

**Comment by ysimonson** [comment]
@jdm FWIW, I tried just making the above change, but it seems that the exception is not consumed upstream:

```
$ ./mach test-wpt tests/wpt/web-platform-tests/fetch
Running 209 tests in web-platform-tests

  ▶ CRASH [expected OK] /fetch/api/request/request-consume.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ assertion failed: !JS_IsExceptionPending(cx) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at components/script/dom/bindings/error.rs:275)
```

The diff:

```
$ git diff --minimal
diff --git a/components/script/body.rs b/components/script/body.rs
index 35ee2dae2c..28a9b4d952 100644
--- a/components/script/body.rs
+++ b/components/script/body.rs
@@ -15,7 +15,6 @@ use dom::promise::Promise;
 use js::jsapi::Heap;
 use js::jsapi::JSContext;
 use js::jsapi::JSObject;
-use js::jsapi::JS_ClearPendingException;
 use js::jsapi::JS_ParseJSON;
 use js::jsapi::Value as JSValue;
 use js::jsval::UndefinedValue;
@@ -133,9 +132,7 @@ fn run_json_data_algorithm(cx: *mut JSContext,
                          json_text.as_ptr(),
                          json_text.len() as u32,
                          rval.handle_mut()) {
-            JS_ClearPendingException(cx);
-            // TODO: See issue #13464. Exception should be thrown instead of cleared.
-            return Err(Error::Type("Failed to parse JSON".to_string()));
+            return Err(Error::JSFailed);
         }
         let rooted_heap = RootedTraceableBox::from_box(Heap::boxed(rval.get()));
         Ok(FetchedData::Json(rooted_heap))
```

...maybe I'm misunderstanding though

**Comment by jdm** [comment]
Ok, I see the problem. Promise::reject_error is invoked from consume_body_with_promise, and that has checks that there's no exception pending. Since `JS_ParseJSON` did set a pending exception, which is no longer cleared, this is the assertion that is failing. Therefore, we should do the following instead:
* revert the removal of `JS_ClearPendingException`
* using the `rooted!` macro, create a new `JSVal` local variable to store the exception value
* use the JS_GetPendingException API to extract the exception, right before we clear it
* add a `JSException(RootedTraceableBox<Heap<JSVal>>)` variant to FetchBody
* store the exception value in this new when and return it instead of Error::JSFailed
* in `consume_body_with_promise`, call `promise.reject_native` and pass the result of `&exception.handle()` from the new enum variant

This should get us to the behaviour that we're looking for!

**Comment by jdm** [comment]
I'm marking this assigned under the assumption that @ysimonson wants to keep working on it.

**Comment by ysimonson** [comment]
Thanks for the gentle walkthrough @jdm! I got it compiling last night, though wpt was still failing. I didn't know what the proper fix was until @kwonoj opened their PR. In any case, I'll open a PR with the changes, but I'm not sure if I deserve credit for it :)

**Comment by kwonoj** [comment]
I do believe you can definitely make PR and sincere apologies that I did create PR without properly checking you were working on it @ysimonson - I'll be careful for futher task. :pray:

**Comment by ysimonson** [comment]
No worries @kwonoj! It's my fault for not self-assigning, and I wouldn't have got it passing without seeing the fix you added.
