### ISSUE TITLE
Implement Node.getRootNode

### ISSUE THREAD

**Issue by nox** [servo/servo#13699]
`Node.rootNode` should be removed as per https://github.com/whatwg/dom/commit/42a45eb0d1af13e510620b6b29696997f0c7aa3d and replaced by [`Node.getRootNode`](https://dom.spec.whatwg.org/#dom-node-getrootnode) as per https://github.com/whatwg/dom/commit/579ef079ded65daa981cac974648621790839072.

Files:
* components/script/dom/node.rs
* components/script/dom/webidls/Node.webidl
* tests/wpt/metadata/dom/historical.html.ini
* tests/wpt/metadata/dom/nodes/rootNode.html.ini
* tests/wpt/metadata/dom/interfaces.ini

**Comment by Rafagd** [comment]
Can I give this a try?

**Comment by nox** [comment]
Sure! :)

**Comment by Rafagd** [comment]
Could you show me how should I test this?

**Comment by Rafagd** [comment]
What is the difference between `NodeMethods::ancestors(&self)` and `NodeMethods::inclusive_ancestors(&self)`?

I'm assuming the latter refers to this '[shadow-including-root](https://dom.spec.whatwg.org/#concept-shadow-including-root)`.

If so I'm assuming that I should return `NodeMethods::inclusive_ancestors(&self)` if `options.composed` is `true`, and `NodeMethods::ancestors(&self)` if it is false.

Am I correct here?

**Comment by jdm** [comment]
Inclusive_ancdstors includes the node itself. That's the only difference.

**Comment by Rafagd** [comment]
Ok, so from what I gather now, a node can categorized as Root, Shadow Root and Normal.

What was implemented before is how to reach the Root node. What I need to do when `composed = true` is to check every ancestor node and stop on the first one that is a `shadow-root`.

But how do I detect if the node is a `shadow-root'?

**Comment by Ms2ger** [comment]
I suggest you ignore everything related to shadow roots; just implement the no-argument form of `getRootNode()`, using the same implementation as the `rootNode` attribute we have right now.

**Comment by Rafagd** [comment]
I've sent this pull request: https://github.com/servo/servo/pull/13703, which already implements the `getRootNode()` method but ignores whatever it has received as argument and returns what the old `rootNode` property was returning before.

**Comment by Rafagd** [comment]
> FAIL [expected PASS] Node interface: calling `getRootNode(GetRootNodeOptions)` on `document.querySelector("[id]").attributes[0]` with too few arguments must throw TypeError

Does the official spec expects the argument to be mandatory?
Seems like a odd design choice for a function that only has one option anyway.
I suppose I should make these Expect: FAIL for now, right?

**Comment by KiChjang** [comment]
I'm not sure why you're getting these errors. The build results are completely contrary to what you're describing here (http://build.servo.org/builders/mac-rel-wpt1/builds/273/steps/test_1/logs/stdio).

**Comment by Rafagd** [comment]
The build errors have surfaced after I've updated the tests expectations:
- `tests/wpt/metadata/dom/historical.html.ini`
- `tests/wpt/metadata/dom/nodes/rootNode.html.ini`
- `tests/wpt/metadata/dom/interfaces.ini`

They happen because I've changed the expectations to be something that wasn't supposed to be.
I'm just asking out of curiosity.

**Comment by KiChjang** [comment]
You haven't pushed your code changes to your PR branch and we haven't ran a try run yet, how are you getting these results?

**Comment by Rafagd** [comment]
./mach test-wpt dom

**Comment by KiChjang** [comment]
AFAIK, changing test expectations do not, and should never cause any behavioral changes. I suspect that there's a difference in the WPT test environment on your local machine vs. buildbot. Could you push your code changes to your PR branch and we'll run a try run and see whether the problem still persists?

**Comment by Rafagd** [comment]
Well, it was mostly my fault.

I just blindly changed every test on `getRootNode(GetRootNodeOptions)` to `PASS`.

Both of them happen because attributes are not inheriting the method `getRootNode`, I assume.
I don't think they are supposed to, so I've asked just to make sure my assumptions are correct and changed both cases to expect `FAIL`.

There are also some tests implying that the argument on `getRootNode` was supposed to be mandatory, in which case they are supposed to expect `FAIL`, but since I've been asked to remove the parameter altogether I've changed them to `PASS`.

Anyway, I've pushed my changes to my branch.
