### ISSUE TITLE
Geckolib unit tests are busted

### ISSUE THREAD

**Issue by jdm** [servo/servo#13721]
It's not clear to me why this is broken on Travis and isn't showing up on builders.
```
./mach test-geckolib
error: use of extern static requires unsafe function or block (error E0133)
    --> /home/travis/build/servo/servo/target/debug/build/style-b398ea74b908472c/out/gecko_properties.rs:6306:46
     |
6306 |             Some(number) => cmp::min(number, nsStyleColumn_kMaxColumnCount),
     |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
     = note: for more information, see issue 36247 <https://github.com/rust-lang/rust/issues/35112>
note: lint level defined here
    --> /home/travis/build/servo/servo/components/style/lib.rs:35:9
     |
35   | #![deny(warnings)]
     |         ^^^^^^^^
error: aborting due to previous error
error: Could not compile `style`.
To learn more, run the command again with --verbose.
The command "./mach test-geckolib" exited with 101.
```

**Comment by Manishearth** [comment]
@bholley turned on `#[deny(warnings)]` in another PR, that might have caused this? Perhaps we should `#[allow(warnings)]` there?

**Comment by Manishearth** [comment]
Oh, wait, that's in a macro and that doesn't work. Right.

**Comment by Manishearth** [comment]
This happens because `test-geckolib` wrongly runs in a Servo build env, using the servo nightly and the servo target dir, instead of the geckolib stable + geckolib target dir. The latest compiler is whinier about the warnings (see comment in style/lib.rs), hence the error.

test-geckolib doesn't do anything anymore -- it's obsolete now that the crates have been merged. Removed in #13722
