### ISSUE TITLE
`mach clean` should remove generated Android files

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#13800]
The `support/android/apk` directory contains generated Android files (Java classes, Android libs, ... see the `.gitignore` there), which are created by `mach package`, and are not cleaned by `mach clean`. This can be a slightly annoying during Android-related development.

**Comment by mmatyas** [comment]
CC @larsbergstrom, @dati91

**Comment by Ms2ger** [comment]
Should the generated code be moved to the objdir instead? Theoretically it should be possible to build with the source in a read-only filesystem.

**Comment by metajack** [comment]
@ms2ger Since `target` is put in the src dir, I don't think we can make that claim, but definitely we should put all generated files in `target`. There have been a few cases in the past where this was not possible due to some technical reason, but it seems like that shouldn't be an issue here and we can just run ant from the right place pointed to the right build files.

**Comment by larsbergstrom** [comment]
I'm a little worried that we might have to copy the entire directory over to the build output dir and build there. The apk build tools that we use from the NDK are pretty sloppy about assuming they can create stuff like a "project.properties" file right next to the makefiles that they are building.

Of course, the right answer here might be to switch to either gradle or whatever the other even-newer build system is (bazel?) for building Android. We're at least one and possibly two toolchains behind right now :-)
