### ISSUE TITLE
Tidy check for etc/ci/buildbot_steps.yml

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#13838]
Now that we are reading Buildbot steps from the main servo/servo repo, we should have a tidy check to ensure the steps file is well formed. (If it is not, the build will fail cleanly, but this makes it easier to catch quick typos locally or on Travis.)

Well-formedness includes:
- file is a valid YAML file
- the file is a map from builder names to list of strings (where each string represents a build step)

Implementation notes:
- use the safe_load variant to try loading the YAML file

Files:
- python/servo/tidy/servo_tidy/tidy.py
- Add a test (or more than 1) to python/servo/tidy/servo_tidy_tests

**Comment by birryree** [comment]
I'll handle this one.

**Comment by KiChjang** [comment]
Go for it!

**Comment by birryree** [comment]
@aneeshusa 

I have code written for this, but wanted to run some things by you.

### 1. Checking for duplicate keys?

I wrote a duplicate YAML key checker as part of my changes because the `PyYAML` module will gladly accept duplicate keys in a `.yml` file and then clobber data. Do you want this functionality?

### 2. Certain typos/improper indentations

I don't have a solution for this one yet, but: Do you want me to support additional well-formed YAML but definitely not-well-formed `buildbot_steps.yml` configurations like this that may result from, say, improper indentation or typos?

```
   mac-dev-unit:
  - ./mach build --dev
    - ./mach test-unit
    - ./mach build-cef
    - ./mach build-geckolib
  - bash ./etc/ci/lockfile_changed.sh
  - bash ./etc/ci/manifest_changed.sh
```
`PyYAML` will load the above like this: 
    
```
['./mach build --dev - ./mach test-unit - ./mach build-cef - ./mach build-geckolib',
 'bash ./etc/ci/lockfile_changed.sh',
 'bash ./etc/ci/manifest_changed.sh']
```

So it's still a valid `buildbot_steps.yml` if we just go by `mapping to list of strings`, but it's clearly a wrong configuration.

### 3. What should the emitted message be for the following cases?


#### Duplicate Keys

I currently emit `Duplicated key [KEY]`, similar to the `json` checker.

#### Unloadable YAML file

I currently emit a line number and the exception message, so it might look like this:

```
./etc/ci/buildbot_steps.yml:22: while scanning a simple key
  in "<string>", line 14, column 1:
    mac-dev-unit
    ^
could not find expected ':'
  in "<string>", line 22, column 1:
    mac-rel-css:
    ^
```

#### Key doesn't map to a `list` object

For something like, say:

```
mac-dev-unit: ./mach build --dev
```

After loading, the mapping looks like this:

```
{ 'mac-dev-unit': './mach build --dev' }
```

Currently I emit a rather large message:

```
Key 'mac-dev-unit' maps to a 'str', but mapping to 'list' expected.
```

#### Key's mapping list contains non-`str` items

A good example would be a mapping to a list-of-lists, like so:

```
mac-dev-unit:
  - - ./mach build --dev
    -  ./mach test-unit
```

This results in this mapping:

```{ 'mac-dev-unit': [[ './mach build --dev', './mach test-unit' ]] }```

I currently emit the message:

```List mapped to 'mac-dev-unit' contains non-string element.```

---

I think the big parts will be what messages should be emitted for the cases in (3) - I'm trying to come up with some good wording but still think they're a little too esoteric.

**Comment by aneeshusa** [comment]
@birryree Feel free to open a WIP PR, it's easier to review inline. Responses to your questions:

1) Yes, checking for duplicate keys definitely sounds useful to have!
2) The goal is to lint the `buildbot_steps.yml`, so any specific linting heuristics like that you can add are helpful. Just make sure to keep the `buildbot_steps.yml` specific things separate so the general YAML checking can be reused.
3) The wording you have sounds fine; I wouldn't stress too much about them yet since I don't expect this to get that much usage. If possible, it would be helpful to get line numbers for some of the other errors.

Also, I'm considering making the format more complicated in the future to make it more powerful and relaxing some of these restrictions, so no need to go overboard with the linting.
