### ISSUE TITLE
Teach tidy to fail on WIP commits

### ISSUE THREAD

**Issue by nox** [servo/servo#14388]
I don't want to land such a commit again. How embarrassing.

**Comment by Wafflespeanut** [comment]
We should add a new function `check_commits` (or something similar), which invokes `git` as a subprocess, getting the last commit has, similar to [this](https://github.com/servo/servo/blob/dc92a5119997e13feb095d00777b1c2c1ce5c03d/python/tidy/servo_tidy/tidy.py#L121). Once we get that, `git log <hash>..HEAD --format=%s` should list the commit messages since that merge. Now, we need to ensure that the messages don't have `WIP`. Testing this would require playing with a new/existing git repo, so we don't have to add any tests for this.

Code: `python/tidy/servo_tidy/tidy.py`

**Comment by SijmenSchoon** [comment]
I'm in, seems like a nice starting issue to get involved with this project

**Comment by Wafflespeanut** [comment]
Great! Let us know if you have any questions :)
