### ISSUE TITLE
Rewrite bluetooth manager methods to return Result instead of sending values over a channel

### ISSUE THREAD

**Issue by jdm** [servo/servo#14590]
The code will be more idiomatic and less redundant if it's converted from:
```rust
fn gatt_server_connect(&mut self, device_id: String, sender: IpcSender<BluetoothResponseResult>) {
   drop(sender.send(Ok(...)))
}
self.gatt_server_connect(device_id, sender)
```
into
```rust
fn gatt_server_connect(&mut self, device_id: String) -> BluetoothResponseResult {
   Ok(...)
}
let _ = sender.send(self.gatt_server_connect(device_id));
```
This will mean we can rewrite the `get_adapter_or_return_error` macro to be a method that returns a result, and the code that uses the macro can use `try!` when calling it instead. This will give us more idiomatic Rust code and it will be harder to accidentally not send a response on the channel.

Code: `components/bluetooth/lib.rs`
Tests: `./mach test-wpt tests/wpt/mozilla/tests/mozilla/bluetooth/`

**Comment by impowski** [comment]
I'll take it.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear!

**Comment by impowski** [comment]
@jdm So what about that `get_adapter_or_return_error` macro? As I understood I need to remove `sender` from there and just return `Err(...)` or `adapter`, but since you said that you want to use `try!` on it it should basically return `Ok(adapter)` then. I see that there is more methods which use `sender` and same macro inside so I should change them too.

**Comment by jdm** [comment]
@impowski I mentioned rewriting from a macro into a method instead. And yes, we should change all of the methods that are written in this style.
