### ISSUE TITLE
Frame should store some of the data that is currently in Pipeline

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14692]
There is some data we are currently storing in Pipeline that should really be in Frame: `parent_info`, `size`, `is_private` and `visible`.

**Comment by nox** [comment]
If you wrote some more details, this issue could probably be E-Easy or E-Mentored.

**Comment by asajeffrey** [comment]
Not sure about E-easy, this refactoring touches a lot of code. Might be doable as E-Mentored. cc @cbrewster

**Comment by mandreyel** [comment]
I tried to look for `Frame` but didn't find it. Has it been renamed, removed, or did I just miss it? Is this issue still relevant (the mentioned fields are still in `Pipeline`)?

**Comment by mandreyel** [comment]
Ah, that makes sense, I recall seeing a few TODOs sprinkled in `Pipeline` to move some fields to `BrowsingContext`.

In that case I'd like to try my hand at this! I can probably start working on it Friday!

**Comment by jdm** [comment]
Please do!

**Comment by mandreyel** [comment]
Okay, so I had some time to work on this and I'm mostly done, but there is one pesky bit that I cannot seem to figure out on which I need your input.

After loading a document inside an iframe for the *first time*, `Constellation::handle_session_history_change` is eventually called, which in this case needs to set up a new `BrowsingContext` for the iframe as it does not exist yet, and insert this new browsing context into its containing parent `Pipeline`'s `children: Vec<BrowsingContext>` field.

Previously it was solved like [this](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L861-L868), but now that `BrowsingContext` instead of `Pipeline` keeps track of its containing parent `Pipeline`, a conundrum arises in that we cannot add this new browsing context to its would-be parent pipeline, since the context has just been created and thus its (optional) field for keeping track of its parent pipeline has not yet been set, nor does its parent pipeline's `children` field contain this browsing context (and thus we cannot find the pertaining pipeline starting from iframe's top level browsing context). So I'm not sure what the best way would be to "attach" a new iframe's browsing context to its parent pipeline.

I see one possible solution: [`Constellation::handle_script_new_iframe`](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L1824) is invoked when script notifies constellation of a new iframe with an [`IFrameLoadInfo`](https://github.com/servo/servo/blob/master/components/script_traits/lib.rs#L600) object, which *does* contain the ID of its parent pipeline. So the new iframe's `browsing_context_id` could simply be inserted in its parent pipeline's `children` field in this function?
However, I'm not sure if this were to break any behaviour since this change would mean that the parent pipeline's `children` field would contain a browsing context whose document hasn't been loaded yet, while previously it was only inserted once the document had become active.

What do you think? Do you see another solution?

Please note, though, that I may just have misunderstood some (or many) things since I'm not yet fully familiar with Servo's code :)

**Comment by mandreyel** [comment]
Another option would be to store a `parent_pipeline_id: Option<PipelineId>` field in `SessionHistoryChange`, so that when the iframe's document is done loading and becomes active we can access the parent pipeline and attach iframe's browsing context to it. I think either could work, though perhaps the previously proposed solution is a bit cleaner--unless that won't work due to the described slight change in behaviour.

**Comment by cbrewster** [comment]
The second approach (adding a new field to `SessionHistoryChange`) sounds like the right way to go about this. The first approach would end up being a behavior change which may cause some test failures (I believe I tried a change similar to that a while back with that result).

**Comment by mandreyel** [comment]
@cbrewster Thanks for chiming in! Having thought about it some more, I would now go with the second approach as well.

In fact, I had initially overlooked that the same difficulty exists when passing `is_private` to a new `BrowsingContext` and probably when passing `visible`--though I don't fully understand the role of the latter yet, so I'm not sure if this could be set at a later point.

I suppose I could just stuff all fields in `SesssionHistoryChange` for now, and see if there is a better solution.
