### ISSUE TITLE
https://download.servo.org/ expired cert.

### ISSUE THREAD

**Issue by a-p-** [servo/servo#14795]
https://download.servo.org/ currently appears to be using a certificate that expired on Dec. 29, 2016.

**Comment by chr4** [comment]
Would it be possible to publish checksums of the files, so it's possible to verify the downloads in the meantime?

**Comment by jdm** [comment]
This is being tracked at https://github.com/servo/download.servo.org/issues/12. Thanks for reporting it!

**Comment by aneeshusa** [comment]
@chr4 That's a good idea, I've added a tracking issue at servo/download.servo.org#14. Unfortunately it's not very helpful without HTTPS, since a MITM could just rewrite the checksums to match any altered files. Since we publish nightlies for multiple platforms, that's too many files to publish checksums for in e.g. this thread.
