### ISSUE TITLE
Experiment with incremental builds

### ISSUE THREAD

**Issue by jdm** [servo/servo#14870]
```
<nmatsakis> 	pcwalton: I won't get to that testing just now, but you can basically do `mkdir ~/incr; RUSTFLAGS=-Zincremental=$HOME/incr` and give it a spin. At some point there was an ICE with the script crate but that has been fixed, still a rustup may be needed :/
```

**Comment by jdm** [comment]
https://github.com/rust-lang/rust/issues/39208

**Comment by SimonSapin** [comment]
Apparently we can now use `CARGO_INCREMENTAL=1`, and Cargo will take care of managing the cache directory somewhere in `target/`.

**Comment by jdm** [comment]
Further updates in https://internals.rust-lang.org/t/incremental-compilation-beta/4721/17.

**Comment by SimonSapin** [comment]
I’m waiting for the next nightly to try that last fix (https://github.com/rust-lang/rust/pull/39424).

**Comment by SimonSapin** [comment]
Well, I didn’t wait. With Rust master, incremental compilation cuts build times after `touch components/style/lib.rs` by ~30% compared to `-C codegen-units=4`. Note though that this is the ideal case for incremental compilation since nothing other than a source file timestamp changes. The time for a real rebuild (with few but non-zero changes) would be somewhere in-between.

As a first step, let’s add it opt-in: https://github.com/servo/servo/pull/15390

**Comment by nox** [comment]
Experimenting was done, given we even have a flag to use it in `mach` now.
