### ISSUE TITLE
Determine if a Document is active

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14876]
(After  #14559 merges)
We currently can only check if a document is `fully active`; however, there are places in the spec that require us to check if the document is just `active` (example: https://html.spec.whatwg.org/multipage/webappapis.html#dom-document-write step 3 whatwg/html#2216). We need to implement a flag to keep track of this.

cc @asajeffrey

**Comment by asajeffrey** [comment]
The way I've been thinking about this is to remove the current freeze and thaw messages that are sent from the constellation to the script thread, and replace them by a message which sets the activity level: either fully active, active or inactive. Slightly annoyingly this means that when we traverse or navigate away from a fully active document document, we need to send a message to every one of its descendants informing them that they're now active rather than fully active.

AFAIK this is just needed for `document.write`.
