### ISSUE TITLE
Implement parsing/serialization for mask-position-{x,y}

### ISSUE THREAD

**Issue by upsuper** [servo/servo#14955]
The spec doesn't have this yet, neither does MDN. But the syntax is basically identical to `background-position-{x,y}`, so it can share the logic of `background-position`.

Files for `mask-position-{x,y}`: https://github.com/servo/servo/blob/master/components/style/properties/longhand/svg.mako.rs
`mask-position` should become a shorthand and be moved to https://github.com/servo/servo/blob/master/components/style/properties/shorthand/mask.mako.rs in this change.

`background-position-{x,y}` is in https://github.com/servo/servo/blob/master/components/style/properties/longhand/background.mako.rs

**Comment by Manishearth** [comment]
@canaltinova want to work on this? or mentor it for someone else?

**Comment by upsuper** [comment]
Filed spec issue for this: w3c/fxtf-drafts#103.

**Comment by upsuper** [comment]
(This may account to up to 1383 failures in style system mochitests.)

**Comment by canaltinova** [comment]
@Manishearth If you think this is easy or less-easy, I can mentor this. Otherwise, I can pick this up. I think we can directly re-export background-position-{x,y} in mask-position-{x,y}.

Similar work for background-position is here: #14509 (ignore first commit)

**Comment by Manishearth** [comment]
Should be easy. Mind leaving a comment with tips on how to make this work?

(Yes, reexporting should be fine.)

**Comment by canaltinova** [comment]
Firstly, we need to implement mask-position-{x,y} as longhands to [here](https://github.com/servo/servo/blob/master/components/style/properties/longhand/svg.mako.rs). It can be done by re-exporting background-position-{x,y} structs([here'](https://github.com/servo/servo/blob/04a3242dc54c670dcdafcf1f0ac5373f2ed612f3/components/style/properties/longhand/box.mako.rs#L827-L838)s an example for this)

After implementing these, we need to convert mask-position to a shorthand. To do this, you can copy and paste background-position to shorthand/mask.mako.rs and convert backgrounds to mask.

And we are going to need to fix `mask` shorthand. We can't mask-position as a sub-property for mask because mask-position become a shorthand on it's own. So we need to write mask-position-x and mask-position-y to mask shorthands instead of mask-position and fix parse implementation. Similar work can be seen in background-position-{x,y} [implementation](https://github.com/servo/servo/pull/14509/commits/ed806efade6b7131a315a4a2ffd48db90971ef2e#diff-947ecedec82b7d6030d6744492b7d2efL9).

Some additional changes probably will be needed but error messages should help.
Ask here or in IRC if anything is unclear.

**Comment by canaltinova** [comment]
Also it will require some changes in gecko glue like background. We can move [these](https://github.com/servo/servo/blob/04a3242dc54c670dcdafcf1f0ac5373f2ed612f3/components/style/properties/gecko.mako.rs#L1838-L1886) functions inside `impl_common_image_layer_properties` again(instead of [these](https://github.com/servo/servo/blob/04a3242dc54c670dcdafcf1f0ac5373f2ed612f3/components/style/properties/gecko.mako.rs#L1583-L1646) functions) and make use of both mask and background I guess.

**Comment by mrmiywj** [comment]
@canaltinova Hi, I'm glad to work on this, could you mentor me?

**Comment by canaltinova** [comment]
@mrmiywj Sure! Feel free to ask any questions!

**Comment by Manishearth** [comment]
Note that this will need to be tested with  `./mach build-geckolib`
