### ISSUE TITLE
position_fixed reftest identical to its reference

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#1516]
Sorry I’m late to the party, but I notice that `src/test/ref/position_fixed_a.html` and `src/test/ref/position_fixed_b.html` (added in #1440) are identical.

This really doesn’t work, as a reftest. The idea is to use the feature being tested in the test page, and have a reference page that does *not* use the feature but should render identically. A bug in the feature being tested will (hopefully) make the test render differently from its reference.

@ibnc, please try to modify these files to make them a reftest. Sometimes coming up with a reference is hard, especially when we have so few layout primitives that are implemented yet. Maybe the reference here could use negative margins. (Do we support those?) If a reftest proves too difficult, please remove the files.

**Comment by mbrubeck** [comment]
These files have moved to these new locations:

* [tests/wpt/mozilla/tests/css/position_fixed_a.html](https://github.com/servo/servo/blob/bcea0ada27de694cd0c465d04fd35eba70503d62/tests/wpt/mozilla/tests/css/position_fixed_a.html)
* [tests/wpt/mozilla/tests/css/position_fixed_b.html](https://github.com/servo/servo/blob/bcea0ada27de694cd0c465d04fd35eba70503d62/tests/wpt/mozilla/tests/css/position_fixed_b.html)

Fixing this will require changing these HTML+CSS files so that the test ("a") file uses `position: fixed`, while the reference ("b") file uses some other styling to achieve the same desired output.  See the link above for more details, and [tests/wpt/README.md](https://github.com/servo/servo/blob/bcea0ada27de694cd0c465d04fd35eba70503d62/tests/wpt/README.md) for instructions on running and editing the tests.

**Comment by mitchhentges** [comment]
I've got this, probably
