### ISSUE TITLE
letter-spacing and word-spacing should accept negative length value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15204]
Spec:
https://drafts.csswg.org/css-text-3/#letter-spacing-property
https://drafts.csswg.org/css-text-3/#word-spacing-property

Relevant code:
https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_text.mako.rs#L337
https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_text.mako.rs#L418-L419

**Comment by samuknet** [comment]
I'd like to give this a go

**Comment by jdm** [comment]
Great! Ask questions if anything's unclear :)

**Comment by samuknet** [comment]
Test case can be found [here](https://samuknet.github.io/test_cases/negativeLetterSpacingWordSpacing/index.html).

**Comment by samuknet** [comment]
@jdm 
I was thinking for letter-spacing it would look like:
Add `pub fn parse_any...` to https://github.com/servo/servo/blob/master/components/style/values/specified/length.rs#L350-L353, which parses both positive and negative values.

Change `pub fn parse...` for `letter-spacing` to use the new `parse_any` instead of `parse_non_negative`.

Then it seems there is no use for the old `parse_non_negative` in `length.rs` so it can be removed.
