### ISSUE TITLE
Service worker code only supports a single content process

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15217]
When a new content process is spawned, we send a `SWManagerMsg::OwnSender` message to the constellation, which does
```rust
                // store service worker manager for communicating with it.
                self.swmanager_chan = Some(sw_sender);
```

and any previous value of that field is gone.

**Comment by gterzian** [comment]
Ok I'd like to fix this one, and I think this actually is a chance to change the infra for service worker a bit, and do something we haven't done yet: run something else than  a script-thread in it's own process. 

The issue mentioned above is essentially due to running the `ServiceWorkerManager` into the script-process(in multi-process mode), and having the constellation only have the ability to have one. 

However, the real solution I think is to not actually run the `ServiceWorkerManager` in the script-process at all. 

Instead, I think we should try to run each `ServiceWorkerManager` in their own process, and have the constellation own a map of `ImmutableOrigin` -> `ServiceWorkerManager`. 

The `ServiceWorkerManager` would then be similar to an `EventLoop`, essentially a process running script code, however it would be running a service worker event-loop instead of a window event-loop(and potentially dedicated worker event-loops). Since service workers are supposed to be entirely event-driven, I think we can get away with running one thread per `ServiceWorkerManager`, which would run the event-loop for all service worker global scopes for a given origin. 

Then, similar to what has already been done with [`WebGPU`](https://github.com/servo/servo/blob/15d8c6058bb5fd21036cb35500a0c2f23a9ef7f7/components/constellation/constellation.rs#L246), the constellation would create a `ServiceWorkerManager` for a given origin when an `EventLoop` would first start using a `ServiceWorker`. 

I think this is also important as a step to be able to fully implement service workers, since they are supposed to be shared on a per-origin basis across the entire browser(currently they are scoped to an script-process, meaning that there can be multiple ones for one origin), and they are also supposed to be able to run when there is no window open at all, so by running them in their own process outside of an `EventLoop`, we both ensure there is only one per origin across the UA, and we also open the door to running them even when there are no `EventLoop` running. 

@jdm what do you think of that proposal? 

cc @CYBAI

**Comment by CYBAI** [comment]
> since they are supposed to be shared on a per-origin basis across the entire browser (currently they are scoped to an EventLoop, meaning that there can be multiple ones for one origin when they are not part of the same browsing-context-group)

I haven't dig into Servo's SW infra though, I recently studied a little bit about SW and yes, I agree with on this!

**Comment by gterzian** [comment]
Ok in the light of https://github.com/servo/servo/issues/7458#issuecomment-606647467 I will try to fix this without introducing more processes...

**Comment by gterzian** [comment]
Ok as a bit of a recap of https://github.com/servo/servo/issues/7458#issuecomment-607047926, and 

1. In order to fix this issue, I would like to run the "service worker manager" in it's own process, and have the constellation own a map of "Origin" -> "Sender to a worker manager process". 
2. That way, we don't start the `ServiceWorkerManager` in each content-process, instead, when a content-process starts using a service worker, it would send a message to the constellation, which could then either spin-up a manager for that origin, or simply keep using a manager that is already running for that origin. 
3. After that, everytime a content-process needs to do an operation with the service worker, the message goes via the constellation and it forwarded to the manager running in its own process. 

That way, at the cost of an additional process, we get a clearly isolated(from a business logic perspective) `ServiceWorkerManager`, acting a bit like an `EventLoop` does for a script-thread. 

I tried fixing it without introducing the new process, in https://github.com/servo/servo/pull/26073, and as noted in https://github.com/servo/servo/issues/7458#issuecomment-607047926, I think going that way would open a can of worms. It means we need to keep an `EventLoop` alive when its running a worker manager that is(or could be) used by other `EventLoop`, and all sorts of other business logic that would go away if we just put the worker manager in it's own construct at the constellation level. 

Also, with this structure, there is no logical difference between single- and multi-process mode. Essentially, the `ServiceWorkerManager` is an `EventLoop`-like construct that either runs in it's own process or not. The current problem in this issue is an example of how something can suddenly not work in either mode, hence requires additional business logic. 

@Manishearth @asajeffrey @jdm Since this is quite a change, please let me know what you think. I think this equally applies to fixing Service workers, as well as to a potential implementation of Shared workers(Actually both could potentially run in one process per origin, so of like how an `EventLoop` is running a bunch of different things as well).

**Comment by jdm** [comment]
I'm in favour!
