### ISSUE TITLE
Serialization of custom property declaration should contain a whitespace after colon if the value is a CSS-wide keyword

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15401]
The following code:
```html
<!DOCTYPE html>
<p style="--a:inherit">hello</p>
<script>
  alert(document.querySelector('p').style.cssText);
</script>
```
should generate `--a: inherit` instead of `--a:inherit` (notice the whitespace after colon).

I think the relevant code is https://github.com/servo/servo/blob/master/components/style/properties/properties.mako.rs#L976-L985 where `value_is_unparsed` unconditionally returns `true` for custom properties, while CSS-wide keywords are actually parsed values. (The parsing code is just several lines below the `value_is_unparsed` function.)

**Comment by munyari** [comment]
@highfive: assign me

**Comment by munyari** [comment]
Hi @upsuper! First time contributor and sorta rust noob here. I can see the `parse` function right below `value_is_unparsed` which you refer to. There, it looks like we pattern match on `PropertyId` instead of `PropertyDeclaration`. From what you said above, css-wide keywords should return false. Should other `Custom` property declarations return true? Looks like `Custom` has a `Name` and `DeclaredValue`. Which is relevant in determining whether it is a css-wide keyword?

**Comment by upsuper** [comment]
No. Other value for custom property should be treated as unparsed, because they are basically just raw string. Only CSS-wide keywords should be considered parsed.

Note that, `--a: foo` is different from `--a:foo` per spec, so we cannot add whitespace after colon if the value is not a CSS-wide keyword.

**Comment by jdm** [comment]
@munyari Have you made any progress yet?

**Comment by munyari** [comment]
Hey @jdm, sorry for taking so long to update on this issue. Life gets in the way sometimes. I've now opened my PR.

**Comment by Wafflespeanut** [comment]
#15918 has fixed this.
