### ISSUE TITLE
Consider linting commit titles and messages

### ISSUE THREAD

**Issue by nox** [servo/servo#15472]
We have way more Gecko people than before contributing to Servo, and it doesn't seem to me like Mercurial users have any kind of similar conventions as Git users when it comes to commit messages.

Messages such as https://github.com/servo/servo/commit/e7a8f5ec30c68f9ff760186abc88daa9d5dc09fe are quite painful for me to read with the `bug <number> - ` thing, lengthening the commit title so much it's unreadable from Git command line and GH's commit log.

Could we put in place some linting over commit messages? Even if only for the maximum length of the commit title?

There are various CI tools that plug into GH to do that already.

Cc @jdm @bholley

**Comment by jdm** [comment]
We already lint for WIP in commit titles. We can add more checks to that, we just need to determine what we want to check for.

**Comment by bholley** [comment]
Nit: It's not really git-vs-hg so much as bugzilla-vs-github (I do all my mozilla work in git).

I'm fine to settle on whatever convention the Servo folks want, though we may want to consider whether it's important to be able to convert between both title formats in a lossless manner. CC @indygreg for thoughts there.

**Comment by indygreg** [comment]
The Git -> Mercurial conversion rewrites the commit message summary line to include the PR title (from the GitHub API). It also does minimal other massaging to add a prefix and say where the PR came from. Code is at https://hg.mozilla.org/hgcustom/version-control-tools/file/de7ba86773e9/vcssync/mozvcssync/gitrewrite/__init__.py#l225 and can easily be changed.

The important thing from the perspective of the current state of that tool is that the PR title in servo/servo is what matters.

**Comment by bholley** [comment]
@indygreg this is about what kind of conversion we want to do in the Mercurial->Git (or more precisely, m-c => s/s) direction.

**Comment by nox** [comment]
@bholley It is also git-vs-hg in my book, for example none of your commits in https://github.com/servo/servo/pull/15480 follow Git recommendations. See https://git-scm.com/book/ch5-2.html#_commit_guidelines.

**Comment by bholley** [comment]
> @bholley It is also git-vs-hg in my book

It's not a very important distinction, but this isn't true. Mozilla's commit formatting convention predates hg by almost a decade, and is used across projects with a number of different source-control backends.

>, for example none of your commits in #15480

To be fair, that PR is a WIP, and the only reason it's in PR form is because submitting a PR is a prerequisite to performing a try push. I will do my best to rewrite commit messages before pushing them on the servo side, but it's an extra step that I (and others) may forget until the process is automated by the autolander. A tidy lint would be helpful.

> follow Git recommendations (and all the titles thus get truncated on GH and won't appear neatly in a console).

Specifically the prefixing of |Bug XXXXXXX - | in each title? That can certainly go away, but I don't think the commit titles are otherwise particularly long.

**Comment by nox** [comment]
The "Bug XXXXXX" part is actually useful, but as you can see on #15480, all your titles are truncated. AFAIR, Github's limit is slightly more than what Git recommends.

**Comment by nox** [comment]
The people have spoken and they don't want this.
