### ISSUE TITLE
text-overflow accepts (and ignores) anything for their second part of value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15491]
Test code:
```html
<!DOCTYPE HTML>
<div style="text-overflow: clip rubbish"></div>
<script>
alert(`decl: ${document.querySelector('div').style.textOverflow}`);
</script>
```

The relevant code should be https://github.com/servo/servo/blob/master/components/style/properties/longhand/text.mako.rs#L52-L72

**Comment by canaltinova** [comment]
To fix this, we need to wrap the second `Side::parse(context, input)` with `input.try()` in the parse function. 
This fails currently because of [this line](https://github.com/servo/servo/blob/0c102e2350a637869cee2bc479ea4665f95e0ddd/components/style/properties/longhand/text.mako.rs#L66). This match arm returns Err, but also the ident value(which is wrong one) is consumed by `input.expect_ident()`. `input.try` ensures that, the parser's position will be revoked if it gets an Error. The longhand parsing will fail if parser is not exhausted.
`input.try` usage examples can be seen here:
https://dxr.mozilla.org/servo/search?q=input.try(&=servo

**Comment by canaltinova** [comment]
@abhiQmar would you like to work on this?

**Comment by abhiQmar** [comment]
@canaltinova Yes, sure. Thanks.
@highfive: assign me
