### ISSUE TITLE
Move style::thread_state to constellation::thread_state

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#15610]
`thread_state.rs` checks whether the current thread calling `get()` is the script thread or the layout thread. This should really be located in the constellation component, since the constellation manages all information pertaining to threads.

Code: `components/style/thread_state.rs`
No need for any tests; if it compiles, it's good for a PR.

cc @jdm @Ms2ger @emilio @asajeffrey

**Comment by SimonSapin** [comment]
Hang on, this requires adding a dependency from `style` to `constellation`, which:

* Would add a whole bunch of new crates to `build-geckolib`. Is a vague "it should be located there" worth that?
* Doesn’t work anyway since `constellation` depends on `gfx` which depends on `style`, and we can’t have cycles in the crate dependency graph.

**Comment by SimonSapin** [comment]
Also keep in mind that `build-geckolib` (whose root crate is `ports/gecko`) needs to compile on stable Rust.

**Comment by Ms2ger** [comment]
What Simon said.
