### ISSUE TITLE
The pref layout.threads should have a default sensible value

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15638]
_This issue is part of an effort to improve Servo's embedding story. See https://github.com/paulrouget/servoshell/projects/2_

Starting Servo from a third party application requires setting the `layout.threads` pref, otherwise pipeline creation fails:

```
PREFS.set("layout.threads", PrefValue::Number(1.0));
```

**Comment by metajack** [comment]
To do this, I think we should add a default_prefs() function to https://github.com/servo/servo/blob/master/components/config/prefs.rs. Then call this from default_opts() in https://github.com/servo/servo/blob/master/components/config/opts.rs#L503.

The actual initial setting should be the same as https://github.com/servo/servo/blob/bc9d7863b6763e59f7efed3d5c9870b19bafb195/components/config/opts.rs#L890-L891

It may be worthwhile extracting that to its own function in prefs.rs so at least that magic number is stored in a unique place.

**Comment by metajack** [comment]
Out of curiosity, I'd like to know why layout.threads is a preference not an option, and what our criteria for option vs. preference is. But that is not in the scope of this bug.

**Comment by zombiefungus** [comment]
@highfive: assign me
@metajack may I eventually ping you for help ?

**Comment by paulrouget** [comment]
@zombiefungus you can also ping me if you need help.

**Comment by metajack** [comment]
@zombiefungus Of course. You can reach me in IRC or just mention me in the bug. If @paulrouget or I aren't around, most folks in the IRC channel will be glad to assist as well.

**Comment by paulrouget** [comment]
I see that `components/constellation/pipeline.rs` and `components/script/dom/htmliframeelement.rs` both use `PREFS.get("layout.threads")`.

Like Jack mentioned, we could maybe use option instead. And I think it make more sense.

So in these 2 files we would use `opts` instead. And initialize opts::layout_threads to:

1) command line value (`-y X`)
2) if no command line, initialize with preference `PREFS.get("layout.threads")`
3) if no command line and no pref, then use [this code](https://github.com/servo/servo/blob/bc9d7863b6763e59f7efed3d5c9870b19bafb195/components/config/opts.rs#L890-L891). This should be done in `default_opts()`.


@zombiefungus Let me know if you need more details for the implementation.

**Comment by metajack** [comment]
I didn't get much feedback in IRC, but here are my thoughts:

- prefs are presumably run-time changeable (like in other browsers)
- prefs can be set in test manifests but options can't

So I think in general options should be used for invocation of the executable related things, and preferences for general configuration.

In this case, layout.threads is definitely something we might want to play with at runtime or override in wpt tests, so I think it should remain a preference.

@zombiefungus After you make a commit that addresses this issue, can you add a second commit that adds rustdoc comments to struct Preferences and struct Opts mentioning the above rationale?

**Comment by paulrouget** [comment]
> so I think it should remain a preference.

Absolutely. And the opts value should be initialized from that preference.

I'm ok if we want to keep the current behavior, but don't you think the priority is 1) argument 2) pref 3) default value. If so, we need a generic way to give access to that value (can't just rely on PREFS), and this can be done via opts?

**Comment by metajack** [comment]
I agree that preference priority should be a) from --pref command line options b) from prefs.js and c) from default prefs. Currently only a) and b) are implemented.

`PREFS` is initialized here: https://github.com/servo/servo/blob/e07cf0a/components/config/prefs.rs#L16-L20

so adding a call to `default_prefs()` at the beginning of the intializer, then changing `read_prefs` to mutate them or adding a `.extend()`-like method to Prefs so that you can call `prefs.extend(read_prefs()...)` seems like the way to go (actually, since under the hood this is a `HashMap`, you can just have default_prefs return a `HashMap` and then use `HashMap`'s `extend` before it gets wrapped in the `Arc`.)

Contrary to what I said intially, we shouldn't need to change `default_opts` at all.

**Comment by paulrouget** [comment]
how does that play with `-y`?

**Comment by metajack** [comment]
`-y` will get parsed and will cause a `PREFS.set` here: https://github.com/servo/servo/blob/a2d3b05/components/config/opts.rs#L871-L878

so this will override anything set by `default_prefs()` or by `read_prefs()`.

**Comment by paulrouget** [comment]
It's kind of weird that we need to introduce `default_prefs()` when there's already default options. What do you think?

I think the pref should be optional. The final way to get this value (from pipeline.rs & co) should be `opts::layout_threads`, not `PREFS.get()`. The value of `opts::layout_thread` would be come from 1) the command line (`-y X`)  2) the pref if there's any 3) finally, `cmp::max(num_cpus::get() * 3 / 4, 1);`.

No?

**Comment by metajack** [comment]
I don't think `-y` should exist, and instead we should be using `--pref layout.threads`. Also, the `Opts` struct does not have a `layout_threads` member. I think in this case `-y` predates our preferences mechanism, which is why it is confusing.

It may be the case that there are more things in `Opts` that should be moved to prefs. In my head, options should be things like `-M` or `--help` which control invocation-related things on the binary that cannot be tweaked (or don't make sense to) at runtime. If such a distinction isn't important, we should collapse everything to prefs. Either way, the steps I outlined would still make sense for this bug.

**Comment by paulrouget** [comment]
Ok, works for me!

@zombiefungus, back to what @metajack [said](https://github.com/servo/servo/issues/15638#issuecomment-299059622). Sorry for the confusion.
