### ISSUE TITLE
Windows Servo renders reddit text squished 

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15698]
As of https://github.com/servo/servo/pull/15681, the Windows build can now render reddit again (along with some other sites on the showcase that were failing).  Yay!

There seems to be an issue rendering reddit with the current master, which displays reddit text like this:

![reddit_with_patch](https://cloud.githubusercontent.com/assets/547158/23240018/a877835a-f9cf-11e6-8254-aefbbb49dce6.png)

**Comment by codec-abc** [comment]
I have started to look at this bug and I have found something that seems rather suspicious. The default line gap for the default font for windows is 0 which seems unusual. If someone have a little time and can run servo on Linux or MacOs and with the following document and tell me what line gap servo compute.
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   </head>
   <body>
      <div>

        <div>a</div>
        <div>b</div>
        <div>c</div>
   </body>
</html>
```

**Comment by codec-abc** [comment]
I think I made some progress. The default font on Windows have a line gap of 0 which seems to be rather suspicious (at least to me). If I put this code 

```
let fixed_line_gap = match dm.lineGap {
            0 => au_from_em(1 as f64),
            x => au_from_du(dm.lineGap as i32),
        };
\\...
let metrics = FontMetrics {
    \\...
    line_gap:         fixed_line_gap
}
```
in components/gfx/platform/windows/font.rs I have this result
![good_rendering](https://cloud.githubusercontent.com/assets/1208646/23857497/cf1f45ba-07fd-11e7-9c3c-7722d12bdc16.PNG)

Since I have zero experience with Servo and Web technologies I leave up to you to judge if this the underlying problem and the appropriate fix.

PS : Sorry for the previous post.

**Comment by jonathandturner** [comment]
@codec-abc - that looks a lot better.  Want to send a PR?  If there's a better fix, the reviewers might know, but at least it gets reddit working again.

**Comment by codec-abc** [comment]
After more thinking I am quite sure that my changes fix the effect and not the cause. I think the issue is that the lineGap value should be read while parsing the font file but ended at 0 for some not yet understood reason. So maybe it is better to get the opinion of people that know this stuff better than me before sending a PR. (Note that I don't mind sending a PR, it just seem not necessary in this case).

**Comment by jonathandturner** [comment]
@codec-abc - right.  that's why I was thinking a PR would help get the discussion going with a reviewer.  It gives them something to look at and go "wait a sec, I think the actual issue is..."
