### ISSUE TITLE
Spurious .DS_Store entries when running ./mach update-manifest on macOS

### ISSUE THREAD

**Issue by nox** [servo/servo#15725]
```diff
diff --git i/tests/wpt/mozilla/meta/MANIFEST.json w/tests/wpt/mozilla/meta/MANIFEST.json
index fc2c7b6818..907e06b8d8 100644
--- i/tests/wpt/mozilla/meta/MANIFEST.json
+++ w/tests/wpt/mozilla/meta/MANIFEST.json
@@ -6633,6 +6633,11 @@
    ]
   },
   "support": {
+   "./.DS_Store": [
+    [
+     {}
+    ]
+   ],
    "./lint.whitelist": [
     [
      {}
@@ -9333,6 +9338,11 @@
      {}
     ]
    ],
+   "mozilla/.DS_Store": [
+    [
+     {}
+    ]
+   ],
    "mozilla/2x2.png": [
     [
      {}
```

**Comment by simartin** [comment]
I'll take a stab at this one

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/16562 was the last attempt, and it contained a suggestion for how to improve it.

**Comment by anrdh** [comment]
I can work on this if I can get some guidance.

**Comment by jdm** [comment]
@anrdh Sure! The problem is that `./mach update-manifest` looks for all files that exist under tests/wpt/web-platform-tests and updates tests/wpt/metadata/MANIFEST.json based on that list. If you view the directory in macOS' Finder, that can unintentionally create a new .DS_Store file in the directory that gets picked up by the manifest. #16562 was a good start at solving this, and contained a suggestion for how to improve the implementation.

**Comment by kregoslup** [comment]
Since there is no asignee, can I work on this?

**Comment by jdm** [comment]
@kregoslup Yes.
