### ISSUE TITLE
about:blank iframe fires two load events

### ISSUE THREAD

**Issue by jdm** [servo/servo#15727]
```html
<iframe onload="console.log('iframe load')"></iframe>
```

**Comment by gpoesia** [comment]
I'd like to investigate this.

**Comment by jdm** [comment]
@gpoesia That would be really useful! I suspect it's caused by the special case in HTMLIFramEelement::process_the_iframe_attributes and ScriptThread::handle_frame_load_event, so we'll probably want to suppress the one invoked by the ScriptThread.

**Comment by cbrewster** [comment]
The first `load` event comes from when the `iframe` is bound to the tree and `create_nested_browsing_context` is called. This will cause `about:blank` to be synchronously loaded which will fire a `load` event (this one is a bit hairy to track down). And then `process_the_iframe_attributes` will be called.
Since it is being called 1. For the first time 2. Without a `src` attribute, it will queue a task to fire the `load` event.

The second load event follows the spec as defined here: https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes

As @jdm said, we will want to suppress the load event that is fired when we are creating the nested browsing context with the initial about:blank load.

**Comment by cbrewster** [comment]
@gpoesia how is this going? Is there anything I can do to help?

**Comment by gpoesia** [comment]
@cbrewster Would you take a look at #16091? I didn't find a better way of testing than waiting for some timeout. It bothers me that this makes the test non-deterministic in theory, but I think there can't be an exact way since we want to assert that "onload won't ever be called again", and that seems undecidable.

**Comment by jdm** [comment]
#16091 was a work in progress to fix this; I believe https://github.com/servo/servo/pull/16091#issuecomment-332214615 was the last set of requests but the author stopped responding.

**Comment by jdm** [comment]
Fixed by #28560.
