### ISSUE TITLE
Clean up Area::parse

### ISSUE THREAD

**Issue by jdm** [servo/servo#15834]
There are some inefficient pieces of code in `Area::parse`:
* `ar_ref` looks like it's unnecessary; we should be able to use `array` directly instead
* let's use str::from_utf8 instead of String::from_utf8 (this allows us to avoid calling clone())
* get rid of the use of `unwrap()` by using `Result::and_then` instead

Code: `components/script/dom/htmlareaelement.rs`

No need for automated tests; if the changes compile then it's good enough for a PR.

**Comment by jdm** [comment]
Claiming this task for some potential Outreachy candidates.

**Comment by Rakhisharma** [comment]
@iamneha and @rakhisharma (me) are working on this issue. @jdm thanks!

**Comment by Rakhisharma** [comment]
@jdm hi, You pointed out three inefficient piece of code in Area::parse,  I am done with first two without any error or warning they both compiled. I am not able to understand the third one :/ 
Will you please help me out what needs to be done there? I gone through the docs of unwrap() and Result::and_then but still seems like I am confuse.

**Comment by Wafflespeanut** [comment]
I guess `and_then` is causing trouble because it finds two different error types (`String::from_utf8` seems to return `FromUtf8Error` whereas `parse::<f32>` returns `ParseFloatError`). You can convert the `Result` to an `Option` using `.ok()` (instead of `unwrap`), which will ignore the error, and now you can use `and_then` to pipe the value to `parse`. You might wanna call `ok` on the parse result too.

**Comment by Manishearth** [comment]
Are you still working on this?

**Comment by jdm** [comment]
Available for anybody.

**Comment by omakk** [comment]
@highfive: assign me
