### ISSUE TITLE
Treat application/xml like text/xml in ParserContext::process_response

### ISSUE THREAD

**Issue by jdm** [servo/servo#15850]
We should be able to support loading documents with the application/xml MIME type, but currently we just show an error instead. This appears in `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm`; we will get more meaningful errors if we make this change.

Code: `components/script/dom/servoparser/mod.rs`

Claiming this for some RGSoC applicants.

**Comment by cynicaldevil** [comment]
Related: #14912

**Comment by pcpeters** [comment]
Hi @jdm , I’ve gone through mod.rs, to see how the different mime contexts are being considered in order to serve a response. What I understand from everything written above is that application/xml files must be treated in the same way that text/xml files are currently being treated. However, in the file mod.rs, at line 587, I see is that nothing is done once we encounter text/xml. 

I'm not sure of how to proceed from here and I'd really appreciate some pointers.

**Comment by jdm** [comment]
Right, the decision for text/xml is "we don't need to do anything special; just process the rest of the page content as usual". The next branch in that match handles any content types that we don't recognize and makes us replace the content with a generic error.

**Comment by jdm** [comment]
The code change is straightforward, and then there are a bunch of test results that need to be updated as discussed in #16341.

**Comment by rigelk** [comment]
I'll take it if nobody is already on it :)
@highfive: assign me

**Comment by jdm** [comment]
Last effort was #17474, which just needs some more work to address the unexpected test results.

**Comment by cgati** [comment]
@jdm could I take a stab at this or would you prefer it be claimed by a RGSoC applicant?

**Comment by jdm** [comment]
No, please do!

**Comment by cgati** [comment]
@highfive : assign me

**Comment by KiChjang** [comment]
Ignore @highfive's message; I've already assigned this issue to you.

**Comment by cgati** [comment]
@KiChjang thanks!
