### ISSUE TITLE
Negative value on flex-basis should be rejected

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15902]
Relevant code: https://github.com/servo/servo/blob/8b8eb5e192295fb903db5855a8f7be85581461b7/components/style/properties/longhand/position.mako.rs#L200-L207

Should be an easy one although I cannot provide how to fix it without further investigation.

**Comment by upsuper** [comment]
cc @Manishearth

**Comment by canaltinova** [comment]
This can be fixed by adding `"parse_non_negative"` and `needs_context=False` parameters to this `helpers.predefined_type` before the spec parameter. This will work fine in stylo build (can be built with `./mach build-geckolib`) But will break servo build because `LengthOrPercentageOrAutoOrContent` doesn't have a `parse_non_negative` method. We need to add this function to enum like [LengthOrPercentageOrAuto implementation](https://dxr.mozilla.org/servo/source/components/style/values/specified/length.rs#1137-1170) except it will have additional `content` parsing.

**Comment by canaltinova** [comment]
Oh, scratch that. It looks like `LengthOrPercentageOrAutoOrContent`'s parse function is already rejecting negative values. Passing something like these parameters will solve the problem without changing parse implementations: `"parse_non_negative" if product == "gecko" else "parse"` `needs_context=False if product == "gecko" else True,`

**Comment by Wafflespeanut** [comment]
Instead of going for a lot of `if ... else` blocks inside the definition, let's have two definitions - one for each servo and gecko.

**Comment by mrkalling** [comment]
Hi, I like to work on this @highfive: assign me

**Comment by Wafflespeanut** [comment]
@mrkalling Did you start working on this?

**Comment by mrkalling** [comment]
I have looked at it but I don't understand what is the problem. When I test to set flex-basis to a negative number servo seems to ignore it which is what we want, right?

**Comment by upsuper** [comment]
It looks like Servo's `LengthOrPercentageOrAutoOrContent` is already only parsing non-negatives, while the Gecko port uses `LengthOrPercentageOrAuto` which does normal parsing. So it is a stylo-only issue. We probably need to use `LengthOrPercentageOrAuto::parse_non_negative` for that.

**Comment by upsuper** [comment]
Probably adding a new line
```python
"parse_non_negative" if product == "gecko" else "parse"
```
would be enough.

**Comment by Wafflespeanut** [comment]
@mrkalling ping?

**Comment by emilio** [comment]
This is Gecko only, and I'm helping out someone working on this.
