### ISSUE TITLE
Build a higher level API for writing structured clone values

### ISSUE THREAD

**Issue by jdm** [servo/servo#16031]
#15519 adds some basic functionality for cloning Blob values as part of the structured clone algorithm. We should build a higher level API for writing Rust types like vectors and strings so we don't need to keep repeating the same low level operations over and over. I envision something like:
```rust
struct StructuredCloneWriter(*mut JSStructuredCloneWriter);
impl StructuredCloneWriter {
    fn write_slice(&self, v: &[u8]);
    fn write_str(&self, s: &str);
    fn write_usize(&self, u: usize);
}
struct StructuredCloneReader(*mut JSStructuredCloneReader);
impl StructuredCloneReader {
    fn read_slice(&self) -> Vec<u8>;
    fn read_str(&self) -> String;
    fn read_usize(&self) -> usize;
}

```
Code: `components/script/bindings/structuredclone.rs`

**Comment by nox** [comment]
Why does the writer have `read` methods?

**Comment by gterzian** [comment]
Could the `S-blocked-on-external` be removed perhaps? Also have you considered labeling this one `E-less-easy`? I would be happy to help the person doing the actual refactoring.

**Comment by alajara** [comment]
hey @gterzian I would like to try this one, if the offer still stand for the help and guidance I will much appreciate it

**Comment by gterzian** [comment]
@alajara absolutely! Thanks for your offer of help.

Have you considered taking a first pass at it, based on @jdm guidance above, and opening a PR(even if not finished)? That way I can help you through comments and reviews on the PR. You can start the PR title with `[WIP]` to tell others it is still a work in progress and not yet ready for a review by one of the project maintainers.

**Comment by gterzian** [comment]
@alajara One thing to note is that [the PR](https://github.com/servo/servo/pull/15519) that added the code to be refactored also [added some tests](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/tests/wpt/web-platform-tests/html/infrastructure/safe-passing-of-structured-data/structured_clone_blob.html), so a good way to work is with the use of those tests as a benchmark, because they are passing now and any refactoring should still have them passing...

**Comment by jdm** [comment]
The tests can be run with `./mach test-wpt tests/wpt/web-platform-tests/html/infrastructure/safe-passing-of-structured-data/structured_clone_blob.html`.

**Comment by alajara** [comment]
@gterzian thank you! I am going to start working on it today.

**Comment by KiChjang** [comment]
Note: the spec recently removed all notions of structured cloning and instead replaced them with structured serialization/deserialization: https://html.spec.whatwg.org/multipage/#structuredclone; relevant PR whatwg/html#2421

**Comment by gterzian** [comment]
@KiChjang thanks for the info! I think the current implementation isn't actually following the various operations defined in the previous spec, I guess in the future as we add support for types other than `Blob` we could do so in ways that conform more closely with the new spec...

**Comment by domenic** [comment]
However the OP's code looks pretty much like the spec, if you rename "StructuredCloneWriter" to "serialization steps" and "StructuredCloneReader" to "deserialization steps". The spec seems to match these ideas a lot better now :)

**Comment by gterzian** [comment]
@domenic awesome 😄

**Comment by jdm** [comment]
I would rather use the names I've suggested and add links to the related specification concepts in comments if they make sense.

**Comment by domenic** [comment]
Well, the problem with your names is that the concept of "structured clone" no longer exists in any specification, so it's a bit mysterious for anyone reading the code.

**Comment by alajara** [comment]
Hey I am still working on it, I am still new to Rust, and wanted to understand the code myself, I hope thats ok sorry for the delay.

**Comment by alajara** [comment]
@gterzian am I changing out the unsafe functions read and write length?

**Comment by jdm** [comment]
Those are still fundamental operations that the higher-level APIs will need to use, so I don't think there's any need to change them.

**Comment by alajara** [comment]
@gterzian someone else should take the PR, I am having a little trouble understanding the code, its going to take me longer than I thought and I don't want to keep you waiting, sorry

**Comment by gterzian** [comment]
@alajara I don't think there is any rush to this, it took me a while to get started on the initial PR as well, at lest a few weeks of just reading stuff. 😄 

I advise you to not try to understand everything that the code does (the actual writing and reading of stuff), and instead just look at what each step of the writing and reading is made out of. You could then try to move those operation into the appropriate method of the `struct` skecthed out by @jdm above. 

In fact that refactoring should only consist of moving code out of the [write blob function](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L85), the [read blob function](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L70) into the appropriate methods of `StructuredCloneWriter` and `StructuredCloneReader`, a new struct which should be added to the code, and then instantiating this struct and using the appropriate methods within those two blob specific functions.

For example, in the [write blob function](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L85) one could instantiate a new `StructuredCloneWriter`, with the [`r: *mut JSStructuredCloneReader`](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L71) as argument, and then using StructuredCloneWriter.write_usize(blob_length) instead of [this line](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L93). Essentially if you look at line 93 until 96, you can see four individual write operations, those could be translated into four calls to a method of this new `StructuredCloneWriter`, for example something like `StructuredCloneWriter.write_slice(blob_vec.as_ptr())` instead of [this](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L95)

Please note that the writing of the [`Uint32Pair`](https://github.com/gterzian/servo/blob/5c4f0be04872f5f2e8736b15a2169f9479509a0e/components/script/dom/bindings/structuredclone.rs#L92) should probably not be part of this `StructuredCloneWriter` struct, so you leave that where it is, focusing on line 93 until 96.

**Comment by gterzian** [comment]
Note: since the struct has only one field, you can literally just declare it in your code as 
```rust
struct StructuredCloneWriter(*mut JSStructuredCloneWriter);
```
(@jdm please let me know if I'm wrong)

and below add an `'impl` block to implement the methods. see https://doc.rust-lang.org/book/method-syntax.html

**Comment by alajara** [comment]
Thank you! Your explanation and guideline really helped me understand what was the task and your examples helped even more. I was getting ahead of my self by looking documentation on the different packages. I am working on it now, and will put it up shortly so you can review it. thanks again.
P.S.
Is JSStructured CloneWiter/Reader a Javascript/Rust  enum type?

**Comment by gterzian** [comment]
`JSStructuredCloneWriter/Reader` are actually [raw pointers](https://doc.rust-lang.org/book/raw-pointers.html), because the stuff in the `js::jsapi` package are in fact bindings to `C` code, so what being done here is somewhat similar to these [ffi examples](https://doc.rust-lang.org/book/ffi.html)... To be honest this is fairly new to me as well.

Glad to hear the examples helped! Let me know if you have other questions...

**Comment by alajara** [comment]
hey @gterzian I uploaded the [WIP} pull request, I ./mach build -d and it passes but when I run the structured clone ./mach test I get a test crash, so I am not doing something correctly. Is there something you see that I need to fix.

**Comment by gterzian** [comment]
@alajara awesome! I will take a look at it in the course of the week...
