### ISSUE TITLE
font-variant is a shorthand

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#16089]
We've implemented it as a longhand that doesn't do anything. Huh.

Spec: https://drafts.csswg.org/css-fonts-3/#propdef-font-variant
MDN: https://developer.mozilla.org/en/docs/Web/CSS/font-variant

**Comment by methyl** [comment]
@highfive assign me

**Comment by methyl** [comment]
@Manishearth can you unassign? I did some research but I'm afraid I won't be able to finish that before vacation next week. 

Quick summary:
There are two variants of font-variant: one is shorthand from css-fonts-3 specification and the other (called [font-variant-css21](https://developer.mozilla.org/en/docs/Web/CSS/font#font-variant-css21)) is longhand which is still used in `font` shorthand. As they differ, I think we could do something like

```
${helpers.single_keyword("font-variant-css21",
                         "normal small-caps",
                         spec="https://drafts.csswg.org/css-fonts/#font-variant-css21-values",
                         animatable=False)}
```

so that we can use it in `font` shorthand and then implement `font-variant` as shorthand 
 according to new specification.

Does that sound reasonable?

**Comment by Manishearth** [comment]
No, that property doesn't exist 😄, we shouldn't invent new properties.

We should support the css-fonts-3 shorthand, that decomposes into all the font-variant longhands. When parsing `font`, we should only parse `normal` and `smallcaps`, and decompose that into whatever font-variant does for those two properties. It seems to redirect them into `font-variant-caps` and reset the rest to initial.

This may involve adding more properties as well.

**Comment by Manishearth** [comment]
Note that when `font-variant-css21` is listed in the shorthand, that's not the name of a property, that's just a thing that can be parsed.

**Comment by Adynatos** [comment]
Hi, I would like to work on this, but would need some mentoring :)

**Comment by jdm** [comment]
@Adynatos Great! Go ahead and ask questions about anything that's unclear!

**Comment by Adynatos** [comment]
First I'd like to check if I understand this correctly.
I should change font-variant to be shorthand, that can be parsed into properties like font-variant-caps.
To do so, I should implement something like font shorthand, right?

**Comment by Manishearth** [comment]
Yes, something like that. You should look at how the spec asks you to parse it.

**Comment by KiChjang** [comment]
@Adynatos Have you made any progress on this?

**Comment by Manishearth** [comment]
Hiro already fixed this.
