### ISSUE TITLE
Move to running CSS testsuite from web-platform-tests

### ISSUE THREAD

**Issue by gsnedders** [servo/servo#16175]
Now that csswg-test has merged into web-platform-tests (ACHIEVEMENT UNLOCKED: BATTLED BUREAUCRACY AND WON), we should move over to running the CSS tests from there to keep them up-to-date.

At the same time as doing this, we should move over to running the unbuilt tests, which makes upstreaming fixes much easier (i.e., the same as for the rest of the wpt repo).

There are two possible major challenges with this:

 1. The quality of our XHTML implementation. (The majority of tests, for historical reasons, have XHTML source files. Changing all of these to HTML is likely impractical.)

 2. Mapping our current expectations to the unbuilt files.

The latter should be basically doable by matching filenames minus their extensions; there's a few cases where that's ambiguous but those shouldn't be hard to work out which is which.

cc/ @SimonSapin @jgraham

**Comment by SimonSapin** [comment]
I consider the quality of our XHTML implementation to be unknown. It would be nice to isolate what unexpected results are due to that (when moving to "unbuilt" csswg tests) as opposed to test changes. The last time `tests/wpt/css-tests` was updated with in 296fa2512ba2fbc8f1d6b7e82e30ad3b5d2a9a20 on 2017-02-06. Maybe we could find the corresponding commit in the (pre-merge) csswg-tests repository and do a run on unbuilt tests with the current set of expectation.

If XHTML-related issues turn out to be major and hard to fix in xml5ever, we should consider switching to or adding support for another XML parser.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/19070 contains all of my investigations.

**Comment by gsnedders** [comment]
@jdm this can be closed right, now that has landed?

**Comment by jdm** [comment]
Yep!
