### ISSUE TITLE
outdated rustc updating instructions

### ISSUE THREAD

**Issue by isonmad** [servo/servo#16261]
The wiki page [Updating the Rust compiler used by Servo](https://github.com/servo/servo/wiki/Updating-the-Rust-compiler-used-by-Servo) is over a year old and has been inaccurate since at least https://github.com/servo/servo/commit/336e6c8f286be636a105af858cac18b4d42c1b12, possibly earlier?

**Comment by SimonSapin** [comment]
I’ve update the “Updating the Rust compiler” section. The “Updating dependencies” section still has outdated info, but I don’t feel like rewriting the whole thing right now.

* We don’t use git submodules anymore.
* Many dependencies are normally obtained through crates.io, not git.
* Servo dependencies not developed by the servo team don’t necessarily have a Github fork in the `servo/` org.
* You may need to use [`[replace]`](http://doc.crates.io/specifying-dependencies.html#overriding-dependencies) rather than `paths`.
* We tend to omit the date from `rustup` branch names. (Rust is now stable enough and we can keep up quickly enough that there is rarely more than one set of breaking changes to update for at a given time.)

**Comment by jdm** [comment]
No point in leaving this open.
