### ISSUE TITLE
Stale windows build still live

### ISSUE THREAD

**Issue by brson** [servo/servo#16339]
The current dl is https://download.servo.org/nightly/windows-msvc/servo-latest.msi, but there's also one up at https://download.servo.org/nightly/windows/servo-latest.msi

I expect the later is old junk. I installed it recently and was horrified at it. The former looks much better.

**Comment by Wafflespeanut** [comment]
cc @larsbergstrom

**Comment by larsbergstrom** [comment]
The `latest*` files are gone, though I left the dated builds in there. The issue is that we used to just have `windows` builds but then once we added msvc builds we split it into separate directories. I agree that having a `servo-lastest.msi` file in the old directory is bad news. Thanks for pointing it out, @brson!

cc @edunham
