### ISSUE TITLE
Also upload the zipfile of Windows with the nightly build

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#16437]
For users without administrative priviledges, it would be nice to have a zipfile that can be unpacked to try out the Servo Windows nightly.

We already build it during the packaging process:
https://github.com/servo/servo/blob/master/python/servo/package_commands.py#L342

The change required should be to update the upload scripts to push up both the zipfile and the MSI:
https://github.com/servo/servo/blob/master/etc/ci/upload_nightly.sh#L94

**Comment by aneeshusa** [comment]
We'll also need to update the [download.servo.org](https://github.com/servo/download.servo.org) website to link to the new zipfile Windows build so that's it's easy to download. This involves updating the `index.html` file in that repository to add the new link, and update the existing Windows build link to mention that it's an MSI.

**Comment by UK992** [comment]
@highfive: assign me
