### ISSUE TITLE
Auto-implement Interpolate and ComputeDistance for macro-generated keyword types

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#16604]
The keyword types are generated using [this macro](https://github.com/servo/servo/blob/46bb635c4c1eb9e420392d7a761956c1cc10ce3a/components/style/values/mod.rs#L111). The `Interpolate` and `ComputeDistance` traits are implemented for them in `components/style/properties/helpers/animated_properties.mako.rs`.

Since they're unit structs, these types don't have anything special, they always return their copy in `Interpolate` impl, and they always return an `Err(())` in `ComputeDistance` impl. So, we should do that with the help of the macro.

**Comment by aacunningham** [comment]
Just to make sure I understand the task, it would essentially be moving some of the `impl ComputeDistance/Interpolate` from `animated_properties.mako.rs` into the macro, ya?

**Comment by aacunningham** [comment]
Anywho, I'll pick this one, should be quick.

@highfive: assign me

**Comment by Wafflespeanut** [comment]
@aacunningham Yes, you only need to import the traits in `components/style/values/mod.rs` and add the impl inside the macro definition.

**Comment by aacunningham** [comment]
Very cool, just implemented those changes (took me a while to figure out how the mako files work and how to import the traits). Currently running into some duplicate declaration/impl issues (can't remember the exact error), but I should have those fixed and a PR up in the by end of today.

**Comment by aacunningham** [comment]
Alright, so I think I have a solution, but I'm not exactly sure what's going on, so I'm hoping to make this a learning experience. I removed the obvious `impl`'s for `Auto` and `Normal` and added the `impl` definitions inside the macro. I then started getting this build error:

<details>
<summary><b>Bugs in here</b></summary>

```
error[E0119]: conflicting implementations of trait `properties::animated_properties::Interpolate` for type `values::Either<app_units::Au, values::None_>`:
     --> /home/aaronc/Coding/rust/servo/target/debug/build/style-4f02e43a0ab74277/out/properties.rs:49595:1
      |
48545 | / impl Interpolate for LengthOrNone {
48546 | |     fn interpolate(&self, other: &Self, progress: f64) -> Result<Self, ()> {
48547 | |         match (*self, *other) {
48548 | |             (Either::First(ref length), Either::First(ref other)) =>
...     |
48552 | |     }
48553 | | }
      | |_- first implementation here
...
49595 | / impl<T, U> Interpolate for Either<T, U>
49596 | |         where T: Interpolate + Copy, U: Interpolate + Copy,
49597 | | {
49598 | |     #[inline]
...     |
49612 | |     }
49613 | | }
      | |_^ conflicting implementation for `values::Either<app_units::Au, values::None_>`
```
</details>

I also got this bug for the other `impl` I moved.

This was obviously fixed by removing the code for one of the `impl`'s, but I'm curious why the bug showed up. My idea is that by adding the `impl`'s to the macro, I added the two `impl`'s to `None_` that weren't there before. This caused the `where` clause of `impl Interpolate for Either` to match the same as `LengthOrNone`, since `LengthOrNone = Either<Length, None_>`.

So I'm not sure what the best path forward is. Should I leave it adding `Interpolate` and `ComputeDistance` to `None_` and remove one of the conflicting `impl`'s (my vote is removing `LengthOrNone`'s)? Or go back to how it was so that `None_` doesn't gain any new `impl`'s, since I'm not sure we want `None_` implementing those.

**Comment by Wafflespeanut** [comment]
Yep, you're right that you should be removing the impl for `LengthOrNone`, since that will be auto-derived by the generic implementation on `Either<A, B>`, and yeah, you should remove the custom impls on the keyword types. It should all belong in the `macro_rules!` definition.
