### ISSUE TITLE
Unsafe AtomicRefCell<T> transmute in Layout component

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#16817]
Hi,

I'm fixing Android SEGV crashes on Servo (see https://github.com/servo/servo/pull/16816) and found that one of them is caused by a highly unsafe cast between ` AtomicRefCell<PersistentLayoutData>` and` AtomicRefCell<PartialPersistentLayoutData> `
```

impl<T: LayoutNode> LayoutNodeHelpers for T {
    fn initialize_data(&self) {
        if self.get_raw_data().is_none() {
            let ptr: *mut NonOpaqueStyleAndLayoutData =
                Box::into_raw(box AtomicRefCell::new(PersistentLayoutData::new()));
            let opaque = OpaqueStyleAndLayoutData {
                ptr: unsafe { NonZero::new(ptr as *mut AtomicRefCell<PartialPersistentLayoutData>) }
            };
            unsafe { self.init_style_and_layout_data(opaque) };
        };
    }
}
```
Even after adding the required repr(C) to guarantee the memory consistency between pure PersistentLayoutData and PartialPersistentLayoutData structs, the cast between both structs contained in AtomicRefCell<T> is unsafe. The problem is that memory alignment is not guaranteed even using C layout because memory alignment may be different between fields in both templates when the structs are contained in the parent [AtomicRefCell](https://github.com/bholley/atomic_refcell/blob/master/src/lib.rs#L59)  (AutomicUsize + RefCell<T>)

I checked the pointer addresses on Android before and after the `ptr as *mut AtomicRefCell<PartialPersistentLayoutData>` by calling and printing AtomicRefCell.as_ptr(). The new pointer address after the transmute is 4 bytes misplaced from the real one. So this leads to some SEGV crashes. On Desktop linux (64 bits) the pointers addresses are equal.

I checked adding a combined` repr(C, packed) ` macro to PartialPersitentData or AtomicRefCell and with that representation the pointers are equal on Android too.

Adding packed representation is not the best solution because it can have other side-effects. Adding a new level of indirection is another solution but it can cause more overhead. Maybe adding a dummy struct to match the alignment (protected with a static assert) or rewriting this part of the code is the best solution. What do you think?

**Comment by SimonSapin** [comment]
What is `std::mem::align_of::<_>()` for both of these structs? (A way to find out might be to add `assert_eq!` tests in `tests/unit/script/`).

Looking around in…

* http://doc.servo.org/script_layout_interface/struct.PartialPersistentLayoutData.html
* http://doc.servo.org/layout/data/struct.PersistentLayoutData.html

… it looks like they would both be word-aligned, but maybe I’m missing a `u64` somewhere.

If `PersistentLayoutData` is 8-bytes-aligned but `PartialPersistentLayoutData` 4-byte-aligned on 32-bit, I think the way to go is adding a dummy `u64` private field to the latter, as you suggested. (Not transmuting at all would be best but I don’t know how to make that work while keeping the separation between `script_layout_interface` and `layout` crates. And ignoring alignment with `packed` seems bad.)

By the way, I suspect that this difference is about 32-bit vs 64-bit rather than (desktop) Linux vs Android. If 32-bit Linux is easier for you to test, you might be able to reproduce this bug that way. (It should be a matter of installing a gcc-multilib package and building with `--target i686-unknown-linux-gnu`.)
