### ISSUE TITLE
incompatibilidad

### ISSUE THREAD

**Issue by 1masyc** [servo/servo#16820]
el paquete de instalcion no es compatible con este tipo de procesador!!. pongase en contacto con el fabricante del producto.

instalacion en windows 7 profesional 86x

**Comment by jdm** [comment]
"The installation package is not compatible with this type of processor !!. Contact the manufacturer of the product.
Installation on windows 7 professional 86x"

**Comment by jdm** [comment]
Our Windows builds may not support 32bit. @larsbergstrom do you know if this is true?

**Comment by larsbergstrom** [comment]
That's correct, and our installer also blocks attempts to install Servo onto 32-bit operating systems here:
https://github.com/servo/servo/blob/master/support/windows/Servo.wxs.mako#L15

@metajack I don't think we have any plans for 32-bit support on Windows, right?

**Comment by metajack** [comment]
I don't think we are planning 32bit Windows, no. While I'm not opposed in principle if the technical requirements to support it are not large, it would require substantial expansion of our testing budget to keep it working.

**Comment by 1masyc** [comment]
Gracias...lo tomare en cuenta...lamentablemente no dispongo de una maquina con esas caracteristicas de 64bit no podre trabajar en ello, muchas gracias por responder

**Comment by keiyakins** [comment]
I'd like to object to this decision. I have no expectations it'll change anyone's minds, of course. I just want to have my objection recorded.

Win32 should be supported for at least as long as Microsoft has mainstream support for a 32-bit version of Windows, which is 2020 at the soonest, since they still have 32-bit versions of Windows 10. Servo is likely to be quite usable by then. Sure, it's not necessarily a priority during development, but it's usually easier to do sooner rather than later, because fewer assumptions that need to be fixed creep in.
