### ISSUE TITLE
Need to implement inlinization of ruby kids

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#16825]
Spec at https://drafts.csswg.org/css-ruby/#anon-gen-inlinize

The Gecko impl is in http://searchfox.org/mozilla-central/rev/cd8c561106d804e26bc09389f18f361846d005eb/layout/style/nsStyleContext.cpp#624-685 and note that it involves styles of not just your parent, to handle cases like `<ruby-thing><inline><block></block></inline>`, afaict.

Note to self: this would get implemented in components/style/style_adjuster.rs

**Comment by bzbarsky** [comment]
Stylo bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1364274

**Comment by Manishearth** [comment]
@emilio another fixup, though I suspect we can make this an easy bug

**Comment by bzbarsky** [comment]
Note that due to https://github.com/w3c/csswg-drafts/issues/1355 the spec is more or less useless here.  Chances are, the only way to get various Gecko tests to pass is to clone Gecko's implementation.  Note that it's defined in terms of the style context tree and uses state from parent style contexts, which will make it extra fun to deal with in servo.

**Comment by emilio** [comment]
So in order to fix this we need to add some sort of flags to the `ComputedValues` struct (note that there are two definitions of this struct, one living in `components/style/properties/properties.mako.rs`, other in `components/style/gecko.mako.rs`). I don't have an immediately good name for this flags, we could call them something like `ComputedValueFlags`?

They should live in another module, `components/style/properties/computed_value_flags.rs` (or similar, depending of the name of the new flags), because I could believe this is the case where we start adding something seemingly innocent to the mako file, and end up growing up a mess.

The flags should only contain one bit, which could be, for symmetry with Gecko, something `SHOULD_SUPPRESS_LINE_BREAK`. This should have a meaningful comment, pointing to this issue, and the spec issue @bzbarsky mentions in the comment above this.

Then we should pretty much implement something similar to the code pointed out in the first comment.

This, as a first step, can ignore the anonymous boxes and pseudo bits, because we don't have access to that information there (I don't think we need the anonymous box bit, but we may need the pseudo-element down there. That should IMO be a different PR.

Happy to mentor this.

**Comment by hgallagher1993** [comment]
Ya so I'd be willing to take this on, I've done a few easy tagged issues but never a less easy so I'd probably need a bit of help with it

**Comment by jdm** [comment]
In that case, ask questions about anything that's unclear :)

**Comment by hgallagher1993** [comment]
👍

**Comment by bd339** [comment]
Is @hgallagher1993 still working on this?
It's listed on Servo Starters, so I'm just stopping by to see if I can pick it up or not.

**Comment by hgallagher1993** [comment]
@bd339 Yes I am still working on it, I'm actually in the middle of it now, got a bit delayed up until a few days ago with college but that's over for good now 😄

**Comment by hgallagher1993** [comment]
@emilio getting back to this task now and I was just wondering how I'd go about testing that it works? I've never actually written a test for Servo before so even just where I'd put it

**Comment by emilio** [comment]
So Servo doesn't have any ruby support, so we'd need to test it on mozilla-central. You can set up a mozilla-central development environment and hack on the `servo/` directory, but you can also open a PR and I can send it to the try server for you if you want :)

**Comment by hgallagher1993** [comment]
Cool, I'll have a look into setting up that environment, I'll try and get some code going first though (which I'll most likely have questions on in the next day or 2)

**Comment by emilio** [comment]
Hi @hgallagher1993, any update on this?

I opened #17525, which introduces the set of flags that are needed to fix this.

**Comment by upsuper** [comment]
Hi @hgallagher1993, are you still working on this?

**Comment by jdm** [comment]
I think it's safe to assume that someone else can look into this.

**Comment by hgallagher1993** [comment]
Sorry about this, something came up with my final year college project that I've been sorting out for the last week or 2. I was actually in the middle of this but I don't know when I'd get a chance to finish it so it was aswell un-asign me.

**Comment by upsuper** [comment]
Ok, I'll take this. Thanks for your contribution.

**Comment by upsuper** [comment]
I guess we want to somehow copy the logic from here: https://dxr.mozilla.org/mozilla-central/rev/d9a144b7b6d994fc9a497c53b13f51a2a654d85e/layout/style/GeckoStyleContext.cpp#452-513

**Comment by upsuper** [comment]
This has been fixed for a while. Closing.
