### ISSUE TITLE
Parse :dir into an enum with two values (ltr/rtl) as opposed to a string for the argument

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#16840]
Would be cleaner in various ways.  We could either stop calling into Gecko to match it or generate the uint16_t* on the fly from the enum value easily.

**Comment by emilio** [comment]
Yeah, we should still have a third variant for serialization purposes, I guess.

For reference, this involves modifying [`non_ts_pseudo_class_list.rs`](https://github.com/servo/servo/blob/master/components/style/gecko/non_ts_pseudo_class_list.rs), and Gecko's [`selector_parser.rs`](https://github.com/servo/servo/blob/master/components/style/gecko/selector_parser.rs).

Ideally, we could modify the macro in order to define it from there, but if it turns out to be complicated, we may want to remove `dir` from the first file instead, and define it manually in the same way `MozAny` is defined, as something like:

```rust
enum Direction {
    Rtl,
    Ltr,
    Other(Box<str>),
}

enum NonTSPseudoClass {
    // ...
    Dir(Direction)
}
```

Once that's done, for matching it we just need to port the relevant code that right now lives in mozilla central, which is http://searchfox.org/mozilla-central/rev/06b337ab22d40e12c4cde8040b23147ea636cc6e/layout/style/nsCSSRuleProcessor.cpp#1751

**Comment by zombiefungus** [comment]
@highfive: assign me

**Comment by jdm** [comment]
@zombiefungus Did you make any progress on this? Are you still working on it?

**Comment by jaredwy** [comment]
@jdm does this mean this issue is up for grabs?

**Comment by emilio** [comment]
Yes, it is :)

**Comment by omakk** [comment]
Hey @jaredwy, are you still interested in this issue? I'd like to take a poke at this, but wanted to make sure before claiming.

**Comment by jaredwy** [comment]
@omakk still keen. Just have to get approval from work. Will ping you if that falls through.

**Comment by jaredwy** [comment]
@highfive: assign me

**Comment by jaredwy** [comment]
Work approved! So will take a crack at this this weekend. Sorry @omakk!

**Comment by omakk** [comment]
No worries @jaredwy! Good luck and enjoy :)

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by omakk** [comment]
@highfive: assign me

**Comment by spectrofflz** [comment]
@highfive assign me

**Comment by KiChjang** [comment]
@sralbertson Are you still working on this?

**Comment by sralbertson** [comment]
I still haven't started. You can remove me from the issue.

**Comment by wilsoniya** [comment]
@highfive: assign me
