### ISSUE TITLE
Implement HTMLElement.offset{Parent,Top,Left,Width,Height}

### ISSUE THREAD

**Issue by jdm** [servo/servo#1714]
http://dev.w3.org/csswg/cssom-view/#extensions-to-the-htmlelement-interface

**Comment by jdm** [comment]
@jviereck I saw you were inquiring about it - yes, this is still quite relevant and unfixed :)

**Comment by jviereck** [comment]
Trying to rebase my old patch from https://github.com/jviereck/servo/compare/fix_1714_HTMLElement_offset_parent with the current master turned out to be not entirely trivial as a lot of things has changed in servo in the mean time (which is great to see :) ). In the following a few questions to show you where I am currently got stuck in the rebase process - could someone please have a look at it (@jdm - you maybe?):

1. I guess the request for the `node.offsetParent` should be done between the script and layout task via an `LayoutRPC` and then defined similar to the one for the `content_box` here: https://github.com/servo/servo/blob/master/components/layout/layout_task.rs#L962
2. In the case of the `content_box` `LayoutRPC` the actual computation seems to happen in `process_content_box_request` function, which stores the result on the `struct LayoutTaskData` in `pub content_box_response: Rect<Au>`. The `process_content_box_request` function is called from `LayoutTask.handle_reflow(...)`. But how is the `LayoutTask.handle_reflow(...)` invoked - is it done on every `LayoutRCP` message?
3. In the concrete case of the `offsetParent` property that I try to compute, do you think that's the right approach to store something like `LayoutTaskData.offset_parent_response: UntrustedNodeAddress` on the `struct LayoutTaskData` and then add an new `process_offset_parent_request`? I am not sure if adding this new `process_offset_parent_request` method is the correct way to go, as not all LayoutRPC requests require additional data on the `struct LayoutTaskData` (e.g. the `hit_test` does not) and I assume adding new fields to the `struct LayoutTaskData` should only be done whenever this is absolutely necessary. But as I am missing the bigger picture here, I am not sure if this is the case :/

**Comment by jviereck** [comment]
Okay, managed to find out about 2. from my last comment: The LayoutRPC request is created from the `Page` object [here](https://github.com/servo/servo/blob/master/components/script/page.rs#L188), which also triggers a layout reflow first:

```rust
    pub fn content_box_query(&self, content_box_request: TrustedNodeAddress) -> Rect<Au> {
        self.flush_layout(ReflowGoal::ForScriptQuery, ReflowQueryType::ContentBoxQuery(content_box_request));
        self.join_layout(); //FIXME: is this necessary, or is layout_rpc's mutex good enough?
        let ContentBoxResponse(rect) = self.layout_rpc.content_box();
        rect
    }
```

Though I am currently not sure why some queries (like the one for the hit_test) do not require an call to `self.join_layout`.

**Comment by jdm** [comment]
I believe that join_layout is a no-op right now, since we stopped running layout and script concurrently.

**Comment by SimonSapin** [comment]
@jviereck Are you still interested in working on this?

**Comment by jviereck** [comment]
Interested yes, but it is unlikely I will manage to continue working on this anytime soon.

In case someone else wants to take over this issue, feel free to go ahead :)

On July 20, 2015 10:17:22 AM GMT+02:00, Simon Sapin <notifications@github.com> wrote:
>@jviereck Are you still interested in working on this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/servo/servo/issues/1714#issuecomment-122805781

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tschneidereit** [comment]
>
> In case someone else wants to take over this issue, feel free to go ahead
> :)
>

I *might* take it as a follow-up to #6662, then :)

**Comment by jdm** [comment]
These were implemented at some point.
