### ISSUE TITLE
Browser::new() changes CEF follow up

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#17273]
Since #16477, we need to make some changes in CEF:

- No need to use the `shell.homepage` pref
- don't call `frame.set_url` in `ServoCefBrowser::new`

/cc @sadmansk

**Comment by sadmansk** [comment]
@paulrouget I'm on it +1

**Comment by sadmansk** [comment]
@paulrouget Hey, just had a quick inquiry. `CefWrap::to_rust(*const cef_string_t)` returns an `&[u16]` value, I have been searching around but I couldn't find a way to convert that to `&str`, what I found was how to convert from utf16 to `std::String`. Since `ServoUrl::parse` takes in a `&str`, that conversion is necessary. Any pointers on how to get from the original `const cef_string_t` to an `&str` that can be passed to `ServoUrl::parse`?

**Comment by jdm** [comment]
CEF strings are UTF-16, while Rust strings are UTF-8. You will need to convert it into a String then obtain the &str from that.

**Comment by sadmansk** [comment]
@jdm That's what I was going for. Thanks for the confirmation!
