### ISSUE TITLE
Document.getElementsByName and friends should only return elements in the HTML namespace

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#1745]
This will become an issue when #1391 lands.

**Comment by iamdanfox** [comment]
I started looking into this bug because it's 'E-easy', but it looks like @jgraham has already fixed this issue with [his commit][2]

The [`HTMLCollection::by_tag_name`][1] function looks like it now matches the intricacies specified by https://dom.spec.whatwg.org/#concept-getelementsbytagname (ie requiring an exact match for non-HTML tagnames and allowing lowercase-matching for elements in the HTML namespace).

@Ms2ger do you think it's good to close?

[1]: https://github.com/servo/servo/blob/6fcc02e92f4c519239a834dc37a2965a4993322a/components/script/dom/htmlcollection.rs#L77
[2]: https://github.com/servo/servo/commit/0b802ab01882dc43ad5ec0f0e8e8699f22866e71#diff-00e0f39cf9a735a77aacc13a5490e4e5R102

**Comment by Ms2ger** [comment]
This issue is not about `getElementsByTagName`, it's about `getElementsByName` (and others defined in the HTML spec).

**Comment by iamdanfox** [comment]
Ah sorry, I misread a comment above.  If I understand correctly, fixing this issue would involve:

 * Adding a new test to the https://github.com/servo/web-platform-tests repo that highlights the `foo`/`FOO` namespacing thing described above.
 * Updating the [GetElementsByName function in documents.rs][1] to permit lowercase matches for HTML-namespaced elements, but require strict matches for non-HTML elements.  Probably using similar code to the `HTMLCollection::by_tag_name` [filter][2].

Would this also need changes to Element

[1]: https://github.com/servo/servo/blob/7fc37dfaa76c9265e6d2145fe5ef2fba5f6bd013/components/script/dom/document.rs#L1206
[2]: https://github.com/servo/servo/blob/7fc37dfaa76c9265e6d2145fe5ef2fba5f6bd013/components/script/dom/htmlcollection.rs#L120

**Comment by jdm** [comment]
@Ms2ger Does the above make sense?

**Comment by Ms2ger** [comment]
No, that appears to still be talking about getElementsByTagName. <https://html.spec.whatwg.org/multipage/dom.html#dom-document-getelementsbyname> only returns elements in the HTML namespace. (See this issue's summary.)

**Comment by neojski** [comment]
This is most likely blocked by #5585.
