### ISSUE TITLE
Brainstorm ways to redesign CSS parse error hierarchy

### ISSUE THREAD

**Issue by jdm** [servo/servo#17495]
There are a few constraints that resulted in the current design of:
* cssparser::ParseError
* selectors::SelectorParseError
* style_traits::StyleParseError
where each type has a type parameter and is used to encapsulate the error types from crates further down the crate hierarchy.

I'm going to use this issue to brainstorm ways the result could be improved.

**Comment by jdm** [comment]
Idea: have StyleParseError contains fewer variants that encapsulate potential errors from distinct parts of the parsing process. This would give us a ValueParseError enum that could be returned by Parse::parse, for example; however, this would likely interact very poorly with trying to use cssparser::Parser methods which would still return the types for the full possible set of CSS parser errors.

**Comment by SimonSapin** [comment]
For https://bugzilla.mozilla.org/show_bug.cgi?id=1347408 and https://bugzilla.mozilla.org/show_bug.cgi?id=1344131#c12 I’d like to eventually remove "rewinding the tokenizer" (the `Parser::try` method) from cssparser.

The way this would work is that the parser/tokenizer would hold a "current token" that could be borrowed (as opposed to having `.next()` give away ownership of a token). There would be separate APIs to advance to the next token. Whenever a bit of syntax contains alternatives (e.g. `|` in grammars), the parser would need to decide which branch to take based on only the current token. This makes pieces of code somewhat more interdependent, but CSS is designed to make this possible.

Anyway, the part relevant to this issue is that in this new design, there would always be a current token. So error value might not need contain a token themselves (or might need less data in general) since the error reporting/formatting could request the current token, which is the one where the error occurred.

**Comment by nox** [comment]
Whichever way we go, it would be preferable if the code can be derived.

**Comment by jdm** [comment]
What code are you referring to?

**Comment by nox** [comment]
Implementations of `Parse`.

**Comment by jdm** [comment]
Brainstorming occurred; no action was taken.
