### ISSUE TITLE
Black boxes behind DuckDuckGo sidebar text

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17942]
Page tested: https://duckduckgo.com/

Open the sidebar with the hamburger button and the text that appears is surrounded by black boxes.

Example image (Servo on the left, Firefox on the right):

![DuckDuckGo sidebar](https://i.imgur.com/IF29Kjh.png)

Tested in Windows 10.

**Comment by jdm** [comment]
Nothing happens in a local macOS build when I click the hamburger menu button.

**Comment by BrunoBernardino** [comment]
I can confirm the [latest `master`](https://github.com/servo/servo/commit/a6369149dc5344b2b80a12fca1c43cf99c94fdc9) still has this issue (of not opening the sidebar), even on macOS 10.12.6 (16G29) and not on FirefoxNightly 57.0a1 (2017-08-04) (I'm not sure if it's running servo already).

This is the result for `./mach run https://duckduckgo.com/`:

![duckduckgo-servo](https://user-images.githubusercontent.com/1239616/28998982-3d189ab8-7a30-11e7-9a30-0b196f9ebd1b.gif)

Is there a way to get a debugger to see what happens when I click? `-p` doesn't show anything useful. Sorry if this isn't a useful question.

**Comment by jdm** [comment]
There is no such debugger, unfortunately.

**Comment by atouchet** [comment]
This is fixed for me now, although it appears the theme selection icons are now busted.
