### ISSUE TITLE
Can't use local webrender

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#18166]
The top level `Cargo.toml` file used to have a `[replace]` section, but it's now replaced by `[patch.crates-io]`. Now I can't use my local checkout of webrender using the old syntax. Here are the error messages:

Case 1:
```
[patch.crates-io]
"https://github.com/servo/webrender" = { path = "../webrender/webrender" }
```
=> `patch for https://github.com/servo/webrender in https://github.com/rust-lang/crates.io-index did not resolve to any crates`

Case 2:
```
[patch.crates-io]
"webrender" = { path = "../webrender/webrender" }
```
=> The override had no effect, all the `webrender` in `Cargo.lock` points to the github one, and there is a section:
```
[[patch.unused]]
name = "webrender"
version = "0.47.0"
```

Case 3:

```
[replace] # Manually add the replace section, because they seem to still be around
"https://github.com/servo/webrender" = { path = "../webrender/webrender" }
```

=> `  no package or project section found.`

What is the correct way to do this (without manually change all 19 Cargo.tomls)? This _kind of_ blocks me on https://github.com/servo/webrender/issues/1314

**Comment by SimonSapin** [comment]
Case 2 has correct syntax. It makes a new or other version of webrender available, but as you can see with `patch.unused` it’s not being used. You need to either change the version number in `../webrender/webrender` to the version used in `Cargo.lock` (currently 0.49.0), or run `cargo update -p webrender --precise 0.47.0` (with 47 being the one you have in your local copy of webrender). The `--precise` part is probably necessary in this case because Cargo doesn’t usually downgrade things, and you seem to be using an earlier version.

**Comment by mrobinson** [comment]
WebRender is an unpublished crate, so the pre-existing ``patch`` syntax won't work. After a bit of hunting, I figured out how to make this work and I have a PR to update the WebRender README here: https://github.com/servo/webrender/pull/2097

The proper syntax is:
```
[patch."https://github.com/servo/webrender"]
"webrender" = { path = "<path>/webrender" }
"webrender_api" = { path = "<path>/webrender_api" }
```

**Comment by mrobinson** [comment]
Since this doesn't seem to be a problem. I'm going to close the issue in favor of the PR which updates the WebRender README.
