### ISSUE TITLE
Implement Node.baseURI

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#1824]
http://dom.spec.whatwg.org/#dom-node-baseuri

Block #1655.

**Comment by Wafflespeanut** [comment]
@jdm It's been an year since this was reported. Is this still an issue?

**Comment by jdm** [comment]
Yep!

**Comment by kball** [comment]
It looks like they've settled on an approach, as per https://www.w3.org/Bugs/Public/show_bug.cgi?id=20976#c32

It isn't represented in the spec yet from what I can see, but based on that issue it seems like the answer is a node should have the base URL of it's document.  Based on that I think this should be fairly trivial to implement.  I'm still working on getting a servo dev environment up and running but once I do I'll take a crack at it.

**Comment by jdm** [comment]
Great!

**Comment by kball** [comment]
There seems to be an interesting grey area around what should be returned if an element has not yet been added to a document.  This does not appear to be specified (specification both as exists and as discussed in that thread is just relative to the owning document), and looking at several browsers behavior varies.  Currently, Chrome returns an empty string (""), Safari returns null,and Firefox returns the baseURL of the window's document.  I don't have an IE setup to check.

The simplest implementation in Servo is to return null.  This would match Safari's behavior.  It is also fairly straightforward to change things to return an empty string, which would match Chrome's.  I do not see a straightforward way to match Firefox's current behavior, and it also seems less correct to me.

@jdm do you have an opinion on which of these routes to go?

**Comment by jdm** [comment]
I would go with null, file a spec bug, and leave a comment pointing to it.

**Comment by kball** [comment]
Ah actually as I read through the spec more carefully to try to file a reasonable bug, I think I was wrong.  I found this:
https://dom.spec.whatwg.org/#concept-node-document
```
Each node has an associated node document, set upon creation, that is a document.
```
And that node document is what should be used for the baseURI.  Set upon creation rather than set upon assign... so I think that implies we should actually match Firefox's behavior, and I need to dig deeper to understand what's happening in that case (where right now we don't seem to have that document associated at all)

**Comment by jdm** [comment]
The associated document for any node is obtained via `document_from_node(some_node)` in Servo.

**Comment by bzbarsky** [comment]
@kball Looking at what Chrome and Safari return from the `baseURI` getter is pointless because their getters are hopelessly buggy.  They don't return the actual base URI they use for the node, as you can tell by writing tests that involve an actual relative URI that needs resolving against the base URI.  There's just no sane reason why one would want to specify or implement what they do.

See https://bugs.webkit.org/show_bug.cgi?id=144652 and https://code.google.com/p/chromium/issues/detail?id=484930 for details.

What `baseURI` should return, morally speaking, is the value that would be used to resolve relative URIs.  This can't be `null` for nodes not in a document, because that's clearly and obviously not web-compatible at least for the case of `<img>`.

**Comment by frewsxcv** [comment]
Was this completed in #6559?

**Comment by jdm** [comment]
Yep.
