### ISSUE TITLE
Speedometer 2.0 fails at backbone test

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#18442]
If you run the [Speedometer 2.0 test on AWFY](https://mozilla.github.io/arewefastyet-speedometer/2.0/), with the latest Servo you can get through the 20 or so tests but then it will stop on the Backbone test at `BackboneJS-TodoMVC(22 / 480)`:

<img width="918" alt="screen shot 2017-09-11 at 8 47 02 am" src="https://user-images.githubusercontent.com/547158/30252865-f7de1792-96cd-11e7-9c04-0da9d315a305.png">

Terminal:

```
DEBUG: -------------------------------
DEBUG: Ember  : 2.6.2
DEBUG: jQuery : 2.2.4
DEBUG: -------------------------------
ERROR:script::dom::bindings::error: Error at https://mozilla.github.io/arewefastyet-speedometer/2.0/resources/tests.js:246:17 checkboxes[i] is undefined
```

(will try to dig in a bit further, but just wanted to post this before I did)

**Comment by jonathandturner** [comment]
I'm having deja vu about this one.  Is this related to needing to bump the mozjs/sm version?

**Comment by KiChjang** [comment]
Here's the surrounding context of the error:
```javascript
        new BenchmarkTestStep('CompletingAllItems', function (newTodo, contentWindow, contentDocument) {
            var checkboxes = contentDocument.querySelectorAll('.toggle');
            for (var i = 0; i < numberOfItemsToAdd; i++)
                checkboxes[i].click();
        }),
```
Here, I'm suspecting that [`querySelectorAll`](https://www.w3.org/TR/selectors-api/#interface-definitions) here was not able to select any elements, causing the [indexed getter](https://dom.spec.whatwg.org/#dom-nodelist-item) to return undefined.

**Comment by mauricioc** [comment]
Can I take this bug? It seems like the test is creating the checkboxes by simulating typing and pressing Enter on an input element. Servo is not handling the Enter keypress correctly for some reason (the event does not reach jQuery, and so it also doesn't reach the TodoMVC JS code), and I would like to investigate a bit.

**Comment by jdm** [comment]
Ooh, please do! Glad to hear you have a theory.

**Comment by KiChjang** [comment]
You may want to look at .https://github.com/servo/servo/blob/master/components/script/textinput.rs

**Comment by mauricioc** [comment]
So, https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L1393 also seems relevant. It seems we only trigger keypress events when they correspond to a printable key, which (naively) we would only get keyup and keydown events for pressing Enter, but never keypress. Does this seem plausible, or is it the kind of thing which would manifest itself in popular websites?

**Comment by jdm** [comment]
Easy test:
```html
<script>addEventListener('keypress', function(e) { console.log("press: " + e.key); })</script>
```
I only see output when pressing keys like 'a', 'f', '5'. Enter does not trigger it.

**Comment by jdm** [comment]
I believe the `is_printable()` check is attempting to address this text from the specification:
```
If supported by a user agent, this event MUST be dispatched when a key is pressed down, if and only if that key normally produces a character value.
```
(https://w3c.github.io/uievents/#event-type-keypress)
I suspect that enter is supposed to be treated as a \n [character value](https://w3c.github.io/uievents/#character-value) in this case, so perhaps printable is the wrong concept to be using.

**Comment by mauricioc** [comment]
Apologies, I made a mistake! There are two issues related to TodoMVC:

1) When running the Backbone.js version of TodoMVC from [0], the Enter key does not work. This is because the glutin frontend sees that Enter is a control character [1] and handles it differently, making the `is_printable()` check mentioned by @jdm return false. This does not match Firefox or Chrome, so I will file a separate bug tomorrow to investigate if/how this should be fixed.

2) The actual bug mentioned by @jonathandturner, in which the Backbone.js template is not evaluated properly. To be precise, escaped HTML gets inserted into the page instead of checkboxes, and this happens because a script tag's innerHTML attribute is getting escaped (which doesn't happen in Firefox). This happens at [2], and I verified that self.parent().html_name is None when serializing the Text node inside the "item-template" script tag for this sample:
```
<script type="text/template" id="item-template"><div></div></script>
<script type="text/javascript">console.log(document.getElementById("item-template").innerHTML</script>
```
I will investigate why this is the case tomorrow.

[0] http://swannodette.github.io/todomvc/architecture-examples/backbone/index.html
[1] https://github.com/servo/servo/blob/master/ports/glutin/window.rs#L373
[2] https://github.com/servo/html5ever/blob/04cfbf3463191ae8229e9f49429e2cb42dd486fd/html5ever/src/serialize/mod.rs#L205

**Comment by jdm** [comment]
Oh, that will be fixed by https://github.com/servo/servo/pull/17896. However, we need to release a new version of html5ever before that can merge.

**Comment by mauricioc** [comment]
Good to know, thanks! So I guess the bug @jonathandturner found is already fixed :) I'll look at the other one (item 1) as soon as possible.

**Comment by jdm** [comment]
We can now progress beyond this test.
