### ISSUE TITLE
OpenGL configuration

### ISSUE THREAD

**Issue by antoyo** [servo/servo#18685]
Hello.
As you can see [here](https://github.com/paulrouget/servo-embedding-example/issues/1), I started to work on integrating `servo` with `gtk-rs`.
I had one rendering issue that was caused by the fact that the depth buffer was not enable in the OpenGL configuration.
So, I wonder what is the configuration that is necessary in order to make servo works correctly.
For instance, do I also need to enable the stencil buffer?
Thanks for your help.

**Comment by jdm** [comment]
@glennw Can you answer this question?

**Comment by paulrouget** [comment]
Same goes for OpenGL ES. What is the minimum version required?

**Comment by paulrouget** [comment]
@antoyo Servo uses http://github.com/servo/glutin - so I usually look at the initialization code there to guess what is needed. But afaik, we don't have a proper descriptions of the API and extensions needed.

@glennw I'm having issues on Android where I can't get to compile the shaders. Likely because I don't use the right OpenGL ES version (1.4 apparently).

**Comment by fabricedesre** [comment]
@paulrouget : that was a while ago, but on Android using:
```
setEGLContextClientVersion(2);
setEGLConfigChooser(8, 8, 8, 8, 24, 0);
```
in a GLSurfaceView worked for me.

**Comment by paulrouget** [comment]
@fabricedesre thank you!

@glennw ideally, when starting WebRender, there would be a sanity check that would help embedders know if they setup something wrong.

**Comment by paulrouget** [comment]
Filed an issue for OpenGL ES: https://github.com/servo/webrender/issues/1795
