### ISSUE TITLE
Move custom elements stuff to their own dom::bindings submodule

### ISSUE THREAD

**Issue by nox** [servo/servo#19179]
The functions `html_constructor` etc have nothing to do in `dom::bindings::interface`.

**Comment by olmanz** [comment]
Hello,

if I understand correctly, the function html_constructor() simply has to be moved into its own .rs file (for example html_constructor.rs in the bindings directory)? I'm new to Rust, therefore it's better if I ask....

**Comment by jdm** [comment]
Yes, that is correct.

**Comment by nox** [comment]
Also:
* `pop_current_element_queue`
* `push_new_element_queue`
* `get_constructor_object_from_local_name`

**Comment by olmanz** [comment]
I moved the html_constructor() to its own file.
When I build the project with ./mach build --dev, I get 560 error messages, here one of them:

```
error[E0432]: unresolved import `dom::bindings::interface::html_constructor`
   --> /home/olmanz/Schreibtisch/workspaces/Rust/servo/target/debug/build/script-512133a4c1d5e960/out/Bindings/XMLHttpRequestUploadBinding.rs:294:5
    |
294 | use dom::bindings::interface::html_constructor;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `html_constructor` in `dom::bindings::interface`
```

All those errors point to various Rust files somewhere in target/debug/build.

It's clear that I get these errors because html_constructor() doesn't exist in interface.rs anymore, but in a new file that I called html_constructor.rs, so the import should be changed to dom::bindings::html_constructor::html_constructor.

The question is rather, where do these files in tagrget/debug/build come from? the /target directory does not exist before the build, it is created during the build....

**Comment by jdm** [comment]
Those files are generated by components/script/dom/bindings/codegen/CodegenRust.py.

**Comment by olmanz** [comment]
I changed line 5720 of CodeGen.py from

`'dom::bindings::interface::html_constructor',`
to
`'dom::bindings::htmlconstructor::html_constructor',`

but that doesn't seem to work. I get again 560 error messages, but now they look like this:

```
error[E0432]: unresolved import `dom::bindings::htmlconstructor`
   --> /home/olmanz/Schreibtisch/workspaces/Rust/servo/target/debug/build/script-512133a4c1d5e960/out/Bindings/XMLHttpRequestUploadBinding.rs:282:20
    |
282 | use dom::bindings::htmlconstructor::html_constructor;
    |                    ^^^^^^^^^^^^^^^ Could not find `htmlconstructor` in `bindings`
```
From my understanding about imports in Rust, dom::bindings::htmlconstructor should point to the file components/script/dom/bindings/htmlconstructor.rs. I have created that file and moved html_constructor() to it from interface.rs, so I'm not sure why I get this error message....

**Comment by jdm** [comment]
Have you added `mod htmlconstructor` to components/script/dom/bindings/mod.rs?

**Comment by olmanz** [comment]
Thanks, that worked.

I will now work further on this issue and also move the other functions to the new file.
