### ISSUE TITLE
Make Service Worker implementation up-to-date

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19302]
As @creativcoder mentioned in #11091, the implementation of Service Worker has changed a lot.
I'd like to create this issue to make the Service Worker implementation up-to-date.

- [ ] Update `webidl`
  - [x] ServiceWorkerRegistration (#22171)
  - [x] ServiceWorkerContainer (#22538)
  - [x] ServiceWorkerGlobalScope (#22191)
  - [x] NavigationPreloadManager (#22218)
  - [x] ServiceWorker (#22540)

**Comment by mandreyel** [comment]
@CYBAI From the referenced PR it looks like you intend to work on this, but it's not assigned. Does that mean there is a chance to collaborate or would you like to work on this yourself?

**Comment by CYBAI** [comment]
@mandreyel Sure! The main goal for this issue is to make the implementation of Service Worker up-to-date. So, my first attempt is to update all the related `webidl` files. Let's update these webidl files first!

**Comment by mandreyel** [comment]
@CYBAI Cool, I'll look into updating some myself this evening, if that's alright!

**Comment by CYBAI** [comment]
@mandreyel Great! You can leave a comment to let me know you'd like to work on which one so that I can work on the others 😆

**Comment by mandreyel** [comment]
@CYBAI Alright, I will (please do the same)! I'm still reading the spec to get a better grip on the concepts at play here.

**Comment by mandreyel** [comment]
I'm going to try updating the WebIDL of `ServiceWorkerGlobalScope`!

**Comment by CYBAI** [comment]
I'm going to try to create `NavigationPreloadManager`.

**Comment by gterzian** [comment]
FYI there seems to be a huge amount of discussions over at https://github.com/whatwg/fetch/search?q=service+worker&type=Issues with regards to how Service Workers integrate with fetch and the http-cache. Related: https://github.com/servo/servo/issues/23495

**Comment by gterzian** [comment]
One thing I'd like to note and check against other people's view:

It seems to me that we spawn one "service worker manager" per script-process, running it as a thread on the same process. 

I think this is perhaps not the right design, because service workers are shared per-origin(with one origin potentially having many scopes), and the concept of a script process doesn't map to origin, it maps essentially to domain. 

Also, even same-origin pages do not necessarily run in the same script process, since they can be part of different browsing context groups. 

So, we could certainly share a service worker across all origins running the in the browser, but it seems sub-optimal to run them inside a script-process in that case. For example, what happens when the script process shuts down? In theory service workers should remain available to any other same-origin page running in another script-process, and lastly, service workers should even remain available once all script-processes have shut down. 

So, I think the right design is for the constellation to keep track of service workers(managers) on a per-origin basis, and run them in their own dedicated process, one per origin(which would be child processes of the constellation, not of script). 

Then, when script requests a service-worker, it would initially be "brokered" by the constellation, which would then make a direct IPC communication possible between a script-process and the requested service-worker. 

The constellation would then also be able to do stuff with service-workers outside of the scope of script, such as forwarding notifications coming from elsewhwere(I understand that's the idea of service workers). 

Please let me know what you think.

**Comment by CYBAI** [comment]
> we could certainly share a service worker running in one script-process across all origins running the in the browser, but it seems sub-optimal to run them inside a script-process in that case

this sounds efficient to me.

> In theory service workers should remain available to any other same-origin page running in another script-process

yes, I think we should be able to reuse the same service worker between different browsing context but same origin?

> Then, when script requests a service-worker, it would initially be "brokered" by the constellation, which would then make a direct IPC communication possible between a script-process and the requested service-worker.
> The constellation would then also be able to do stuff with service-workers outside of the scope of script, such as forwarding notifications coming from elsewhere(I understand that's part of the idea of service workers).
> Please let me know what you think.

@gterzian Sure! Don't have too much time recently 😓 but I will read the code and share my thought again here! (also read the SharedWorker issue you just opened) Btw, I'm working on #23545 because we'll also need to handle `modules` for service workers!

**Comment by gterzian** [comment]
> the same service worker between different browsing context but same origin

Yes, so the idea is, I think, that every ScriptThread for a given origin should use a single `ServiceWorkerGlobalScope`. 

I'm reading a bit more through the existing code and there something that surprises me:

The constellation seems to have only one `swmanager_chan`, and it's [set to a new value each time a sw_manager registers itself](https://github.com/servo/servo/blob/d9ea7ae1781f090ba52423b39ff6e9ee96e550c2/components/constellation/constellation.rs#L1250). So I in multiprocess Servo, I think this means that each time a new script process is started, a new [`sw_manager` will be registered](https://github.com/servo/servo/blob/8328763ff277bf6c050c94a91bd4b41ff1518e3c/components/servo/lib.rs#L925), at which point it will [send it's  `swmanager_chan` to the constellation](https://github.com/servo/servo/blob/5ec725488f0d5cb8e132e32e03bcfa52afb8c810/components/script/serviceworker_manager.rs#L69) and effectively overwrite a previous one. So it seems that in multiprocess mode, the process is broken since you'll end-up with only one SW manager, and each new script-process will overwrite a previously registered one. Anyone noticed this, or am I missing something?

In single-process mode a single sw_manager is created on start-up, however it runs all workers in the same process(obviously). 

So my proposal is essentially have only one sw_manager, like is currently done in single-process Servo, but have it run one process per origin, and have all script-threads/processes use that single sw_manager, running one `ServiceWorkerGlobalScope` per origin(and have that run multiple registration scopes in one thread, or one thread per registration scope?)

**Comment by gterzian** [comment]
This is worth reading: https://docs.google.com/presentation/d/1GZJ3VnLIO_Pw0jr9nRw6_-trg68ol-AkliMxJ6jo6Bo/edit#slide=id.g36f61837b7_1_69

**Comment by gterzian** [comment]
I think we've ticked all the boxes at https://github.com/servo/servo/issues/19302#issue-275379996

Time to close this one?
