### ISSUE TITLE
Servo forks serde with [patch]

### ISSUE THREAD

**Issue by DustinByfuglien** [servo/servo#19588]
I'm trying a build simple servo app with cargo build (rustc 1.24.0-nightly (3bee2b44c 2017-12-16)):

```
extern crate servo;

fn main() {
    println!("Servo version: {}", servo::config::servo_version());
}
```

Cargo.toml includes:
```
[dependencies]
servo = { git = "https://github.com/servo/servo" }
```

But building is terminating with exit code 101:

> error: Package `serde_derive v1.0.23` does not have these features: `deserialize_from`

Windows 7x64.

Help please.

**Comment by fabricedesre** [comment]
Servo uses a serde fork, the current version in Cargo.lock is https://github.com/gankro/serde?branch=deserialize_from_enums3#fc611736

Does that match yours? Note how in https://github.com/paulrouget/servo-embedding-example they recommend to copy Servo's Cargo.lock in your project to avoid these kind of issues.

**Comment by DustinByfuglien** [comment]
Thank you for the link.
Now I understand wat was wrong.

**Comment by SimonSapin** [comment]
Servo has this section in its root `Cargo.toml`, which you probably need to copy in yours:

```toml
[replace]
"serde:1.0.23" = { git = "https://github.com/gankro/serde", branch = "deserialize_from_enums3" }
"serde_derive:1.0.23" = { git = "https://github.com/gankro/serde", branch = "deserialize_from_enums3", feature="deserialize_from" }
```

This also seems to make using `[patch]` impossible. @Gankro, is there a plan to upstream these serde features, or somehow stop using `[replace]`?

**Comment by SimonSapin** [comment]
https://github.com/servo/servo/pull/19590 replaces `[replace]` with `[patch]` which fixes some problems, but this is still not ideal. When `[patch]`’ing another library which depends on `serde = "1.0"`, cargo insisted on upgrading that dependency to 1.0.24 from crates.io instead of 1.0.23 from the forked git repo, even after explicitly downgrading it: `cargo update -p serde:1.0.24 --precise 1.0.23` would succeed, but then the next build would "upgrade" again.

This may be a Cargo bug, but `[patch]` / `[replace]` is still something that should not be in master IMO.

**Comment by dtolnay** [comment]
I will be publishing a Serde version with most of the changes from the fork in the next few days. As I understand it, at that point Servo will be able to drop the [patch] of `serde` but wants to keep using a fork of `serde_derive` -- so we need to upstream the rest of the changes somehow or figure out a long-term solution for the fork.

**Comment by Gankro** [comment]
With the serde work upstreamed servo could remove both patches, as the serde_derive fork “only” introduces a transparent optimization. Performance of gecko is more critical (in the shirt term), so we would continue to apply the derive patch there.

**Comment by SimonSapin** [comment]
More breakage cause by this: https://github.com/servo/servo/issues/19698. Though I think part of the reason is that the fork’s version number is behind crates.io. Doing either of:

* Keep the fork up to date whenever upstream publishes a new version
* Or change the fork’s version number from 1.0.23 to something like 1.0.1023

might help. What do think @Gankro ?

**Comment by Gankro** [comment]
You can remove the fork in the next webrender update, it’s been upstreamed. Webrender still forks serde_derive but it’s for a transparent optimization, failing to include it just means you’re a bit slower.

**Comment by jdm** [comment]
The fork was indeed removed in https://github.com/servo/servo/pull/19614.
