### ISSUE TITLE
Move `contain` outside of mako.

### ISSUE THREAD

**Issue by emilio** [servo/servo#19656]
See  #19015.

**Comment by emilio** [comment]
Tentatively assigning it to @stevel98 :)

**Comment by stevel98** [comment]
Hi,
I'm still new to rust, and I'm puzzled over the purpose of the `computed_value` module under the `contains` longhand in `box.mako.rs`.
```
pub mod computed_value {
    pub type T = super::SpecifiedValue;
}
```

I only see it used in:
```
#[inline]
pub fn get_initial_value() -> computed_value::T {
    computed_value::T::empty()
}
```

But wouldn't this be the same as:
```
#[inline]
pub fn get_initial_value() -> computed_value::T {
    Self::empty()
}
```

**Comment by CYBAI** [comment]
@stevel98 

This block means you can just implement the `Contain` type inside `specified` module; then, due to same for both `specified` and `computed`, you can just export (`pub use`) the `specified` type in `computed` module. You can check [this PR](https://github.com/servo/servo/pull/19583/files). I think they're not same but similar.

```rust
pub mod computed_value {
    pub type T = super::SpecifiedValue;
}
```

For this block, yeah, you can use `Self::empty()`.

```rust
#[inline]
pub fn get_initial_value() -> computed_value::T {
    computed_value::T::empty()
}
```

#### Another note:
For this case, I didn't try but maybe you don't need this `get_initial_value` function? I think you can just use `empty` for `initial_value`?

cc @emilio 
If I'm wrong, please correct me :P

**Comment by emilio** [comment]
Yes, but in this case, since the types are the same, it's completely redundant to use `computed_value::T` instead of `Self`. This is the kind of stuff we're trying to remove :)

**Comment by stevel98** [comment]
Thanks! I'll try to remove it then.
