### ISSUE TITLE
Move -servo-display-for-hypothetical-box outside of mako.

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19697]
I'll take this one as a sub-issue of #19015

**Comment by emilio** [comment]
This is great! Do you have any particular plan for it? My idea for this is getting rid of the custom_cascade stuff, and unify how it works with Gecko.

Gecko uses `mOriginalDisplay` for this, and sets that from `gecko.mako.rs`. I planned to unify it setting it in `StyleAdjuster::adjust`, something like:

```rust
if let Some(mut box) = self.style.get_box_if_mutated() {
    // Save the display value without style adjustments now, which we need for hypothetical boxes.
    let display = box.get_display();
    box.set_original_display(display);
}
```

And we can remove `set_adjusted_display`, since now it's just `set_display`, and remove the whole `-servo-display-for-hypothetical-box`, which is just `get_original_display`, or something like that.

**Comment by CYBAI** [comment]
@emilio No, I didn't have my own plan. However, after you mentioned, I searched `custom_cascade` in Servo. Then, I found it's only used for `-servo-text-decorations-in-effect` and `-servo-display-for-hypothetical-box`. I'm willing to help to get rid of it and make it unify with Gecko.

So, after removing all `set_adjusted_display` methods and setting `display` inside `StyleAdjuster::adjust`, then we don't have the attribute, `-servo-display-for-hypothetical-box`, because it's just `get_original_display`, am I right?
