### ISSUE TITLE
Show `list-style-type: disc` incorrectly

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19796]
URL: https://leanpub.com/purescript/read

The `list-style-type: disc` dots are shown under the Table of Contents; instead, it should be like follwoing

- Core logic written in PureScript, with the user interface written in JavaScript.
- Application written in JavaScript or another compile-to-JS language, with tests written in PureScript.
- PureScript used to automate user interface tests for an existing application.

In Firefox Nightly:
![image](https://user-images.githubusercontent.com/6782666/35056885-218fe6a8-fbee-11e7-8085-fb4b0a5b735c.png)

In Servo (built with 4f09987611):
![image](https://user-images.githubusercontent.com/6782666/35056864-0ece5de2-fbee-11e7-820d-58428f2989e4.png)

Tested in `macOS 10.12.6`

**Comment by CYBAI** [comment]
@jonleighton Please take it! I will check your PR to understand how I can work on issue like this in the future 😄 Besides, thanks for the test case!

**Comment by jonleighton** [comment]
This is actually a better test case, since my previous one renders differently on Chrome:

``` html
<!doctype html>
<style>
body {
  padding: 30px;
}

#sidebar {
  float: left;
  width: 200px;
  height: 100px;
  background: yellow;
}

ul {
  padding: 0;
}
</style>

<div id="sidebar">
  Sidebar
</div>

<ul>
  <li>Core logic written in PureScript, with the user interface written in JavaScript.</li>
  <li>Application written in JavaScript or another compile-to-JS language, with tests written in PureScript.</li>
  <li>PureScript used to automate user interface tests for an existing application.</li>
</ul>
```

*However*, I've dug into this a bit and I think that Servo's rendering may actually be compliant with the spec. This is what [the current CSS 2.2 draft says](https://www.w3.org/TR/CSS22/generate.html#propdef-list-style-position) about `list-style-position: outside` when used adjacent to a float:

> The position of the list-item marker adjacent to floats is undefined in CSS 2.2. CSS 2.2 does not specify the precise location of the marker box or its position in the painting order, but does require that for list items whose 'direction' property is 'ltr' the marker box be on the left side of the content and for elements whose 'direction' property is 'rtl' the marker box be on the right side of the content. The marker box is fixed with respect to the principal block box's border and does not scroll with the principal block box's content.

I can't find anything more specific about where the marker should be rendered.

Nonetheless, Servo's rendering is different to how Firefox and Chrome implement this, so maybe we should change it? @pcwalton, it seems you wrote most of the current implementation, do you have any thoughts?
