### ISSUE TITLE
Uuid no longer supports custom RNGs

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#20306]
PR https://github.com/uuid-rs/uuid/pull/112/ removed the `Rand` impl from `Uuid`, so we can no longer generate UUIDs using the `servo_rand` custom RNG.

Uuid issue: https://github.com/uuid-rs/uuid/issues/153

**Comment by asajeffrey** [comment]
cc @nox @Eijebong

**Comment by asajeffrey** [comment]
IRC chat: https://mozilla.logbot.info/servo/20180315#c14464165

**Comment by kinggoesgaming** [comment]
I think I will try to get a temporary fix this week until rand stabilizes.

**Comment by nox** [comment]
What kind of temporary fix do you have in mind? Could we just make rand a public dependency again and bit the bullet and make a breaking bump in uuid when one is made in rand, please?

**Comment by kinggoesgaming** [comment]
I will be opening a PR to patch it in a few and until thats merged and released, you can use a `[patch]` in `Cargo.toml`

**Comment by asajeffrey** [comment]
Thanks!

**Comment by KodrAus** [comment]
Sorry, chiming in a bit late.

The reason `rand` was removed as a public dependency was so that we aren't stuck with a specific minor version when `uuid` stabilises. Since `rand` is actively churning at the moment I'm not sure there's any stable version of `rand` on the near horizon. If we pull this in, we'll just end up in the same boat whenever we want to stabilise `uuid`.

Having said that, I'm not totally against just bringing it back, but it would be good if we can explore other options to support what Servo needs without making `rand` public first.

**Comment by nox** [comment]
AFAICT providing a `new_v4_from_bytes` method that would do the same `set_variant`/`set_version` calls as `new_v4` would be enough to fit the needs of Servo. @asajeffrey can you confirm that?

**Comment by asajeffrey** [comment]
Yes, part of the problem is there's no workaround for generating a v4 uuid by hand, since `set_variant`and `set_version` are private.

**Comment by Eijebong** [comment]
We bumped uuid to 0.6 now, I think this can be closed
