### ISSUE TITLE
Use BufferSource in TextDecoder API

### ISSUE THREAD

**Issue by jdm** [servo/servo#20344]
Now that #20267 has merged, we can uncomment the `decode` method in TextDecoder.webidl that accepts BufferSource and remove the one that fakes it by accepting an `option` value. This will require similar cleanup as #20342.

Code: `components/script/dom/webidls/TextDecoder.webidl`, `components/script/dom/textdecoder.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/encoding/textdecoder*`

**Comment by christianpoveda** [comment]
@highfive assign me

**Comment by christianpoveda** [comment]
Just started working on it. I have a first working version [here](https://github.com/christianpoveda/servo/blob/issue_20344/components/script/dom/textdecoder.rs#L69). Nevertheless a bunch of tests are failing and I don't know what's causing that.

All the failing tests are because `fatal` is set to `true` and in cases where the decoding is supposed to fail `Decode` does not throw anything. For example:
```
 FAIL [expected PASS] Fatal flag: utf-16le - truncated code unit
  │   → assert_throws: function "function () {
            new TextDecoder(t.encoding, {fatal: true}).decode(new Uint8Array(t.input))
        }" did not throw
```

However reading the spec, `{fatal: true}` should be passed as a second parameter to `decode` (which is the options parameter in the rust code) not to `TextDecoder`'s constructor. 

Should I modify the tests? or should I keep using `self.fatal` instead of `options.fatal`?

**Comment by christianpoveda** [comment]
Ohh sorry I was confused, I did not realized `TextDecodeOptions` exists and is not just a typo. Nevertheless what should I do with `TextDecodeOptions` and `stream`?

**Comment by jdm** [comment]
Let's accept a TextDecodeOptions as the second argument but ignore the stream member for the purposes of this issue. We can file another issue to implement the steps in https://encoding.spec.whatwg.org/#dom-textdecoder-decode that it affects.

**Comment by jdm** [comment]
Actually, we shouldn't need to add TextDecodeOptions for this issue at all. I'll file the issue for updating the implementation to match the spec.

**Comment by jdm** [comment]
Ah, that's #13234.

**Comment by christianpoveda** [comment]
hehe, Ok i'll let the TextDecodeOptions in the webidl file but will not use it in the body of Decode. What about the exceptions?

**Comment by jdm** [comment]
What do you mean by "the specification says Decode does not throw exceptions"? If you mean that the spec webIDL doesn't include [Throws], that's because that's an implementation-specific extension that we use.

**Comment by christianpoveda** [comment]
oh ok got it
