### ISSUE TITLE
Parse webIDL from compiler plugin to verify inheritance of DOM objects matches IDL

### ISSUE THREAD

**Issue by jdm** [servo/servo#20461]
Given [this crate](https://crates.io/crates/webidl), we could theoretically add a [compiler plugin](https://github.com/servo/servo/tree/master/components/script_plugins) that iterates over the types in script::dom::types, parses the WebIDL file that matches that type name, and verifies that the first field of the DOM type matches the name of the parent type of the interface, per [the documentation](https://doc.servo.org/script/dom/index.html#inheritance).

**Comment by Succo** [comment]
Hi, would that be a good first task? If so I would be interested.

**Comment by jdm** [comment]
I do not believe this would be a good first task.

**Comment by KiChjang** [comment]
@jdm How much additional time would be spent on compilation if we perform this check?

**Comment by jdm** [comment]
No idea!

**Comment by jdm** [comment]
Sorry, I was on vacation for all of April. There are four main parts to this project:
* extend the dom_struct macro to add a new `#[webidl]` attribute to structures marked `#[dom_struct]` (`components/dom_struct/lib.rs`)
* create a new compiler plugin (modeled after `components/script_plugins/unrooted_must_root.rs`) which checks for the presence of the `#[webidl]` attribute, then uses the name of the struct to open the equivalent webidl file found in `components/script/dom/webidls`
* parse the webidl file using the [webidl](https://crates.io/crates/webidl) crate when the file has been opened successfully
* determine the parent interface of the matching interface that has been parsed, and verify that the first field of the rust structure matches that interface name

**Comment by jdm** [comment]
As to @KiChjang's concerns about compilation time, if we can get this working I think we should figure out how long this check takes in isolation, and whether it affects overall build time significantly.

**Comment by aeweston98** [comment]
Ok, great I will start working on that. Can you assign the issue to me? Thanks!

**Comment by aeweston98** [comment]
@jdm I have read the rust docs for Attributes and Procedural Macros and I just want to clarify a few things to make sure I understand correctly. I have taken bullet 1 to mean add a #[webidl] Token to the attributes set in the existing dom_struct macro, like [so](https://github.com/aeweston98/servo/blob/6969392bdc43b301f05876af52cf5dde4ace12e2/components/dom_struct/lib.rs#L20). Based on the code in unrooted_must_root.rs, the new plugin will then check for the new webidl attribute using the [LateContext.tcx.has_attr](https://manishearth.github.io/rust-internals-docs/rustc/ty/struct.TyCtxt.html#method.has_attr) function. Please let me know if I have misinterpreted anything, otherwise I will start on the compiler plug-in, thanks!

**Comment by jdm** [comment]
That is correct.

**Comment by aeweston98** [comment]
@jdm I have made the skeleton for the compiler plugin (based on unrooted_must_root.rs). I added a new file [verify_webidl.rs](https://github.com/aeweston98/servo/blob/8d5d8510ddda5765853358286daa914bf8658c68/components/script_plugins/verify_webidl.rs) and modified [lib.rs](https://github.com/aeweston98/servo/blob/8d5d8510ddda5765853358286daa914bf8658c68/components/script_plugins/lib.rs#L41-L42). 

First, based on the must_root plugin, I chose the LateLintPass trait for WebIdlPass, however I wanted to check if that is correct since there are other LintPass variants that could be used. Additionally, I thought that I should define the function check_struct_def, since this should give access to both the attributes of the struct (to check for webidl attribute) and the string field which is the parent interface name as a TyStr. That should be the only function to implement for WebIdlPass as far as I can tell.

If the above is correct, I will start to work on the actual opening, parsing and checking of the webidl file. Thanks!

**Comment by KiChjang** [comment]
@aeweston98 The logic in your verify_webidl.rs makes sense, though I think you can get the DefId of the struct itself by calling [cx.tcx.hir.local_def_id](https://manishearth.github.io/rust-internals-docs/rustc/hir/map/struct.Map.html#method.local_def_id). Have you made any further progress on this?

**Comment by aeweston98** [comment]
@KiChjang  I am in school right now, so I have been busy for a little while and haven't had a chance to progress further. I would like to continue working on it now, if that is ok.

**Comment by jdm** [comment]
Ack, I'm sorry for missing the previous comment. You are welcome to continue working on it :)

**Comment by aeweston98** [comment]
@jdm Sorry for the slow progress. The past few weeks have been very busy with midterms and co-op interviews. I have been making some progress on using the webidl crate to parse the files. I will try to have some results and/or questions by the end of the weekend. Thanks!

**Comment by jdm** [comment]
@manishearth Is this redundant with the PR you merged recently?

**Comment by Manishearth** [comment]
Yes, however mine is a somewhat hacky bridge between the Rust codegen and Python codegen, so improving it would be nice. But not much of a priority.

**Comment by KiChjang** [comment]
@aeweston98 Are you still working on this?

**Comment by aeweston98** [comment]
@KiChjang No I am not actively working on it

**Comment by CYBAI** [comment]
> Yes, however mine is a somewhat hacky bridge between the Rust codegen and Python codegen, so improving it would be nice. But not much of a priority.

This is #21105

**Comment by krk** [comment]
@highfive assign me

**Comment by krk** [comment]
I have a draft PR checking the first field of `#[webidl]` structs. Currently, it prints errors for the structs that have `Reflector` as the first field. 

Example error:
```
error: webidl-rust inheritance mismatch, rust: "XRViewport", rust parent: "Reflector", webidl parent: ""
  --> components/script/dom/xrviewport.rs:13:12
   |
13 | pub struct XRViewport {
   |            ^^^^^^^^^^
```

Definition of `XRViewport`:
https://github.com/servo/servo/blob/17204544d975a44f813b96ed3e0eae3b688596bc/components/script/dom/xrviewport.rs#L12-L14

How should I handle the `Reflector`?

**Comment by KiChjang** [comment]
@krk If the WebIDL interface does not have a parent, then yes, we should check whether the first field is a `Reflector`, since that's ultimately the JavaScript object that represents the Rust implementation of the WebIDL interface.

**Comment by krk** [comment]
@KiChjang After requiring `Reflector` for interfaces that do not extend other interfaces and handling `PaintRenderingContext2D` as per https://github.com/servo/servo/blob/a14b952fa3eedec86e6308213c525538bcb20827/components/script/dom/bindings/codegen/CodegenRust.py#L2205-L2208 there are two errors left in the build:

1. `WindowProxy` definition is not in `WindowProxy.webidl` but in `Window.webidl`. Is this a bug?
```
error: No such file or directory (os error 2)
  --> components/script/dom/windowproxy.rs:59:12
   |
59 | pub struct WindowProxy {
   |            ^^^^^^^^^^^
```
2.
```
error: webidl-rust inheritance mismatch, rust: "TestBindingProxy", rust parent: "Reflector", webidl parent: "TestBinding"
  --> components/script/dom/testbindingproxy.rs:13:12
   |
13 | pub struct TestBindingProxy {
   |            ^^^^^^^^^^^^^^^^
   |
   = note: #[deny(webidl_inherit_correct)] on by default
```

**Comment by jdm** [comment]
Interesting! The WindowProxy declaration can probably move to WindowProxy.webidl; I'm not really sure why it was put there originally. And the TestBindingProxy issue looks like a legitimate bug.

**Comment by krk** [comment]
I have moved `WindowProxy` declaration to its own file.

**Comment by krk** [comment]
Search for `TestBindingProxy`  in the repo does not reveal much, it is only declared and has an `impl` in https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/script/dom/testbindingproxy.rs#L13

I declared it as 

```rust
#[dom_struct]
pub struct TestBindingProxy {
    testbinding_: TestBinding,
}
```

Finally, `./mach build -d` can finish successfully :smile:
