### ISSUE TITLE
Typing "3" in an input field doesn't work

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#20681]
While all other num keys work... A cursory look didn't surface an obvious typo or cut/paste error...

**Comment by tigercosmos** [comment]
I just reproduced it. amazing...

**Comment by kwonoj** [comment]
maybe regression caused by https://github.com/servo/servo/pull/20327 ?  I'll try to repro and bisect without changes.

**Comment by fabricedesre** [comment]
> maybe regression caused by #20327 ? I'll try to repro and bisect without changes.

I just checked, and `is_identifier_ignorable` returns `false` in this case, so this is not the cause.

**Comment by kwonoj** [comment]
Nailed it, it isa regression caused by me, but in different PR than #20327.

I did assign a new hotkey for capture webrender in #20315, https://github.com/servo/servo/pull/20315/files#diff-4d1fd4a873c7f3f5e352fad96ac6db87R1233 and it is aggressively eats up keyevent when it doesn't match with modifier combination, ends up with omitting actual keyevent.

I'll try to fix this. (not sure I can assign via @highfive 🤔 )

**Comment by kwonoj** [comment]
@highfive assign me
