### ISSUE TITLE
GetChildBrowsingContextId returns BCIDs in reverse tree-order

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#20890]
Given the following HTML:
```
<!doctype html>
<title>cross-document channel</title>
<iframe src=004-1.html></iframe>
<iframe src=004-2.html></iframe>
```

Running `window[0]` would return the iframe with the src of `004-2.html`, and `window[1]` returns the one with `004-1.html`.

The relevant code snippet in the constellation that processes this IPC message is here:
https://github.com/servo/servo/blob/022daccbe102aa67c6a4442f8d9cbccc3a7e221b/components/constellation/constellation.rs#L1166-L1174

... which causes me to think that perhaps the `AllBrowsingContextsIterator` defined in `constellation/browsingcontext.rs` is traversing the HTML tree in reversed tree order... but I think that isn't really the case either, so perhaps the HTML parser is inserting them in reversed order?

**Comment by jdm** [comment]
The iterator appends the child browsing contexts in tree order (https://github.com/servo/servo/blob/022daccbe102aa67c6a4442f8d9cbccc3a7e221b/components/constellation/browsingcontext.rs#L136), but returns them in reverse order because it uses [pop](https://github.com/servo/servo/blob/022daccbe102aa67c6a4442f8d9cbccc3a7e221b/components/constellation/browsingcontext.rs#L125).
