### ISSUE TITLE
Elements with a combination of 'border' and 'border-radius' are drawn incorrectly

### ISSUE THREAD

**Issue by MartinRogalla** [servo/servo#20922]
Excuse my narcism here for posting my own profile picture, but I was checking out my own [website](https://martinrogalla.com) in servo. What I noticed is that my profile picture that is supposed to be round, get's drawn incorrectly:

Google Chrome:
<img width="201" alt="chrome" src="https://user-images.githubusercontent.com/1066157/41006727-0ef36c34-6923-11e8-9eb7-57b9934f8532.png">

Servo:
<img width="206" alt="servo" src="https://user-images.githubusercontent.com/1066157/41006129-97400c9e-6920-11e8-83c8-d980984b5c07.png">

When I try to create a 'circular' element with the following attributes:
```css
border: 3px solid #fff;
border-radius: 100px; /* note, border-radius >= 75px for the element do be 'circular' */
width: 150px;
height: 150px;
```

To me it looks like the image gets square borders and then is rounded, instead of the other way around. I'm interested in contributing to servo and would love to pick this issue up if you think it's doable.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/11edbfc159e30b5dffdf9df4e1880ba02cc3f0f8/components/layout/display_list/background.rs#L714 is the code that is responsible for creating a border radius value that is added to display list items. It would be worth creating a minimal testcase so it's easier to trace the code that ends up reaching there.

**Comment by MartinRogalla** [comment]
Perfect, will do. Thanks!

**Comment by MartinRogalla** [comment]
The following document should render render a purple circle with a pink border:
```html
<html>
<head>
    <link rel=match href=border_radius_border_solid_combination.html>
</head>
<body>
    <div style="background: #1f1f2e; border-radius: 50%; border: 10px solid #ff3399; width: 250px; height: 250px;"></div>
</body>
</html>
```
**Expected output:**
<img width="290" alt="correct" src="https://user-images.githubusercontent.com/1066157/41048281-ab41d6b2-69ae-11e8-9134-f5c0d89cc0f3.png">
**Actual output:**
<img width="290" alt="actual" src="https://user-images.githubusercontent.com/1066157/41048312-b3a3bb90-69ae-11e8-96a2-44247ca8f154.png">

This is only happening when the border is greater than 3px. If it is 3px or less, it renders as expected.

[Display-list Dump](https://gist.github.com/MartinRogalla/cb2970f3ea1699419ac15f7799c63c48)

Nothing in the display-lists caught my eye caught my eye, that indicate why it's incorrectly rendering. I will keep looking.

**Comment by jdm** [comment]
It may be that our display list is correct and webrender is interpreting it incorrectly. @gw3583 does this ring any bells?

**Comment by MartinRogalla** [comment]
I think the issue might be here: [webrender/src/util.rs extract_inner_rect_impl](https://github.com/servo/webrender/blob/fac0040b4597d6c4a4b36fffbb8117782027e7ca/webrender/src/util.rs#L342-L346). I'll have another look in a bit and if needed will try to build the webrenderer and use that to debug where it's going wrong.

**Comment by gw3583** [comment]
It doesn't ring any bells. It's certainly possible it could be a bug in WR, although I don't think we've seen anything like this in Gecko thus far. One option would be to build wrench (the standalone WR reftest tool) and see if you can reproduce it in wrench by modifying some of the border reftests (for example https://github.com/servo/webrender/tree/master/wrench/reftests/border).

**Comment by gw3583** [comment]
If you can reproduce it there, that would rule out Servo being the issue.

**Comment by MartinRogalla** [comment]
Perfect, I'll try that. Thanks!

**Comment by MartinRogalla** [comment]
Running the border-tests using:
```
cd wrench && cargo run -- reftest reftests/border/
```
in WebRender outputs failing tests:
```
REFTEST INFO | 15 passing, 5 failing
Reftests with unexpected results:
        reftests/border/border-clamp-corner-radius.yaml == reftests/border/border-clamp-corner-radius.png
        reftests/border/border-suite.yaml == reftests/border/border-suite.png
        reftests/border/border-suite-2.yaml == reftests/border/border-suite-2.png
        reftests/border/border-suite-3.yaml == reftests/border/border-suite-3.png
        reftests/border/degenerate-curve.yaml == reftests/border/degenerate-curve.png
```
Is this to be expected (as in tests written but not yet implemented), or should these reftests always pass?

**Comment by gw3583** [comment]
For the reftests, you'll need to use the headless script to run them - this will ensure that they are drawn with a software rasterizer for consistency between machines:

```./script/headless.py reftest reftests/border/```

**Comment by dralley** [comment]
The test snippet from https://github.com/servo/servo/issues/20922#issuecomment-395125018 is fixed, but the original website link still renders incorrectly.

**Comment by jdm** [comment]
```html
<style>
#avatar {
        border: 3px solid #000;
        border-radius: 100px;
        width: 150px;
        height: 150px;
}
</style>
<img id="avatar" src="https://martinrogalla.com/img/martin-rogalla-bw.jpg">
```
Firefox:
<img width="176" alt="Screen Shot 2020-04-06 at 2 24 16 PM" src="https://user-images.githubusercontent.com/27658/78592030-622bbf00-7812-11ea-8ee6-ec3a4279f8e4.png">
Servo:
<img width="165" alt="Screen Shot 2020-04-06 at 2 24 30 PM" src="https://user-images.githubusercontent.com/27658/78592038-648e1900-7812-11ea-9b51-b394a9722abe.png">

**Comment by jdm** [comment]
Switching the img to a div shows the expected circular background color with the borders appearing over top as expected.

**Comment by dralley** [comment]
Any idea where the code that influences this would be located?

**Comment by dralley** [comment]
@jdm ^

**Comment by jdm** [comment]
* https://github.com/servo/servo/blob/master/components/layout/display_list/builder.rs#L811-L813 is the code for adding images to the display list [1]
* https://github.com/servo/servo/blob/master/components/layout/display_list/builder.rs#L1061-L1063 is the code for adding borders to the display list
* https://github.com/servo/servo/blob/master/components/layout/display_list/builder.rs#L1697-L1704 is the code that should ultimate end up calling [1], and note how it's after a call to [2]

Of course, it's not clear to me if ultimately the problem is that:
1. we're drawing the image over the borders
1. our border calculation code is incorrect
1. our border-radius calculation code is incorrect
1. something else??

**Comment by dralley** [comment]
![Screenshot from 2020-04-13 18-12-34](https://user-images.githubusercontent.com/2751996/79166158-9410c880-7db2-11ea-9b02-e006dfdb62e9.png)

Seems like #1?  The overall size is exactly the same and the width of the border is the same.  The image itself looks like it's being shrunk to the correct dimensions.

Other differences, irrelevant to the current problem but might be worthwhile to think about:

* Firefox seems to add a tiny white edge between the border and the image so that you can distinguish the two when they have very similar colors
* The Servo-rendered image has a lot more pixelation

**Comment by dralley** [comment]
Found a duplicate issue, it's a lot more obvious with the example they use: https://github.com/servo/servo/issues/22818

**Comment by dralley** [comment]
Layout 2020, meanwhile, looks like this:

![Screenshot from 2020-04-14 10-58-27](https://user-images.githubusercontent.com/2751996/79239828-03cc9500-7e3f-11ea-852d-320d5d6f63bc.png)
![Screenshot from 2020-04-14 10-58-43](https://user-images.githubusercontent.com/2751996/79239835-05965880-7e3f-11ea-9aa8-15b69294675f.png)

**Comment by dralley** [comment]
Ignore https://github.com/servo/servo/issues/20922#issuecomment-613127087, I'm wrong, it's definitely drawing a round border and then drawing the rectangular image on top of that.  It's obvious if you toss a panic in before the image gets drawn.

All the dimensions are correct when I measure with GIMP (as far as I know, I have very little web dev experience).  It seems like the image stops painting at the outer edge of the border rather than the inner edge.

I assume the issue is probably somewhere in here? https://github.com/servo/servo/blob/master/components/layout/display_list/builder.rs#L1720

**Comment by jdm** [comment]
The CSS specification defines an order in which elements are painted in https://www.w3.org/TR/CSS2/zindex.html#painting-order. Given this, I believe that painting borders before the image content is correct. Since changing the border-radius to 0 in the testcase shows the border correctly, this suggests to me that the calculations for border-radius interact poorly with the calculations for where to draw the border, which suggests that the error is in https://github.com/servo/servo/blob/master/components/layout/display_list/builder.rs#L1731-L1739 or https://github.com/servo/servo/blob/master/components/layout/display_list/builder.rs#L574-L590
