### ISSUE TITLE
Keybindings don't work on Linux and maybe windows

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21161]
Maybe because of #21087

**Comment by dorfsmay** [comment]
I've had a look but made very little progress. I'm not sure how useful this will be, but just in case, here's what I have found on Linux:

Everything happens in `ports/servo/glutin_app/window.rs` and `components/servo/lib.rs`

* the `run` function in windows.rs does a callback to self.winit_event_to_servo_event on each window events.

* printing out the event (e) in the events_loop, before the callback shows that all events are the same at this point, `Key::KeyboardInput`

* the Window::handle_events interprets normal alphabet and Alt keys as `[Key]`, but interprets the control key as a `[MouseMove]`!

* I think the issue is that `winit_event_to_servo_event` (in ports/servo/glutin_app/window.rs) is matching for `winit::WindowEvent::KeyboardInput` but the Control key is still a `winit::Key::KeyboardInput`. I had some code that showed this, but removed it since, and haven't had time to dig there since then.

* the control keys create a sticky state: If you press CTRL -X (x or any letter it doesn't matter) once, then all keys pressed after that show `ctrl: true` as a ModifiersState. The only way to change that state back to false is to again press CTRL *with a key*. Pressing CTRL on its own will not change the state. 

* This point above explains why CTRL-L in servo on Linux does not bring the URL menu. You can get the URL menu following this sequence:
  * start servo
  * press CTRL-L (not necessarily L, any letter at the same time as CTRL)
  * press the key 'L' on its own
  * press CTRL-L (any letter) again to switch away from the control modifier

**Comment by paulrouget** [comment]
@dorfsmay thank you. I think I might need help later with extensive testing.

**Comment by paulrouget** [comment]
PR: https://github.com/servo/servo/pull/21250
