### ISSUE TITLE
Taskcluster builds fail in mozjs bindgen build step

### ISSUE THREAD

**Issue by jdm** [servo/servo#21311]
```
error: unknown argument: '-fno-sized-deallocation', err: true
```
Maybe we need to have a newer version of clang in our taskcluster setup?

**Comment by jdm** [comment]
cc @asajeffrey

**Comment by SimonSapin** [comment]
Yes I suspect that the build dependencies in the docker image need an update. However since we’re not gating on Taskcluster at the moment there is no pressing need to fix this. The next Taskcluster-related thing I’d like to do is having Docker images themselves being built on Taskcluster per https://github.com/servo/saltfs/issues/559#issuecomment-409632684. This build failure could be a test case for that.

**Comment by asajeffrey** [comment]
That's odd, I've seen that warning before, but not as an error.

**Comment by jdm** [comment]
This is fixed.
