### ISSUE TITLE
Check for renderbuffer storage exceeding max renderbuffer size

### ISSUE THREAD

**Issue by jdm** [servo/servo#21485]
From 4.4.3, renderbufferStorage (https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf#nameddest=section-4.4.3):
```
If  either width or height is greater than the value of MAX_RENDERBUFFER_SIZE , the error INVALID_VALUE is generated
```
The implementation of WebGLRenderbuffer::storage does not include this check.

**Comment by nox** [comment]
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glRenderbufferStorage.xml

**Comment by sumit0190** [comment]
Not sure what's the best way to do this, but I was able to perform some crude validation using `get_integer_v` and obtaining the value of `GL_MAX_RENDERBUFFER_SIZE`. @jdm @nox thoughts?

**Comment by jdm** [comment]
@sumit0190 The GLLimits structure includes a max_renderbuffer_size field, and it's available from WebGLRenderingContext.limits().

**Comment by sumit0190** [comment]
@jdm Whoops...I saw that chunk of code yesterday and I still forgot. Sorry about that.
Anyway, I see that the parameter is an unsigned int, but obtaining this using `glGetIntegerv` returns a signed value, since a negative value indicates that the implementation doesn't support that construct. I guess for now just comparing `width` and `height` to this parameter is good enough?

**Comment by jdm** [comment]
Yep.

**Comment by jdm** [comment]
I didn't realize that we already perform this check in WebGLRenderingContext::RenderbufferStorage.
