### ISSUE TITLE
AudioBuffer can't be reused between BufferSourceNodes

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#21887]
If the buffer contents have already been acquired, we return an empty buffer.

Changing [this line](https://github.com/servo/servo/blob/d048aa9c519cf17e2998c198136b9f85d3fefbcb/components/script/dom/audiobuffer.rs#L153) to `continue` fixes this for me, but not perfectly.

The spec isn't very clear here, @ferjm do you have a better idea of what we should do here? This is affecting a lot of tests.

**Comment by ferjm** [comment]
> If the buffer contents have already been acquired, we return an empty buffer.

I believe this is the expected behavior. At least, that was my interpretation of the [spec](https://webaudio.github.io/web-audio-api/#acquire-the-content) (step 1 of acquire the content). FWIW that seems to be what [Gecko is doing](https://dxr.mozilla.org/mozilla-central/source/dom/media/webaudio/AudioBuffer.cpp#431) as well.

Note that an AudioBuffer can be reused between AudioBufferSourceNodes (even in different AudioContexts) if the content has not been acquired yet (i.e. start has not been called). There's a test for this [here](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audiobuffer-interface/ctor-audiobuffer.html#L186).

Could you point me to the affected tests, please?

**Comment by Manishearth** [comment]
Testcase:


```html
<script type="text/javascript">
let sampleRate = 44100;
let context = new OfflineAudioContext(
    2, sampleRate *  0.1, sampleRate);

let buf = context.createBuffer(1, 0.1 * sampleRate, context.sampleRate);
let data = buf.getChannelData(0);
data[0] = 0.5;
data[1] = 0.25;
let b1 = context.createBufferSource();
b1.buffer = buf;
b1.start();
let b2 = context.createBufferSource();
b2.buffer = buf;
b2.start();
let merger = context.createChannelMerger(2);
b1.connect(merger, 0, 0);
b2.connect(merger, 0, 1);
merger.connect(context.destination);
context.startRendering().then(buffer => {
    console.log(buffer.getChannelData(0)[0], buffer.getChannelData(1)[0]);
    console.log(buffer.getChannelData(0)[1], buffer.getChannelData(1)[1]);
})
</script>
```

In Firefox this logs 0.5 0.5 0.25 0.25, in Servo it logs 0.5 0 0.25 0. In Servo, b2 is effectively silent because the buffer was taken away from it.
