### ISSUE TITLE
Unresponsive scrolling

### ISSUE THREAD

**Issue by ferjm** [servo/servo#21991]
Navigating to https://google.com and scrolling up and down eventually makes scrolling unresponsive. Clicking on links continue working.

**Comment by ferjm** [comment]
Actually, I see this behavior on other sites like https://servo.org or https://mozilla.org.

I see nothing useful on the logcat.

**Comment by fabricedesre** [comment]
did you try tweaking the user agent?

**Comment by paulrouget** [comment]
Sometimes, after a fling gesture, we can't scroll anymore.

**Comment by ferjm** [comment]
> did you try tweaking the user agent?

No. Which UA should I set?

> what does the top left label says when it's blocked: IDLE or LOOP?

IDLE

**Comment by fabricedesre** [comment]
I commented on the wrong issue, sorry. Was meant for https://github.com/servo/servo/issues/21990

**Comment by LifeIsStrange** [comment]
@paulrouget   « Sometimes, after a fling gesture, we can't scroll anymore. » actually servo is unusable on my android tablet since the beginning of the android port because of this and this is my last big remaining issue (as most things display well else).

After a fling gesture most of my attempt to scroll Again will be ignored and idle.
But if I scroll with my finger always on Touch with the screen then scrolling works..
