### ISSUE TITLE
Enable buffering and caching media data in gstreamer

### ISSUE THREAD

**Issue by jdm** [servo/servo#22055]
```
<jdm> does gsteamer do any caching, or does it throw away the original buffer it receives?
<ferjm> jdm, I believe so, but I think it requires some setup that we are currently not doing. I need to look into the buffering/caching strategy
```

**Comment by ceyusa** [comment]
What player/playbin can do (and it would need to be configured in servo/media) is *buffering*. Basically it stores in a [queue](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-plugins/html/gstreamer-plugins-multiqueue.html) the specified size/time of *the demuxed data*.

Also, player/playbin could be configured for *downloading*, which will add a [special queue](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-plugins/html/gstreamer-plugins-downloadbuffer.html) after source element, which can cache on disk (until certain size) what it is received from the source element.

In my opinion, adding some buffering would make sense for servo, but I'm to sure about downloading, since that caching perhaps would be better handled by the networking subsystem.

**Comment by ceyusa** [comment]
After reading https://github.com/servo/servo/issues/22054 perhaps it would make sense add that feature, temporarily, in media/gstreamer
