### ISSUE TITLE
details element toggle not working

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22106]
When I tried to click to toggle the following `details` element, it didn't work.

```html
<details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>
```

Built with latest master (4ec7dedce1) on macOS 10.13.6

(Not sure if #21336 can be resolved once this issue resolved)

**Comment by CYBAI** [comment]
I tried to check how Gecko implemented `click` for `summary` and `details`. It seems the click event is handled by `HTMLSummaryElement` which is not implemented in Servo yet. 

Ref:
- https://searchfox.org/mozilla-central/source/dom/html/HTMLSummaryElement.cpp#29-97
- https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element

Or, it should be fine to just `impl Activatable for HTMLDetailsElement` ?

**Comment by jdm** [comment]
Implementing Activatable is probably the right choice here. It would be nice to use this for the SSL cert error page.

**Comment by ghostd** [comment]
@jdm i'd like to make the couple details/summary "activatable"

I created an HMTLSummaryElement but since there is no official IDL my element has no binding and is not "Castable". How can i workd around this? Create an IDL file would be a quick fix but it would be aligned with the specifications. Do you have any advice?

I didnt find any other similar case in the code. Even 'span' has an official IDL.

**Comment by jdm** [comment]
@ghostd You could work around the lack of an official HTMLSummaryElement interface by implementing Activatable for HTMLElement and checking `self.upcast::<Element>().local_name() == local_name!(summary)`.
