### ISSUE TITLE
Release lumin runtime crashes at startup

### ISSUE THREAD

**Issue by jdm** [servo/servo#22188]
When I do a release build of servo and package it with `-t lumin_release` the app does not start correctly. When I use `-t lumin_debug` instead, it works.

**Comment by asajeffrey** [comment]
IRC log: https://mozilla.logbot.info/servo/20181116#c15620117
tl;dr: adding `--add-tail-data-args=--debuggable` to the mabu incantation fixes the crash.

**Comment by asajeffrey** [comment]
#22210 is a workaround, which makes the app `debuggable`. The issue can be kept open until we find a proper fix.

**Comment by asajeffrey** [comment]
Tracking this down is painful because there are no debugging tools other than println debugging, sigh. The problem turns out to be https://github.com/servo/servo/blob/928fbc909f2448f54c7f9a1dffbced809ee4e2ea/components/script/script_runtime.rs#L328

which calls `InitSelfHostedCode(js_context)` at https://github.com/servo/rust-mozjs/blob/f84b87a8ab57ead998475353ad5ca5874acb5c85/src/rust.rs#L200 and that call of `InitSelfHostedCode` is what produces the segmentation fault.

**Comment by asajeffrey** [comment]
And digging further, when SM creates JIT code, it sets the page to be executable using `mprotect` at https://github.com/servo/mozjs/blob/efc951c915477b0d0940eed0990810928f43e189/mozjs/js/src/jit/ProcessExecutableMemory.cpp#L677. This call to mprotect is failing, which takes down SM with it.

**Comment by asajeffrey** [comment]
The ML forum discussion https://forum.magicleap.com/hc/en-us/community/posts/360030731772-Segmentation-fault-in-release-builds (requires login).

**Comment by atouchet** [comment]
From what I've inferred the Lumin runtime is part of the Magic Leap software stack. Is this issue still relevant?
