### ISSUE TITLE
In VR mode, ServoView constructor is called twice

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#22197]
Which leads to a panic (`assert(DEFAULT_OPTION.is_null())`).

I have no idea why the view is constructed twice.

**Comment by paulrouget** [comment]
googlevr.

**Comment by Manishearth** [comment]
Hm, I'm not hitting this. What I get is:

 - visiting a page that uses vr lazy-loads googlevr, which causes the app to go back to the homepage (the brightness also seems to change, I think it's flickering really fast)

 - doing it again after the lazy load works. entering VR works _sometimes_ (I sometimes get an error saying the app is compatible with Cardboard but not Daydream)

I'm not able to display to VR yet because of https://github.com/servo/servo/issues/22162

**Comment by paulrouget** [comment]
From Slack:

---

One thing that could affect is this: https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/AndroidManifest.xml#L27

```android:configChanges="density|keyboardHidden|navigation|orientation|screenSize|uiMode"```

Check that you are using the same configChanges in the servo android manifest.xml

**Comment by paulrouget** [comment]
So Servo is (likely) destroyed and reloaded because of a change of config. I was wondering why this wasn't a problem with FxR. It's because FxR doesn't use servo arguments. Anyway, that should not be too hard to fix. Looking at it.
