### ISSUE TITLE
Enter and backspace don't trigger onkeypress events for text inputs

### ISSUE THREAD

**Issue by jdm** [servo/servo#22346]
`./mach run -d 'data:text/html,<input value="hi" onkeypress="console.log(event)">'`

**Comment by jdm** [comment]
They do trigger onkeydown and onkeyup, however.

**Comment by krk** [comment]
For enter and backspace, `onkeypress` is not triggered because the result of `legacy_charcode()` is `0` at https://github.com/servo/servo/blob/dd2deeabca7eeb40e6a8fe0c1ee4550d64e0c235/components/script/dom/document.rs#L1411

**Comment by jdm** [comment]
Thanks for investigating that! The specification says we should be generating these events for any input that represents a [character value](https://w3c.github.io/uievents/#character-value) (see [spec](https://w3c.github.io/uievents/#event-type-keypress) text that starts "if and only if that key normally produces a character value"). It seems like we should not be using the `legacy_charcode` to decide if that's the case.

**Comment by garasubo** [comment]
I'm interested in this issue. I'm still new to this project and it is not labelled as "E-easy", but looks not so hard.
So, what I should do is:
1. Fix the condition to trigger onkeypress based on the spec
2. Update wpt test if necessary
Is that correct? If so, could you assign this issue to me?

**Comment by CYBAI** [comment]
@garasubo Looks like worth a try! Go ahead! 🚀

**Comment by garasubo** [comment]
@highfive assign me

**Comment by garasubo** [comment]
I read the [spec](https://w3c.github.io/uievents/#event-type-keypress), and if my understanding is correct, "Enter" key should trigger onkeypress events, but "Backspace" should not because backspace does not produce a character value. I also checked this behaviour in firefox and chromium, and those browsers trigger onkeypress events for Enter key, but not for Backspace key.

So, my understanding is:
1. if [key string](https://w3c.github.io/uievents-key/#key-string) is a non-control character, it should be trigger onkeypress.
2. otherwise, most keys doesn't represent any character value, but [white space keys]([https://w3c.github.io/uievents-key/#keys-whitespace]) (including Enter key) are exception. For tab key, I'm not sure how it should handle since this will change active element before keypress event phase. I couldn't find a way to prevent this transition and trigger key press event in firefox and chrome.

Does anyone have a suggestion for tabs? Also please correct me if I am wrong

**Comment by garasubo** [comment]
Found anohter problem. When I use IME, it also triggers onkeypress event, but according to the spec, we should not trigger in this case.
> It MUST NOT be fired when using an input method editor.

However, in dispatch_key_event function, I couldn't find a way to distinguish IME input with other normal keyboard event. I may need to dig into this (or maybe open a new issue for it).

**Comment by jdm** [comment]
I wouldn't worry about the tab case. Everything else you wrote sounds sensible to me!

**Comment by garasubo** [comment]
Submitted a PR for it. As I mentioned in the description of the PR, It seems composition events are not trigger in the current Servo implementation.
I use Ubuntu 18.04 and mozc-fcitx as IME. When I press keys in the input box with IME, keypress and compositionStart were not triggered either (Ref: https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event).
