### ISSUE TITLE
Media Fragments URI support for audio and video

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22366]
Spec: https://www.w3.org/TR/media-frags/

Particularly interested on use cases like https://www.w3.org/TR/2009/WD-media-frags-reqs-20091217/#scenario1.1

**Comment by sreeise** [comment]
@highfive assign me

**Comment by sreeise** [comment]
@ferjm I can gladly work on this. I am wondering whether you want this to be relatively close to the Gecko implementation?

**Comment by ferjm** [comment]
Thanks @sreeise! You can certainly look at other browser's implementations (I added links to Gecko's and Blink's ones [here](https://github.com/servo/media/issues/156)) for inspiration or guidance, but Servo's implementation does not necesarily need to be close to them. I haven't read the spec in detail and I haven't really put much thought into this yet, so I am afraid that I don't have any design in mind that I can share with you at the moment. Feel free to explore any approach that you consider worthwhile.

**Comment by sreeise** [comment]
@ferjm Looking at the specification and then at different websites such as YouTube it looks like there is multiple formats or syntax, at least for specifying temporal clippings for video/audio, that doesn't necessarily match the specification.

According to the spec for temporal clippings, where you can specify start and end times for video/audio, the normal supported formats are NPT, SMPTE, and real world clock which is in the form of a UTC timestamp. However, some sites such as YouTube use their own format: `HHhMMmSS.Fs`. For example, `t=1m3s` would be a start time of 63 seconds and the end time as the duration of the audio or video.

I am wondering what you believe would be the best route to take. Should I add support for a site like YouTube, or stick to only what is in the specification? One thing that I noticed is that it looks like Firefox only supports NPT. Since syntax for YouTube does work on Firefox this leads to me to believe that YouTube is parsing the URL fragment itself as the format is not in NPT.

**Comment by ferjm** [comment]
In general, I would prefer to stick to what the specification says instead of implementing specific behaviors for specific sites (even if these are important sites like Youtube).

> One thing that I noticed is that it looks like Firefox only supports NPT

Yes, looking at [Gecko's code](https://dxr.mozilla.org/mozilla-central/source/netwerk/base/nsMediaFragmentURIParser.cpp) that seems to be the case.

>  Since syntax for YouTube does work on Firefox this leads to me to believe that YouTube is parsing the URL fragment itself as the format is not in NPT.

I share your believe here. Youtube indeed seems to be using and parsing its own query params format. In fact, Firefox's media fragment support is limited to the source attributes for media elements, and there is no support for urls in the browser top address bar. So whatever query parameter you add to a Youtube URL in Firefox is not used by Gecko, but by Youtube.
