### ISSUE TITLE
Implement missing functionality of AudioBufferSourceNode

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22363]
We have only very basic support for AudioBufferSourceNode. We still need to implement most part of the [playback of AudioBuffer contents algorithm](https://webaudio.github.io/web-audio-api/#playback-AudioBufferSourceNode), add the `loop`, `loopStart`, `loopEnd`, `playbackRate` and `detune` attributes and the `offset` and `duration` arguments of the `start` method.

Spec: https://webaudio.github.io/web-audio-api/#AudioBufferSourceNode

**Comment by collares** [comment]
@highfive assign me

**Comment by jdm** [comment]
@collares Have you made any progress? Do you have any questions?

**Comment by collares** [comment]
Thanks for the reminding me! I didn't get as much time to work on this as I expected, but I will go back to working on this issue next week. I would still like to work on this, but please do let me know if this is blocking other work (or if someone else is eager to work on this); I can unassign myself and pick some other bug later if that's the case.

**Comment by ferjm** [comment]
@collares are you still working on this issue?

**Comment by collares** [comment]
Yes, sorry again! This semester left me with almost no free time :( Back in March I took detailed spec notes to understand the problem, but ran out of time before finishing the implementation. I will definitely submit a PR tomorrow for feedback, since I now have time to work on this again.

A tiny problem is that I'll use linear interpolation for resampling (as Chromium does) instead of doing what Firefox does, which is to use sinc interpolation (via libspeex), at least initially. Since I have a couple of free weeks, I can fix this in a follow-up if the audio quality ends up being unacceptable. I don't want to put the cart before the horse, though, so I'll get back to this problem once I actually submit something.
