### ISSUE TITLE
Implement missing DOMException constructor

### ISSUE THREAD

**Issue by jdm** [servo/servo#22412]
The DOMException specification has been updated since we implemented it. https://heycam.github.io/webidl/#idl-DOMException includes a constructor that is required for the bluetooth tests in #20437. This requires updating the WebIDL file at `components/script/dom/webidls/DOMException.webidl` with the constructor from the specification, then implementing the new `Constructor` static method in `components/script/dom/domexception.rs` based on https://heycam.github.io/webidl/#dom-domexception-domexception . This should improve the results of `./mach test-wpt tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/es-exceptions/`.

**Comment by CYBAI** [comment]
@vuamitom These tests passed due to the settings in `tests/wpt/metadata/WebIDL/ecmascript-binding/es-exceptions/`.

For example, currently, the test cases in [DOMException-constructor-behavior](https://github.com/servo/servo/blob/master/tests/wpt/metadata/WebIDL/ecmascript-binding/es-exceptions/DOMException-constructor-behavior.any.js.ini) are set to `FAIL`.

You can try to remove these `FAIL` and run the `test-wpt` again. You would see fail tests.

After implementing the `DOMException constructor`, they should be passed.

**Comment by cdeler** [comment]
@vuamitom @CYBAI 
Do you have any objections, if I take this issue (and start working on it)?

**Comment by vuamitom** [comment]
No objection, please go ahead. I think you should ask @highfive to assign it to you.

**Comment by cdeler** [comment]
@highfive: assign me
