### ISSUE TITLE
[Question] Any plans to support embedding on other platforms?

### ISSUE THREAD

**Issue by matthew-dean** [servo/servo#22757]
For work, I'm currently evaluating embedded browser engines for applications on Xbox / PS4, and possibly for Smart TV (WebOS / Tizen). Is it possible to build / embed Servo for those platforms? If not, is that something that may happen eventually?

**Comment by fabricedesre** [comment]
My experience with getting Servo working on gonk based devices is that Servo itself is quite easy to port: you basically need to provide it a GL context and input events. The hard part can be managing to compile SpiderMonkey for your platform, because of the build system used by SM is not really flexible.
