### ISSUE TITLE
Integrate DOM audio and video track selection with media player

### ISSUE THREAD

**Issue by jdm** [servo/servo#22799]
#22622 added DOM interfaces representing the available audio and video tracks for a media resource. We need to figure out how to make enabling or disabling a particular track cause that equivalent track to be toggled in the underlying media player as well.

**Comment by sreeise** [comment]
While looking at Servo media I noticed that `PlayerInner` in bakends/gstreamer/player.rs uses `gst_player::Player` which has methods `set_video_track(stream_index: i32)` and `set_audio_track(stream_index: i32)`. Just by looking at it I believe the stream index is the same index as it would be in the metadata when we receive it in `HTMLMediaElement`. This may be something worth looking to set specific tracks in the media player.

**Comment by sreeise** [comment]
There is also `set_audio_track_enabled(enabled: bool)` and `set_video_track_enabled(enabled: bool)`. Guessing that a current track would need to be set and then enabled it but i'm not sure if that would work for enabling multiple audio tracks.

**Comment by sreeise** [comment]
Hey @jdm, I am currently testing a solution for this and have a question if you don't mind answering. Sorry if this is obvious but am I correct in thinking that when the tracks are enabled/disabled from JS, the audio track itself is the object that gets changed internally? So for instance if the zeroth track were disabled:
```
video.audioTracks[0].enabled = false
```
the actual object at index zero is the track itself and not the audio track list. I am just guessing here but wouldn't the underlying player then need to be disabled internally from the audio/video tracks themselves or in some way have a reference to the media element to enable/disable tracks (since the media element has access to the underlying player)?

**Comment by jdm** [comment]
Yes, that sounds correct to me.
