### ISSUE TITLE
Make target=_blank imply noopener; support opener

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22845]
whatwg/html#4330
web-platform-tests/wpt#15188

**Comment by gterzian** [comment]
Code https://github.com/servo/servo/blob/71ba247942a95d1511c9fa62f06d860fcc03de1c/components/script/dom/htmlanchorelement.rs#L608

**Comment by gterzian** [comment]
This would require replace 

https://github.com/servo/servo/blob/71ba247942a95d1511c9fa62f06d860fcc03de1c/components/script/dom/htmlanchorelement.rs#L611

with an assertation that the link **doesn't** contain `opener`

**Comment by georgeroman** [comment]
@highfive: assign me

**Comment by gterzian** [comment]
The relevant test is at https://github.com/servo/servo/blob/ac3c002138cb2b2ebeaf840436d7022d4bb72ffc/tests/wpt/web-platform-tests/html/semantics/links/links-created-by-a-and-area-elements/target_blank_implicit_noopener.html

and can be run with `./mach test-wpt /html/semantics/links/links-created-by-a-and-area-elements/target_blank_implicit_noopener.html`

Since it is currently set to `FAIL` at https://github.com/servo/servo/blob/ac3c002138cb2b2ebeaf840436d7022d4bb72ffc/tests/wpt/metadata/html/semantics/links/links-created-by-a-and-area-elements/target_blank_implicit_noopener.html.ini and this PR should make it pass, so to test run on the server should have complained of an unexpected pass. (If we make those tests pass this PR will also need to remove those `FAIL` expectations)

**Comment by jdm** [comment]
@georgeroman Was this fixed by #22851?

**Comment by georgeroman** [comment]
@jdm Sorry for the late response. Yes, this should have been fixed.

**Comment by jdm** [comment]
Do we know why #22851 did not change any test results?

**Comment by georgeroman** [comment]
The tests were failing due to an unrelated issue: https://github.com/servo/servo/pull/22851#issuecomment-471178128.
