### ISSUE TITLE
Event timestamp should use same clock as Performance.now

### ISSUE THREAD

**Issue by jdm** [servo/servo#22885]
Right now we initialize the event timestamps to `time::get_time().sec`, which is very different than Performance.now's `time::precise_time_ns()` using the navigation start as the time origin.

Code: `components/script/dom/event.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/dom/events/Event-timestamp-high-resolution.html`

**Comment by jdm** [comment]
The spec says `Returns the event’s timestamp as the number of milliseconds measured relative to the time origin.`.

**Comment by georgeroman** [comment]
@highfive assign me

**Comment by georgeroman** [comment]
I have a question regarding the implementation. So, in order to access the proper time origin, I need to have access to the event's global scope `performance().TimeOrigin()` value and I can only access this value by passing the global scope to `Event::new_inherited`. But this in turn requires modifications in all the events, since they all call `Event::new_inherited` behind the scenes. Is this the way to do it?

**Comment by jdm** [comment]
Every DOM object has a `global()` method which will return the associated global. You should be able to get the performance object from that.
