### ISSUE TITLE
Migrate windows nightly builds to taskcluster

### ISSUE THREAD

**Issue by jdm** [servo/servo#22950]

**Comment by SimonSapin** [comment]
This should be similar to https://github.com/servo/servo/pull/22464.

By the way, instead of writing a `.aws/credentials` file in the task’s script we could add support to `mach` for downloading AWS secrets itself and passing them to `boto3.client()`, all within one Python process.

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#method-parameters

https://github.com/servo/servo/blob/de3d2f74951bf0c0834dfda8837d934b3e88aff2/python/servo/package_commands.py#L548-L549

**Comment by SimonSapin** [comment]
CC https://github.com/servo/servo/issues/22325

**Comment by SimonSapin** [comment]
Done in #23304.
