### ISSUE TITLE
Separate command line option parsing into global and embedding-specific options 

### ISSUE THREAD

**Issue by jdm** [servo/servo#23009]
Right now there are global options like `--disable-vsync`, `--headless`, `--multiprocess`, and the forthcoming `--angle` that set fields in the global `Options` structure, but are only used by the Glutin embedding for desktop builds. It would be nice to remove backend-specific options from the global set of engine options. Instead of the current `from_cmdline_args` API which creates an `Options` value and returns `ArgumentParsingResult`, we could have this:
```rust
fn from_cmdline_args(mut opts: getopts::Options, args: &[String]) -> getopts::Result
```
This would allow the embedder to provide an Options object with embedder-specific option parsing, which the engine then appends global option parsing to, parses the provided argument values, updates the global options with the resulting values, then returns a result which includes the parsed options that should be handled by the embedder.

There are two parts to this work:
1. modifying the API to support accepting an existing Options object and returning the parsing result
2. extracting the embedder-specific preferences from the global argument parsing code into the caller code in `ports/servo/non_android_main`

Code: `components/config/opts.rs`, `ports/servo/non_android_main.rs`, `ports/servo/glutin_app/window.rs`, `ports/libsimpleservo/api/src/lib.rs`

Tests: This command should continue to exit without popping a window after these changes - `./mach run -d --headless -x tests/html/about-mozilla.html`

**Comment by ejmg** [comment]
@highfive: assign me

**Comment by ejmg** [comment]
Is an essential aspect of this PR moving the option generating logic in `from_cmdline_arg()` into a helper function in `non_android_main.rs`?

I ask because throwing the option generating code straight into the main function of `non_android_main.rs`, before calling `from_cmdline_arg()`, seems undesirable.

**Comment by jdm** [comment]
We would only be moving the embedding-specific option generating logic into non_android_main.rs. A helper function might make sense for that.

**Comment by jdm** [comment]
@ejmg Are you planning to return to the work in #23061?

**Comment by ejmg** [comment]
School is finally out, so yes. I am really sorry for so many delays on this. 

I might just end up copying over the work I had previously on the current PR branch I had and try rebasing again to avoid whatever mess-up I incurred on the last attempt. Messing with cargo deps really threw that branch into a mess and I'm not sure I can fix it, so deleting it is probably my best return on time at this point :sweat_smile:

**Comment by jdm** [comment]
The work in #23061 was on the right track, but I had some review comments that needed to be addressed and the author disappeared.

**Comment by glowe** [comment]
@highfive: assign me

**Comment by glowe** [comment]
@jdm I'm orienting myself to the problem and could use a bit of help.

Handling the `--angle` and `--disable_vsync` options is straightforward since they're `glutin` specific. We can extract their values from the embedder `Options` and then pass this along to `App::run` and so on.

The other two options are more complicated, because they're used outside of `glutin`. The `headless` option appears in `components/constellation/pipeline.rs` and `components/script/script_thread.rs`. The `multiprocess` option, or its derivative, is used in `components/constellation/constellation.rs`, `components/constellation/pipeline.rs`, `components/servo/lib.rs`, `components/canvas_traits/webgl_channel/mod.rs`, and `components/media/media_channel/mod.rs`. These options look like they're no longer embedder specific? If so, then maybe we should scope this issue back to `angle` and `disable_vsync`?

**Comment by jdm** [comment]
Sure, let's keep the scope focused on the self-contained changes and when those are working we can see if it's more clear how to expand it.

**Comment by atouchet** [comment]
In #24525 it says this was only partially fixed. Should this issue be closed?

**Comment by jdm** [comment]
I think this has been fixed as I originally envisioned it. We can open new issues for any new opportunities we find.
