### ISSUE TITLE
info: syncing channel updates for 'nightly-2019-03-03-x86_64-apple-darwin' 

### ISSUE THREAD

**Issue by Axighi** [servo/servo#23099]
This error always shows up every time I execute a command:
![image](https://user-images.githubusercontent.com/1728926/54975957-c0a14900-4fd3-11e9-87b8-68dd9db96b5e.png)

**Comment by SimonSapin** [comment]
Random guess: is your shell configured to show the Rust version number in the prompt, by running `rustc --version`? Then, since the first `rustc` in your `$PATH` is in fact rustup’s proxy executable, it looks in the current directory and up, finds the `rust-toolchain` file at the root of the repository, and attempts to use the Nightly version that we specify. And you get an error message because that version is not install.

If you build Servo, `mach` will automatically tell rustup to install this version, which should fix the error message. Or, you may want to disable this part of your prompt customization.

**Comment by Axighi** [comment]
Thanks a lot.
> Random guess: is your shell configured to show the Rust version number in the prompt, by running `rustc --version`? Then, since the first `rustc` in your `$PATH` is in fact rustup’s proxy executable, it looks in the current directory and up, finds the `rust-toolchain` file at the root of the repository, and attempts to use the Nightly version that we specify. And you get an error message because that version is not install.

You're right! When I open repo folder in bash, and all commands work fine.

> If you build Servo, `mach` will automatically tell rustup to install this version, which should fix the error message. Or, you may want to disable this part of your prompt customization.

Right again! I add this line `SPACESHIP_RUST_SHOW="false"` into my .zshrc to disable the rust version displaying and the error disappeared.
