### ISSUE TITLE
Use headless context instead of OsMesa

### ISSUE THREAD

**Issue by jdm** [servo/servo#23132]
Glutin's context builder supports a [build_headless](https://github.com/tomaka/glutin/blob/2695ebc292193401a8d4c0ac145e144f565cb6e1/glutin/src/lib.rs#L269-L276) API. We should see if we can use that, since it will get us headless support on all platforms rather than the current OsMesa solution.

**Comment by SimonSapin** [comment]
On Linux, as far as I can tell the code behind this `build_headless` API relies on the presence of a X11 or Wayland server (only without creating a window). So I suspect it requires a hardware GPU, whereas OSMesa provides a CPU-based/software implementation of GL.

(Glutin also has `glutin::os::unix::OsMesaContextExt`, which might help simplify our code a bit but does not otherwise change much.)

**Comment by SimonSapin** [comment]
OSMesa-src and Glutin is are longer used since https://github.com/servo/servo/pull/25853.
