### ISSUE TITLE
Documentation: Python virtualenv is not installed. 

### ISSUE THREAD

**Issue by ShalokShalom** [servo/servo#23210]
This should be part of the installation instructions. 

> Python virtualenv is not installed. Please install it prior to running mach.

Simply recommend it in all the build instructions.  

Thanks a lot

**Comment by luka-zitnik** [comment]
Hello @jdm 

This looks like a chicken-and-egg problem. Virtualenv is an os package, intended to be installed with https://github.com/servo/servo/blob/c0ee7594c2c2f8c954e17a28f19dd4f3743c2bbc/python/mach_bootstrap.py#L254, but it is required before that, with https://github.com/servo/servo/blob/c0ee7594c2c2f8c954e17a28f19dd4f3743c2bbc/python/mach_bootstrap.py#L245

Does it make sense to install virtualenv with pip (if it's not already installed) instead or raising the error?

**Comment by jdm** [comment]
It would certainly be nice if it could be installed automatically.

**Comment by luka-zitnik** [comment]
@jdm So, because I might not have pip, I'd either have to employ a more involved, rudimentary technique in order to discover the linux distro (and possibly version) or just add instructions to documentation and remove the few packages from the bootstrap command? Personally, I'd rather do the latter and start checking out the rust code.

**Comment by ShalokShalom** [comment]
I have no problem packaging that, or distros have no problem packaging that, just knowing it is needed would be nice.
