### ISSUE TITLE
What's different from chrome V8?

### ISSUE THREAD

**Issue by g10guang** [servo/servo#23261]

**Comment by CYBAI** [comment]
As you can see from the [V8](https://v8.dev/)'s official blog website

> V8 is Google’s open source high-performance JavaScript and WebAssembly engine, written in C++.

We can know it's a [`JavaScript Engine`](https://en.wikipedia.org/wiki/JavaScript_engine).

Then, let's see [Servo](https://servo.org/)'s official website

> Servo is a modern, high-performance browser engine designed for both application and embedded use.

It's a [`Browser Engine`](https://en.wikipedia.org/wiki/Browser_engine).

A browser engine will have a JS Engine to run JS code.
In Servo, we have binding with SpiderMonkey which is JS Engine of Gecko to run JS code.

Hope this help you to clarify it! I'm going to close this issue, Thanks.

**Comment by g10guang** [comment]
@CYBAI  So servo is like electron?

In mobile App, servo can Render css/Image. So will servo better than v8?

In china, some browser is base on v8. Such as [QQ browser](https://browser.qq.com/),  [360 Browser](https://browser.360.cn/). If they switch v8 to servo, will it be much easier to develop?

Is servo based on v8 or firefox core?

I am a green hand. Maybe I will ask some stupid questions.

**Comment by CYBAI** [comment]
Before answering following questions, I will recommend you to read [this post](https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/) to see `How Browser Works`; there's also a Simplified Chinese translation for it.

Quoted from the post

> The **`browser engine`**: marshals actions between the UI and the rendering engine.

For example,

`Browser Engine` of Chrome, Opera, Vivaldi and also **`360 Browser`** is [`Chromium`][Chromium]. (Btw, there's a [Chromium-based browser list][ChromiumList] in Wikipedia)

`Browser Engine` of Firefox is [`Gecko`][Gecko].

`Browser Engine` of Safari is [`WebKit`][WebKit].

And `Servo` is also a `Browser Engine`.

#### Is servo based on v8 or firefox core?

So, let's clarify the relation between these 3 things:

`V8`: JS Engine
`Firefox`: Browser
`Servo`: Browser Engine

In Servo, our JS Engine is `mozjs` which is binding of `SpiderMonkey` and `SpiderMonkey` is JS Engine of `Gecko`.

#### So servo is like electron?

No, you can check [Electron's wiki][Electron]. It's a combination of `Chromium` and `Node.js` so that's the reason why you can use Node.js API on top of the browser-like desktop application.

If you're finding a Electron-like framework, there's someone built a Rust + Servo Electron like framework (https://github.com/justinmichaud/ion). You can check it.

#### In mobile App, servo can Render css/Image. So will servo better than v8?

Again. V8 is a JS Engine and Servo is a Browser Engine. Personally, I won't compare them together.

#### In china, some browser is base on v8. Such as [QQ browser](https://browser.qq.com/), [360 Browser](https://browser.360.cn/). If they switch v8 to servo, will it be much easier to develop?

I think both `360 Browser` and `QQ Browser` are based on `Chromium` + `Trident`.

> The browser by default renders the webpage using the WebKit-based engine adapted for Google Chrome, Blink, and when running in compatibility mode, it renders webpage using the Trident engine found in Internet Explorer.

 Quoted from wikipedia of 360 Browser

#### I am a green hand. Maybe I will ask some stupid questions.

No worries. Please let me know if you don't understand my explanation.

[Electron]: https://en.wikipedia.org/wiki/Electron_(software_framework)
[Chromium]: https://en.wikipedia.org/wiki/Chromium_(web_browser)
[Gecko]: https://en.wikipedia.org/wiki/Gecko_(software)
[WebKit]: https://en.wikipedia.org/wiki/WebKit
[ChromiumList]: https://en.wikipedia.org/wiki/Chromium_(web_browser)#Browsers_based_on_Chromium

**Comment by KiChjang** [comment]
@g10guang It must be stressed that Servo is an experimental browser engine, and so is not a fully featured engine that can be compared with others such as Chromium, Webkit or Gecko.

**Comment by liumuqi** [comment]
> Before answering following questions, I will recommend you to read [this post](https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/) to see `How Browser Works`; there's also a Simplified Chinese translation for it.
> 
> Quoted from the post
> 
> > The **`browser engine`**: marshals actions between the UI and the rendering engine.
> 
> For example,
> 
> `Browser Engine` of Chrome, Opera, Vivaldi and also **`360 Browser`** is [`Chromium`](https://en.wikipedia.org/wiki/Chromium_(web_browser)). (Btw, there's a [Chromium-based browser list](https://en.wikipedia.org/wiki/Chromium_(web_browser)#Browsers_based_on_Chromium) in Wikipedia)
> 
> `Browser Engine` of Firefox is [`Gecko`](https://en.wikipedia.org/wiki/Gecko_(software)).
> 
> `Browser Engine` of Safari is [`WebKit`](https://en.wikipedia.org/wiki/WebKit).
> 
> And `Servo` is also a `Browser Engine`.
> 
> #### Is servo based on v8 or firefox core?
> So, let's clarify the relation between these 3 things:
> 
> `V8`: JS Engine
> `Firefox`: Browser
> `Servo`: Browser Engine
> 
> In Servo, our JS Engine is `mozjs` which is binding of `SpiderMonkey` and `SpiderMonkey` is JS Engine of `Gecko`.
> 
> #### So servo is like electron?
> No, you can check [Electron's wiki](https://en.wikipedia.org/wiki/Electron_(software_framework)). It's a combination of `Chromium` and `Node.js` so that's the reason why you can use Node.js API on top of the browser-like desktop application.
> 
> If you're finding a Electron-like framework, there's someone built a Rust + Servo Electron like framework (https://github.com/justinmichaud/ion). You can check it.
> 
> #### In mobile App, servo can Render css/Image. So will servo better than v8?
> Again. V8 is a JS Engine and Servo is a Browser Engine. Personally, I won't compare them together.
> 
> #### In china, some browser is base on v8. Such as [QQ browser](https://browser.qq.com/), [360 Browser](https://browser.360.cn/). If they switch v8 to servo, will it be much easier to develop?
> I think both `360 Browser` and `QQ Browser` are based on `Chromium` + `Trident`.
> 
> > The browser by default renders the webpage using the WebKit-based engine adapted for Google Chrome, Blink, and when running in compatibility mode, it renders webpage using the Trident engine found in Internet Explorer.
> 
> Quoted from wikipedia of 360 Browser
> 
> #### I am a green hand. Maybe I will ask some stupid questions.
> No worries. Please let me know if you don't understand my explanation.

very nice man
