### ISSUE TITLE
Bindings generation ignores Exposed annotations on members and partial interfaces

### ISSUE THREAD

**Issue by jdm** [servo/servo#23332]
Despite https://github.com/servo/servo/issues/12414 being closed, exposed annotations do on members do not actually affect whether those members are exposed in the generated bindings. https://github.com/servo/servo/compare/master...jdm:exposed-member contains an automated test that demonstrates this.

**Comment by jdm** [comment]
This requires:
* adding a `Exposed(Globals)` variant to the Condition enum
* making Condition::is_satisfied call `is_exposed_in` for the new variant
* updating the code generator's `MemberCondition` to accept a new argument for exposed conditions and returning `Condition::Exposed` when appropriate
* updating `getControllingCondition` to pass a list of exposed globals when appropriate

Code: `components/script/dom/bindings/guard.rs`, `components/script/dom/bindings/codegen/CodegenRust.py`

**Comment by sreeise** [comment]
@highfive: assign me

I can work on this :)

**Comment by jdm** [comment]
Please let me know if anything is unclear!

**Comment by sreeise** [comment]
@jdm Hey, so I started on this in the [commit here](https://github.com/sreeise/servo/commit/1c922e7589aa600f0990c4246f052d863c51e761), but it doesn't compile yet so I didn't bother to make a pr.

The main issue currently is where the Exposed annotation could either be a list or it could be a string. When a match is found, in Guard.rs, and the ` is_exposed_in` method is called it expects a single global to be passed as an argument which works only if the Exposed attribute in any given webidl has one member, i.e., `Exposed=Window` as opposed to `Exposed=(Window, Worker)`. Because there is a possibility that the attribute is set to a list, compilation will fail because `is_exposed_in` does not expect a list.

For example, when the code is generated for a list the arguments don't get parsed correctly:
```

1349 |     Guard::new(Condition::Exposed(['Window', 'Worker']), sMethods_specs[1]),
     |                                              ^^^^^^^^
help: if you meant to write a `str` literal, use double quotes
     |
1349 |     Guard::new(Condition::Exposed(['Window', "Worker"]), sMethods_specs[1]),
```
The compiler complains about using double quotes for a string literal which really isn't the problem as `is_exposed_in` only accepts one `InterfaceObjectMap::Globals` argument anyway (I am assuming that globals is not an `&str` so I could be wrong).

I am honestly not sure where in CodgenRust.py to write a fix for this or if I am possibly missing something that should be changed. I havn't worked in the codegen section before so I figured I'd ask about this before attempting to find a solution. Thanks for your help :).

**Comment by jdm** [comment]
The Globals type is actually a bitset. I recommend using the following code as a model: https://github.com/servo/servo/blob/8dc7a25893cbe9a2c958966618d28757201899b6/components/script/dom/bindings/codegen/CodegenRust.py#L2581-L2583 .

**Comment by jdm** [comment]
More specifically, returning `Condition::Exposed(%s)` with the Globals bitset value from `MemberCondition` seems like the right choice to me.

**Comment by jdm** [comment]
You can see the documentation for the Globals type at https://doc.servo.org/script/dom/bindings/codegen/InterfaceObjectMap/struct.Globals.html if that helps.
