### ISSUE TITLE
libiconv-2.dll is missing from Windows nightly

### ISSUE THREAD

**Issue by jdm** [servo/servo#23348]

**Comment by jdm** [comment]
It worked as of 4/1.

**Comment by jdm** [comment]
Broken in the 5/6 nightly.

**Comment by jdm** [comment]
Working in the 5/3 nightly. No nightlies in between.

**Comment by jdm** [comment]
Working: https://github.com/servo/servo/commit/9f6005be163520f9a06d5a51a0f81bc43f9ea5a3
Not working: https://github.com/servo/servo/commit/115a4ac4ff0c38fbe1c705e4aaa76d1dfcdeaab6

I suspect it's the harfbuzz update. cc @Eijebong

**Comment by Eijebong** [comment]
I don't get it. There's no reference to iconv in rust-harfbuzz nor in unicode-script which are the only two crates that were updated

**Comment by jdm** [comment]
Regression range: https://github.com/servo/servo/compare/9f6005b...115a4ac

**Comment by jdm** [comment]
I don't know what to make of the fact that a local Windows build still works fine.

**Comment by jdm** [comment]
More specifically, I packaged a debug build on servo-windows3 and ran it from another directory in a new terminal environment, and it worked fine. I'm trying a release build next.

**Comment by jdm** [comment]
The 5/6 nightly was the first one produced by the taskcluster CI instead of buildbot, which could explain why none of the commits in the regression range look related.

**Comment by jdm** [comment]
A release build on servo-windows3 also runs fine.

**Comment by GarethPW** [comment]
Latest build still exhibits this issue.

**Comment by CShepartd** [comment]
Still missing ``libiconv-2.dll`` (downloaded from https://download.servo.org/nightly/windows-msvc/servo-latest.zip)

**Comment by jdm** [comment]
Until this issue is closed, there is no change expected.

**Comment by pinggi** [comment]
I can confirm the missing `libiconv-2.dll` as well.

First I was getting `The application was unable to start correctly (0x000007b). Click OK to close the application.` everytime I ran `servo.exe`. Was really disapointed. After several days I tried again and got he same error. I decided to investigate it. By `depends.exe` (dependency walker) I found that the 64-bit `servo.exe` was dependent on 32-bit `libiconv-2.dll`. It was because I had `mingw` 32-bit in `PATH`. I downloaded AMD64 version of `libiconv-2.dll` and copied it to `C:\Program Files\Mozilla Research\Servo Tech Demo`. Now I can run `servo.exe` without any problem.

What issues are here:
1. `libiconv-2.dll` file is missing
2. 64-bit servo app shouldn't load 32-bit versions of libraries
3. it should show an error if the libraries are missing or are corrupted or the architecture is wrong

I don't know if it's an issue of Windows, Rust, or Servo app, but somebody could look at.

**Comment by pinggi** [comment]
Here is the dependency tree I could see when the servo was installed, the `libiconv-2.dll` file was missing in the servo folder but was found in mingw folder:

![image](https://user-images.githubusercontent.com/18471834/58278918-53c0ea00-7d9d-11e9-975e-f33d0926e924.png)

**Comment by Heartade** [comment]
Dependency Walker shows `libiconv-2.dll` was found in MinGW folder like @pinggi mentioned, but the program subsequently crashed as follows:
> Error: At least one required implicit or forwarded dependency was not found.
> Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
> Error: Modules with different CPU types were found.
> Warning: At least one delay-load dependency module was not found.
> Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

I believe "different CPU types" error refers to `libiconv-2dll` in MinGW being x86.

**Comment by jdm** [comment]
Aha, https://gstreamer.freedesktop.org/documentation/application-development/appendix/integration.html?gi-language=c#building-gstreamer-under-win32 explains that GStreamer expects some tools to already be installed for building like libiconv. I see that the gstreamer installation on the old windows machine we were using for nightly builds contains libicon-2.dll; my suspicion is that we ended up with a blended 1.14/1.15/1.16 installation. I'm seeing if #23484 improves matters; I'll try downloading and running the builds once they complete.

**Comment by bkdwt** [comment]
Same problem here with last nightly on Windows 10.

![servo error](https://user-images.githubusercontent.com/51302074/58847081-00ca1b00-8658-11e9-8571-cce65c6d3145.PNG)
