### ISSUE TITLE
Use merge parent for build tasks in taskcluster

### ISSUE THREAD

**Issue by jdm** [servo/servo#23378]
Every time bors starts a test run, it creates a new merge commit. This means that retrying a build that happened on taskcluster starts all of the builds from scratch, because it looks at the head git sha and checks if there are any reusable tasks based on that sha. If we could use the equivalent of `git show MERGE_SHA^2` instead, we should be able to get the latest commit for the branch being merged and reuse artifacts to avoid rebuilding unnecessarily.

**Comment by jdm** [comment]
https://developer.github.com/v3/activity/events/types/#pushevent

**Comment by SimonSapin** [comment]
+1 to reducing redundant builds. I think we should base the index key on the hashes of **both parent commits** of the merge, so that we rebuild if another PR was merged in the meantime.

In fact we can do the same for every task, not just builds. If WPT chunk number 2 succeeded previously with a given build, no need to run it again and risk hitting an intermittent failure.

**Comment by jdm** [comment]
This was implemented.
