### ISSUE TITLE
Add panic catching to C API

### ISSUE THREAD

**Issue by jdm** [servo/servo#23514]

**Comment by paulrouget** [comment]
Is it just a matter of adding `panic::catch_unwind` to each calls and report the error if panic?

**Comment by jdm** [comment]
Yes. My hope is that it would make it easier to determine the problem when a panic occurs, since when I saw one in HLServo it was completely unclear what was going wrong.

**Comment by jdm** [comment]
https://doc.rust-lang.org/std/panic/fn.catch_unwind.html

**Comment by jdm** [comment]
In the short term, it would be best to make all of the `extern "C"` APIs in https://github.com/servo/servo/blob/master/ports/libsimpleservo/capi/src/lib.rs fallible (by returning failure values like null pointers or adding boolean returns to them), and update the ServoApp integration to check the return values of all of them and output appropriate debugging information before terminating.

**Comment by angelortiz1007** [comment]
Would it be best to wait for paul's winrt HoloLens to be integrated into the winrt-servo branch I have?
https://github.com/angelortiz1007/servo/tree/winrt-servo 

This way I can properly implement the correct return.  Otherwise I can temporarily just return true on my branch and later work with the new winrt HoloLens.

Here is my understanding of the integration of RUST and HoloLens.

If I understand this correctly, I will need to touch files from the following:
1. servo\ports\libsimpleservo\api\src\lib.rs
Here I would need to modify the return values of traits within: pub trait HostTrait {...}

2. servo\ports\libsimpleservo\Capi\src\lib.rs
Here I would need to modify the return values of impl HostTrait for HostCallbacks {…}

3. C:\git-mozilla\servo-angelortiz1007\support\hololens\servo.cpp
Here the following extern "C" functions from servo\ports\libsimpleservo\Capi\src\lib.rs  are used by servo, some of which may not be implemented:

/// Callback used by Servo internals
#[repr(C)]
pub struct CHostCallbacks {
    pub flush: extern "C" fn() -> bool,
    pub make_current: extern "C" fn(),
    pub on_load_started: extern "C" fn(),
    pub on_load_ended: extern "C" fn(),
    pub on_title_changed: extern "C" fn(title: *const c_char),
    pub on_allow_navigation: extern "C" fn(url: *const c_char) -> bool,
    pub on_url_changed: extern "C" fn(url: *const c_char),
    pub on_history_changed: extern "C" fn(can_go_back: bool, can_go_forward: bool),
    pub on_animating_changed: extern "C" fn(animating: bool),
    pub on_shutdown_complete: extern "C" fn(),
    pub on_ime_state_changed: extern "C" fn(show: bool),
    pub get_clipboard_contents: extern "C" fn() -> *const c_char,
    pub set_clipboard_contents: extern "C" fn(contents: *const c_char),
}

Here is a list of unimplemented externs in HoloLens:
void on_load_started() {}
void on_load_ended() {}
void on_title_changed(const char* title) {}
void on_url_changed(const char* url) {}
void on_history_changed(bool back, bool fwd) {}
void on_shutdown_complete() {}

**Comment by jdm** [comment]
For the purposes of protecting the C API from panics, I don't believe there is any need to modify libsimpleservo/api. Those are all Rust functions that will be called from Rust code, so panics can propagate without issue. It's the free functions in libsimpleservo/capi that are defined as `extern "C" fn foo(...)` and have an actual implementation that we need to focus on. The members of CHostCallbacks are function pointers that will be provided by the C++ caller (Servo.cpp, in this case), so we don't need to catch any panics because Rust panics cannot originate inside of C++ code.

**Comment by angelortiz1007** [comment]
Got it now!

 

I was looking at the wrong externs.
