### ISSUE TITLE
[hololens] Automate app package creation

### ISSUE THREAD

**Issue by jdm** [servo/servo#23617]
https://github.com/Microsoft/msbuild/issues/2445 has some information that we should be able to make use of in order to automate building app packages in CI.

**Comment by jdm** [comment]
This is something we will want to support as part of the `mach package` command, implemented in [this code](https://github.com/servo/servo/blob/555fa75b2c7f4faa0818e86296a4ea3d5b8e4d42/python/servo/package_commands.py#L206).

**Comment by angelortiz1007** [comment]
Observations:

While building servo (mach build -d --uwp), the build will not complete with a link time error as follows:
…
…
b" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\git-mozilla\\servo-angelortiz1007\\target\\debug\\deps\\simpleservo.dll.lib"
  = note: lld-link: error: could not open libEGL.lib: no such file or directory
          lld-link: error: could not open libEGL.lib: no such file or directory

Resolution:  To resolve this link time error, the user is required to open the support\HoloLens\ServoApp.sln and attempt to build the x64 build type.  It will also fail with the following msg:
1>c:\git-mozilla\servo-angelortiz1007\support\hololens\servoapp\browserpage.cpp(60): warning C4189: 'visible': local variable is initialized but not referenced
1>LINK : fatal error LNK1181: cannot open input file 'simpleservo.dll.lib'

This failure is due to the mach build -d --uwp link time error not building the simpleservo.dll.lib.

However, the required libegl.lib is then created and found at:
support\hololens\packages\ANGLE.WindowsStore.Servo.2.1.13\bin\UAP\x64

Now the user can complete the mach build -d --uwp build where the simpleservo.dll.lib library is built.

Summary:
In order to automate a full build, the build steps would require the following when executing mach build -d/-r --uwp:
1. The nuget.exe package must create libegl.lib in support\hololens\packages\ANGLE.WindowsStore.Servo.2.1.13\bin\UAP\x64

2. complete the mach build -d/-r --uwp build where simpleservo.dll.lib is created for HoloLens/ServoApp.

3. Proceed to the ServoApp/HoloLens msbuild step.

During research it appears that nuget.exe can be used to create the libegl.lib packages directory for HoloLens using the following command:

nuget update ServoApp.sln
nuget restore ServoApp.sln

The above commands recreated the required packages directory for Angle without the need to open the ServoApp.sln and attempt a build.

After the above nuget commands were executed, the mach -build -r --uwp succeeded without any Servoapp build.

**Comment by jdm** [comment]
The nuget installation already works on CI. I am ok with requiring developers to perform the initial VS build locally, then allow subsequent builds to be automated.

**Comment by jdm** [comment]
Note that the previous comments are really describing https://github.com/servo/servo/issues/23753. This issue is focused on the equivalent of choosing the "Store > Create app package" option from inside Visual Studio.

**Comment by angelortiz1007** [comment]
I'll copy my comments to the #23753 issue too.  Its the best place as you say.

I was seeing the process of:
1. mach build …
2. Store ->Crate app

**Comment by jdm** [comment]
This has been fixed by #24149.
