### ISSUE TITLE
[Hololens] Support launching with specific URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#23615]
https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh452686(v=win.10)

**Comment by paulrouget** [comment]
From #23908:

> We want to support launching directly into immersive content from other device content (such as Edge). The easiest way to do that is by registering a custom protocol handler and using information passed through it to load a page in Servo and provide implicit permission for entering immersive mode.

I'm not sure what the workflow would look like. Jumping right into immersive mode will be a bit tricky because immersive mode is triggered from JS which needs to load within a 2D page.

For now, I will be working on implementing a simple protocol handler ("servo://https://example.com") that will open Servo and load the page in a 2D view.

**Comment by paulrouget** [comment]
Fixed: #24008
