### ISSUE TITLE
No stdout/stderr in UWP app

### ISSUE THREAD

**Issue by jdm** [servo/servo#23734]
This makes debugging panics much more frustrating than it could be. It would be nice to do something involving the APIs in https://docs.microsoft.com/en-us/windows/console/console-handles to redirect it to OutputDebugString. https://social.msdn.microsoft.com/Forums/sqlserver/en-US/34909aa7-e8ad-4d14-91e2-7df1bc2c6fea/where-does-stdout-printf-cout-go-on-windows-universal-apps?forum=wpdevelop may have some other suggestions too.

**Comment by angelortiz1007** [comment]
For Information:
------------------
In my effort to work on this issue I found the following link:
http://unixwiz.net/techtips/outputdebugstring.html 

The API windows OutputDebugString() API uses a protocol to output messages to the debugger.  The protocol and kernel objects used are listed in the link above.

Of interest to me was the DBWinMutex used by the API.  If multiple threads are outputting debug statements, the mutex may introduce a timing effect on the running application and may mask timing issues when used.

Will investigate further.

**Comment by jdm** [comment]
For reference, we have dealt with this on other platforms before to redirect stdout/stderr to the native logging solution: https://github.com/servo/servo/blob/9b14bbdc98ea078a4f868abee1b7c7244161f46d/ports/libsimpleservo/jniapi/src/lib.rs#L531-L614

**Comment by angelortiz1007** [comment]
This is a good reference where STDOUT (1) and STDERR(2) file handles are dup2() into a pipe for redirecting stdout and stderr to a file.

In our case (If I understand correctly), we would like **STDOUT (1)** and **STDERR(2)** to be redirected - somehow/if possible - to OutputDebugString().  I don't see a way to determine the file handle the OutputDebugString() uses, but much like what was done in _redirect_stdout_to_logcat(),_ the following link also describe the steps needed.

https://stackoverflow.com/questions/5248704/how-to-redirect-stdout-to-output-window-from-visual-studio

**Comment by jdm** [comment]
Yeah, it may be possible to use the same pipe-based mechanism and call OutputDebugString directly instead of __android_log_print.

**Comment by angelortiz1007** [comment]
Looking at the reference code I believe thread::spawn() is the function to spawn a thread.

In windows you can specify a file handle/Read/Write operation to be blocking or non-blocking.  blocking is good because a read() operation will not return on the read file handle unless there is data.  I suspect RUST would also have a way to specify a read/write blocking operation and/or non-blocking read operation.

**Comment by angelortiz1007** [comment]
I was able to create a VS2017 solution called StdErrRedirect to verify under windows if STDOUT/STDERR could be redirected via pipes and sent to OutputDebugString() string.

The link to the code is: https://github.com/angelortiz1007/StdErrRedirect and the repository is:
https://github.com/angelortiz1007/StdErrRedirect.git.

Next step is to add into capi/lib.rs.

Question... Should we allow for redirecting to a log file in addition to OutputDebugString().

Observations:
The sleeps introduced in the example/sample code are only there to add some latency between the write()/printf() and the thread.

**Comment by paulrouget** [comment]
> Question... Should we allow for redirecting to a log file in addition to OutputDebugString().

At the moment it's not necessary.

**Comment by angelortiz1007** [comment]
I have determined that crate winapi does not seem to contain the following win32 APIs.
1. _open_osfhandle()
 (https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle?view=vs-2019)

2. _dup2()
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/dup-dup2?view=vs-2019

Seems a LoadLibrary() may be required unless there is another suggestion.

**Comment by jdm** [comment]
@angelortiz1007 For _dup2, it may be possible to use [libc::dup2](https://docs.rs/libc/0.2.60/libc/fn.dup2.html). If not, if those APIs are part of the statically linked libraries, you could try this:
``rust
extern "C" {
    fn _open_osfhandle(osfhandle: isize, flags: i32) -> i32;
    fn _dup2(fd1: i32, fd2: i32) -> i32;
}
```

**Comment by angelortiz1007** [comment]
After my last comment I found _dup2() in libc.  However, I could not find _open_osfhandle().

I will try your "extern" suggestion.

Thanks!!!!

**Comment by jdm** [comment]
Actually it looks like open_osfhandle is in libc as well: https://docs.rs/libc/0.2.60/x86_64-pc-windows-msvc/libc/fn.open_osfhandle.html

The defualt docs.rs view shows the linux docs, so I had to change the platform.

**Comment by angelortiz1007** [comment]
Oh... I see what happened in my search for dup2() and open_osfhandle().
I was looking in https://docs.rs/libc/0.2.60/libc/index.html?search=open_osfhandle instead of https://docs.rs/libc/0.2.60/x86_64-pc-windows-msvc/libc/fn.open_osfhandle.html.

What threw me off was I did find dup2() in the first link.  I got it now.

**Comment by angelortiz1007** [comment]
Question regarding threads..

Should the CreateThread() win api be used or does RUST have a better mechanism?

**Comment by jdm** [comment]
The standard library's thread::spawn is the way to go. The code I linked earlier uses that.

**Comment by angelortiz1007** [comment]
I have completed the coding of fn **redirect_stdout_stderr()** -> bool {}, but been struggling with the read() function blocking in the thread::spawn().  I have verified all the windows functions return the correct return value and if not, the return from fn **redirect_stdout_stderr()** -> bool {}

Any ideas/suggestions why the read() function in the thread may be blocking even though I do a println()/printf()?

Prior to checking code in, if a sanity check of the code can be done?

BTW, a mach fmt was performed on the file.

fn redirect_stdout_stderr() -> bool {
    let mut hReadPipe: winnt::HANDLE = handleapi::INVALID_HANDLE_VALUE;
    let mut hWritePipe: winnt::HANDLE = handleapi::INVALID_HANDLE_VALUE;
    let mut hThread: winnt::HANDLE = handleapi::INVALID_HANDLE_VALUE;
    let mut secattr: minwinbase::SECURITY_ATTRIBUTES = unsafe { mem::zeroed() };

    secattr.nLength = mem::size_of::<minwinbase::SECURITY_ATTRIBUTES>() as u32;
    secattr.bInheritHandle = shared::minwindef::TRUE;
    secattr.lpSecurityDescriptor = shared::ntdef::NULL;

    unsafe {
        if (namedpipeapi::CreatePipe(&mut hReadPipe, &mut hWritePipe, &mut secattr, 512) == 0) {
            return false;
        }

        let hReadPipeFD = libc::open_osfhandle(hReadPipe as libc::intptr_t, libc::O_RDONLY);
        let hWritePipeFD = libc::open_osfhandle(hWritePipe as libc::intptr_t, libc::O_WRONLY);

        if ((hReadPipeFD == -1) && (hWritePipeFD == -1)) {
            return false;
        }

        // 0 indicates success.
        if (libc::dup2(hWritePipeFD, 1) != 0) && (libc::dup2(hWritePipeFD, 2) != 0) {
            return false;
        }

        // Spawn a thread.  The thread will redirect all STDOUT and STDERR messages
        // to OutputDebugString()
        let handler = thread::spawn(move || {
            loop {
                const BUF_LENGTH: usize = 512;
                let mut read_buf: [i8; BUF_LENGTH] = mem::zeroed();

                let result = {
                    libc::read(
                        hReadPipeFD,
                        read_buf.as_mut_ptr() as *mut _,
                        read_buf.len() as u32,
                    );

                    // Write to Debug port.
                    debugapi::OutputDebugStringA(read_buf.as_mut_ptr() as winnt::LPSTR);
                };
            }
        });
    }

    return true;
}

**Comment by angelortiz1007** [comment]
Observations:

In a UWP window based application printf() - even with fflush() - does not cause the read() to unblock.

A _write(1,...) or _write(2, ….) does cause the read() function to unblock and read the redirected STDOUT and STDERR buffer to display.

**Comment by jdm** [comment]
I suspect there is additional buffering in play. https://stackoverflow.com/a/52749115 suggests that calling setvbuf may help; also, we might want to use ReadFile on the pipe read handle rather than calling read directly.

**Comment by angelortiz1007** [comment]
Josh, Thanks for reviewing my comments.  I saw that stackoverflow article too.  Here is what I know regarding buffering on Windows and on the servo rust code so far.

**Windows Console App** 
On a VS2017 console app, after a printf() you have to perform a fflush().  Alternatively, you can use setbuf(stdout, NULL) and you don't have to perform a fflush().  When either is done, the thread performing the read() function call returns.

However, all write(1, "output to stdout.\n") calls are not buffered and the thread's read() function call returns.

**Windows UWP non-console App**
On a VS2017 non-console app (window app) only the write(1, …) or write(2, …) function calls cause the thread's read() function call to return.  printf() operations followed by setbuf() or fflush() did not cause the thread's read() function call to return.

Reference: https://docs.microsoft.com/en-us/windows/console/getstdhandle
Due to the above 2 observations, I decided to also employ the setbuf() api in servo.  In order to call setbuf(), I had to obtained the FILE * equivalent to the stdout file descriptor.

I then performed a GetStdHandle(STD_OUTPUT_HANDLE) to get a window HANDLE for stdout.  Then I did an open_osfhandle() to obtain a file descriptor for stdout.  This file descriptor was then used  with fdopen() to get a  FILE * to stdout.  The FILE * to stdout is needed for setbuf().  This was then used for setbuf(FILE *, NULL).  See code snippet sample below.

 _unsafe {
        let hStdout = processenv::GetStdHandle(winbase::STD_OUTPUT_HANDLE);
        if ((hStdout == handleapi::INVALID_HANDLE_VALUE) || (hStdout == shared::ntdef::NULL)) {
            return false;
        }_

        let hStdoutFD = libc::open_osfhandle(hStdout as libc::intptr_t, libc::O_WRONLY);
        if (hStdoutFD == -1) {
            return false;
        }

        let mut pStdout: *mut libc::FILE;
        let rdstr = c_str_macro::c_str!("RW");

        pStdout = libc::fdopen(hStdoutFD, rdstr.as_ptr());

        libc::setbuf(pStdout, std::ptr::null_mut());
.......
 }__

During execution of ServoApp, I determined that the return value for  let **hStdout = processenv::GetStdHandle(winbase::STD_OUTPUT_HANDLE);** was **NULL**.  Based on Reference: https://docs.microsoft.com/en-us/windows/console/getstdhandle, it says:

**If the function fails, the return value is INVALID_HANDLE_VALUE. To get extended error information, call GetLastError.
_If an application does not have associated standard handles, such as a service running on an interactive desktop, and has not redirected them, the return value is NULL.**_

What does _**"If an application does not have associated standard handles"**_ mean in servo?

**Comment by angelortiz1007** [comment]
Some progress....  After thinking and researching I added the SetStdHandle() function immediately after the call to CreatePipe().  Since the Microsoft refersnce states the application does not have an associated standard handle, I thought by performing  a SetStdHandle() for stdout and stderr to the Pipe's write handle would/may do the trick.

At this point, the read() function withing the thread is not blocking anymore.  However, ServoApp seems to be putting out a lot of data to the VS2017 "Output" window.  Need to research mroe.  See code snippet below.


    unsafe {
        if (namedpipeapi::CreatePipe(&mut hReadPipe, &mut hWritePipe, &mut secattr, 512) == 0) {
            return false;
        }

        if ((processenv::SetStdHandle(winbase::STD_OUTPUT_HANDLE, hWritePipe) == 0) ||
            (processenv::SetStdHandle(winbase::STD_ERROR_HANDLE, hWritePipe) == 0))
        {
            return false;
        }

**Comment by angelortiz1007** [comment]
SUCCESS!!!!

within init() function in capi\lib.rs I added a println!() statement.  See below.  ServoApp was rebuilt and on the VS2017 "_Output" window, the sting ""Capi/lib.rs: init() function called redirect_stdout_stderr() successfully._" appeared. 

_unsafe fn init(
    opts: CInitOptions,
    gl: gl_glue::ServoGl,
    gl_context: Option<*const c_void>,
    display: Option<*const c_void>,
    wakeup: extern "C" fn(),
    callbacks: CHostCallbacks,
) {
    init_logger();

    if (redirect_stdout_stderr() == false) {
        warn!("Error redirecting STDOUT/STDERR.")
    }

	println!("Capi/lib.rs: init() function called redirect_stdout_stderr() successfully.\n");_

The solution to the problem in STDOUT/STDERR in applications that don't have the standard handles/file descriptors associated with them is to use  CreatePipe(), then assign the STDOUT and STDERR to the write pipe handle/file descriptor.

Need to test further and clean up code.

**Comment by paulrouget** [comment]
> SUCCESS!!!!

:D

**Comment by angelortiz1007** [comment]
Thx Paul :)
