### ISSUE TITLE
Rewrite HoloLens GL thread code

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23823]
At the moment, we loop and block on a condition variable. Every time the loop is unblocked we check what's in a shared event array and do the servo calls according to what's in the array.

I think it would be better to not loop but capture the GL thread `apartment_context` and later switch back to the context with `co_await` and then directly make the Servo calls. No need for a loop or a shared array.

The only thing I'm not sure about is what should be done when Servo is animating. We'll need to loop but how can we interrupt the coroutine in the case of a UI event (for example clicking while animating)?

**Comment by paulrouget** [comment]
Documentation: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency

**Comment by jdm** [comment]
This might be a good topic for next week if we don't need to solve it before that time.

**Comment by paulrouget** [comment]
Absolutely.

**Comment by gterzian** [comment]
I'm wondering what the problem is with 

https://github.com/servo/servo/blob/b52bfbe68aed9b0abb39a6e994c5dad37cf7d33c/support/hololens/ServoApp/BrowserPage.cpp#L122

and 

https://github.com/servo/servo/blob/b52bfbe68aed9b0abb39a6e994c5dad37cf7d33c/support/hololens/ServoApp/BrowserPage.cpp#L255

Since if you look at 

https://github.com/servo/servo/blob/b52bfbe68aed9b0abb39a6e994c5dad37cf7d33c/support/hololens/ServoApp/BrowserPage.cpp#L331

It seems to add an even to the shared list. 

So in theory, if in `mAnimating` mode, the loop should eventually release the lock and call `mServo->PerformUpdates()`, which gives a chance to `BrowserPage::SendEventToServo` to acquire the lock. Then when the loop starts another iteration is should handle the event, no?

If not in `mAnimating`, in theory two things can happen:

1. The loop is waiting on the event, without holding the lock.
2. The loop is handling event and holds the lock.
3. The loops is calling `PerformUpdateds` which means it's not waiting, yet it's also not holding the lock. 

I guess in 3, it's then possible for `SendEventToServo` to acquire the lock, add an event, and dispatch the event. 

Even if the loop is not waiting, it should still be woken-up the next time it starts waiting, see 

>  The state of an auto-reset event object remains signaled until a single waiting thread is released, at which time the system automatically sets the state to nonsignaled. If no threads are waiting, the event object's state remains signaled. https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-setevent#remarks

So it's not clear to me where the problem is coming from. 

Since you first block on the event, and then acquire the lock if woken-up, there might be some weird race between the event and the lock. 

You could consider using an actual conditon variable instead of an event, since the condvar is more integrated with the lock(you need to first acquire the lock and then start waiting).

There is an example here: https://docs.microsoft.com/en-us/windows/win32/sync/using-condition-variables

It looks like they have a bunch of "lock-like" and "condvar-like" objects you can use instead of the raw stuff...

**Comment by paulrouget** [comment]
WatchSingleObject/condvar + mutex can work. It just needs to keep looping when the event array is not empty (basically, only WatchSingleObject if not animating and array not empty). That's what's missing here.

But I think I'll use a coroutine as it looks like it's the "right way" to do such things with c++17. I also believe I can avoid looping by doing so.

I'll be talking to people this week who know more about how these things should be done with winrt+UWP.

**Comment by paulrouget** [comment]
You're right about the unexpected behavior though... it should not be blocking. Not sure why. I'll be looking at this this week.

**Comment by gterzian** [comment]
> But I think I'll use a coroutine as it looks like it's the "right way" to do such things with c++17. I also believe I can avoid looping by doing so.

You might also want to checkout it the dispatcher queue:

https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue.tryenqueue#Windows_System_DispatcherQueue_TryEnqueue_Windows_System_DispatcherQueueHandler_

**Comment by gterzian** [comment]
Ok so, here is my five-cents:

What can lead to problems is that currently the lock is not held while the even is awaited. It's not clear to me what guarantees "events" give in this context, however condvar usually mean you pair them with a lock, and then each time you want to access some shared-state you do:

1. acquire the lock(guard, non-blocking). 
2. wait on the condvar. 

The condvar will then atomically release the lock, allow for a consumer to acquire it, do something with the share-state, and then signal on the condvar. When the waiting thread wakes-up, the condvar atomically re-aquires the lock. 

So, jus to make the current setup more robust(potential later use of `co_await` nowithstanding). I'd do the following:

1. Consider using the "critical section" and "conditional variable" objects, not the lower-level locks. See https://docs.microsoft.com/en-us/windows/win32/sync/using-condition-variables
2. In the `Loop`:
    a. acquire the lock `EnterCriticalSection (&BufferLock);`
    b. `while events.size > 0 || mAnimating { }
    b. Wait on the condvar `SleepConditionVariableCS (&BufferNotFull, &BufferLock, `INFINITE`);`

3. in `OnAnimatingChanged`: `WakeConditionVariable (&BufferNotFull);`

4. In `SendEventToServo`
    a. `EnterCriticalSection (&BufferLock);`
    b. ` mEvents.push_back(event);`
    c. `WakeConditionVariable (&BufferNotEmpty);`
    d. `LeaveCriticalSection (&BufferLock);`

**Comment by paulrouget** [comment]
@gterzian thank you! I'm gonna try to follow your recommendation.

**Comment by gterzian** [comment]
great! You're welcome. 

Lastly, I just realized we still need to do `WakeUp`, and it fits nicely into the above, since you could do:

```c++
void BrowserPage::WakeUp() {
  SendEventToServo({{Event::WAKEUP}});
}
```

and in the light of https://github.com/servo/servo/issues/23865

once can imagine doing:
```c++
void BrowserPage::WakeUp(Event event) {
  SendEventToServo({{event}});
}
```

**Comment by paulrouget** [comment]
> So it's not clear to me where the problem is coming from.

The problem was that: https://github.com/servo/servo/blob/174bcc443435100da31b20db5ab684f4f3c8255b/ports/libsimpleservo/api/src/lib.rs#L491

In batch mode this would never process. Fix incoming.
