### ISSUE TITLE
Expand wpt lint to cover moz suite as well

### ISSUE THREAD

**Issue by gterzian** [servo/servo#23897]
There is a wpt lint that checks for stuff like leaving a `console.log` in a test file, at 
https://github.com/servo/servo/blob/510ffde3f18d02f19be1e90baa903239922a8e49/python/servo/lints/wpt_lint.py

However, it doesn't seem to work for tests added to the "mozilla" folder, see https://github.com/servo/servo/pull/23887/files#r309177019

The "mozilla" folder is at https://github.com/servo/servo/tree/510ffde3f18d02f19be1e90baa903239922a8e49/tests/wpt/mozilla/tests/mozilla

Could be an error in the python code using the wrong filepath...

**Comment by gterzian** [comment]
A good way to check your check is simply doing `./mach test-tidy`, since we currently have a `console.log` checked-in, it should fail. Then you could also remove it, so that your PR would actually pass CI...

**Comment by mrobinson** [comment]
The lint is actually running, but it doesn't catch `console.log` because those errors are currently ignored in the `lint.ignore` file. I think we could open a PR cleaning up these errors as we find them. Additionally, we should be relying less and less on the tests in `mozilla` and more on the tests in the WPT suite where we can.
