### ISSUE TITLE
Pages load sluggishly on hololens

### ISSUE THREAD

**Issue by jdm** [servo/servo#24102]
I've been loading a bunch of three.js examples (such as http://rawcdn.githack.com/mrdoob/three.js/r105/examples/webvr_rollercoaster.html) and the servo.org homepage, and both release and debug builds display a general sluggishness in getting past the initial white page. The Servo homepage in particular has a very long delay before the screenshot appears, and it's only 200kb (but it is also 2.4k x 1.5k pixels).

**Comment by jdm** [comment]
I've loaded the demos and the Servo homepage in desktop servo quickly on a different wifi network, so I'll try with the same machine on the same wifi network that the hololens is using.

**Comment by jdm** [comment]
@paulrouget What are some specific pages that load slowly?

**Comment by paulrouget** [comment]
Images, especially the background, are taking a long time to show up: https://servo.org/hl-home/

**Comment by jdm** [comment]
Do you notice a difference in performance between the device and a laptop on the same network?

**Comment by paulrouget** [comment]
I've tested with the device and emulator. For the landing page, load speed is more or less as good as IE. Sluggishness happens on the emulator, but it really feels like it's a screen refreshing delay. The background image was taking quite a long time to load, but I believe is was because of the original size of the background (which I optimized in the latest landing page PR).

As for the demos. For the rollercoaster, it's hard to notice any significant differences.

For https://servo.org/hl-home/bbjs/espilit/, on the device 31s. 27s on IE on the device.

Nothing significant.

@jdm I'm closing this. Reopen if there are any other page that is slow or need testing.
