### ISSUE TITLE
Floats and images within are misplaced on Wikipedia

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#2422]
Test case: http://en.wikipedia.org/wiki/Coyote

The images and floats are in the wrong place.

**Comment by mrobinson** [comment]
Wikipedia has changed *a lot* since this bug was opened and it's unclear what it was referring to since there's no screenshot or test case here. The layout of the article content looks very similar to me in both legacy and non-legacy layout, so it's unclear what to do here. I'm just going to close this as it's quite likely that the original layout has changed.
