### ISSUE TITLE
Support OffscreenCanvas as CanvasImageSource

### ISSUE THREAD

**Issue by jdm** [servo/servo#24269]
Code:
* https://github.com/servo/servo/blob/4fe8238b14d535f7ca94a36effda06624b73ecbe/components/script/dom/webidls/CanvasRenderingContext2D.webidl#L15
* https://github.com/servo/servo/blob/4fe8238b14d535f7ca94a36effda06624b73ecbe/components/script/dom/canvasrenderingcontext2d.rs#L335-L350
* https://github.com/servo/servo/blob/4fe8238b14d535f7ca94a36effda06624b73ecbe/components/script/dom/canvasrenderingcontext2d.rs#L359-L419

Tests:
* `./mach test-wpt tests/wpt/web-platform-tests/offscreen-canvas/drawing-images-to-the-canvas` should report [newly passing tests](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations)

We'll want to generalize draw_html_canvas_element to support offscreen canvases as well, since the majority of the code is applicable to both. An enum argument is probably the best way to do that.

**Comment by bblanke** [comment]
On this

**Comment by bblanke** [comment]
Okay! I made some changes to the repo, and there are now 30 new tests passing! However, none of them are in drawing-images-to-the-canvas. I'm trying to figure out what's missing.

I added a match statement in [canvas_state.rs](https://github.com/bblanke/servo/blob/13ba9da91cd840fe721e1caa8141f8427b5c8058/components/script/canvas_state.rs#L360) to call the proper draw function when an offscreen canvas is passed in. I then created my own version of the [draw_html_canvas_element_offscreen](https://github.com/bblanke/servo/blob/13ba9da91cd840fe721e1caa8141f8427b5c8058/components/script/canvas_state.rs#L418) that basically does the same as the original function, but instead of matching a "normal" canvas's context, it matches for an OffscreenCanvasContext and sends it a message to draw the source's canvas into it. Do you see anything inherently wrong with this?

I'd appreciate any help that you could offer! Also, how do you effectively debug? Is there a way to view print statements from Rust code while running tests? Do I need to just bite the bullet and learn how to use GDB? What's your best advice on this?

Thanks so much for your time!

**Comment by jdm** [comment]
It's most effective to run a single test along with the `--log-raw -` argument. This will let you see the output of println! in your terminal. Alternatively, if you use macros like info!/debug!/warn!/etc. in a file like components/canvas/canvas_paint_thread.rs or components/script/dom/offscreencanvas.rs, then you can run tests with `RUST_LOG=script::dom::offscreencanvas,canvas::canvas_paint_thread` to see the output (that's an environment variable, in case it's unclear).

As for the code snippets, those seem reasonable to me (and nothing else in https://github.com/servo/servo/compare/master...bblanke:OffscreenCanvasasCanvasImageSoure seems unreasonable). I recommend deleting the contents of https://github.com/bblanke/servo/blob/13ba9da91cd840fe721e1caa8141f8427b5c8058/tests/wpt/metadata/offscreen-canvas/drawing-images-to-the-canvas/2d.drawImage.canvas.html.ini and running that test to see the exact failing output that is reported. That might help narrow down where the failure is coming from.

**Comment by jdm** [comment]
As for gdb, that can definitely be an efficient way to figure out if code is actually running. You can go a long way with the following commands: `run` (start the program execution), `break file.rs:45` (interrupt execution when line 45 of file.rs is reached), `continue` (continue executing from a breakpoint), `next` (advance to the next line), `step` (step into a function call), `finish` (continue execution until it has returned from the current function)

You can use `./mach test-wpt path/to/test.html --debugger` to launch a gdb session with the test ready to start, set some breakpoints, then use `run` to start execution.

**Comment by bblanke** [comment]
GDB is working great
I had to use this instead of the shorthand:
`breakpoint set --file foo.c --line 12`

Good article for anyone else that finds themselves here: https://lldb.llvm.org/use/tutorial.html

**Comment by jdm** [comment]
Ah, when you said GDB I assumed you were actually using GDB, not LLDB :)

**Comment by bblanke** [comment]
Lol shoot yeah lldb! Also, through the lldb magic, I found out that the functions that I expect to get called are indeed getting called (specifically, [draw_html_canvas_offscreen](https://github.com/bblanke/servo/blob/13ba9da91cd840fe721e1caa8141f8427b5c8058/components/script/canvas_state.rs#L418)). I also know that the test is failing because there's a location where the code expects a colored pixel, but the pixel is black. So, I'm wondering if there's something wrong with the way that I request the destination canvas to draw the source canvas onto it (through Canvas2dMsg::DrawImageInOther)? Does OffscreenCanvas need something added to  it to make it support this operation?

**Comment by jdm** [comment]
I recommend adding some assertions to the test to verify that the canvas that's being used as the image source contains the expected pixels before the draw operation occurs. That should narrow down where the unexpected behaviour is stemming from.

**Comment by bblanke** [comment]
Figured it out! The Offscreen Canvas's width and height properties were switched. I fixed that and ran tests and now 830 new tests are passing...

Few questions:
1) The code builds and all of the tests unexpectedly pass (no fails)...is there still a possibility that I just totally screwed something? Up or is this just a really lucky bug fix?
2) Is there an easier way to delete the metadata for the passing tests? I could look into writing a script (maybe extend mach?) if there isn't one yet.

**Comment by jdm** [comment]
Woo! I'm pretty sure this is just a lucky bug fix if a lot of tests happen to rely on using OffscreenCanvas as an image source. We already pass lots of onscreen canvas tests and the offscreen canvas uses the exact same backend, so this result makes sense to me. You can run the tests for a particular directory with `--log-raw wptlog` and then run `./mach update-wpt wptlog` and the metadata will be updated for you.

**Comment by jdm** [comment]
With very convenient timing, we just merged 03e574fd3e8dee3c2286cb48692cced6c8589f48 which incorporated https://github.com/web-platform-tests/wpt/pull/20277. You will need to rebase your changes to master and regenerate the test results; I suspect they will be less overwhelmingly fail->pass as a result.

**Comment by bblanke** [comment]
Alright; I think I have it now. Submitted an incorrect commit earlier.
