### ISSUE TITLE
FileReader.read does not clear any existing result value

### ISSUE THREAD

**Issue by jdm** [servo/servo#24288]
Spec: https://w3c.github.io/FileAPI/#readOperation
Code: `components/script/dom/filereader.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/FileAPI/reading-data-section/filereader_result.html`

`FileReader::GetResult` checks if there is already a result and returns it. If there are multiple read operations in a row, the result should be cleared when the second one is started, but that does not happen right now.

**Comment by tigleym** [comment]
Hello! I'd be interested in tackling this issue. 

@highfive: assign me

**Comment by tigleym** [comment]
@jdm I'm hitting a timeout in the tests where the "loadstart" event is not firing after the second read call.  

I think the issue is coming from https://github.com/servo/servo/blob/da559d47b93854e4c7d4acf0a0d2029a9e643794/components/script/dom/filereader.rs#L224 . Though I'm unsure of why the generation ids are different in this case. 

As described in the spec, I'm setting `result` to `null` after the state is set to "loading" like this: 
```
*self.result.borrow_mut() = None;
```

Would you be able to point me in the right direction on what I might be doing wrong here?

**Comment by jdm** [comment]
Good find @tigleym! I suspect the problem is that we call [terminate_ongoing_reading](https://github.com/servo/servo/blob/da559d47b93854e4c7d4acf0a0d2029a9e643794/components/script/dom/filereader.rs#L283) after the loadend event - if the event listener watching for that event ends up initiating a new read operation, it will be started with the old generation id. It's really not clear to me why that code does that, and the specification has been rewritten so the existing step comments don't help much. I propose that as part of the `read` method we should also increase the generation id, and remove the `terminate_ongoing_reading` call from `process_read_eof`.
