### ISSUE TITLE
WebGL: Allow TexImage from a different origin if CORS used

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24330]
https://github.com/servo/servo/blob/cf725fc3f59bc1b94e3b35ab4cfe60b3d41559cc/components/script/dom/webglrenderingcontext.rs#L567

**Comment by paulrouget** [comment]
@jdm: Is it just a matter of checking the cross origin attribute or it's more convoluted?

**Comment by jdm** [comment]
@paulrouget it requires storing some information at https://github.com/servo/servo/blob/master/components/script/dom/htmlimageelement.rs#L192 about what kind of filtering was present in the response body. If it's opaque, then CORS should not allow reading from the image. Otherwise we should be able to allow it.
