### ISSUE TITLE
font-style italic with font-family doesn't work

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#24554]
```html
<style>
body {
  font-family: helvetica, arial, sans-serif;
}

h1 {
  font-style: italic;
}
</style>

<h1>Italic Font Style!</h1>
```

![image](https://user-images.githubusercontent.com/6782666/67573466-5cb24f00-f773-11e9-9d02-012107a07c89.png)

The `h1` should be rendered with italic style.

Built with latest master (b7b1b903d3) on macOS 10.14.6

cc @emilio

**Comment by atouchet** [comment]
![font](https://user-images.githubusercontent.com/26315797/80873172-8b056f80-8c6b-11ea-9d16-0f43a900100c.png)

I am not able to reproduce the issue using the latest nightly build in Windows 10.

**Comment by CYBAI** [comment]
I can still reproduce this on macOS 10.14.6.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/6782666/80896398-71762d80-8d28-11ea-87ec-def9952ef868.png">

**Comment by atouchet** [comment]
@CYBAI are you still able to reproduce this issue? There were some Mac font crate updates recently.

**Comment by CYBAI** [comment]
yes 😂 this is screenshot I run it with latest master.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/6782666/84467065-e6d50680-acb5-11ea-8d30-97f31a9bd8e8.png">

**Comment by mrobinson** [comment]
The issue here seem to be that Helvetica is stored in a TTC collection of fonts. Thus multiple faces with different properties have the same path.

The CoreText backend doesn't properly support instantiating CoreText fonts with their path and postscript name, which is the only reliable way to get the right font from a TTC file with CoreText. Other platforms allow passing an index when instantiating a font, but this isn't possible for CoreText. This means that font attributes (like weight and slant) aren't read properly from the font. We can also get this information straight from the system font list, which is what we should probably do.

In both cases we need to properly instantiate the CoreText font though.

**Comment by lumiscosity** [comment]
Still happens on Arch Linux x86_64, Servo built against commit 6c2ac81cd15795d469c46782419f96c9bb55d09d. I have both Helvetica and Arial installed.

<img width="1024" height="740" alt="Image" src="https://github.com/user-attachments/assets/9f592e59-8851-4c95-9ca0-9f992c367fd9" />

**Comment by mrobinson** [comment]
The original issue was for macOS, so perhaps in this case you are facing a different one? Do you mind opening a new bug for this with the list of fonts you have installed (via `fc-list`)?

**Comment by lumiscosity** [comment]
Aah, noted. Will do that in a second.

EDIT: Nevermind, false alarm. Turns out I had a font that masqueraded as Helvetica for some fancy text stacking replacement reasons ([nasin nanpa](https://github.com/etbcor/nasin-nanpa/releases/tag/n4.0.2)). Still a new issue, though - this should probably fall back to the next available font (Arial), or try to synthesize the italics as Firefox does.
