### ISSUE TITLE
Reloading bbjs basic scene can panic

### ISSUE THREAD

**Issue by jdm** [servo/servo#24591]
In the HL emulator I reloaded http://paulrouget.com/test/bbjs/basic/ and got a panic trying to access the window proxy.

**Comment by paulrouget** [comment]
Panic happens here: https://github.com/servo/servo/blob/dfa78986a6f74176bc36f4ba29969ec421a8730c/components/script/dom/document.rs#L4745

A simple raf loop triggers the panic. It happens "most of the times" when the page loads from http: (as opposed to a file: url).

This example panics all the time over http:

```html
<script>
  window.addEventListener("unload", () => {
    console.log("JS: UNLOAD");
    window.requestAnimationFrame(() => {
      console.log("RAF AFTER UNLOAD:" + window.document.title);
    });
  });
  window.location.reload();
</script>
```

**Comment by paulrouget** [comment]
I really this would do the trick, but it doesn't. Wondering why:

```diff
diff --git a/components/script/script_thread.rs b/components/script/script_thread.rs
index 191df335ec..c5cfbbd0b9 100644
--- a/components/script/script_thread.rs
+++ b/components/script/script_thread.rs
@@ -2914,11 +2914,17 @@ impl ScriptThread {
 
     /// Handles when layout thread finishes all animation in one tick
     fn handle_tick_all_animations(&self, id: PipelineId) {
-        let document = match { self.documents.borrow().find_document(id) } {
-            Some(document) => document,
+        let window = match { self.documents.borrow().find_window(id) } {
+            Some(window) => window,
             None => return warn!("Message sent to closed pipeline {}.", id),
         };
-        document.run_the_animation_frame_callbacks();
+        if !window.Closed() {
+            let document = match { self.documents.borrow().find_document(id) } {
+                Some(document) => document,
+                None => return warn!("Message sent to closed pipeline {}.", id),
+            };
+            document.run_the_animation_frame_callbacks();
+        }
     }
 
     /// Handles firing of transition events.
```

**Comment by paulrouget** [comment]
The above patch is not supposed to be necessary.

The document is supposed to not be part of `self.documents` after `window.clear_js_runtime()` is called.

Investigating…

**Comment by paulrouget** [comment]
Navigating from document A to document B:

In the unload event callback of A, the `window` global is the one from B. Creating all sort of problems when `requestAnimationFrame` is called in there.

To illustrate the issue:

```
<script>
  window.addEventListener("unload", () => {
    console.log(window.location); // will print "about:blank"
  });
  window.location.assign("about:blank");
</script>
``` 

Or to generate a crash:

```html
<script>
  window.addEventListener("unload", () => {
    window.requestAnimationFrame(() => {
      window.document.title;
    });
  });
  window.location.assign("about:blank");
</script>
```

Making these changes shows the global mixup:

```difff
diff --git a/components/script/dom/document.rs b/components/script/dom/document.rs
index 5a34487900..9c6c529730 100644
--- a/components/script/dom/document.rs
+++ b/components/script/dom/document.rs
@@ -1604,6 +1604,9 @@ impl Document {
 
     /// <https://html.spec.whatwg.org/multipage/#dom-window-requestanimationframe>
     pub fn request_animation_frame(&self, callback: AnimationFrameCallback) -> u32 {
+        let handle = std::thread::current();
+        let pipeline_id = self.window.upcast::<GlobalScope>().pipeline_id();
+        println!("from script_thread {:?}:\n  RequestAnimationFrame url: {:?} pipeline: ", handle.name(), self.url(), pipeline_id);
         let ident = self.animation_frame_ident.get() + 1;
 
         self.animation_frame_ident.set(ident);
diff --git a/components/script/dom/eventtarget.rs b/components/script/dom/eventtarget.rs
index 12cf7d0253..9aa2aed451 100644
--- a/components/script/dom/eventtarget.rs
+++ b/components/script/dom/eventtarget.rs
@@ -160,6 +160,8 @@ impl CompiledEventListener {
         // Step 3
         match *self {
             CompiledEventListener::Listener(ref listener) => {
+                let handle = std::thread::current();
+                println!("{:?}: HandleEvent_: {:?}", handle.name(), object.global().pipeline_id());
                 let _ = listener.HandleEvent_(object, event, exception_handle);
             },
             CompiledEventListener::Handler(ref handler) => {
```

In the call to request_animation_frame I think we're supposed to expect the pipeline_id of A, not of B.

Does anyone with more experience with globals and context have any idea of what might be going wrong here? /cc @jdm @gterzian

**Comment by gterzian** [comment]
Ok, I'm still debugging, but I have an idea, and some factual obervations.

Facts:

1. constellation sends an "unload" message for pipeline 1.
2. Inside `unload`, in the Rust code, if you check the pipeline id, you also get 1. 
3. Inside the JS run in response to firing the `unload` event, if you do anything that ends-up calling into `Window`, and then print the pipeline from Rust, you get pipeline 2. 
4. That's why for example a animation frame callback is requested for pipeline 2, not 1, even though it happens while running the unload code for pipeline 1. 

So basically, the Rust is right, but the JS uses a different window. 

Here's what's happening:

- In `ScriptThread.load`, which is called into by the parser in response to the fetch message that headers are available, we create a new window for an existing browsing context. 
- Then we set the window of pipeline 2 to be the "active window" of the browsing context, while pipeline 1 hasn't been unloaded yet. 
- Then the script thread handles the "unload" message for pipeline 1. At that point, from Spidermonkey's perspective, pipeline 2 has already become the active window, so when `unload` fires, `window` as used in JS resolves to pipeline 2, not 1. 
- If you do anything inside that `unload` handler, you'll do it for pipeline 2, for example requesting an animation frame.

Later, the script-thread handles the "exit pipeline" message for pipeline 1, and the window clears it's js runtime(setting windowproxy to none). 

So this last point I'm not sure about, but I think when you clear the js runtime for pipeline 1, it actually clears the currently active window, which is 2. 

Then, the animation callback runs, and pipeline 2 doesn't have a window anymore, crash.

**Comment by paulrouget** [comment]
> Then we set the window of pipeline 2 to be the "active window" of the browsing context, while pipeline 1 hasn't been unloaded yet.

Is that the "proper" behavior?

**Comment by gterzian** [comment]
> Is that the "proper" behavior?

I don't think so. 

If you look at https://html.spec.whatwg.org/multipage/browsing-the-web.html#navigate-html

It says to:

1. Create a new document,
2. After creating the Document object, but before any script execution, certainly before the parser stops, the user agent must update the session history with the new page.

https://html.spec.whatwg.org/multipage/browsing-the-web.html#update-the-session-history-with-the-new-page

says to:
2. unload the old one,
3. traverse the session history to the new one(which make it the "active" entry for the BC). 

So the problem here is sort-of a symptom of https://github.com/servo/servo/issues/23479

There is a fix for the unloading/nullifying of the window proxy at https://github.com/servo/servo/pull/24789

**Comment by gterzian** [comment]
Ok so I think that https://github.com/servo/servo/pull/24789 shows what the problem, and potential  solution, is. 

So indeed, when the script-thread `load`s a new pipeline, it already sets it to be the currently-active one for the window-proxy. 

Then, it handles the `unload` message, for the old pipeline, from the constellation, which calls into JS via various events. So the problem is that at that point `window` inside the JS resolves to the new pipeline, because it has already been set to be the currently-active one. 

So the solution is to unload the old pipeline while it is still the active window for the browsing context. 

However, unloading the pipeline "earlier" breaks the history traversal workflow, I think because it potentially results in discarding the pipeline(if a listener for unload has been set). 

So this might require some larger re-structuring(although I'm still trying to see if some minimal change could do the trick).
