### ISSUE TITLE
Fmt not working?

### ISSUE THREAD

**Issue by gterzian** [servo/servo#24696]
Has anyone noticed that calling `./mach fmt` doesn't seem to always work? I was working on `component/script/dom/globalscope.rs` and it seemed to have no effect. At the same time it was working in `component/constellation/constellation.rs`.

**Comment by jdm** [comment]
What's an example of how it did not work? I haven't noticed any problems with it.

**Comment by gterzian** [comment]
I just narrowed it down, it has no effect inside a `task!` macro, which is perhaps expected...

**Comment by CYBAI** [comment]
@gterzian is it like rust-lang/rustfmt#3478 👀?

**Comment by gterzian** [comment]
yes

**Comment by CYBAI** [comment]
How about leaving a comment in that thread so that rustfmt folks can reopen that issue and investigate it 👀?

**Comment by gterzian** [comment]
fmt is using 1.4.8 on my machine, and the commit that would have fixed it would have been included in one of the two recent ones I think. We could first see if updating fmt helps...

**Comment by SimonSapin** [comment]
rustfmt mostly does not format things inside macros, because an unknown could accept arbitrary Rust token trees that are not necessarily valid Rust language syntax.

* https://github.com/rust-lang/rustfmt/issues/8
* https://github.com/rust-lang/rustfmt/issues/2905
* https://github.com/rust-lang/rustfmt/issues/3445
* https://github.com/rust-lang/rustfmt/issues/3705

**Comment by dralley** [comment]
Seems like this is fixed or not an issue - close?
