### ISSUE TITLE
Optional pipeline in WorkerScriptLoadOrigin should not be optional

### ISSUE THREAD

**Issue by jdm** [servo/servo#24772]
All code that creates a WorkerScriptLoadOrigin passes a Some value for the pipeline, so we should remove the Option from the struct member field.

Code:
* `components/script_traits/lib.rs`
* `components/script/dom/serviceworkerregistration.rs`
* `components/script/dom/worker.rs`

No need to run tests - if it builds, it's good enough for a pull request.

**Comment by phil3112** [comment]
@highfive: assign me

This looks like something I could do.

**Comment by FighttoSurvivor** [comment]
i help but dont give back

**Comment by warren-fisher** [comment]
@highfive : assign me

**Comment by warren-fisher** [comment]
I have looked into this and this is my understanding:
`components/script/dom/serviceworkerregistration.rs` and `components/script/dom/worker.rs` create new instances of the `WorkerScriptLoadOrigin` struct with pipeline_id as a `Some(pipeline_id)`. Therefore the Option type of the `WorkerScriptLoadOrigin` is not necessary since we can always expect a `Some(pipeline_id)` and never a `None`. So I tried changing it so that the `WorkerScriptLoadOrigin` pipeline_id field accepts a `PipelineId` type, as well as changing it so that in `components/script/dom/serviceworkerregistration.rs` and `components/script/dom/worker.rs` when creating this struct it gives it a `PipelineId` instead of a Some. 

My problem with this is that both `components/script/dom/serviceworkerglobalscope.rs` and `components/script/dom/dedicatedworkerglobalscope.rs` expect an Option type in a few places so the compiler fails with mismatched types. Perhaps I am completely off on my ideas about this (very new to Rust) or perhaps these other files need updating as well. I will not proceed any further for the moment.

**Comment by jdm** [comment]
@warren-fisher I'm not sure I understand the issue - I believe any code in those files that expects an Option can be passed `Some(pipline_id)` and satisfy the compiler.

**Comment by warren-fisher** [comment]
@jdm Perhaps I didn't explain very well. If I change the `WorkerScriptLoadOrigin` struct to have a `PipelineId` and not an `Option<PipelineId>` then that means I have to change the instances where `Some(pipeline_id)` occurs to `pipeline_id` or else there is a type mismatch. Perhaps I misunderstood this issue and it is not correct to change `Option<PipelineId>` into `PipelineId` in the `WorkerScriptLoadOrigin` struct in `components/script/dom/serviceworkerregistration.rs`. 

This then has cascading affects in a few of the other files I mentioned where they were expecting an Optional but not are being passed a PipelineId struct instead. It is very possible that I misunderstood the goal of this issue, I am still new to Rust.

**Comment by jdm** [comment]
It certainly sounds like you're on the right track. We want to change the `Option<PipelineId>` to a `PipelineId` in `WorkerScriptLoadOrigin`; this means that any code that handles a None case when reading that value can be removed entirely. I think it might help if you linked to particular lines of code that are giving errors that you aren't sure how to address.
