### ISSUE TITLE
Request and response bodies as something potentially streamable rather than simple Option<vec<u8>>s

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24876]
net_traits::request::Request needs a big change to implement the full fetch API. Its concept of "body" is currently an Option<Vec<u8>>: either the body isn't there, or the entire body is there, with no sense of streaming; contrast with Response having distinct Receiving and Done states in its ResponseBody.

hyperium's http::Request looks like it's already prepared to take a stream if we give it one, so the matter becomes updating net_traits::request to have that possibility. An obvious real Web use case of this would be large file uploads, so that we're not allocating the entire file into a vec<u8> at once before sending it across the network. 

I wasn't sure how big or small a task this would be, so I took some time digging into everything that seemed likely to care about request bodies and made notes. In case anyone wants to follow along:

<details>
<summary>Which code cares about request bodies?</summary>

Code that just fires a request via RequestBuilder and doesn't care about the Request object itself probably doesn't have to worry about these changes; I didn't bother listing these files individually.
Some code implementing FetchResponseListener may care about these changes, as a streaming request will result in chunk-by-chunk calls to process_request_body followed by a separate process_request_eof call. However, most things that listen for a fetch response only care about the response and are indifferent to the streaming state of the request, so the most common process_request_body and process_request_eof are no-ops. 
Code that uses net_traits::Request objects themselves is obviously most likely to be affected by changes, but in many cases Requests are passed around without any inspection of their bodies. It looks like only a few files use Requests in a way that notices the type or semantics of the body, and so changing the body implementation shouldn't involve a large overhaul.

--

CODE THAT USES FetchResponseListener:

These files touch FetchResponseListener but don't implement it and probably aren't affected by the details of fetch requests:
script/script_thread.rs
script/network_listener.rs 

These classes have a FetchResponseListener where request events are a no-op and this seems like it is probably correct behavior (but signatures might have to change if the events end up having data in them):
script/dom/servoparser/mod.rs ParserContext
script/dom/htmlmediaelement.rs HTMLMediaElementFetchListener
script/dom/htmlvideoelement.rs PosterFrameFetchContext
script/dom/htmlimageelement.rs ImageContext
script/stylesheet_loader.rs StylesheetContext
script/layout_image.rs LayoutImageContext

components/net_traits/lib.rs FetchTaskTarget is a FetchResponseListener that forwards request events over IPC, but it handles the events opaquely and just needs to be updated to continue reflecting them after any signature changes

These classes have a FetchResponseListener where request events are marked TODO, suggesting they are waiting on code to be written in them once the request events work:
script/fetch.rs FetchContext
script/dom/htmlscriptelement.rs ClassicContext
script/dom/eventsource.rs EventSourceContext
script/dom/xmlhttprequest.rs XHRContext

--

CODE THAT USES net_traits::Request:

These files touch Request but not the request body and are probably unaffected by changes to the body implementation:
net/fetch/cors_cache.rs
net/http_cache.rs
script/dom/bindings/trace.rs

net/http_loader.rs uses request bodies and will be affected by an implementation change. Mostly it passes them to http::Request, but it also assumes vec![] is a way to make an empty one.
net/fetch/methods.rs cares deeply about the nature of request bodies; step 21, for example, is commented as a placeholder that must change when they become streams of chunks.
script/dom/request.rs has some responsibility for creating request bodies and needs to be updated to create streamable ones
script/fetch.rs clones the body out of a Request to put it in a RequestBuilder, which might or might not still be correct behavior when the body involves a stream and may need thinking about
net_traits/lib.rs contains fetch_async, which may need to become more complex when requests can have streams.
</details>

--

It's likely that implementing the sense of streamable request bodies can be done with changes to just those last five files, and I will see if I can make that happen over the next few days.

**Comment by jdm** [comment]
The fact that htmlscriptelement and eventsource have TODO comments is a reflection of copy-pasting that happened; I would not expect either source to care about the request events. Otherwise, I agree with all of your notes!

**Comment by pshaughn** [comment]
https://fetch.spec.whatwg.org/#concept-body defines the idea of a body in the sense of both request and response bodies, and https://github.com/servo/servo/blob/master/components/script/body.rs defines the trait BodyOperations for things-that-have-a-body, which are just Requests and Responses.

BodyOperations currently has a leaky abstraction: it assumes that, when we synchronously take the body from the thing that has it, we get an Option<Vec<u8>>. This is fine if we're calling consume_body when we already know the data is ready to be read, but as the TODOs in consume_body show, it is not fine in the more general case.

That more general case also includes the possibility of calling .getReader() on a response body, which isn't yet possible and is commented out at the IDL level. Current response bodies support streaming from network into a big RAM buffer, but not streaming out _from_ that big RAM buffer chunk-by-chunk, so for instance a large file download via the Fetch API must hold the entire file in RAM before it can start sending it to disk. I hadn't realized this getReader functionality was missing when I started this issue.

Because of the way request and response body operations are defined together in the Fetch standard, and because response is missing some stream functionality too, I no longer believe it's a good idea to just modify request bodies without simultaneously modifying response bodies. Because I'm new to this project, I don't believe I'm yet qualified to make the larger-scale changes required to both request bodies and response bodies.

I'm updating the issue name to reflect that it applies to both responses and requests, and I am backing away from it for now to investigate other WPT failures. I might pick this issue up again in a few weeks if no one else has done so, since I think I have a decent high-level understanding of what needs to happen and I'll be more confident in my knowledge of Rust and Servo then.

**Comment by gterzian** [comment]
I think that at the end of the day this is about implementing [`ReadableStream`](https://fetch.spec.whatwg.org/#concept-readablestream), and use that for the [`body`](https://fetch.spec.whatwg.org/#bodies) of both response and requests. 

In terms of "streaming a request body", the spec actually specifies it quite precisely via the [`transmit_body`](https://fetch.spec.whatwg.org/#concept-request-transmit-body) algorithm, via would roughly correspond to https://github.com/servo/servo/blob/8abc272d27edf06840b23db79f76a4c3a6a8ed41/components/net/http_loader.rs#L362

In terms of the actually plumbing, as you pointed out you can pass a stream to `HyperRequest`, for example one could look into using https://docs.rs/hyper/0.13.0-alpha.4/hyper/struct.Body.html#method.wrap_stream, and use an IPC `ROUTER` in `net` to plug the data from script or elsewhere into the stream(see https://github.com/servo/ipc-channel/blob/master/src/asynch.rs). 

I wonder if body could literally be an enum like:

```rust
RequestBody {
    /// Essentially the current body.
    Sync(Option<Vec<u8>>),
    /// Stream variant.
    Stream(IpcReceiver<Vec<u8>>)
}
```

Then in `http_network_fetch`, in the stream case, you could call `to_stream` on the ipc receiver and add it to the hyper body. This might require a bit more plumbing to call `request_body` and `request_eof`, so it might not be so simple, yet I think there is a path to stream a request body. 

I think you could try to do this only for request at first. I think implementing `ReadableStream` for the response body could be quite different, since as you noted it is already sort of "streamed" over IPC from net to script, and making it an actual stream might require an extra layer on the script side, but perhaps not so much change in net. 

Wherease to stream a request body requires some new plumbing(as tentatively described above).

If you use something like the enum described above, you might actually get away with not changing too much at first on those `BodyOperations` method for `Request`(just return `None` for the stream at first, for example).

**Comment by gterzian** [comment]
Ok so I've looked a bit more into the streams standard, and I don't think you would need to actually implement the JS side of things, which would be quite complicated. However, you can make a start by replacing those `Vec<u8>` bodies with something that "streams" data from script to net(request body), and later from net to script(response body). So those wouldn't integrate with the javascript  with corresponding streams objects yet, however they would be the beginning of streams on the rust side of things that would be used to resolve promises in JS, or used in the `net` components to implement the streaming in Rust as it relates to the fetch spec only. 

I think the way the fetch spec uses streams is amenable to doing something only in Rust first, and not necessarily having the matching JS objects just yet. At least in limited parts, and that could already be a big step in the right direction.

**Comment by pshaughn** [comment]
That makes sense, @gterzian. Response-specific code that's currently written for a synchronous body could be updated to just panic on a stream one in the short term.

I think there are times when stream data won't even be coming from another process, for instance if it's really already in a vec<u8> but we have a reason to want to see it as a stream. For that reason, declaring them to always be IPC would be overkill and a wrapper that hides the detail whether it's IPC or not would make more sense.

I think the eventual goal state might be that a body is always acted on via the wrapper and the exposed vec<u8> ends up dropped entirely, unless there are meaningful performance implications, but an enum makes sense as the interim to minimize impact on existing code.

**Comment by gterzian** [comment]
> a wrapper that hides the detail whether it's IPC or not would make more sense

Yes one thing that can help is that the struct that is sent over IPC to `net` is a `net_traits::RequestBuilder`, containing a body, while that which is stored on the DOM request is a `net_traits::Request`. 

So the `body` of the `RequestBuilder` could always be some sort of IPC aware stream, since it is by definition sent over IPC from script to net. 

The body of the request as held on by script(the actual DOM request), could indeed be both, depending on where the body is coming from(if it's a large file, maybe it would come in chunks over IPC from the file manager). 

However, at this point, to make the DOM request body a stream, you'd have to integrate everything with the JS and basically fully implement JS readable streams. To me it looks like `RequestInit` itself, which is the actual JS binding used when calling `fetch` from JS, seems to assume body is some sort of non-stream source (see `BlobOrBufferSourceOrFormDataOrStringOrURLSearchParams`), for which you need to first build the project(although `./mach check` is enough) to generate the bindings. 

So I'd say it could be an easier first step to keep the JS side of things as it is, and to add some sort of IPC streaming from script to net, using the body of `RequestBuilder`. The "in-process" streaming of data would require fully integrating with the JS engine, I think, and that would be a bigger project that could benefit from some earlier simpler work. 

----

Having looked a bit more into streams, I think one way forward would be to implement, in Rust(so not fully integrated with JS yet), a concept of "controller" that would be in the same process as the "source", and that could be "pulled from" over IPC if necessary, or just directly accessed if in the same process. 

For example, looking at fetch, when you send the request over HTTP, you're supposed to [`transmit the body`](https://fetch.spec.whatwg.org/#concept-request-transmit-body), which means:
1. getting a reader for the body stream: https://fetch.spec.whatwg.org/#concept-get-reader
2. Reading chunks from the reader: https://fetch.spec.whatwg.org/#concept-read-chunk-from-readablestream
3. This calls in to the "pull steps" of the controller, via https://streams.spec.whatwg.org/#readable-stream-default-reader-read, which calls into https://streams.spec.whatwg.org/#abstract-opdef-pullsteps

With those "pull steps" defined as "The controller’s steps that run when a default reader is read from, used to pull from the controller any queued chunks, or pull from the underlying source to get more chunks. "

So that "should" call into the `pull` method of the JS readable stream, but I don't think this is necessary to already start implementing this in Rust and use it in fetch(although you probably would have to keep it in mind).

Instead, the controller could be just a Rust concept for new, which fetch would "pull from" over IPC.

One way to do that would be to make `RequestBuilder.body` a `Option<IpcSender<IpcSender<Vec<u8>>>`(yes that's a sender that can be used to send a sender) and have a workflow looking like:

1. In script, for example in `components/script/fetch.rs` the `Fetch` function,
2. Setup an IPC route with a receiver of type `IpcReceiver<IpcSender<Vec<u8>>`, where messages would be handled by a `FetchRequestStreamController` or similar, and store the current `Option<Vec<u8>>` onto this controller(for example if it is something, take it out and add it to a queue).  
3. When a message comes in, you use the sender in the message to send a `Vec<u8>` back, in one chunk. 
4. In fetch, inside `obtain_response`, you would create a new ipc channel, turn the receiver into a stream and pass that to hyper, and send the sender back to script using the sender in the `body` of `RequestBuilder`. 

So at that point the body is still streamed as one single chunk, but at least there is some plumbing in place to message from script to net and potentially do so in multiple chunks. 

The question then would be how to plug this `FetchRequestStreamController` into the event-loop in script so that script could enqueue chunks of `Vec<u8>` asynchronously, and those would then be forwarded over IPC. 

One way to do this would be to use a dedicated thread, instead of the IPC router, that would select on two channels: 1. the IPC channel routed to a threaded channel, 2. a threaded channel whose sender would be held somewhere in script and used to send `Vec<u8>` messages. Then whenever a message containing a `Vec<u8>` comes in, you could either buffer it internally, or immediately forward it to net over IPC, depending on whether you'd receive an IPC message from net asking for chunks yet or not. 

To make this simpler, at the cost of unnecessary IPC in the same process, you could just do everything over IPC, and simply use an enum as message that would look like:

```rust
FetchStreamMsg {
    /// Sent from net as part of `transmit_body`.
    StartStreaming(IpcSender<Vec<u8>>),
    /// Sent from script to enqueue chunks.
    EnqueueChunk(Vec<u8>),
}
```

And just use the IPC router for both messages, using a `IpcReceiver<FetchStreamMsg>`. 

So with such a controller, when `Fetch` is called by script, you would instead of storing the `Option<Vec<u8>>` on the controller directly, you would send it on a message later to be handled by the controller. That would still be in one big chunk, but there would be some more plumbing in place already to send it in smaller chunks(which would ultimately require integration with the JS).

**Comment by gterzian** [comment]
Ah so Spidermonkey actually implements stream, so it would be more about using the relevant API and then adding some glue layer for the IPC to fetch. 

here is a description of how Gecko does it for the "fetch body", we would have to do something that fits how script and net communicate instead: https://searchfox.org/mozilla-central/source/dom/fetch/Fetch.h#92

**Comment by gterzian** [comment]
Ok so the thing I don't fully understand is that the stream API from Spidermonkey would seem to require calling into from an event-loop(script), since you need to pass a js context to some of those methods, and they also return js objects. Yet fetch is done "in-parellel" to the event-loop. 

So as I described above, we would need a way for fetch to communicate back to script, via IPC, and ask it so start pulling data from the request stream so that is can be transmitted over the network in chunks. This pulling would seem to require doing on the event-loop in some way, and then sending the data back over IPC to fetch. 

it's also a question at the spec level for me, since it appears fetch is directly manipulating JS streams from "in-parallel" steps. I've asked it over at: https://github.com/whatwg/fetch/issues/976

**Comment by gterzian** [comment]
Ok so here is an actual plan of action on how to do this:

1. Do https://github.com/servo/servo/issues/21482 (the "minimum" part)

For requests:

2. If the request body is a stream, use [`ReadableStreamGetReader`](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h#L325) to get a reader.
3. Use [`ReadableStreamDefaultReaderRead`](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h#L456) to get a promise representing a chunk.
4. Define a struct that implements [`Callback`](https://github.com/servo/servo/blob/d8d70f66b1cbd156e9ff979babb84a1c5b579886/components/script/dom/promisenativehandler.rs#L15) as the native handler for that promise(this roughly corresponds to https://searchfox.org/mozilla-central/source/dom/fetch/FetchStreamReader.cpp#191).
5. When the promise resolves, from the callback, send the chunk over IPC to the net component. (To be received by an ipc-receiver turned into a futures stream and passed to hyper as the body stream as described in an earlier comment). This would also require taking the chunk out of the resolved promise, which would require some additional JS bindings as can be seen at https://searchfox.org/mozilla-central/source/dom/fetch/FetchStreamReader.cpp#230

If the body isn't a stream, the `Vec<u8>` could simply be sent over IPC in one chunk. In both cases, `RequestBuilder.body` would be an `IpcReceiver<Vec<u8>>`, to be turned into a futures stream and passed to hyper in [`obtain_response`](https://github.com/servo/servo/blob/8abc272d27edf06840b23db79f76a4c3a6a8ed41/components/net/http_loader.rs#L362)(which could be renamed to `transmit_body` with a link to the spec). 

For response bodies:

1. When first creating the `Response`: 
    - Create a rust struct that implements [`ReadableStreamUnderlyingSource`](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h#L79)
    - set the response body to a new stream created with [`NewReadableExternalSourceStreamObject`](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h#L180), passing along a pointer to the struct created at one. 
    - Store the struct on the response(it needs to live as long as the stream).
2. Each time `FetchResponseListener.process_response_chunk` is called, do:
    - call [`ReadableStreamUpdateDataAvailableFromSource`](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h#L238) on the response body, and append the chunk to an internal queue of the struct created at 1.  
    - Spidermonkey will then call into [`writeIntoReadRequestBuffer`](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h#L107), a method of the struct, inside of which you would take the previously enqueued chunk and write it into the buffer received as an argument. 

I don't think the DOM response needs the `ResponseBody` from `net_traits`, so the DOM response body could just always be a stream. I think the above doesn't require changing the use of `ResponsBody` inside `net`, since that is used internally in that component and chunks are ultimately sent back to script over IPC.

This describes how to plug the JS stream into the script <-> net communication happening over IPC. There would be some additional work required to update `BodyOperations` and other stuff in `script/body.rs` to further integrate streams into the various workflows, which could be done by using the various functions in: https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/public/Stream.h

For the request body, a stream would be provided by the JS, for the response body, you would provide a stream to the JS and back it with a struct implementing `ReadableStreamUnderlyingSource`. 

A lot of details have been ommitted, some of which would be revealed by a complaining compiler when trying to implement the above. 

Note that there is a ton of stuff implementing `FetchResponseListener`, so this could turn into a pretty big refactoring.

**Comment by gterzian** [comment]
I've ended-up addressing this in broad-lines as part of https://github.com/servo/servo/pull/25873

There are still quite some a few tests failing, I think because there is quite a lot of business logic and not everything was done in that PR yet, and there are also some related things like "Consume request's body as json" that do not work and might relate to the streaming itself but rather other algorithms used as part of consuming bodies.
