### ISSUE TITLE
Implement DOMTokenList.supports API

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24965]
html/semantics/embedded-content/the-iframe-element/sandbox-ascii-case-insensitive incidentally fails, separately from what it's trying to test, because there's no .supports on iframe.sandbox. It looks like Servo's IDL doesn't even mention it; https://dom.spec.whatwg.org/#interface-domtokenlist does.

**Comment by pshaughn** [comment]
html/semantics/document-metadata/the-link-element/link-rellist.html also wants .supports.

**Comment by pshaughn** [comment]
Every attribute that can be the associated attribute of a DOMTokenList defines a set of "supported tokens" for use in feature-sniffing, e.g. https://html.spec.whatwg.org/multipage/forms.html#attr-form-rel defines them for the rel attribute of a form and https://html.spec.whatwg.org/#attr-hyperlink-rel defines slightly different ones for the rel attribute of an anchor. Since the purpose is feature-sniffing, we're explicitly only supposed to include the ones the browser actually implements, not ones that we'd be ignoring; it might be desirable to have some well-defined way of keeping it in sync with implementation progress.

**Comment by jdm** [comment]
To represent the [validation steps](https://dom.spec.whatwg.org/#concept-domtokenlist-validation) when there is a static list of supported keywords, we should add a new optional argument to DOMTokenList::new (`&'static [&'static str]`). Whenever `DOMTokenList::new` is called for the following token lists, the caller should provide the list as an argument.

* HTMLAnchorElement.relList: keyword list ("noopener", "noreferrer", "opener")
* HTMLLinkElement.relList: keyword list ("alternate", "stylesheet", "icon", "apple-touch-icon")
* Element.classList: no list
* HTMLAreaElement.relList: keyword list (empty list)
* HMTLIFrameElement.sandbox: keyword list ("allow-same-origin", "allow-forms", "allow-pointer-lock", "allow-popups", "allow-scripts", "allow-top-navigation")

When implementing DOMTokenList::supports, if no list was provided then any we should compare the provided token against the tokens in the element's attribute. Otherwise, we should use the list of provided tokens from the constructor and compare the provided token against that.

Spec:
* https://dom.spec.whatwg.org/#dom-domtokenlist-supports
* https://dom.spec.whatwg.org/#ref-for-dom-domtokenlist-supports

Code:
* `components/script/dom/webidls/DOMTokenList.webidl`
* `components/script/dom/domtokenlist.rs`

Tests:
* `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/rellist-feature-detection.html`
* `./mach test-wpt tests/wpt/web-platform-tests/html/dom/idlharness.https.html`

We'll need to update the corresponding INI files (`tests/wpt/metadata/html/semantics/rellist-feature-detection.html.ini`, `tests/wpt/metadata/html/dom/idlharness.https.html.ini`) to remove the expected failures after fixing this.

**Comment by jdm** [comment]
This should also fix https://github.com/servo/servo/issues/27251 and https://github.com/servo/servo/issues/25769.

**Comment by Nicklas-Carpenter** [comment]
I've looked into this issue a bit and would be willing pick it up.

**Comment by ghostd** [comment]
Hi @Nicklas-Carpenter 

Are you still working on this issue? Otherwise, i'd like to provide a PR. Let me know :)

Regards

**Comment by Nicklas-Carpenter** [comment]
> Hi @Nicklas-Carpenter 
> 
> Are you still working on this issue? Otherwise, i'd like to provide a PR. Let me know :)
> 
> Regards

Go ahead and make the PR.

**Comment by ghostd** [comment]
Hi @jdm 

I have a partial working implementation, but i have some questions:
* according to the [test](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/semantics/rellist-feature-detection.html#L26), the HTMLAreaElement.relList should have the same content than HTMLAnchorElement.relList, but in [your comment](https://github.com/servo/servo/issues/24965#issuecomment-657644521) you indicate we should set an empty list. So, should i update the code or the test? :)
* can you explain why "if no list was provided then any we should compare the provided token against the tokens in the element's attribute."? the specification seems [expect a TypeError](https://dom.spec.whatwg.org/#concept-domtokenlist-validation) if no list is provided and 'supports' is called

**Comment by jdm** [comment]
You're right that we should throw a TypeError if there is no list of supported tokens provided. I'm not sure why I claimed otherwise in my previous comment. As for HTMLAreaElement.relList, the standard doesn't define a list of supported tokens but it makes sense that it would match the one for HTMLAnchorElement.

**Comment by jdm** [comment]
My mistake, the spec does define them at https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-rel and https://html.spec.whatwg.org/multipage/links.html#linkTypes.
