### ISSUE TITLE
el.toggleAttribute("style") after assigning to el.style returns true instead of false

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25130]
WPT dom/nodes/attributes.html tests toggleAttribute in many situations, most of which pass, but "Toggling element with inline style should make inline style disappear" fails. It's actually just testing what toggleAttribute returns and not strictly testing whether the style has disappeared or not, but the return value of toggleAttribute should definitely be false here. Special things I can see here to distinguish this case from passing ones are that this test is using .style= instead of setAttribute, and that style might be the only [PutForward] attribute in the entire test.

**Comment by pshaughn** [comment]
When we .style= in
https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/dom/nodes/attributes.html#L142
we see None returned by GetAttribute in
https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1906

If we setAttribute("style") instead of .style=, then the test passes as written, but the type returned by GetAttribute is DOMSTring, not CSSStyleDeclaration; it's like the content attribute isn't connected to either the IDL type or to the Javascript object attribute.

Setting el.style as it is in the test, and then reading back el.style from Javascript, gets a CSSStyleDeclaration, so the IDL attribute is there on the Javascript DOM element, but seemingly entirely separately from get/set/toggleAttribute.

**Comment by jdm** [comment]
Oh! https://github.com/servo/servo/blob/33de38aa85a2c84228d9a3b15ef012b31a1867ec/components/script/dom/webidls/ElementCSSInlineStyle.webidl#L9 has the PutForwards commented out and the attribute is readonly, so there _is_ no code that handles setting the style IDL property right now. Setting the content attribute works because of [this code](https://github.com/servo/servo/blob/a5c368fd0115527aaaa555641d292be43258a6ef/components/script/dom/element.rs#L2688-L2694).

**Comment by jdm** [comment]
I am astounded that we apparently haven't had a working style setter in 7 years.

**Comment by pshaughn** [comment]
Fixed by #25450
