### ISSUE TITLE
Implement MessageEvent.initMessageEvent

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25192]
This is expected by WPT html/webappapis/scripting/events/messageevent-constructor.https.html and has IDL in https://html.spec.whatwg.org/multipage/comms.html#the-messageevent-interface

**Comment by jdm** [comment]
Code: `components/script/dom/messageevent.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/webappapis/scripting/events/messageevent-constructor.https.html

**Comment by kunalmohan** [comment]
I would like to try and solve this one.
@highfive: assign me

**Comment by kunalmohan** [comment]
I am having trouble initializing variables which are DOMString type. How should I get past it?

**Comment by jdm** [comment]
@kunalmohan Are you using DOMString::new() for an empty string and DOMString::from(...) to create a DOMString from an existing Rust string value?

**Comment by kunalmohan** [comment]
I have defined the function as
```
fn InitMessageEvent(
        &self,
        _cx: JSContext,
        type_: DOMString,
        bubbles: bool,
        cancelable: bool,
        data: HandleValue,
        origin: DOMString,
        lastEventId: DOMString,
        source: Option<WindowProxyOrMessagePortOrServiceWorker>,
        ports: Vec<DomRoot<MessagePort>>
    )
```

I am not taking `origin` and `lastEventId` as string because then I get the following error:
```
method `InitMessageEvent` has an incompatible type for trait
```

**Comment by jdm** [comment]
What is the trouble you are having with initialization, in that case?

**Comment by kunalmohan** [comment]
Actually it's not just the DOMString.
First, I cannot initialize a key like `self.[key]=value` because `self is not mutable reference`. But initializing it using `*self.[key]=value` gives the error `doesn't have size known at compile time` for `lastEventId`, `ports` and `origin`.
Second, I cannot figure out why the statements `*self.origin=origin` (and same for `lastEventId`) are giving the error
 ```
expected `str`, found struct `dom::bindings::str::DOMString`
```
for the values obtained as parameters.

**Comment by jdm** [comment]
Ah. You will need to put the members that need to be reinitialized inside DOMRefCell or Cell values. These allow mutating the values inside of methods that take &self instead of &mut self, like all of our DOM APIs. As for the str vs. DOMString error, that also surprises me. See if it goes away when you use the appropriate DOMRefCell/Cell wrappers?

**Comment by kunalmohan** [comment]
Okay, I'll use the DOMRefCell/Cell wrappers. Would there be a need to edit other functions for the `MessageEvent` struct after implementing the wrappers?

**Comment by jdm** [comment]
Any method that uses the members that are now wrapped in cells will need to be adjusted in order to compile, yes.

**Comment by kunalmohan** [comment]
That was quite helpful. Thanks :)
