### ISSUE TITLE
is_cors_safelisted_request_header is implemented twice, with differences

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25235]
script/dom/headers.rs has one that takes name:&str and value:&[u8], which is called from the DOM Request constructor only when a request init's mode is explicitly set to no-cors. 

net/fetch/methods.rs has one that takes name:&HeaderName and value:&HeaderValue, which is called routinely as part of the "main fetch" algorithm.

Due to the different data types, unifying them isn't as simple as I'd like it to be, but it's obviously the right thing to do. Neither is currently implementing the full specification logic, possibly due to specification changes since they were written.

**Comment by jdm** [comment]
Since HeaderName has a [as_str](https://docs.rs/http/0.2.0/http/header/struct.HeaderName.html#method.as_str) method and has a [as_bytes](https://docs.rs/http/0.2.0/http/header/struct.HeaderValue.html#method.as_bytes) method, we should probably make the official implementation rely on &str and &[u8] and have it live in net_traits, so that it's accessible from both net and script.

**Comment by pshaughn** [comment]
Thank you! I was unifying them into net/fetch/methods and just about to ask why I couldn't import them from there into script/dom/headers.
