### ISSUE TITLE
Implement form dirname

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25379]
https://html.spec.whatwg.org/#constructing-form-data-set 5.13 is tested in a few WPT cases under html/semantics/forms/attributes-common-to-form-controls/ ; the idea here is that if an element has a "dirname" attribute, that attribute's value names an additional synthetic form submit datum with value "ltr" or "rtl" depending on the element's directionality as sniffed by https://html.spec.whatwg.org/multipage/dom.html#the-directionality

https://github.com/servo/servo/blob/8002c6bc53041c55dc1148fed008b9a229df0e9b/components/script/dom/htmlformelement.rs#L931-L932

**Comment by NeverHappened** [comment]
Can I take this one?

**Comment by jdm** [comment]
You're welcome to it! You will need to:
* add the dirName IDL attribute in HTMLInputElement.webidl, and corresponding getter/setter macros in htmlinputelement.rs
* implement the directionality algorithm as a function in htmlformelement.rs
* replace the TODO in htmlformelement.rs about handling dirnames

**Comment by NeverHappened** [comment]
Hey, @jdm!

I've started doing the changes..
Not yet finished.

If can, please review my PR and say if I'm on the right track

**Comment by jdm** [comment]
Yes, that looks like what I expected to see :)

**Comment by NeverHappened** [comment]
Hey!
I've mostly done with this MR.

There are few problems I still need to resolve somehow:
- Element#directionality not tested and not used anywhere, because it was just an implementation of  https://html.spec.whatwg.org/#the-directionality. I probably can delete it or save it in other branch if this code will be needed for something else.
- wpt test only passes with timeout set (this relates to issue with iframes) https://github.com/servo/servo/issues/24828
- my macbook don't build in dev mode on new master :(

**Comment by jdm** [comment]
#25499 has tests that don't include any timeouts; am I missing something?

**Comment by pshaughn** [comment]
I believe the timeout referred to was a workaround for the about:blank double load event. NeverHappened originally used a timeout to get the tests working, and then revised them to explicitly check for about:blank loads like in other tests.
