### ISSUE TITLE
Extract HTMLConstructor handling from CGClassConstructHook

### ISSUE THREAD

**Issue by jdm** [servo/servo#25395]
There's a big block of "generated" Rust code in CGClassConstructHook in CodegenRust.py which should be extracted into a helper method in a file like components/script/dom/bindings/utils.rs instead. Currently we end up with a lot of duplicated code in many files, and we could instead just generate a single call to the new helper method instead.

No need to run any tests; if the result compiles, that's good enough for a pull request.

Code: `components/script/dom/bindings/codegen/CodegenRust.py`

**Comment by warren-fisher** [comment]
@highfive: assign me
I will work on this over the next couple of days.

**Comment by warren-fisher** [comment]
I have made some initial work on this but I am stuck on dealing with the unknown types. I extracted some of it to a [function in utils.rs](https://github.com/warren-fisher/servo/commit/ad750483bb8156a44d5b044e05ab0b29b4baed8c#diff-fa2a9cd0e53132e0b95fdb0d37d0662cR626-R670) but I do not know how to deal with `global` variable which is [initialized earlier](https://github.com/warren-fisher/servo/blob/ad750483bb8156a44d5b044e05ab0b29b4baed8c/components/script/dom/bindings/codegen/CodegenRust.py#L5665) in `CodegenRust.py`. Since its type is variable I cannot pass it as a function argument. Perhaps the best course of action is to also leave this part alone and in `CodegenRust.py`. As it stands this would mean not a lot of code could be extracted to `utils.rs`.

**Comment by warren-fisher** [comment]
I am having trouble with this. Here is what my [CodegenRust.py](https://github.com/warren-fisher/servo/blob/52a7378e0a3ad2a4ea06d81196d51d107c8d3ab2/components/script/dom/bindings/codegen/CodegenRust.py#L5643-L5679) and [utils.rs](https://github.com/warren-fisher/servo/blob/master/components/script/dom/bindings/utils.rs#L631-L689) look like at the moment. 

Initially I have copied most of the big block of code in the CGClassConstructHook into a helper function in utils.rs and resolved any missing dependencies. I attempted to use generic traits and the turbofish operator in replacement of the string formatting for the [type declaration](https://github.com/warren-fisher/servo/blob/52a7378e0a3ad2a4ea06d81196d51d107c8d3ab2/components/script/dom/bindings/utils.rs#L674) of result. The compiler gave me this error and a few other similar errors for other methods

> error[E0599]: no method named `upcast` found for type `U` in the current scope
>    --> components/script/dom/bindings/utils.rs:642:40
>     |
> 642 |         throw_dom_exception(cx, global.upcast::<GlobalScope>(),
>     |                                        ^^^^^^ method not found in `U`
>     |
>     = help: items from traits can only be used if the type parameter is bounded by the trait
> help: the following trait defines an item `upcast`, perhaps you need to restrict type parameter `U` with it:
>     |
> 631 | pub fn html_constructor_handling<T, U: dom::bindings::inheritance::Castable>(cx: SafeJSContext, args: CallArgs, global: U) -> bool {

Now I have realized that it seems like the early returns are necessary so some functions / methods are only called if certain criteria are met. Implementing the trait bounds for the helper function I created did not help because then it meant more compiler errors are received for when any of the generated code does not implement those traits. Presumably this was not a problem because early-returns meant this was never dealt with, but now I am not sure that the method I have taken is appropriate due to the way generics work in Rust.

**Comment by jdm** [comment]
You should be able to take a &GlobalScope argument instead of the second generic. Does that help?

**Comment by warren-fisher** [comment]
I am not sure that is working. I removed that generic and set it as a &GlobalScope argument and I receive these errors (among many other similar errors). 

> error[E0308]: mismatched types
>     --> /home/warren/programming/servo-self/target/debug/build/script-e947c18a24273ccd/out/Bindings/HTMLAnchorElementBinding.rs:2351:108
>      |
> 2351 |         let r = dom::bindings::utils::html_constructor_handling::<dom::types::HTMLAnchorElement>(cx, args, global);
>      |                                                                                                            ^^^^^^ expected `&dom::globalscope::GlobalScope`, found struct `dom::bindings::root::Root`
>      |
>      = note: expected reference `&dom::globalscope::GlobalScope`
>                    found struct `dom::bindings::root::Root<dom::bindings::root::Dom<dom::window::Window>>`

> error[E0308]: mismatched types
>    --> /home/warren/programming/servo-self/target/debug/build/script-e947c18a24273ccd/out/Bindings/HTMLAreaElementBinding.rs:815:106
>     |
> 815 |         let r = dom::bindings::utils::html_constructor_handling::<dom::types::HTMLAreaElement>(cx, args, global);
>     |                                                                                                          ^^^^^^ expected `&dom::globalscope::GlobalScope`, found struct `dom::bindings::root::Root`
>     |
>     = note: expected reference `&dom::globalscope::GlobalScope`
>                   found struct `dom::bindings::root::Root<dom::bindings::root::Dom<dom::window::Window>>`

I believe that was why I made it a generic in the first place. As can be seen sometimes it is a big nested type or simpler variations as that. I think that this probably arises from [this preamble ](https://github.com/servo/servo/blob/afa1b85766caeb55254b739529aef205f04d3585/components/script/dom/bindings/codegen/CodegenRust.py#L5665) if the exposureSet has a len(1), but I am not sure of the greater context of this code. I will test to see if this works for scenarios when the exposureSet does not have len(1).

**Comment by jdm** [comment]
I think it should be possible to pass `global.upcast()`, or possibly `(&*global).upcast()`. Any global object there will be possible to upcast to GlobalScope, whether it's a Window/WorkerGlobalScope/GlobalScope object inside of a `Root<Dom<T>>` wrapper.

**Comment by jdm** [comment]
Actually, we should be able to take a &Window argument instead of &GlobalScope, and then we should be able to pass &*global directly.

**Comment by warren-fisher** [comment]
That did fix my problem and now I've greatly reduced the number of compiler errors. One error I am unsure about is this: 

> 
> error[E0425]: cannot find function, tuple struct or tuple variant `GetProtoObject` in this scope
>    --> components/script/dom/bindings/utils.rs:666:13
>     |
> 666 |             GetProtoObject(cx, RawHandle::from(global_object.handle()), RawMutableHandle::from(prototype.handle_mut()));
>     |             ^^^^^^^^^^^^^^ not found in this scope
>     |
> help: possible candidates are found in other modules, you can import them into scope
>     |
> 7   | use crate::dom::bindings::codegen::Bindings::ANGLEInstancedArraysBinding::ANGLEInstancedArraysBinding::GetProtoObject;
>     |
> 7   | use crate::dom::bindings::codegen::Bindings::AnalyserNodeBinding::AnalyserNodeBinding::GetProtoObject;
>     |
> 7   | use crate::dom::bindings::codegen::Bindings::AttrBinding::AttrBinding::GetProtoObject;
>     |
> 7   | use crate::dom::bindings::codegen::Bindings::AudioBufferBinding::AudioBufferBinding::GetProtoObject;
>     |
>       and 360 other candidates

Which stems from [this line](https://github.com/warren-fisher/servo/blob/33ebe366cd92baa861d1ed9828f901a2dfabcf2a/components/script/dom/bindings/utils.rs#L666). It seems that this method is implemented differently within each bindings file so it does not seems possible to import it for the entire utils.rs file. I am not sure how to tackle this problem.

Another problem I have is with trait bounds. I received these two somewhat related errors:

> 
> error[E0277]: the trait bound `T: dom::bindings::reflector::DomObject` is not satisfied
>    --> components/script/dom/bindings/utils.rs:676:17
>     |
> 633 | pub fn html_constructor_handling<T>(cx: SafeJSContext, args: CallArgs, global: &Window) -> bool {
>     |                                  - help: consider restricting this bound: `T: dom::bindings::reflector::DomObject`
> ...
> 676 |     let result: Result<DomRoot<T>, Error> = html_constructor(&global, &args);
>     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `dom::bindings::reflector::DomObject` is not implemented for `T`
>     | 
>    ::: components/script/dom/bindings/root.rs:50:1
>     |
> 50  | pub struct Root<T: StableTraceObject> {
>     | ------------------------------------- required by `dom::bindings::root::Root`
>     |
>     = note: required because of the requirements on the impl of `dom::bindings::root::StableTraceObject` for `dom::bindings::root::Dom<T>`
> 
> error[E0277]: the trait bound `T: dom::bindings::conversions::DerivedFrom<dom::element::Element>` is not satisfied
>    --> components/script/dom/bindings/utils.rs:676:45
>     |
> 633 | pub fn html_constructor_handling<T>(cx: SafeJSContext, args: CallArgs, global: &Window) -> bool {
>     |                                  - help: consider restricting this bound: `T: dom::bindings::conversions::DerivedFrom<dom::element::Element>`
> ...
> 676 |     let result: Result<DomRoot<T>, Error> = html_constructor(&global, &args);
>     |                                             ^^^^^^^^^^^^^^^^ the trait `dom::bindings::conversions::DerivedFrom<dom::element::Element>` is not implemented for `T`
>     | 
>    ::: components/script/dom/bindings/htmlconstructor.rs:91:15
>     |
> 91  | pub unsafe fn html_constructor<T>(window: &Window, call_args: &CallArgs) -> Fallible<DomRoot<T>>
>     |               ----------------
> 92  | where
> 93  |     T: DerivedFrom<Element>,
>     |        -------------------- required by this bound in `dom::bindings::htmlconstructor::html_constructor`

These stem from [here](https://github.com/warren-fisher/servo/blob/33ebe366cd92baa861d1ed9828f901a2dfabcf2a/components/script/dom/bindings/utils.rs#L676). I tried bounding the generic type T to these traits but then it meant that many errors occurred during `./mach build --dev` because my method html_constructor_handling was being called for types that do not implement these traits. Perhaps the best course of attack would be to return a Optional prototype right before the `let result: Result<DomRoot<T>, Error> = html_constructor...`, and to place this part back into CodegenRust.py. I will try that and see how it goes.

**Comment by jdm** [comment]
It's not clear to me why `T: DomObject + DerivedFrom<Element>` would not work. What are the precise errors that you get with a bound like that?

**Comment by jdm** [comment]
Oh, and about GetProtoObject - I think you will need to pass the generated GetProtoObject as a  function pointer argument like this: `GetProtoObject: fn(SafeJSContext, HandleObject, MutHandleObject)`.

**Comment by warren-fisher** [comment]
Appears that I had mistakenly put StableTraceObject as the trait and not DomObject. I have now fixed all the errors and it compiles. Thanks for all your help. I will submit a pull request shortly.
