### ISSUE TITLE
Try making creation of GPUBuffer async(even without a promise)

### ISSUE THREAD

**Issue by gterzian** [servo/servo#25472]
When a buffer is created at https://github.com/servo/servo/blob/4ae3c8bc6d8a3af51ab3e78464f93e0ea592c51c/components/script/dom/gpudevice.rs#L166

The script-thread blocks on the IPC response from the WebGPU component at https://github.com/servo/servo/blob/4ae3c8bc6d8a3af51ab3e78464f93e0ea592c51c/components/script/dom/gpudevice.rs#L191

Instead, I think you could make it non-blocking. 

First of all, why doesn't the spec use a promise? 

Secondly, even without a promise, you can still do it(I think), in the following way:

1. Use a pattern similar to [`response_async`](https://github.com/servo/servo/blob/4ae3c8bc6d8a3af51ab3e78464f93e0ea592c51c/components/script/dom/gpu.rs#L67), but without the promise(Basically just use an IPC route and a `Trusted<GPUBuffer>`). 
2. Make `GPUBuffer.buffer` optional inside a dom refcell.
3. Add a `DomRefCell<VecDeque<BufferCommands>>` to `GPUBuffer`. 

With `BufferCommand` being something like:
```rust
enum BufferCommand {
    UnMap,
    Destroy,
}
```

Then, when you create the buffer, just return it immediately without blocking on the IPC, setting the buffer to `None`. 

As long as the buffer is none, you queue any `WebGPURequest` as a corresponding `BufferCommand`.

When the buffer is received from WebGPU, you, via a task via a task queued from the IPC route(similar to `response_async`):
- Set the buffer to some.
- Drain the buffer of `BufferCommand` and send corresponding `WebGPURequest` in order to WebGPU. 

This would appear spec compliant in the light of the note at https://gpuweb.github.io/gpuweb/#buffer-destruction

> Note: This allows the user agent to reclaim the GPU memory associated with the GPUBuffer once all previously submitted operations using it are complete.

Which I read as saying that you can indeed queue requests, even if one of them is the destruction of the buffer, so long as you submit them in order at some point to WebGPU for processing. 

@kvark @zakorgy

**Comment by kvark** [comment]
> First of all, why doesn't the spec use a promise?

Spec tries to reduce the use of promises in order to ease up transition for the current users of native GPU APIs (which are generally fully sync). For buffer creation, no blocking is expected. The object is returned immediately. If there is an error, the object will become invalid, and all operations done with it will be invalid: https://gpuweb.github.io/gpuweb/#invalid-objects

**Comment by gterzian** [comment]
Ok thanks for the info.

So it might be worth it to try to make the object "internally async" as described and while returning it immediately when created, initially buffering operations until the "buffer" is received, although it might also not be due to the extra complexity.

**Comment by kvark** [comment]
To clarify, the expected behavior of the object creation is:
  1. content side allocates a new ID, associated with the JS object it returns (immediately)
  2. content side sends a request to the GPU process to create a buffer and associate with this ID
  3. when the GPU process gets to it, it associates internally this ID with the new buffer. If an error occurs, it communicates (asynchronously) that to the content side.
