### ISSUE TITLE
ignore_malloc_size_of in NodeIterator and HTMLCollection points at closed issue #6870

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25682]
Since #6870 was resolved I tried taking out the ignore_malloc_size_of lines here, but we still seem to need them. I might not understand what's really happening here, but it looks like the NodeIterator one involves an `Rc<NodeFilterBinding::NodeFilter>`, which seems like the kind of thing 6870 was supposed to fix. The HTMLCollection one involves a `Box<dyn CollectionFilter + 'static>` which seems like it probably has to stay ignore_malloc_size_of since the CollectionFilter trait could be hiding anything as far as the compiler knows. The sensible thing to do in the latter case might just be to clean up the comment and leave the ignore on, but the former could point at something to fix in the macros.

**Comment by wulanseruniati** [comment]
Hi!
I'd like to work on cleaning up the memory size measurement for both NodeIterator and HTMLCollection. I’ve noticed that while issue #6870 was resolved, there are still ignore_malloc_size_of lines that seem necessary due to the nature of the structures involved.

For HTMLCollection, the Box<dyn CollectionFilter> likely needs to retain the ignore annotation, since trait objects are unsized and can't be accurately measured by the current tool. I’ve cleaned up the comment to clarify that this is expected behavior.

For NodeIterator, the Rc<NodeFilter> presents a shared ownership scenario where accurate size measurement is also difficult, so keeping the ignore_malloc_size_of annotation makes sense here as well. I’ve updated the comment to reflect this.

Please let me know if this approach seems good or if there are any further changes you'd like to see!
Thanks!
