### ISSUE TITLE
Text is not wrapped around div with replaced content in layout_2020

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#25709]
In the following test case the text appears on top of the div, but it should really be positioned under it.

```
<div><img style="background: pink; width: 100px; height: 100px;"></div>
<p>this should be under</p>
```

Output:
![Screenshot from 2020-02-07 16-32-07](https://user-images.githubusercontent.com/13536/74042230-6fb9f980-49c7-11ea-997f-b504ee03d059.png)

**Comment by mrobinson** [comment]
cc @SimonSapin

**Comment by SimonSapin** [comment]
This `<img>` element has the initial `display: inline`, so it ends being part of a line box. It looks like the height of that line box incorrectly ends up being zero. Since the element doesn’t have an `src` attribute I’m not sure what kind of box it ends up generating. Either way, the bug likely a missing `something.max_block_size_of_fragments_so_far.max_assign(something)` somewhere in `components/layout_2020/flow/inline.rs`
