### ISSUE TITLE
DLL file `api-ms-win-crt-runtime-l1-1-0.dll` not found!

### ISSUE THREAD

**Issue by shreyarastogi** [servo/servo#25787]
shrey@LAPTOP-L08HN83K MINGW64 /c/Users/shrey/servo (master)
$ ./mach build --dev
warning: Error finalizing incremental compilation session directory `\\?\C:\Users\shrey\servo\target\debug\incremental\canvas_traits-aj1987kq9sua\s-fkbu5d627i-159yjr0-working`: Access is denied. (os error 5)

warning: method `Constructor` should have a snake case name
  --> components\script\dom\doge.rs:34:8
   |
34 | pub fn Constructor(global: &GlobalScope, init: Option<DogeInit>) -> Fallible<DomRoot<Doge>> {
   |        ^^^^^^^^^^^ help: convert the identifier to snake case (notice the capitalization): `constructor`
   |
   = note: `#[warn(non_snake_case)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 9.22s
Packaging EGL DLLs
Packaging gstreamer DLLs
Packaging MSVC DLLs
DLL file `api-ms-win-crt-runtime-l1-1-0.dll` not found!
Build FAILED in 0:00:09

facing this error, took help from google but haven't been able to solve it.

**Comment by jdm** [comment]
MINGW isn't a supported environment. What happens if you open a regular windows terminal window and run `mach build --dev`?

**Comment by shreyarastogi** [comment]
It is building in a regular windows terminal window. I opened Command prompt in VS code itself and it is getting built there. So what do you suggest, I shouldn't build it using the bash terminal?

**Comment by jdm** [comment]
If the terminal is running bash, it's not a regular terminal window. Only the windows command prompt environment is supported; you can launch it by running "cmd" from the windows start menu search.

**Comment by Darkspirit** [comment]
I followed the steps from https://github.com/servo/servo#on-windows-msvc and got the same error.
(Chocolatery + Gstreamer 1.16.**2** + without "troubleshooting" + had to remove LLVM-9.0.0-win64.exe because of mozjs_sys failure)
Powershell: `./mach build -d`, cmd: `.\mach build -d`

---

https://github.com/servo/servo#on-windows-msvc
> If you got the error DLL file api-ms-win-crt-runtime-l1-1-0.dll not found! then set the WindowsSdkDir environment variable to an appropriate Windows Kit directory containing Redist\ucrt\DLLs\x64\api-ms-win-crt-runtime-l1-1-0.dll, for example C:\Program Files (x86)\Windows Kits\10.

`$env:WindowsSdkDir="C:\Program Files (x86)\Windows Kits\10"; ./mach build -d`
only worked after changing 
https://github.com/servo/servo/blob/8f3622af35a391b1d15ec1768aa90721ebc5396e/python/servo/build_commands.py#L1006-L1007

to
```
import glob
redist_dirs += glob.glob(path.join(os.environ["WindowsSdkDir"], "Redist", "*", "ucrt", "DLLs", vs_platform))
```

because the correct path is C:\Program Files (x86)\Windows Kits\10\Redist\\**10.0.17763.0**\ucrt\DLLs\x64\api-ms-win-crt-runtime-l1-1-0.dll.

**Comment by jdm** [comment]
I worked around the problem by running `mach build -d` inside of a Visual Studio command prompts, rather than the stock Windows command prompt.

**Comment by mrobinson** [comment]
I think this can be closed because many changes have been made to the Windows build setup since it was opened.
