### ISSUE TITLE
Back button on Chrome triggers download

### ISSUE THREAD

**Issue by chchang6** [servo/servo#25909]
Not sure where or how to report this. I'm using the DDG Privacy Essentials extension in Chrome 80.0.3987.122 on OSX Catalina. I have little correlation to go on, but now and again (at least once a day), when I hit the Back button in Chrome, instead of changing the page a download starts. I usually kill it immediately, but today let it complete. It a small binary (2304 B), with some textual header info. Unfortunately I deleted that file from the CLI. 

Has anyone else heard of anything similar? If I can replicate, will add more and run it through some kind of malware scanner.

**Comment by CYBAI** [comment]
Hi @chchang6 , thanks for reporting issue. Unfortunately, here is the repo for [Servo](https://servo.org) browser engine instead of Chrome.

For Chromium issue, I think you can file issue from crbug.com and they might be able to answer your question :)

So, I'm going to close this issue due to not related to Servo.

**Comment by chchang6** [comment]
Thanks so much, and sorry for the cluelessness!
