### ISSUE TITLE
Pop WebRender reference frames in layout 2020

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#26066]
Followup of #26063

I'm not familiar with layout 2020, but I think all we need to do is call `pop_reference_frame` at the end of the function if the following returns true: https://github.com/servo/servo/blob/687156ac90d0cead80e89b63b9394d1a6f7a808e/components/layout_2020/display_list/stacking_context.rs#L477-L478

cc @mrobinson @dralley

**Comment by dralley** [comment]
Can I suggest a small refactor?

```build_reference_frame_if_necessary()``` currently has a bunch of side effects, one of which is pushing the reference frame, and returns a boolean if it did.  It's only used in one place.  How about it returns an option containing the reference frame instead, and we move the side effects to ```build_stacking_context_for_children```?

That way the push and pop would be happening in the same function.

**Comment by mrobinson** [comment]
I *think* that `pop_reference_frame` is only necessary to adjust mapping of stacking context coordinates to reference frame coordinates. Since Layout 2020 only uses reference frame coordinates, it shouldn't be necessary to include this in the display list.

On the other hand, now that Layout 2020 is using reference frame coordinates everywhere, it raises the question of whether or not Layout 2013 and Gecko should as well. This would have the benefit of allowing the removal of the coordinate space mapper from `scene_building.rs` and removing the `PopReferenceFrame` display item. Spatial nodes are allowed to have children in various places in the display list, not just hierarchically so I have some doubts about the coordinate mapping anyhow. Thoughts @dralley?

The refactor that you are suggesting probably makes sense either way.

**Comment by dralley** [comment]
Ah, sorry, I deleted that comment after thinking about it some more.  Old-layout passed around intermediate objects and I didn't immediately recognize that ```push_reference_frame``` was a function with many-argument signature rather than doing as old-layout did -- once I recognized that, the refactor idea didn't make as much sense, or at least would require a bit more work.
