### ISSUE TITLE
Did we forget x86?

### ISSUE THREAD

**Issue by vixalien** [servo/servo#26187]
Hello !

I have been amazed with servo, the problem is, I can't install it because I have an (old) 32 bit (x86) computer (and I don't have ways to upgrade now) that can't install anything like rust so I can built servo myself and the files at [the download server](download.servo.org) are all for 64-bit machines.

Can we build servo for 32-bit machines, too ?

Any alternative solution available ?

**Comment by jdm** [comment]
There are no 32 bit builds available, sorry.

**Comment by reekotubbs** [comment]
Will x86 be developed at all? Missing the love on Hololens Gen 1.

**Comment by jdm** [comment]
We used to support x86 Windows builds, but we [removed them](https://github.com/servo/servo/pull/23712#issuecomment-509277383) from our CI because they weren't useful for our needs, and required additional troubleshooting when we were integrating media support for Windows. At this point we are not expecting to spend time supporting gen 1 HoloLens devices.

**Comment by reekotubbs** [comment]
Sorry to hear that. Thanks.
