### ISSUE TITLE
libsimpleservo docs aren't present on doc.servo.org

### ISSUE THREAD

**Issue by jdm** [servo/servo#26235]
We chould generate the docs with a `--libsimpleservo` build, but that would cut out the docs from ports/glutin. It would be nice if there were a way to merge the two builds somehow.

**Comment by SimonSapin** [comment]
What happens if we run both `cargo doc` commands? I expect files that have the same path and name will be overwritten by the second command, but no file will be deleted. (Note that `cargo doc` shares compiler artifacts with `cargo check` but not with `cargo build`.)

It’d be easiest to try locally because CI doesn’t (by default) upload docs anywhere easily browsable unless a PR is merged into `master`, but once we have a series of commands that produces the desired output it can be put here to change https://doc.servo.org/:

https://github.com/servo/servo/blob/4c4f5881785a293642d7c4a8a815f0411012e267/etc/taskcluster/decision_task.py#L204

**Comment by mrobinson** [comment]
I think there's no longer a separate libsimpleservo. It's integrated into the minibrowser now.
