### ISSUE TITLE
Implement EXT_frag_depth extension

### ISSUE THREAD

**Issue by jdm** [servo/servo#26341]
https://www.khronos.org/registry/webgl/extensions/EXT_frag_depth/

There are no new constants or APIs. All it requires is checking if the underlying extension is supported, which we should be able to copy from Gecko: https://searchfox.org/mozilla-central/source/dom/canvas/WebGLExtensionFragDepth.cpp#19-29

**Comment by jdm** [comment]
This is used by https://threejs.org/examples/webxr_vr_lorenzattractor.html.

**Comment by jdm** [comment]
We will also need to enable the EXT_frag_depth field of https://github.com/servo/servo/blob/master/components/script/dom/webglshader.rs#L224 as well.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/22112 is a good model showing how to implement a new WebGL extension.

**Comment by PeterZhizhin** [comment]
@highfive: assign me

**Comment by PeterZhizhin** [comment]
Sorry, please unassign me. I will have time to return back to this problem after the 20th of May.

**Comment by splav** [comment]
@highfive: assign me

**Comment by splav** [comment]
Hi! I've a question:
Does servo always use ANGLE to translate shaders? Is it safe to assume that if the feature is supported somehow - it's supported in WebGL?

According to Gecko code ( https://searchfox.org/mozilla-central/source/gfx/gl/GLContextFeatures.cpp#142 ) the feature is assumed to be supported if we have GL > 2 or GLES > 3 or extension. This logic could be replicated.

Alternatively, we could test GLSL version. It should be 1.10+ for GL ( https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FragDepth.xhtml ) and 3.00+ for GLES ( https://www.khronos.org/registry/webgl/extensions/EXT_frag_depth/ ) . I'd prefer this option - it seems to be more explicit, since this is a shading language feature.

**Comment by jdm** [comment]
Yes, ANGLE is always used to translate shaders.
