### ISSUE TITLE
Intermittent error in /webxr/hit-test/ar_hittest_subscription_inputSources.https.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#26347]
```
  ▶ ERROR [expected OK] /webxr/hit-test/ar_hittest_subscription_inputSources.https.html
  │   → input_source is undefined
  │ 
  └ testFunction/</</<@https://web-platform.test:8443/webxr/hit-test/ar_hittest_subscription_inputSources.https.html:66:11
```

cc @Manishearth

**Comment by Manishearth** [comment]
This is probably happening because of a race between `simulateInputSource()` and the rAF. That function is supposed to run by the next animation frame, but at that point we have been silently ticking the frame loop so sometimes a queued up raf ends up running instead.

It's a bit annoying to fix, though. We could potentially have it process frames a little bit differently in the mock implementation.

**Comment by Manishearth** [comment]
This is easier to fix in the tests, IMO 

https://github.com/immersive-web/webxr-test-api/issues/64

**Comment by Manishearth** [comment]
This will be fixed in the tests, though I'd wait for https://chromium-review.googlesource.com/c/chromium/src/+/2173519 to land before actually fixing the tests.

**Comment by Manishearth** [comment]
Fixed the races in the tests: https://github.com/web-platform-tests/wpt/pull/23350

should be a few days for this to land; we're waiting on a different WPT change to land and sync from Chromium.

**Comment by Manishearth** [comment]
Merged upstream
