### ISSUE TITLE
repo bundles make git hash in nightly versions useless

### ISSUE THREAD

**Issue by jdm** [servo/servo#26386]
The code to create a bundle ends up creating a git commit that doesn't match anything in the master branch: https://github.com/servo/servo/blob/4e650e83284bc25b781902085df4c25b39d95dd5/etc/taskcluster/decisionlib.py#L870-L883

This means that the code that [populates](https://github.com/servo/servo/blob/174bcc443435100da31b20db5ab684f4f3c8255b/components/config/lib.rs#L24) the binary's version information uses a hash that is meaningless: https://github.com/servo/servo/blob/306e8ac5f9b1f5b30c83f6861cfc3139273274bc/python/servo/command_base.py#L736-L742

We could potentially make CI set the GIT_INFO environment variable when before building to CONFIG.git_sha, and make the avoid overwriting that variable from the mach code if it's already set.

**Comment by SimonSapin** [comment]
What lead to the first chunk of code is:

* When CI starts for a push to a branch, there may be some time before a given task starts. For example a WPT task only starts after a build task has finished. In the meantime, the git branch may have been removed or force-pushed, such that the original commit is not there anymore. Therefore, we have the decision task package the repository as an artifact and have other tasks use that instead of fetching from GitHub

* `git bundle` is an easy way to package a repo into a single file. Compressed, `servo/servo` with its full history is ~470 MB but tasks only need the current tree which is ~90 MB. `git bundle` does not have an equivalent of shallow clone, so this code synthesizes a commit with the same git tree but no parent, and bundles that.

To keep the correct commit hash, instead of `git bundle` we could tar the `.git` directory of the repository and use it as-is. The decision task already uses `git fetch --depth 1` (shallow clone), which produces a single compressed git pack file without history, so there is no need to gzip that tarball.

We’d also need to change this code for dependent tasks to use `tar` and `git checkout` instead of using `git fetch` from the bundle:

https://github.com/servo/servo/blob/4e650e83284bc25b781902085df4c25b39d95dd5/etc/taskcluster/decisionlib.py#L315-L321

**Comment by camelid** [comment]
Could the code that populates the version info just extract the real commit hash from the message of the synthesized commit?

**Comment by SimonSapin** [comment]
Good point, I forgot this message was included :)
