### ISSUE TITLE
Improve spec compliance of validity check

### ISSUE THREAD

**Issue by gterzian** [servo/servo#27133]
This line https://github.com/servo/servo/pull/27100/files#diff-db2031d1f23ecf1a921fc100cfed753dR677

appears incorrect, since the spec only says to fire events on the fields that are invalid, via step 6.1 of https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#statically-validate-the-constraints, which is called into by https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-form-submit

An event is fired on the form element as a whole only as part of the ["check validity steps"](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#check-validity-steps), and those are called into from other places(for example the `checkValidity` method). 

So the implementation of `checkValidaty` could also be updated to actually fire an event.

see `components/script/dom/htmlformelement.rs`.

**Comment by muodov** [comment]
@highfive assign me

**Comment by muodov** [comment]
Turns out, this is quite a recent change in HTML spec. The `invalid` event on the `<form>` element was removed.
So it seems like we can just remove that line in the form submission implementation.

Links:
- [HTML issue](https://github.com/whatwg/html/issues/4626) ([PR](https://github.com/whatwg/html/pull/5507))
- corresponding [WPT change](https://github.com/web-platform-tests/wpt/pull/23380)

The validation methods (`checkValidity()` and `reportValidity()`) of the `<form>` element specifically don't mention this event either. The ["check validity steps"](https://html.spec.whatwg.org/multipage/#check-validity-steps) and ["report validity steps"](https://html.spec.whatwg.org/multipage/#report-validity-steps) are actually never referred to from the [validation section of the `<form>`](https://html.spec.whatwg.org/multipage/#constraint-validation), so they only apply to form controls and not the form itself. Those cases are already covered in current implementation.

**Comment by gterzian** [comment]
Ok, thanks for looking into this. 

> The validation methods (checkValidity() and reportValidity()) of the <form> element specifically don't mention this event either.

Re this, doesn't [`checkValidity`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-cva-checkvalidity) directly call into [the check validity steps](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#check-validity-steps) that fire this event?

**Comment by muodov** [comment]
@gterzian it took me some time to figure it out, but [checkValidity() in "The constraint validation API"](https://html.spec.whatwg.org/multipage/#dom-cva-checkvalidity) has nothing to do with the [checkValidity() of the form element](https://html.spec.whatwg.org/multipage/#dom-form-checkvalidity).
[The constraint validation API](https://html.spec.whatwg.org/multipage/#the-constraint-validation-api) is explicitly referred to from form controls specs, for example [input element](https://html.spec.whatwg.org/multipage/#the-input-element:the-constraint-validation-api)

**Comment by gterzian** [comment]
Ah ok, so those I was referring to are about form controls, not the form element, as you already had pointed out. Thanks!
