### ISSUE TITLE
Update to euclid 0.22

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#27424]
https://crates.io/crates/euclid/0.21.0

This contains [a number of breaking changes](https://github.com/servo/euclid/pulls?q=is%3Apr+is%3Aclosed+label%3A%22breaking+change%22)

Most are minor, and I believe all of them pair behavior changes with method renames. The ones that will be the trickiest are:

 - [Move away from pre_transform/post_transform terminology](https://github.com/servo/euclid/pull/451)
 - [Adopt the column-major-column-vector notation](https://github.com/servo/euclid/pull/452)

This essentially means we'll need to flip our `from_row_majors` and also fix up our `pre_transform`/etc usage. Currently we do things backwards because we want to use column-major column vectors, this will make it easier for us to do that, but will involve a bit of work.

**Comment by avr1254** [comment]
@highfive:assignme

**Comment by avr1254** [comment]
@Manishearth Can you tell me where in the codebase I should start looking to find and update these changes?

**Comment by Manishearth** [comment]
It's actually all over multiple codebases: you'd need to figure out which dependencies use Euclid, update them, and apply fixes

**Comment by avr1254** [comment]
@Manishearth  Sorry for the newb question, but does that include repositories outside of servo/servo?

**Comment by Manishearth** [comment]
I don't think so. But this needs to be done in a coordinated way,I would recommend going through Cargo.lock to see which deps use them, and then try to bump and patch

**Comment by CYBAI** [comment]
@avr1254 Let me provide some more information which might be helpful for you to understand this issue.

### Why we need to update packages for multiple codebases?

Servo is a large codebase and it has depended on a large amount of dependencies (as you can see in Cargo.lock). Thus, if it's possible, we'd like to avoid introducing duplicated version crates.

#### What does duplicated version crates mean?

Let's assume crate `A` depends on crate `C 0.1.0` and crate `B` depends on crate `C 0.3.0`. When you try to install both crate `A` and `B`, cargo will install both `C 0.1.0` and `C 0.3.0` for you because they are necessary for both A and B.

#### Why do we want do avoid that?

If we try to introduce more and more duplicate version crates to Servo, the development experience for Servo might be horrible because we have a lot of dependencies.

#### But, how if we want to introduce something ASAP but it will introduce duplicate version crates?

Sometimes, we need to introduce some features ASAP but it will need more effort to update crates for many other dependencies. In this situation, we will just `ignore` it in our CI checking. Let me explain what the CI checking is in next point.

#### Check duplicated version crates with servo-tidy

Because we want to avoid duplicated version crates, we introduced a check into `./mach test-tidy` and it will go through the Cargo.lock file to see if there's any duplicated version crates, if yes, it will fail to let you know.

and for previous point, how can we ignore it?

there's a `[ignore]` section in `servo-tidy.toml` and it's for the purpose.

https://github.com/servo/servo/blob/c6a3dcb90dbf657afacab7ab291bdc5b50adb47c/servo-tidy.toml#L29-L31

### Conclusion

We want to avoid introducing duplicated version crates so we'd like to update the crate for any other our dependencies which also depends on it (in this case, it's `euclid`).

For another example, if we'd like to upgrade `hyper` and `tokio`, it will need more efforts like mentioned in https://github.com/servo/servo/issues/26933#issuecomment-645043235.

Hope this is helpful for you to understand why you'll need to check other deps 🙏

**Comment by avr1254** [comment]
@Manishearth I'm starting the update by looking at the Canvas component. When I update the Cargo.toml file to have euclid="0.21", I get several errors, presumably because the webrender_api crate also uses Euclid, but is not upgraded either. I don't have the source code, should I fork the repository or move on to other parts of the code?

**Comment by avr1254** [comment]
@CYBAI  Lovely write-up! I am having a bit of an issue, however. When I add "euclid" to the servo-tidy.toml file, the test-tidy doesn't complain. However, when I build the engine, it appears that the program sees conflicting versions of euclid. A common error I get is:
 `expected reference "&euclid::Point2D<f32, euclid::UnknownUnit>"
               found reference "&webrender_api::euclid::Point2D<f32, webrender_api::euclid::UnknownUnit>"
    = note: perhaps two different versions of crate "euclid" are being used?`

Any thoughts on how I can specify to use euclid instead of webrender_api::euclid?

**Comment by jdm** [comment]
Since the version of webrender we depend upon is still using euclid 0.20, we must pass euclid 0.20 types to it. The only way I see to deal with that is to depend on both euclid 0.20 and euclid 0.21 in the same crate (like how [net depends on two versions of tokio](https://github.com/servo/servo/blob/6a3c3a4e18370d5604644d5491430b82d51c5be9/components/net/Cargo.toml#L60-L61)) and for any 0.21 values that need to be passed to webrender, create a corresponding 0.20 value from the 0.21 value.

**Comment by Manishearth** [comment]
@jdm I would propose updating WebRender as well, the breaking changes were made by the moz gfx team and I suspect they wish to update webrender too.

I would rather update everything at once, adding conversion between two kinds of incompatible euclid units sounds like a recipe for disaster.

**Comment by CYBAI** [comment]
> @CYBAI Lovely write-up! I am having a bit of an issue, however. When I add "euclid" to the servo-tidy.toml file, the test-tidy doesn't complain.

Oops, maybe I didn't explain it properly. Adding the crate into `servo-tidy.toml` means you want to `ignore` it so it's correct that test-tidy won't complain. But, in this case, I think we want to update all related dependencies and don't want to add it into the ignore section in `servo-tidy.toml`.

**Comment by jdm** [comment]
@Manishearth According to https://github.com/servo/webrender/blob/ed6ed92ac1cdfa39118fb95b63df7ea804fbbbd1/webrender_api/Cargo.toml#L21, upstream webrender hasn't updated to euclid 0.21 yet either.

**Comment by avr1254** [comment]
@jdm I was trying to implement your idea two comments ago, but it seems like I can't use both versions of Euclid in the same file. Do you know if this is possible?

**Comment by jdm** [comment]
@avr1254 It should be. What's an example of code that isn't working for you?

**Comment by Manishearth** [comment]
@jdm yes, we should do that ourselves or wait for it to happen, which i imagine will be soon :smile:

**Comment by avr1254** [comment]
@jdm Well it looks like I found a way to incorporate both crates, but now I'm having an issue with the Serialize trait. Looking at Euclid's implementation for 0.21's Size2D, they implemented it, but I get errors like: 
the trait bound `euclid::Size2D<u32, euclid::UnknownUnit>: serde::Deserialize<'_>` is not satisfied
  --> components/canvas_traits/webgl.rs:67:9
   |
67 |         Size2D<u32>,
   |         ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `euclid::Size2D<u32, euclid::UnknownUnit>`
   |
   = note: required by `serde::de::SeqAccess::next_element`

**Comment by jdm** [comment]
@avr1254 Did you enable the "serde" feature for euclid 0.21 package?

**Comment by jdm** [comment]
@avr1254 You will need to enable the optional serde dependency of euclid like https://github.com/servo/servo/blob/master/components/style_traits/Cargo.toml#L13.

**Comment by avr1254** [comment]
@jdm I don't see a Display trait for Size2D in Euclid anymore. New change or just my bad?

**Comment by atouchet** [comment]
euclid 0.22 is now out: https://crates.io/crates/euclid/0.22.0

**Comment by jdm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1656236 has been filed to track the work in webrender , which is apparently almost complete but waiting on an upgrade to the plane-split crate.

**Comment by avr1254** [comment]
Maybe I just cant find it, but does anybody know what the change in Rect::max_rect() is? I can't find the change on euclid's github history.

**Comment by jdm** [comment]
@avr1254 Rect::max_rect isn't a method in https://github.com/servo/euclid/blob/master/src/rect.rs. What problem are you trying to solve?

**Comment by avr1254** [comment]
In components/layout/block.rs, it seems like there's a call to Rect::max_rect() on line 2337. I did some digging, and it looks like its a trait from the crate servo_geometry. Only issue is, I can't find that crate.

**Comment by jdm** [comment]
That's https://github.com/servo/servo/blob/a360b873becf2521c4b32706b678ce05f400c809/components/geometry/lib.rs#L40. You can trace that back by looking at https://github.com/servo/servo/blob/a360b873becf2521c4b32706b678ce05f400c809/components/layout/Cargo.toml#L45, which shows that the crate is in components/geometry.
