### ISSUE TITLE
Rust lang should be also hosted by Linux foundation.

### ISSUE THREAD

**Issue by netroby** [servo/servo#27776]
Rust lang should be also hosted by Linux foundation.
Why ? Because Servo was written with Rust, If we lost control with Rust. or mozilla gave up Rust.

It should be a plan to continue improve and maintain the Rust language.

It is not possible to convert one programming language into another.

So please make Rust language hosted with Linux foundation.

The Rust lang was the very most important thing with servo engine

**Comment by jdm** [comment]
If you really want to pursue this topic, I recommend https://internals.rust-lang.org/. The Servo Project has no say in how the Rust language organization is governed.

**Comment by KiChjang** [comment]
@netroby FYI, the Rust Core team has been considering setting up a foundation separate from Mozilla: http://smallcultfollowing.com/babysteps/blog/2020/01/09/towards-a-rust-foundation/. The blog has clearly stated that Rust already has a governance structure that is independent of Mozilla since inception, which hopefully addresses your concerns.
