### ISSUE TITLE
--devtools argument is not being handled correctly by the arg parser

### ISSUE THREAD

**Issue by pecastro** [servo/servo#28304]
I can't seem to be able to pass a `--devtools 12345` option to servo.
Whilst doing to so it breaks the argument handling to the point that Servo won't load a page 
```
 target/debug/servo --devtools 12345 --resolution 1024x1024 https://google.com
```
Will not load.
Debugging showed the `resolution` argument is being handled correctly whereas the `devtools` isn't.
Further investigation seemed to hint at something wrong with the getops library.

**Comment by ghostd** [comment]
Since the `devtools` is a "optional flag with an optional value", the following command line seems working (with the `=` character):
```
target/debug/servo --devtools=12345 --resolution 1024x1024 https://google.com
```

According to the current `getopt` tests, it seems to be an expected behavior:
https://github.com/rust-lang/getopts/blob/c11eb65097d0dc9fe9ceb351d63c3ac8b5f05e0b/src/tests/mod.rs#L412-L427

**Comment by pecastro** [comment]
Yes I  see that.  :/ 
I honestly didn't know until I read the linux getopt document with laser eyes that the `=` was a requirement to handle optional values, and because neither the servo or the rust getopt made any mention to that fact I assumed it was a bug whose test might have been wrong...
