### ISSUE TITLE
Floats and inlines in a block box aren't positioned correctly

### ISSUE THREAD

**Issue by jdm** [servo/servo#28748]
This causes tests/wpt/web-platform-tests/css/CSS2/box-display/box-generation-001.xht to fail.

**Comment by ggeier** [comment]
To my understanding, this test fails, because anonymous tables are not (yet) implemented. The actual tests are layouted correctly (as can be seen e.g. on https://wpt.fyi/). The reference, however, differs, as it includes anonymous tables invoked by `display: table-cell`.
As a result, this comes down to the issue of implementing tables #27459. The same goes for https://github.com/servo/servo/issues/28749.

**Comment by mrobinson** [comment]
This issue was almost certainly opened about the old layout system (`--legacy-layout`). It's true that tables are in progress for the new layout system. Likely once tables are more complete there we will probably close all of the old table bugs.

**Comment by mrobinson** [comment]
Indeed, this is now passing in the new layout system, so I think we can close this issue as part of the effort to clean up legacy layout issues and focus on issues with the new layout system.
