### ISSUE TITLE
module '_distutils_hack' has no attribute 'ensure_shim'

### ISSUE THREAD

**Issue by glyh** [servo/servo#28775]
After I cloned servo, I run this command:
```
./mach build --dev
```

Here's what I got:
```
Error processing line 1 of /home/lyh/Test/servo/python/_virtualenv3.10/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'

Remainder of file ignored
^CTraceback (most recent call last):
  File "/home/lyh/Test/servo/./mach", line 47, in <module>
    main(sys.argv)
  File "/home/lyh/Test/servo/./mach", line 29, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/home/lyh/Test/servo/python/mach_bootstrap.py", line 292, in bootstrap
    _activate_virtualenv(topdir, is_firefox)
  File "/home/lyh/Test/servo/python/mach_bootstrap.py", line 214, in _activate_virtualenv
    _process_exec([python, "-m", "pip", "install", "-I", "-r", req_path])
  File "/home/lyh/Test/servo/python/mach_bootstrap.py", line 104, in _process_exec
    process.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by CYBAI** [comment]
Thanks for reporting the issue.

Which platform are you on?
Could you please check if you already installed necessary dependencies (https://github.com/servo/servo#other-dependencies)?

**Comment by glyh** [comment]
This seem like a bug in distutils, I wonder if updating distutils would fix this.

**Comment by souravdas142** [comment]
Any update on this ? I occurred on the same issue.

**Comment by Exagone313** [comment]
I got a similar issue, unrelated to servo, but I can explain where this issue is coming from (this issue is easy to find on Google with these keywords).

A fix of this issue was released in setuptools 60.2.0: https://github.com/pypa/setuptools/commit/d0da0142609318e534d5874bfa0c44d1254f9e38

But this is not so simple.

Arch Linux ships virtualenv 20.11.0. The behavior of virtualenv is that it installs bundled wheels in created virtualenvs. This version contains setuptools 60.1.0, which doesn't have the fix above.

https://github.com/pypa/virtualenv/tree/20.11.0/src/virtualenv/seed/wheels/embed (I checked locally installed files, the wheels are untouched by Arch Linux maintainers.)

You could try to install a more up-to-date virtualenv package, but since mixing multiple versions of packages leads to conflicts and bugs, I recommend not using Arch Linux Python distribution. [asdf](https://asdf-vm.com/) might be a way to solve this.

**Comment by artudytu** [comment]
also had this error on archlinux, tried advice above without success but:
`python3 -m pip install -U setuptools` solved it for me

**Comment by michaelgrigoryan25** [comment]
@jdm seems like this issue can be closed.
