### ISSUE TITLE
Will there be a situation that makes this code in refcounted.rs OOM?

### ISSUE THREAD

**Issue by zhang915** [servo/servo#28906]
Will there be a situation that makes this code OOM?
[https://github.com/servo/servo/blob/0d0cfd030347ab0711b3c0607a9ee07ffe7124cf/components/script/dom/bindings/refcounted.rs](url)
```rust
if (0 < capacity) && (capacity <= len) {
    info!("growing refcounted references by {}", len);
    remove_nulls(&mut table);
    table.reserve(len);
}
```
I found that you solved similar problems before, why not use fallible API here?

```rust
    table.try_reserve(len)?;
```
I would be appreciated if you could answer my question.

**Comment by zhang915** [comment]
I see you have updated stylelist.rs in 2017 and now it uses try_push() or other fallible APIs you maintain yourself .
[https://github.com/servo/servo/blob/master/components/style/stylist.rs](url)
Like this:
```rust
if let Some(parts) = selector.parts() {
self.part_rules
    .get_or_insert_with(|| Box::new(Default::default()))
    .for_insertion(pseudo_element)
    .try_entry(parts.last().unwrap().clone().0)?
    .or_insert_with(SmallVec::new)
    .try_push(rule)?;
}
```
Committed on 10 Sep 2017
[https://github.com/servo/servo/commit/c85633f48eff8989dfd0050521347f404611bf62](url)

But I now understand servo's attitude towards the OOM situation, thank you for your reply. Could you tell me why Servo isn't ready to try to handle OOM situations for now?

**Comment by jdm** [comment]
In my experience, handling OOM errors correctly is more complex than just using a fallible operation. The question must be asked - can the engine actually continue running if this allocation fails? What should the caller do if we cannot allocate more space for references in the code in question? It would be unsafe to proceed, because we rely on that table to store all outstanding references to objects that can be garbage collected, and we would no longer have confidence that our engine can prevent them from being GCed while they remain in use.

**Comment by jdm** [comment]
Additionally, beyond just writing code that looks correct, it's very difficult to test the code paths that attempt to handle allocation errors. As long as Servo is not actively trying to run in low-memory environments where these kind of errors are expected, I don't see any value in putting in the effort to try to handle them correctly.

**Comment by zhang915** [comment]
Thanks for your comment! It was very helpful for my research.
