### ISSUE TITLE
CI in forks

### ISSUE THREAD

**Issue by sagudev** [servo/servo#29379]
Currently if you enable CI on fork you get handful of scheduled builds and builds that are only working on main repo, that should be disabled on forks:
- [docs](https://github.com/servo/servo/blob/master/.github/workflows/docs.yml)
- [nightly-rust](https://github.com/servo/servo/blob/master/.github/workflows/nightly-rust.yml)
- [nightly](https://github.com/servo/servo/blob/master/.github/workflows/nightly.yml) (main builds creates own artifacts)
- [wpt-nightly](https://github.com/servo/servo/blob/master/.github/workflows/wpt-nightly.yml)
- [upstream-nightly-changes](https://github.com/servo/servo/blob/master/.github/workflows/upstream-wpt-changes.yml)

Most work could be done with simple if guards: `if: ${{ github.repository == "servo/servo" }}`.

As for the [main](https://github.com/servo/servo/blob/master/.github/workflows/main.yml) I am currently using `git push origin local-branch:try --force` to replicate `@bors-servo try` command. The easiest option would be to change branch on which the job is run (all branches). I believe this would be beneficial also to internal contributors (those who have permissions to run `@bors-servo try`) as they could fully test their changes in personal forks and thus having less try-fail CI runs on main repo (remember: whole servo organization shares a limited number of parallel GitHub Actions workers).

OFF-TOPIC IDEA: Make servo/servo CI try/auto runs on `@bors-servo` so all other servo org repos aren't burdened by servo/servo CI runs. The only problem here may be check reports back in main repo.

OFF-TOPIC IDEA: Provide artifacts on PRs.

**Comment by sagudev** [comment]
Investigate reporting (GitHub annotations?) for aggregated_expected_results on forks when there is no PR.

**Comment by delan** [comment]
i’m not familiar with the docs workflow, but here’s what i know about the others.

**nightly-rust** is a smoke test build that checks if servo still works with the latest nightly rust. it’s not really redundant, because we sometimes rely on unstable or internal rust features that might break, and it’s good to find out about that early so we can fix our code accordingly. this workflow probably doesn’t need to run on forks.

**nightly** builds and uploads our nightly releases to [the servo website](https://servo.org), under the downloads section. this workflow definitely shouldn’t run on forks.

the [web platform tests](https://web-platform-tests.org) are a shared resource that comes from [a separate repo](https://github.com/web-platform-tests/wpt), but we have our own copy of the tests in this repo, so we need to keep the two in sync when changes are made on either side.

**wpt-nightly** imports any changes to those tests made outside our repo each day, creating pull requests in servo like [this one](https://github.com/servo/servo/pull/29394). this workflow probably doesn’t need to run on forks, because forks will get those changes when they sync with the main servo repo.

**upstream-wpt-changes** exports changes made to our copy of those tests from servo pull requests, creating pull requests in wpt like [this one](https://github.com/web-platform-tests/wpt/pull/37280) (i wasn’t able to find any recent servo examples). this workflow probably doesn’t need to run on forks, because forks will have their changes exported when they make a pull request to the main servo repo.

**Comment by sagudev** [comment]
>nightly-rust is a smoke test build that checks if servo still works with the latest nightly rust. it’s not really redundant ...

When I say redundant I mean redundant **for forks**, as forks usually do not have changes on master but on other branches so those workflows are doing redundant work.  Sorry for my bad wording.

> upstream-wpt-changes exports changes made to our copy of those tests from servo pull requests, creating pull requests in wpt like https://github.com/web-platform-tests/wpt/pull/37280 (i wasn’t able to find any recent servo examples). this workflow probably doesn’t need to run on forks, because forks will have their changes exported when they make a pull request to the main servo repo.

Couldn't they be restricted with something like: `paths: ["test/wpt/**"]` so we do not run it when no wpt tests are changed? That's what was bugging me most about `upstream-wpt-changes`, but I thought I understand them wrong.

**Comment by sagudev** [comment]
Unfortunately, I cannot reopen this issue. Anyway, for the third part of my work I am planning on adding `./mach try` functionality ([ref: mozilla-central's mach](https://firefox-source-docs.mozilla.org/taskcluster/try.html)) that would mainly function as running `git push origin HEAD:try --force` command (with safeguard to prevent usage on upstream servo).

@jdm What exactly is status of other `try-*` branches?
