### ISSUE TITLE
Test results are reported for pull requests multiple times after it has merged

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#29583]
Once a pull request has merged, test results are reported multiple times after it has merged. This can be observed here: https://github.com/servo/servo/pull/29504#issuecomment-1496956124. I believe these results are coming from running the main workflow on the `master` branch.

cc @sagudev who has done a lot of work on workflows lately.

**Comment by sagudev** [comment]
The results are actually coming from `try-wpt` branch, probably due to this invocation: https://github.com/servo/servo/pull/29581#issuecomment-1497104759

I believe this is coming due to bors [triggering two builds](https://github.com/servo/servo/actions?query=branch%3Atry-wpt), probably due to force pushing of previous commit and then pushing try merge commit. This may have been intended functionality @jdm?

Which bors/home deployment is behind `@bors-servo`? Is it still [servo/homu](https://github.com/servo/homu) or anything else. How does servo's homu differ from rust-lang's homu? Can we just use theirs with servo's config to ease maintenance burden? I am also asking this because in the last week I was looking at another problem that may also be due to bors.

**Comment by jdm** [comment]
Yes, servo/homu is the one in use. I don't know anything about rust's homu.
