### ISSUE TITLE
Servo embedding: Create a mini-browser

### ISSUE THREAD

**Issue by atbrakhi** [servo/servo#29930]
Current status

We use winit to create this window
![](https://notes.igalia.com/uploads/7a4fa579-1977-437a-80e2-2c4c6f4c3d45.png)

**Mini browser**

Minimal requirement:
![](https://notes.igalia.com/uploads/f77ac4ed-3edf-44bc-80b1-0bf04988fa56.png)
^ This window was created using egui

**Option 1: Winit + egui**
Steps:
- Create a window using winit
- Use [egui_winit](https://github.com/emilk/egui/tree/master/crates/egui-winit) to create a url bar and to render the page inside the window we created using winit. We might need to do something similar to this [egui_winit example](https://github.com/hasenbanck/egui_example)

note: I think it might not make sense to go with this option, as why would I use winit to create a window when I can create that same window using egui.

**Option 2: Egui**
Steps:
- Create window using [egui](https://github.com/emilk/egui)
- Create url bar using egui/eframe 
- Integrate servo *engine* into egui to render pages

Question: Can we achieve option 2 without changing embedding api too much?

I am still exploring the options to execute this task. Opinions and suggestions are welcomed :)

**Comment by mrego** [comment]
We want this simple browser to be the default thing developers will use when using `./mach run`.

One important consideration is that it'd be really nice to use the same binary for run tests (maybe passing some `--no-chrome` parameter or something like that).

**Comment by delan** [comment]
> Question: Can we achieve option 2 without changing embedding api too much?

This may be a silly question, but do we have any embedding api other than libsimpleservo? It looks like the winit port uses the servo crate directly, so I think we should be ok?

**Comment by atbrakhi** [comment]
> 

I am only aware of `libsimpleservo` and `libservo`

**Comment by delan** [comment]
Neither of them have had any releases published, so I think it’s ok if we need to make breaking api changes.

From what I understand, egui can’t actually create windows on its own. We need [additional integration code](https://docs.rs/egui/latest/egui/#integrating-with-egui) to receive input from and display output to a window, and we also need to create the window. Both of these tasks ultimately rely on either winit or [SDL2](https://github.com/ArjunNair/egui_sdl2_gl/blob/d7599d8073fb9f94ff2389d2d1e1964c7f792a3c/examples/basic.rs#L15-L29), which abstract over the platform (x11, wayland, winapi, etc).

[eframe](https://docs.rs/eframe/latest/eframe/) can handle both tasks using winit under the hood, and [I use that](https://github.com/delan/wbe.rs/blob/a6b3aa371fc757ecc9d01d1ba0c0ff5aebdf2818/src/main.rs) in [my toy web browser](https://github.com/delan/wbe.rs), but eframe forces you to use [its update lifecycle](https://docs.rs/eframe/latest/eframe/trait.App.html#tymethod.update), so I don’t think it’s appropriate for us. But eframe is based on

* [egui-winit](https://docs.rs/egui-winit/latest/egui_winit/) for input — we will almost certainly need this
* [egui_glow](https://docs.rs/crate/egui_glow/latest) for output — this _may_ be appropriate too, though it’s not yet clear to me how glow will interact/overlap with surfman (the library we plumb our webrender output to)

and we wouldn’t need to reimplement eframe’s [window creation code](https://github.com/emilk/egui/blob/9478e50d012c5138551c38cbee16b07bc1fcf283/crates/eframe/src/native/epi_integration.rs#L102-L113), because we already have code for that in our winit port, so I think option 1 is the only option that makes sense.

**Comment by jdm** [comment]
We can absolutely make breaking changes to the embedding API.
