### ISSUE TITLE
Clean-up Style integration

### ISSUE THREAD

**Issue by gterzian** [servo/servo#31222]
Came-up during TSC. Make it easier to use the style system outside of Servo.

- [ ] Remove (unused?) Webrender dependency. The only direct dependency seems to be on WR API [here](https://github.com/servo/servo/blob/2fbb120e94013d0387eaa8c3fc6d649aed7f599f/components/style_traits/Cargo.toml#L33).
- [ ] Remove direct use of filesystem to make it compilable into wasm. I could see [this use of WalkDir](https://github.com/servo/servo/blob/2fbb120e94013d0387eaa8c3fc6d649aed7f599f/components/style/build.rs#L46), not sure if that is what was meant. Servo configs seems to rely on the embedding to read configs from the style system and pass it to [this](https://github.com/servo/servo/blob/2fbb120e94013d0387eaa8c3fc6d649aed7f599f/components/config/prefs.rs#L64)

**Comment by servo-highfive** [comment]
cc @emilio

**Comment by gterzian** [comment]
cc @jkelleyrtp @nicoburns

**Comment by nicoburns** [comment]
Update on this: it seems that webrender is not a dependency of the `style` crate. But that stylo-dioxus is depending on webrender at the top level. However if I remove this dependency I get a crash.

**Comment by jkelleyrtp** [comment]
The servo crate is manually patching the webrenderer API crate so we have copied the similar patch into stylo-dioxus.

**Comment by nicoburns** [comment]
> The servo crate is manually patching the webrenderer API crate so we have copied the similar patch into stylo-dioxus.

Hmm... but the `webrender_api` crate and the `webrender` crate are different crates (where `webrender` depends on `webrender_api` but not the other way around - indeed the whole point of `webrender_api` is to avoid other crates needing to depend on `webrender` itself), so unless something somewhere is depending on `webrender` it seems like it ought not need to be compiled *at all* (thus (in theory?) making it irrelevant whether the version is patched or not)

**Comment by gterzian** [comment]
Have you tried based on the latest Servo? This change may have helped: https://github.com/servo/servo/pull/31212

**Comment by nicoburns** [comment]
My major issues here were fixed when `servo_config` was replaced with `style_config`. The `style` crate still has what I believe are unnecessary dependencies. For example, it depends on `html5ever` just for a few types which I believe are all available in the `markup5ever` crate (which excludes the actual html parser). And there is also still the big issue of so much code being conditionally compiled based on the CSS properties that Servo happens to support (so Stylo isn't really a generic CSS library atm). But perhaps those would be better tracked separately (and perhaps on the stylo repo rather than this one?)

**Comment by mrobinson** [comment]
I think we can go ahead and close this one, but we should can open up other issues to track specific things that we can clean up about the style interface.
