### ISSUE TITLE
Web fonts are not loaded from stylsheets included via `@import` rules

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#31598]
Web fonts can be loaded from stylesheets, but when those stylesheets are updated via `@import` rules, the web fonts from the imported stylesheet are not loaded at all.

**Comment by ssemanich** [comment]
this Nicholas I think u should use this <link rel="stylesheet" href="styles.css">.Instead of using @import which has some limitations

**Comment by MunishMummadi** [comment]
hey @mrobinson if I am solution is ok with you. I can PR it in an hour.

**Issue Analysis:**
The issue occurs when web fonts from imported stylesheets are not loaded when the stylesheets are updated via `@import` rules. This happens because the existing code does not handle the loading of web fonts from imported stylesheets. To solve this, we need to ensure that web fonts are properly loaded and applied when new stylesheets are imported.

**Proposed Solution:**
Here's the proposed solution to address this issue:

1. **Update `StylesheetContext` to Handle `@import` Rules:**
   - Modify the `StylesheetContext` struct to include a new field `is_imported_stylesheet` to track whether the context represents an imported stylesheet.
   - In the `FetchResponseListener` implementation for `StylesheetContext`, add a method `load_web_fonts_from_imported_stylesheet` to handle loading web fonts from imported stylesheets.
   - When `process_response_eof` is called, check if the context is for an imported stylesheet (`is_imported_stylesheet`). If true, call `load_web_fonts_from_imported_stylesheet` to load web fonts.

2. **Modify `StylesheetLoader` to Properly Load Stylesheets:**
   - Update the `StylesheetLoader` struct and its `load` method to include a new parameter `is_imported_stylesheet` to indicate whether the stylesheet being loaded is imported.
   - When loading an imported stylesheet using `StylesheetLoader`, pass `true` for `is_imported_stylesheet`.

**Comment by mrobinson** [comment]
@MunishMummadi thanks for the input. I’m already working on a fix for this issue. I hope to post it soon.

**Comment by MunishMummadi** [comment]
No problem. Little guidance on my approach is highly appreciated. Thanks in advance.
