### ISSUE TITLE
effective_vertical_align_for_inline_layout is bogus and needs to be removed

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31634]
```html
<!DOCTYPE html>
<style>
.container {
  width: 50px;
  vertical-align: top;
  border: solid;
}
</style>
<div class="container" style="display: flow-root">
  <canvas width="50" height="50" style="background: cyan"></canvas>
</div>
<div class="container" style="display: inline-block">
  <canvas width="50" height="50" style="background: cyan"></canvas>
</div>
```

![](https://github.com/servo/servo/assets/7477678/16d678ec-3765-4353-8060-c15b8e2b3293)

The 1st case is good, the 2nd is bad.

What happens is that, in the IFC established by the containers, they generate the strut using the `effective_vertical_align_for_inline_layout()` of the container! That just happens to work if the container is block-level because we get `baseline`, but if fails for inline-level containers.

We should just use `baseline` in all cases and get rid of `effective_vertical_align_for_inline_layout`.

**Comment by mrobinson** [comment]
Perhaps this should be checking if the container is the root of the inline formatting context instead of the `display` value. We don't think we want to apply something like `vertical-align: top` to children of the root of the inline formatting context, because they are "virtually" placed into anonymous boxes and `vertical-align` isn't inherited.

**Comment by Loirooriol** [comment]
Yes that's right, these `effective_vertical_align_for_inline_layout` should be `baseline` at the root of the IFC, or the `vertical-align` when nested inside.
