### ISSUE TITLE
Video without autoplay doesn't show up

### ISSUE THREAD

**Issue by mrego** [servo/servo#31666]
The following example:
```html
<video>
  <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">
  <p>Video not supported</video>
</video>
```

Shows *Video not supported*.

However simply adding `autoplay` makes the video to show and play properly:
```html
<video autoplay>
  <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">
  <p>Video not supported</video>
</video>
```

Maybe this is a known/duplicated issue, sorry if that's the case.

**Comment by aditi5926** [comment]
So basically you want the reason why is this happening right? No code is required right?

**Comment by jdm** [comment]
This issue can only be closed when videos that do not have the autoplay attribute are rendered correctly. That will require code changes.

**Comment by RustAndMetal** [comment]
I just spent some time looking into this, for anyone else interested in this issue, here's some things that I thought might be of note to someone working on this issue (not exhaustive but maybe it is helpful to someone):

- The section of the spec that is violated here is this:

> When the [video](https://html.spec.whatwg.org/multipage/media.html#the-video-element) element is [paused](https://html.spec.whatwg.org/multipage/media.html#dom-media-paused), the [current playback position](https://html.spec.whatwg.org/multipage/media.html#current-playback-position) is the first frame of video, and the element's [show poster flag](https://html.spec.whatwg.org/multipage/media.html#show-poster-flag) is set
The [video](https://html.spec.whatwg.org/multipage/media.html#the-video-element) element [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) its [poster frame](https://html.spec.whatwg.org/multipage/media.html#poster-frame), if any, or else the first frame of the video.

https://html.spec.whatwg.org/multipage/media.html#the-video-element:the-video-element-9

- Poster frames already partially work, so there does appear to be some code path that displays "something else" when the above condition is met:

```html
<video poster="https://placehold.co/500x500.jpg">
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">
    <p>Video not supported</p>
</video>
```

Note that even then, before the video is loaded, it is not displayed.

- The issue isn't "really" with autoplay but just with all paused videos at the first frame. Using JavaScript to play a video without an autoplay tag makes it show up once the first frame is rendered:

```html
<video>
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">
    <p>Video not supported</p>
</video>
<script>
    setTimeout(() => {
        document.querySelector('video').play();
    }, 1000);
</script>
```

- This _might_ actually be an issue in [the media crate](https://github.com/servo/media/tree/main) or _might_ at least require code changes there too, to allow us to properly show the first frame. Though this is just speculation, maybe someone with more experience in this part of the codebase can shed some light on this.

**Comment by eerii** [comment]
I did some testing and it seems that #31746 addresses some of this issues. However, it still doesn't show the first frame of the video as the placeholder. Here's a comparison:

Current behaviour:

![image](https://github.com/servo/servo/assets/22449369/faf18b69-e14c-4337-9520-cd077a6e8193)

With #31746:

![image](https://github.com/servo/servo/assets/22449369/25a27e84-0bf1-432d-956d-0240e48d4686)

Testing with:

```html
<!DOCTYPE html>
<body>
    <video style="border: 1px solid red">
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"/>
    <p>Video not supported</p>
  </video>

  <video autoplay style="border: 1px solid blue">
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"/>
    <p>Video not supported</p>
  </video>

  <video poster="https://placehold.co/500x500.jpg" style="border: 1px solid yellow">
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"/>
    <p>Video not supported</p>
  </video>

  <video width="400" style="border: 1px solid green">
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"/>
    <p>Video not supported</p>
  </video>
</body>
```

The videos are definitely loading and the size is set correctly (the red rectangle is the same as the blue one, the other two are different because either the poster sets the size or the default width was modified). I'll take a look at the code tomorrow to see if I can get the first frame to render by default.

**Comment by eerii** [comment]
Update: I have been looking into this and going into servo-media and gstreamer code. One way this could be solved is by adding a function to servo-media's [`Player`](https://github.com/servo/media/blob/main/player/lib.rs#L92) that requests a frame to be rendered (without starting play the video), something like `request_frame`.

Inside this function we could call [`gst_player_get_video_snapshot`](https://github.com/sdroege/gstreamer-rs/blob/main/gstreamer-player/src/player.rs#L86), which returns a `Sample` with the current frame of the video. With the `Sample` we can then call the renderer's [`get_frame_from_sample`](https://github.com/servo/media/blob/main/backends/gstreamer/render.rs#L108), which gives us a `VideoFrame`. Finally, this can be used to call [`VideoFrameRenderer::render()`](https://github.com/servo/media/blob/main/player/video.rs#L72), which is implemented in `htmlmediaelement.rs` by [`MediaFrameRenderer`](https://github.com/servo/servo/blob/main/components/script/dom/htmlmediaelement.rs#L183). This should update the current frame so it shows on screen just like when a video is paused. 

```rust
fn request_frame(&self) -> Result<(), PlayerError> {
    let inner = self.inner.borrow();
    let mut inner = inner.as_ref().unwrap().lock().unwrap();
    let Some(sample) = inner.player.video_snapshot(...) else {
        return Err(...);
    };
    let Ok(frame) = self.render.lock().unwrap().get_frame_from_sample(sample) else {
        return Err(...);
    };
    if let Some(video_renderer) = &self.video_renderer {
        video_renderer.lock().unwrap().render(frame);
    }
    Ok(())
}
```

The new function could be called somewhere around [here](https://github.com/servo/servo/blob/main/components/script/dom/htmlmediaelement.rs#L664), when `ReadyState::HaveEnoughData` is detected and `self.autoplaying` is disabled. I have a very messy implementation of all of this, but I'm still trying to solve a few issues. The main one is that I am getting

```
GLib-GObject-CRITICAL **: 16:17:12.052: g_object_get_is_valid_property: object class 'GstPlayBin3' has no property named 'n-video'
```

when calling `gst_player_get_video_snapshot`, which looking at gstreamer's [`gst_play_get_video_snapshot`](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-plugins-bad/gst-libs/gst/play/gstplay.c#L4595) outside of the rust wrapper leads me to believe that I am calling it when the video is not yet initialized, so more testing will need to be done.

```c
g_object_get (self->playbin, "n-video", &video_tracks, NULL); // This crashes
if (video_tracks == 0) {
    GST_DEBUG_OBJECT (self, "total video track num is 0");
    return NULL;
}
```

I'll try to diagnose the 'n-video' error and get this working, but if anyone that is familiar with gstreamer has any pointers they are greatly appreciated!

**Comment by jdm** [comment]
I can't provide any gstreamer assistance, but that all sounds pretty reasonable to me!

**Comment by eerii** [comment]
I have a working proof of concept for this!

![image](https://github.com/servo/servo/assets/22449369/b207dbd7-6416-49f6-b2d0-0385e79a80f8)

The critical error was coming directly from a GStreamer regression on the latest version, I opened a pr there (https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6516). I also had to find another place from where to call `request_frame` in `htmlmediaelement`, since it needs the video buffer to exist before extracting a sample, and using `PlayerEvent::StateChanged` with `PlaybackState::Paused` seems to do the trick.

The implementation still needs a bit of cleanup, as well as handling some details like asking `video_snapshot` for the correct size, checking if a poster already exists and reviewing the spec and test expectations so it is fully compatible.

The change will require two prs, one in [servo/media](https://github.com/servo/media) that adds the `request_frame` player trait function, and one here with the changes to `htmlmediaelement`. I'll try to have the first one ready tomorrow.

**Comment by ceyusa** [comment]
Hi @eerii 


Thanks for your hard work. Your proposal of a  video snapshot is interesting and it looks to solve the issue.  But I wonder how required is too add new code for that.

As you already found out, in a GStreamer pipeline, before passing to PLAYING state, it has to change first to PAUSED state, and in to reach PAUSED state, all  sinks have to receive a buffer, this operation is known as [preroll](https://gstreamer.freedesktop.org/documentation/additional/design/preroll.html). So, as far as I remember, when the GStreamer's pipeline pass to PAUSED, the `ReadyState::HaveEnoughData` is emitted. Then, there should be already a video frame to draw, the first one received at preroll, and that should be drawn.

All I'm saying that perhaps it's a bug to fix rather than a workaround to add.

**Comment by eerii** [comment]
Thank you so much for all the information, the page on preroll was very useful.

> So, as far as I remember, when the GStreamer's pipeline pass to PAUSED, the `ReadyState::HaveEnoughData` is emitted. Then, there should be already a video frame to draw, the first one received at preroll, and that should be drawn.

This makes a lot of sense, I observed that`gst_play_get_video_snapshot` only works when there is a buffer loaded, for example, after switching to the PAUSED state. This makes sense because internally it is emitting a `convert-sample` event, and according to [this](https://gstreamer.freedesktop.org/documentation/playback/playbin3.html?gi-language=c#playbin3::convert-sample) it returns NULL when there is no current buffer:

Returns ([GstSample](https://gstreamer.freedesktop.org/documentation/gstreamer/gstsample.html#GstSample) *) – a [GstSample](https://gstreamer.freedesktop.org/documentation/gstreamer/gstsample.html#GstSample) of the current video frame converted to caps. The caps on the sample will describe the final layout of the buffer data. [NULL](https://developer.gnome.org/glib/unstable/glib-Standard-Macros.html#NULL:CAPS) is returned when no current buffer can be retrieved or when the conversion failed.

Additionally, if no `caps` is passed to the `convert-sample` event it just returns the `sample` property and no conversion is done, so there shouldn't be too much overhead to call this.

> All I'm saying that perhaps it's a bug to fix rather than a workaround to add. Not sure, though.

I'll look closely into the code to see if it's supposed to be rendered somewhere already. As far as I could tell before, the buffer was loaded but no calls to render were made, but I'll review the comments and todos just in case. There needs to be a place where we render this initial frame, maybe it can be done directly on servo/media when the video first enters the PAUSED state, I'll look into it. Thank you a lot!

**Comment by eerii** [comment]
I created a new pr in servo/media which renders the first frame on the preroll callback. There are two issues but they need to be resolved in this repo:

- Intrinsic sizing has to apply to the rendered frame, but this is better suited as an addition to #31746.
- Not yet compliant with the spec, because it shows the first frame over the poster if it exists (The [video](https://html.spec.whatwg.org/multipage/media.html#the-video-element) element [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) its [poster frame](https://html.spec.whatwg.org/multipage/media.html#poster-frame), if any, or else the first frame of the video).
