### ISSUE TITLE
Fix WPT reference no_red_3x3_monospace_table-ref.xht

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31752]
Tests that are matched against this reference use `padding: 1px`, e.g. https://github.com/servo/servo/blob/06a021db552c1d2f8899484f7c1143424c387eef/tests/wpt/tests/css/CSS2/tables/table-anonymous-objects-060.xht#L13

However, the reference uses `position: absolute; top: 1px; left: 1px` https://github.com/servo/servo/blob/06a021db552c1d2f8899484f7c1143424c387eef/tests/wpt/tests/css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht#L17-L19

This is a problem: the former shrinks the containing block by 2px (1px on the left and 1px on the right), while the latter only by 1px on the left.

This is not noticeable on other browsers because the text is small enough to fit without wrapping, but Servo defaults to a bigger `font-size` so the text needs wrapping. `./mach run -r tests/wpt/tests/css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht  --resolution 800x600`

![](https://github.com/servo/servo/assets/7477678/a5455a22-ae21-4025-b5cb-a05766e05644)

I guess we should make `font-family: monospace` default to `font-size: 12px` instead of `16px`, but it seems wrong to have this assumption in these tests, since they are about tables, not fonts. Also, `font-size: 12px` doesn't really guarantee that the text will not wrap, since browsers may use different monospaced fonts with varying behaviors.

So I think the steps here are:
1. Modify `no_red_3x3_monospace_table-ref.xht` by adding `right: 1px`
2. [Run all the tests](https://github.com/servo/servo/blob/main/tests/wpt/README.md#running-the-tests) in `tests/wpt/tests/css/CSS2/tables/`, [updating the expectations](https://github.com/servo/servo/blob/main/tests/wpt/README.md#updating-test-expectations)
3. Create a PR fixing the problem. It will be automatically exported to WPT, where the change will be tested on Gecko, Blink and WebKit. You will need to confirm that they won't be negatively affected.

**Comment by richarddushime** [comment]
Hi @Loirooriol 
I would love to work on this 
can you assign me it ?

**Comment by Loirooriol** [comment]
You can comment `@servo-highfive: assign me` to get it assigned to you.

**Comment by sandeepB3** [comment]
Hey @Loirooriol , sorry for not updating here earlier. I've been working on this. Actually, 104 tests passed unexpectedly when they were `expected: FAIL`. I've already modified half of the 104 tests' respective .ini files to mark them as `expected: PASS`. Should I create a pull request for those and let @richarddushime handle the rest of them?

**Comment by Loirooriol** [comment]
You don't have to manually update them one by one, see the docs I linked. Something like

```
./mach build -r
./mach test-wpt -r --log-raw /tmp/servo.log tests/wpt/tests/css/CSS2/tables/
./mach update-wpt /tmp/servo.log
```

**Comment by sandeepB3** [comment]
Okay, my bad. Got it. Go ahead, @richarddushime.

**Comment by richarddushime** [comment]
> Okay, my bad. Got it. Go ahead, @richarddushime.

Thanks

**Comment by richarddushime** [comment]
> You don't have to manually update them one by one, see the docs I linked. Something like
> 
> ```
> ./mach build -r
> ./mach test-wpt -r --log-raw /tmp/servo.log tests/wpt/tests/css/CSS2/tables/
> ./mach update-wpt /tmp/servo.log
> ```

@Loirooriol Hope you are doing well 
I have been facing this build error for some time 
what could be the main reasons ?   even on the main branch 

`
rdm@rdm:~/Desktop/servo$ ./mach build -r
   Compiling mozjs_sys v0.68.2 (https://github.com/servo/mozjs#d1f1519b)
   Compiling mozjs v0.14.1 (https://github.com/servo/mozjs#d1f1519b)
   Compiling script v0.0.1 (/home/rdm/Desktop/servo/components/script)
error: failed to build archive: bad archive: truncated or malformed archive (offset to next archive member past the end of the archive after member Unified_cpp_js_src_jit4.o)

The following warnings were emitted during compilation:

warning: In file included from src/jsapi.cpp:7:
warning: In file included from src/jsapi.hpp:30:
warning: In file included from /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExp.h:16:
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:88:3: warning: definition of implicit copy assignment operator for 'RegExpFlags' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
warning:   RegExpFlags(const RegExpFlags&) = default;
warning:   ^
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:130:9: note: in implicit copy assignment operator for 'JS::RegExpFlags' first required here
warning:   flags = flags & flag;
warning:         ^
warning: 1 warning generated.
warning: In file included from src/jsglue.cpp:26:
warning: In file included from /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExp.h:16:
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:88:3: warning: definition of implicit copy assignment operator for 'RegExpFlags' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
warning:   RegExpFlags(const RegExpFlags&) = default;
warning:   ^
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:130:9: note: in implicit copy assignment operator for 'JS::RegExpFlags' first required here
warning:   flags = flags & flag;
warning:         ^
warning: 1 warning generated.

error: could not compile `mozjs_sys` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
      Timing report saved to /home/rdm/Desktop/servo/target/cargo-timings/cargo-timing-20240320T203813Z.html
Failed in 0:08:31
`

**Comment by richarddushime** [comment]
> You don't have to manually update them one by one, see the docs I linked. Something like
> 
> ```
> ./mach build -r
> ./mach test-wpt -r --log-raw /tmp/servo.log tests/wpt/tests/css/CSS2/tables/
> ./mach update-wpt /tmp/servo.log
> ```
@Loirooriol Hope you are doing well 
What could be the main reasons , i have been facing the below errors 
Note i ready made the change above 

rdm@rdm:~/Desktop/servo$ ./mach build -r

   Compiling mozjs_sys v0.68.2 (https://github.com/servo/mozjs#d1f1519b)
   Compiling mozjs v0.14.1 (https://github.com/servo/mozjs#d1f1519b)
   Compiling script v0.0.1 (/home/rdm/Desktop/servo/components/script)
error: failed to build archive: bad archive: truncated or malformed archive (offset to next archive member past the end of the archive after member Unified_cpp_js_src_jit4.o)

The following warnings were emitted during compilation:

warning: In file included from src/jsapi.cpp:7:
warning: In file included from src/jsapi.hpp:30:
warning: In file included from /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExp.h:16:
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:88:3: warning: definition of implicit copy assignment operator for 'RegExpFlags' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
warning:   RegExpFlags(const RegExpFlags&) = default;
warning:   ^
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:130:9: note: in implicit copy assignment operator for 'JS::RegExpFlags' first required here
warning:   flags = flags & flag;
warning:         ^
warning: 1 warning generated.
warning: In file included from src/jsglue.cpp:26:
warning: In file included from /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExp.h:16:
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:88:3: warning: definition of implicit copy assignment operator for 'RegExpFlags' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
warning:   RegExpFlags(const RegExpFlags&) = default;
warning:   ^
warning: /home/rdm/Desktop/servo/target/release/build/mozjs_sys-3b1e332e0d11cdbc/out/build/dist/include/js/RegExpFlags.h:130:9: note: in implicit copy assignment operator for 'JS::RegExpFlags' first required here
warning:   flags = flags & flag;
warning:         ^
warning: 1 warning generated.

error: could not compile `mozjs_sys` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
      Timing report saved to /home/rdm/Desktop/servo/target/cargo-timings/cargo-timing-20240320T203813Z.html
Failed in 0:08:31
`

**Comment by Loirooriol** [comment]
Seems to be https://github.com/rust-lang/rust/issues/42857

**Comment by mrobinson** [comment]
Perhaps try a clean build with `./mach clean` before building.
