### ISSUE TITLE
(Policy change request) Website support tracking

### ISSUE THREAD

**Issue by hardBSDk** [servo/servo#32092]
You have a policy to close issues about unimplemented things that break websites.

But if you close the issues on websites, how the community will know when some website was fixed?

Most people don't know the technical parts that the websites need, when you report that "x API was implemented", only developers will understand.

While the rest will interpret that a closed issue is a website fix.

Emulators use issues to track the game support and each status update inside the issue.

**Comment by mrobinson** [comment]
First off thanks for your interest in Servo. I would like to clarify that there is no policy like the one you describe. I closed some of your issues because Servo is an experimental browser engine (which means incomplete) and also we are going through a layout engine change. Most of the folks that work on Servo know that sites are broken. Right now it's a bit of a surprise when a site does work! 

Reports that sites are broken right now aren't very useful, unless there is some indication of *why* that site is broken. That requires a bit of work to trim away the other bits of HTML and CSS to identify what's going wrong. At this point many sites are using flexbox and grid, which servo has incomplete or missing support for so of course those sites don't work. Simply making an issue for every broken site isn't going to help them get fixed. You would also need to make an issue for most of the web I think. 

The other issue is that most websites change faster than Servo. Without a minimized test case by the time someone looks at a generic bug in a few years the original site will have changed. Again this isn't very useful.

> Most people don't the technical parts that the websites need, when you report that "x API was implemented", only developers will understand.

Servo is an experimental web browser engine. I think it's a huge assumption that those wishing to embed it into their applications are willing to do a bit of research about web technologies. As mentioned before, sites change fast, so we can't guarantee that any site is working or keeps working. The bug report will unfortunately not change that. That said, we are always looking for better ways to communicate our work. 

I didn't mean to discourage you by closing your issues, but I also want establish some expectations about useful bug reports. If you are interested in learning more about how to contribute to Servo or how to create reduced test cases I'm happy to help!

**Comment by hardBSDk** [comment]
@mrobinson I agree that more tests on the test suite is the best method to verify if things are working.

You are right, thanks for your reply!
