### ISSUE TITLE
Dependabot merging PRs that fail servo-tidy

### ISSUE THREAD

**Issue by atouchet** [servo/servo#32530]
https://github.com/servo/servo/pull/32522

This was automatically merged despite introducing a new duplicate dependency. Is something going wrong here?

**Comment by mukilan** [comment]
It does look like `test-tidy` is now broken. It always skips Cargo.lock lints.

The [logs](https://github.com/servo/servo/actions/runs/9551001003/job/26324329326) from test-tidy run in #32522:

```
 ➤  Skipping `Cargo.lock` lint checks, because it is unchanged.
```

I suspect #32465 broke the lint because it calls os.walk with a filename (`./Cargo.lock`) but os.walk only accepts directories.
