### ISSUE TITLE
Devtools console will break with Firefox 131

### ISSUE THREAD

**Issue by webbeef** [servo/servo#33275]
**Describe the bug:**
Because of the changes in https://bugzilla.mozilla.org/show_bug.cgi?id=1912237 we'll have to update the messages we send for the devtools console API (and maybe others).

**To Reproduce:**
Connect Servo to Firefox 131 (currently in Nighly). `console.log()` messages are not showing up any more.

cc @eerii in case you want to take a look :)

**Comment by eerii** [comment]
Thanks, I'll look into it! :)

**Comment by sagudev** [comment]
It's hard to target moving target. I suggest we target latest ESR Firefox release (like we do in mozjs for SM).

**Comment by eerii** [comment]
> It's hard to target moving target. I suggest we target latest ESR Firefox release (like we do in mozjs for SM).

That sounds very reasonable

**Comment by eerii** [comment]
On one hand, it is hard to track a moving target API so using ESR seems good in that way. However, if things start breaking in the stable version of the browser that people use, that would mean that they would have to download another entire browser just to use the tools. But because of packaging differences and preference some users might be using very different versions, so I may be leaning more towards ESR.

Do you have any insight into this @mrobinson @jdm?

**Comment by sagudev** [comment]
Just to be clear I am not against supporting newer firefox versions, if it does not break last ESR version (can we support both?).

BTW: I daily drive firefox beta.

**Comment by mrobinson** [comment]
> Do you have any insight into this @mrobinson @jdm?

This is a really tricky question. Do you know if the DevTools protocols offers any kind of stability guarantees at all?

**Comment by sagudev** [comment]
> > Do you have any insight into this @mrobinson @jdm?
> 
> This is a really tricky question. Do you know if the DevTools protocols offers any kind of stability guarantees at all?

Per https://firefox-source-docs.mozilla.org/devtools/release.html#remove-backwards-compatibility-code

> we only support connecting to server 2 versions older than the client

**Comment by sagudev** [comment]
Although from my search there are many old stuff not yet removed: https://searchfox.org/mozilla-central/search?q=%40backward-compat&path=&case=false&regexp=false

**Comment by eerii** [comment]
> Although from my search there are many old stuff not yet removed

Yes, I came across many old or deprecated things when I was working on it. I suppose the 2 versions is a lower bound but in reality it is usually longer.

**Comment by ochameau** [comment]
Hello from Mozilla (I'm an employee working on firefox devtools),

We are actively removing backend APIs which are no longer used by the frontend.

In order to keep track of this, we are putting comments in code to remind ourself to cleanup the now-unused codepaths.
You can keep track of all the upcoming removal by looking for ``// @backward-compat` in mozilla-central:
https://searchfox.org/mozilla-central/search?q=%2F%2F+%40backward-compat&path=&case=false&regexp=false
You will notice that some old version have not been cleaned up, that's because we started these cleanups only a few years ago. (See that there is nothing for recent versions)

We are only supporting debugging Release from Nightly, so only two release number difference.
We are not supporting debugging ESR from Nightly.

You can also watch https://bugzilla.mozilla.org/show_bug.cgi?id=1704796 where one bug will be opened per Nightly cycle to do this cleanup (alongside other per-release work).

I imagine here, you have to migrate from `resource-available-form` to `resources-available-array`.
That's actually something I introduced in https://bugzilla.mozilla.org/show_bug.cgi?id=1901643

I could easily have warned you about that particular one.
We might be able to flag bugs on bugzilla to help keep track of such change sooner than later.

**Comment by eerii** [comment]
I opened a PR to fix this specific issue in the newly released version of Firefox, but having a schedule for which version of Firefox we target would make keeping up to date with the breaking changes more manageable.

Also, as discussed in [Zulip](https://servo.zulipchat.com/#narrow/stream/263398-general/topic/devtools/near/472777090), there is this (https://bugzilla.mozilla.org/show_bug.cgi?id=1921118) change request that would allow Servo to get the version of the DevTools client from the browser, which might allow us to extend the support by conditionally sending different messages.
