### ISSUE TITLE
Hosted runners seem to be busted

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#33382]
**Describe the bug:**

When sending a PR to the merge queue, I noticed that tests that should have been passing were failing. The merge queue run is here: https://github.com/servo/servo/pull/33355#event-14183820033

The commit we want to test is ` f47ca27`, but the runner seems to have compiled `938fd8c12f`. I have disabled hosted runners on the Servo repository in the meantime using `NO_SELF_HOSTED_RUNNERS`.

**Comment by sagudev** [comment]
see also chat on zulip: https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Is.20the.20merge.20queue.20broken.3F

I think the problem is that `$env:GITHUB_SHA` is powershell syntax that doesn't get evaluated correctly on linux:
https://github.com/servo/servo/blob/d169a82d2e146704db3d9eb2b5f9f49f9ef8b1da/.github/workflows/linux.yml#L109

**Comment by delan** [comment]
NO_SELF_HOSTED_RUNNERS unset.
