### ISSUE TITLE
Investigate WPT mimesniff tests failing

### ISSUE THREAD

**Issue by msub2** [servo/servo#33467]
While comparing WPT passes between Servo and Ladybird I noticed that Servo didn't seem to be passing any of the mimesniff tests, despite the functionality for doing so existing already. It looks like there's a JSON parse error that's tripping up Servo and preventing any of the subtests from running. Link for ref:

https://wpt.fyi/results/mimesniff/mime-types/parsing.any.html?label=master&product=servo&product=ladybird

**Comment by jdm** [comment]
Interesting. I don't reproduce that json error when running the test locally with `./mach test-wpt /mimesniff/mime-types/parsing.any.html`.

**Comment by msub2** [comment]
It seems the issue is somewhat intermittent. The first time I tried it I got the same behavior as WPT, but on subsequent loads I would sometimes go through all of it, but also sometimes crash part way through. Not sure what to make of that yet

**Comment by jdm** [comment]
Building with `--debug-mozjs` and running the test with `--pref js.mem.gc.zeal.level=2 --pref js.mem.gc.zeal.frequency=10` did not reveal any new information.

**Comment by jdm** [comment]
Based on logging and debugger breakpoints, I believe this failure happens when the [second fetch request]((https://searchfox.org/mozilla-central/rev/f549a50b1e39b1e6bea19912d92545c4c0a06b7b/testing/web-platform/tests/mimesniff/mime-types/parsing.any.js#5-6)) completes before the Promise.all callback has a chance to run. When each network request completes, it calls [Reponse::finish](https://github.com/servo/servo/blob/main/components/script/fetch.rs#L277) which ends up closing the underlying stream. Somehow this causes the behaviour described in https://github.com/servo/servo/issues/33467#issuecomment-2355964279, where the read result apparently gets confused.

**Comment by jdm** [comment]
I found the logic bug that's causing the buffer to start with data from the middle of the file: https://github.com/servo/servo/blob/main/components/script/dom/readablestream.rs#L470-L476
