### ISSUE TITLE
Can't run Servo - PostBuildCommands.run() got an unexpected keyword argument 'flavor'

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33559]
```
$ ./mach run -r
Error running mach:

    ['run', '-r']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

TypeError: PostBuildCommands.run() got an unexpected keyword argument 'flavor'

  File "/home/oriol/src/servo/python/servo/command_base.py", line 637, in configuration_decorator
    return original_function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oriol/src/servo/python/servo/command_base.py", line 654, in target_configuration_decorator
    return original_function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Suspect: #33512 @jschwe

**Comment by jschwe** [comment]
Note that it's probably not just `mach run`, but all commands that are decorated with `@CommandBase.common_command_arguments(binary_selection=True)` and don't take flavor or kwargs as arguments.

I'm not sure what the best way to fix this would be. Short term we could just add `flavor` or `kwargs` parameters to the relevant commands, but e.g. in the case of `mach run` flavor doesn't actually make much sense, since
- flavor is currently on relevant on android / ohos
- on android / ohos there is actually no binary selection during `mach run`, since we assume the user previosly ran `mach install` (installing takes time, so we don't want to reinstall automatically)

Maybe we should add a new parameter kind for common_command_arguments, but since we want to fix the bustage asap, perhaps we just accept flavor on all the affected commands for now, and improve the decorator later?

**Comment by Loirooriol** [comment]
Or just revert the offending patch and figure it out later in a reland.
