### ISSUE TITLE
Create Safe JSContext wrappers

### ISSUE THREAD

**Issue by sagudev** [servo/servo#33759]
based on https://github.com/servo/servo/pull/33718#issuecomment-2402134951:

I think we need to have something like this:

```rust
pub struct SafeJSContext {
    cx: *mut JSContext,
    mt_cx: Arc<Mutex<Option<*mut JSContext>>>,
}

impl SafeJSContext {
    unsafe fn cx(&self) -> *mut JSContext {
        self.cx
    }

    fn thread_safe_cx(&self) -> ThreadSafeJSContext {
         ThreadSafeJSContext {
            cx: mt_cx,
         }
    }
}

// It safe to send jscontext, but only one thread can access most fields so it basically owns jscontext
// hence it does not impl clone
unsafe impl Send for SafeJSContext {}

impl Drop for SafeJSContext {
    fn drop(&mut self) {
         self.valid.lock().unwrap() = None;
         DestroyContext(self.cx)
    }
}

pub struct ThreadSafeJSContext {
    cx: Arc<Mutex<Option<*mut JSContext>>>,
}

unsafe impl Send for ThreadSafeJSContext {}
unsafe impl Sync for ThreadSafeJSContext {}

impl ThreadSafeJSContext {
    // ... impl only thread safe operations

    fn request_int_callback(&self) {
    if let Some(cx) = self.valid.lock().unwrap() {
        JS_RequestInterruptCallback(cx)
    }
}
```

**Comment by sagudev** [comment]
if we just add some stuff from `safejscontext` to https://github.com/servo/mozjs/blob/d9b283cbc2e8d464bef0d32ffc3514915525e56d/mozjs/src/rust.rs#L280 and create ThreadSafeJSContext that would be enough.

**Comment by sagudev** [comment]
there is also: https://github.com/servo/servo/blob/c430645606396a300b57a4d9c909db959486ca4c/components/script/script_runtime.rs#L954

but it's just for passing Ref to cx around without raw ptr.

**Comment by mrobinson** [comment]
Hrm. In this case why not just have `context: Mutex<*mut JSContext>`?

**Comment by sagudev** [comment]
> Hrm. In this case why not just have `context: Mutex<*mut JSContext>`?

To avoid locking on non-MT safe variant.

**Comment by mrobinson** [comment]
> > Hrm. In this case why not just have `context: Mutex<*mut JSContext>`?
> 
> To avoid locking on non-MT safe variant.

Ah, I see. I think as long as the data structure is well documented, guarding the actual pointer itself shouldn't be an issue. Indeed, there is a race condition in the code posted above because the data and the lock are separate. In `ThreadSafeJsContext`, `let guard = self.valid.lock().unwrap();` immediately releases the lock and then you access `self.cx` after. Between these two lines, the main thread could take the lock again and call `let guard = self.valid.lock().unwrap();`. 

 Of course, guarding the pointer would be expensive because the main thread would need to take the lock every time it accesses the `JsContext`.If the data was a pointer to a pointer, `ContextForRequestInterrupt` could take a lock to the pointer to a pointer and hold it while calling `ContextForRequestInterrupt`. Meanwhile the main thread could, take the lock and clear the pointer to a pointer.

**Comment by sagudev** [comment]
> let guard = self.valid.lock().unwrap(); immediately releases the lock and then you access self.cx after. Between these two lines, the main thread could take the lock again and call DestroyContext(self.cx);.

Actually [`lock()`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.lock) returns [LockResult](https://doc.rust-lang.org/std/sync/type.LockResult.html)<[MutexGuard](https://doc.rust-lang.org/std/sync/struct.MutexGuard.html)<'_, T>>, so guard has type `MutexGuard` that will release lock when dropped. But `self.valid.lock().unwrap() = false;` does releases lock immediately, but that's ok, as we set valid to false.
