### ISSUE TITLE
Redirects are not reflected in the embedder history

### ISSUE THREAD

**Issue by webbeef** [servo/servo#33876]
**Describe the bug:**
The history sent to the embedder in the `EmbedderMsg::HistoryChanged(...)` message is not correct when the loaded page was redirected.

**To Reproduce:**

Launch Servo to a redirecting url, eg. https://google.com :

```shell
❯ RUST_LOG=info ./mach run -r https://google.com 
[2024-10-16T23:55:12Z INFO  servoshell::desktop::webview] Devtools Server running on port 6222
[2024-10-16T23:55:12Z WARN  constellation::constellation] Trying to get an event-loop from an unknown browsing context group
[2024-10-16T23:55:12Z WARN  constellation::constellation] Pipeline(1,1): Visibility change for closed pipeline
[2024-10-16T23:55:12Z WARN  webrender::device::gl] Cropping texture upload Box2D((0, 0), (0, 1)) to None
[2024-10-16T23:55:12Z WARN  webrender::device::gl] Cropping texture upload Box2D((0, 0), (0, 1)) to None
[2024-10-16T23:55:12Z WARN  webrender::device::gl] Cropping texture upload Box2D((0, 0), (0, 1)) to None
[2024-10-16T23:55:12Z INFO  net::cookie_storage]  === COOKIES SENT:
[2024-10-16T23:55:12Z INFO  net::http_loader] GET request for https://google.com/
[2024-10-16T23:55:12Z INFO  net::http_loader] got 301 response for "https://google.com/"
[2024-10-16T23:55:12Z INFO  net::cookie_storage]  === COOKIES SENT:
[2024-10-16T23:55:12Z INFO  net::http_loader] GET request for https://www.google.com/
[2024-10-16T23:55:12Z INFO  net::http_loader] got 200 response for "https://google.com/"

```

Observed:

The only `HistoryChanged` message sent to the embedder is:

`HistoryChanged ["https://google.com/"] current=0`

Expected:

The embedder receives `HistoryChanged ["https://www.google.com/"] current=0`

**Platform:**
Not platform specific.

**Comment by rwakulszowa** [comment]
I can take a look, unless this is super complex / already being worked on.

If I understand correctly, the issue here is that the address bar (+ history entries) displays the entered URL, instead of the `Location` field of the 301 response.

### My current understanding

I played with the code for a bit, and here's my limited understanding.

We take the `.load_data` field for the current pipeline:
https://github.com/servo/servo/blob/ea875f0a51551914f85e56945a663ca0e749cc0e/components/constellation/constellation.rs#L4723-L4728

Then pass it to the embedder in `entries`:
https://github.com/servo/servo/blob/ea875f0a51551914f85e56945a663ca0e749cc0e/components/constellation/constellation.rs#L4795
https://github.com/servo/servo/blob/ea875f0a51551914f85e56945a663ca0e749cc0e/components/constellation/constellation.rs#L4804-L4810
reading the `load_data.url` field in the process.

Looking at the definition of `Pipeline`,
https://github.com/servo/servo/blob/ea875f0a51551914f85e56945a663ca0e749cc0e/components/constellation/pipeline.rs#L83-L84
https://github.com/servo/servo/blob/ea875f0a51551914f85e56945a663ca0e749cc0e/components/constellation/pipeline.rs#L71-L74
it seems `Pipeline.load_data` (and `Pipeline.load_data.url`) represents the initial state, while `Pipeline.url` represents the current state.

I tested it locally and it looks like `Pipeline.url` is correctly set to `https://www.google.com`.

Obviously, I don't yet have enough context to understand what's really going under the hood, but am I on the right track? Is reading `Pipeline.url` instead of `Pipeline.load_data.url` the fix, or is something going to explode in the process?

**Comment by rwakulszowa** [comment]
Tested with a local file with a link to https://google.com. Tested also with wikipedia main page - it's got plenty of links with redirects. As far as I can tell, the tweak mentioned above (`Pipeline.load_data.url` -> `Pipeline.url`) makes it work fine. The navigation bar displays the final URL, navigation forward and backwards works correctly.

I'll spend some time reading the code before sending a PR, but I think we can assign it to me.

**Comment by rwakulszowa** [comment]
Ok, so I _think_ using the correct value for that URL will suffice, because that's the only value that's actually read by anyone:
https://github.com/servo/servo/blob/9ad59d14593ec8255fa2b3151fc1037e2dfc31fb/ports/servoshell/desktop/webview.rs#L874-L884

Everything else (`.future` / `.past`) is actually ignored. I guess there's some long term planning behind that code structure, but it's kinda hard to tell what the plan is. Are we passing the whole history, because we want the future browser to be able to display future / past URLs? If so, we probably want them to be resolved correctly. That being said, I believe the current UI won't tell a difference between fixing a single URL and all URLs.

So, my question is: how should I approach this?
1. Fix the current URL by using `Pipeline.url` instead of `Pipeline.load_data.url`, potentially clean up the whole method a bit, removing unnecessary work.
2. Fix all URLs. Using `url` instead of `load_data.url` should be easy in most cases, except `NeedsToReload::Yes`
https://github.com/servo/servo/blob/9ad59d14593ec8255fa2b3151fc1037e2dfc31fb/components/constellation/constellation.rs#L4741-L4747
https://github.com/servo/servo/blob/9ad59d14593ec8255fa2b3151fc1037e2dfc31fb/components/constellation/session_history.rs#L139-L141
It stores a reference to `LoadData` and, according to the comment, its `PipelineId` has been discarded. Would it be enough to just use `LoadData.url` in this case? Will the method be called again when the URL gets resolved to the right value?

Option 2. sounds a bit more future proof, so I'm open to do that.
