### ISSUE TITLE
Layout crash loading https://wallhaven.cc/w/7pzj1y

### ISSUE THREAD

**Issue by webbeef** [servo/servo#33961]
**To Reproduce:**
Load https://wallhaven.cc/w/7pzj1y

Expected: page loads properly

Observed: crash with the following info:

`attempt to multiply with overflow (thread Script(1,1), at components/layout_2020/replaced.rs:621)`

The values are:

`max_inline_size=42408 block_size=172800 max_block_size=36389 inline_size=307200`

This is indeed overflowing the range of a `Au` which is an `i32`. Casting the values on line 621 to `i64` prevents the crash, but is that appropriate?

**Platform:**
Tested on Linux Ubuntu 24.10

**Comment by Loirooriol** [comment]
Testcase:

```html
<!DOCTYPE html>
<canvas height="10000" width="10000" style="max-width: 500px; max-height: 500px;"></canvas>
```

The logic is wrong anyways, because it assumes that the aspect ratio applies to the content box, e.g.

```html
<style>canvas { max-width: 50px; max-height: 50px; aspect-ratio: 1 / 1; box-sizing: border-box; border: solid; }</style>
<canvas style="border-width: 0 50px"></canvas>
<canvas style="border-width: 50px 0"></canvas>
```

| Servo | Blink |
| - | - |
| ![](https://github.com/user-attachments/assets/95ec56b2-6e6f-4c35-8712-3cff5a5ebc9b) | ![](https://github.com/user-attachments/assets/49352dde-a47a-450e-8913-3c4164f256de) |
