### ISSUE TITLE
Devtools: iframes appear in the list of tabs

### ISSUE THREAD

**Issue by webbeef** [servo/servo#34010]
**Describe the bug:**
iframes are listed in as tabs in the devtools, but we should only show top level pipelines.

**To Reproduce:**
- Start with `./mach run -r --devtools=6000`
- Connect Firefox devtools.

Expected:
- A single tab for `https://servo.org/`

Observed:
- 3 tabs: `https://servo.org`, one for `about:blank` and one for the youtube iframe included in the top level document.﻿ I suspect the about:blank one to be the one created when loading the iframe.
<img width="710" alt="image" src="https://github.com/user-attachments/assets/edc9248a-7f17-44f7-9833-432f51919ea9">

**Platform:**
All

**Comment by sagudev** [comment]
cc @eerii

**Comment by brutusyhy** [comment]
The crash seems to be a distinct issue that has to do with minimize window, rather than with inspecting iframe per se. The crash comes from the assertion on line 2323-2333 in "\components\compositing\compositor.rs". Specifically, the webrender_gl's frame_buffer_status should be FRAMEBUFFER_COMPLETE (0x8CD5/36053) but is instead FRAMEBUFFER_INCOMPLETE_ATTACHMENT (0x8CD6/36054).
This crash is predictably triggered in Windows 10 debug build using ./mach build -d, whether running with devtools or not, as soon as you minimize the window. In contrast, if you place the servo window alongside the firefox window, clicking on the non-existent entries prompts an error message on Firefox but will not crash servo.
![No crash when clicking on iframe inspection](https://github.com/user-attachments/assets/55eebf4a-5ee0-4692-8260-2df9a533763e)
Once you click on the minimize button, however, there will be a predictable crash:
![Crash on clicking minimize](https://github.com/user-attachments/assets/eb6bf573-9880-412a-a138-eb416d4fb01d)

**Comment by brutusyhy** [comment]
> Thansk for filing the issue on the "minimize button" action, but that looks unrelated to this one, which is specific to devtools.

Let me try reproducing your bug again: last time it seemed that clicking on the devtools' non-existent entries' inspection will disconnect the devtools, but won't crash servo per se. That's why I was suspecting the issue has to do with rendering rather than devtools itself.

**Comment by fabricedesre** [comment]
We likely need to add the ToplevelBrowserContextId to the `ids` parameters of https://github.com/servo/servo/blob/20ce979c4c9669e1cde270afe8fd72aaa7eda9a4/components/devtools/lib.rs#L281C8-L281C25

**Comment by eerii** [comment]
Hi, thank you for opening an issue for this. Having things that are not tabs listed is definitely an issue, since it can lead to confusion and crashes, I just didn't look into it before since there were other more pressing things at the time, and the minibrowser didn't allow multiple tabs back then.

> We likely need to add the ToplevelBrowserContextId to the `ids` parameters of [`20ce979`/components/devtools/lib.rs#L281C8-L281C25](https://github.com/servo/servo/blob/20ce979c4c9669e1cde270afe8fd72aaa7eda9a4/components/devtools/lib.rs#L281C8-L281C25)

Instead of adding the `ToplevelBrowserContextId` to the function parameters, couldn't we just avoid sending the non top-level context to the devtools in the first place if they are not going to be inspectable? This works as a quick patch.

```diff
diff --git a/components/script/script_thread.rs b/components/script/script_thread.rs
index a367967bd4..4a4494f5b7 100644
--- a/components/script/script_thread.rs
+++ b/components/script/script_thread.rs
@@ -3866,11 +3866,13 @@ impl ScriptThread {
             .unwrap();
 
         // Notify devtools that a new script global exists.
-        self.notify_devtools(
-            document.Title(),
-            final_url.clone(),
-            (incomplete.browsing_context_id, incomplete.pipeline_id, None),
-        );
+        if incomplete.top_level_browsing_context_id.0 == incomplete.browsing_context_id {
+            self.notify_devtools(
+                document.Title(),
+                final_url.clone(),
+                (incomplete.browsing_context_id, incomplete.pipeline_id, None),
+            );
+        }
 
         document.set_https_state(metadata.https_state);
         document.set_navigation_start(incomplete.navigation_start);
```

![image](https://github.com/user-attachments/assets/fbbfd63a-f23a-4692-9816-80f5f40c6882)
