### ISSUE TITLE
Incorrect image alignment on https://servo.org

### ISSUE THREAD

**Issue by nicoburns** [servo/servo#34079]
**Describe the bug:**
The header of https://servo.org has incorrectly aligned images when rendered with Servo (it works fine in Chrome, so this is rendering engine bug). See screenshot below:

<img width="1150" alt="Screenshot 2024-10-31 at 11 59 18" src="https://github.com/user-attachments/assets/e1fc7d0f-e473-4add-aebb-978cce204783">

In both cases it seems like the images are getting "start" alignment rather than "center/middle" alignment. But that might just be a coincidence.

**To Reproduce:**
Load https://servo.org in Servo.

**Platform:**
Presumably all platforms. Tested on macOS.

**Comment by simonwuelker** [comment]
Reduced to
```html
<!DOCTYPE html>
<html>
<head>
  <style>
    .button {
      display: inline-flex;
      justify-content: center;
      outline: 1px solid black;
    }

    .icon {
      height: 2em;
      width: 2em;
      margin: 0 1em;
      outline: 1px solid green;
    }
  </style>
</head>

<body>
  <a class="button">
    <span class="icon"></i></span>
  </a>
</body>
</html>
```
| Servo cc6f7c5bc42c049302480d42a5ebd70f984a1e8e | Firefox |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/88e5f6e6-4740-4b79-be2f-fe488aa13a46)| ![image](https://github.com/user-attachments/assets/74db5932-ba47-4e38-9e6c-358da236a7c3) |

(This is a reduction for the social media icons, it's possible that the misalignment of the servo brand image on the left is caused by something else)
