### ISSUE TITLE
`mozjs` fails to build from source on GitHub hosted runners

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34571]
last good: https://github.com/servo/servo/actions/runs/12255916416

first busted: https://github.com/servo/servo/actions/runs/12261266973/job/34207914801

between them https://github.com/servo/servo/pull/34562 opened, so maybe it busted some caches or smth, can somebody try to clear github CI caches to see if this fixes the issue.

**Comment by sagudev** [comment]
There are no changes in runner images or in action steps hashes (uses directives).

**Comment by mukilan** [comment]
> can somebody try to clear github CI caches to see if this fixes the issue.

I've triggered deletion of all caches using `gh cache delete --all`. It is still running, will update here once it completes.

**Comment by mukilan** [comment]
I'm running into rate limit errors with `gh cache delete --all`. There are still >32K caches remaining, so I don't think it would be possible to delete them all. 

I do see a recent build which has succeeded https://github.com/servo/servo/actions/runs/12270556869/job/34235967250

**Comment by jschwe** [comment]
In my bindgen PR I'm seeing these errors randomly on all jobs on Linux hosts. Very wierd.

**Comment by jschwe** [comment]
> between them https://github.com/servo/servo/pull/34562 opened, so maybe it busted some caches or smth, can somebody try to clear github CI caches to see if this fixes the issue.

CI caches of non default branches don't affect other branches on github AFAIK

**Comment by mukilan** [comment]
It does seem like the issue is related to caching. Things seem better after #34577.

**Comment by jschwe** [comment]
Hmm, I wonder if the recently released sccache 0.9.0 version broke something. In that case we might need to delete more caches, since I have been seeing it also in different pipelines.

**Comment by mukilan** [comment]
> In my bindgen PR I'm seeing these errors randomly on all jobs on Linux hosts. Very wierd.

Do you still see the errors if you run them with sccache disabled?

**Comment by jschwe** [comment]
> I'm running into rate limit errors with gh cache delete --all. There are still >32K caches remaining, so I don't think it would be possible to delete them all.

I'm also running into this in my fork, along with a lot of 503 errors and a very very slow speed in deleting the entries.
I remember that there used to be a key one could press to delete **all** the action caches at once, but that seems to have been removed....

**Comment by mukilan** [comment]
Perhaps we can use the [`SCCACHE_C_CUSTOM_CACHE_BUSTER` environment variable](https://github.com/mozilla/sccache?tab=readme-ov-file#separating-caches-between-invocations) to make sure the existing caches are not used.

**Comment by jschwe** [comment]
I can confirm that servo builds fine again in my fork, after i finally managed to delete the whole cache: https://github.com/jschwe/servo/actions/runs/12304749939/job/34342893828

**Comment by mukilan** [comment]
Nice! I guess we have couple of options:
1) Contact Github support to see if they can delete all caches in servo/servo.
2) Set the [SCCACHE_C_CUSTOM_CACHE_BUSTER](https://github.com/mozilla/sccache?tab=readme-ov-file#separating-caches-between-invocations) variable and see if that helps.
3) Stop using `sscache` for Linux and Android. I see Android jobs typically have ~30% hit rate, so not sure if we are loosing much. The build times might increase by few minutes. I'm not sure about the impact on Linux jobs. Some jobs have ~20% hit rate while few have ~60%.

For 1 and 2, I guess since don't have any idea about the root cause, we can't be sure this will not manifest again.

**Comment by mukilan** [comment]
I wonder if the Try label workflow is causing the cache issues. From the [Github documentation for `pull_request_target` event](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target) (used by the try-label.yml workflow):
> Additionally, any caches share the same scope as the base branch. To help prevent cache poisoning, you should not save the cache if there is a possibility that the cache contents were altered. For more information, see "[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)" on the GitHub Security Lab website.

**Comment by jschwe** [comment]
I also saw the issue on non-try branches for the regular Linux build job.

**Comment by mukilan** [comment]
> I also saw the issue on non-try branches for the regular Linux build job.

Can't that be explained by the fact that all workflows can fallback to the caches of the default (main) branch? The doc warns against saving the cache, presumably because PRs can then write corrupt cache entries to their base branch, which for our PRs is just the `main` branch usually.

But still, I am not sure how that explains the error we are seeing, which seems to be related to `make` issuing a wrong compilation command.

```
2024-12-11T08:42:30.8525685Z   make[4]: *** No rule to make target '/home/runner/.cargo/git/checkouts/mozjs-76be79f630786c2e/daad60b/mozjs-sys/mozjs/build/pure_virtual/pure_virtual.c', needed by 'pure_virtual.o'.  Stop.
2024-12-11T08:42:30.8526903Z   make[3]: *** [/home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/18ab014/mozjs-sys/mozjs/config/recurse.mk:72: build/pure_virtual/target] Error 2
```

The path to `mozjs-sys` source code is different in both lines. The first is under `.../mozjs-76be79f630786c2e/daad60b/..` path while the actual mozjs checkout that the rest of the build uses is under `../mozjs-fa11ffc7d4f1cc2d/18ab014/`. 

The *No rule to make target* error is the only one that references the` ../mozjs-76be79f630786c2e/daad60b/..` path in the whole [build log](https://productionresultssa7.blob.core.windows.net/actions-results/87260054-a42c-4dd6-9b9d-1059e9c16bf0/workflow-job-run-644610c7-6215-5239-0278-ebe8d087ccbb/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-12-15T16%3A47%3A44Z&sig=jwb8SXCkp4bWv36WhuWjLHKgUEDyH1dQESgZvApwCfQ%3D&ske=2024-12-16T01%3A47%3A30Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-12-15T13%3A47%3A30Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-12-15T16%3A37%3A39Z&sv=2024-11-04).

**Comment by mukilan** [comment]
This is happening again in #34629. I think moving away from sccache-action and handling it manually using `actions/cache` and sccache's local backend is probably a better approach as it solves two issues 

1) Little benefit from sccache due to rate limiting of GHA cache service https://github.com/orgs/community/discussions/55049 & https://github.com/Mozilla-Actions/sccache-action/issues/50
2) No support for 'READ_ONLY' mode in sccache's GHA backend to avoid the 'pull_request_target' builds from corrupting base branch's cache. The [local](https://github.com/mozilla/sccache/blob/f3cf79a7f2e814c7fab80913dc1be67d1b5d3234/docs/Local.md?plain=1#L49)  and [Google Cloud Storage](https://github.com/mozilla/sccache/blob/f3cf79a7f2e814c7fab80913dc1be67d1b5d3234/docs/Gcs.md?plain=1#L7) backends have support for this mode though.
