### ISSUE TITLE
CI is busted on new advisories problems

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34764]
Currently this is https://github.com/servo/servo/actions/runs/12471362195/job/34808186467#step:10:32:

> /home/runner/work/servo/servo/deny.toml:230: Unsoundness in `Iterator` and `DoubleEndedIterator` impls for `glib::VariantStrIter`: glib 0.19.9 registry+https://github.com/rust-lang/crates.io-index

**Comment by sagudev** [comment]
maybe we should disable checking advisories in CI: https://github.com/EmbarkStudios/cargo-deny/issues/345#issuecomment-839650712

**Comment by jschwe** [comment]
https://github.com/servo/servo/pull/34447/files switched from `check licenses` to just `check` which includes all checks and whitelisted two advisories. We could whitelist new advisories as they come in (assuming it doesn't happen too frequently), since overall it is still valuable information that should lead to us prioritizing updates of certain dependencies.
