### ISSUE TITLE
Make Constructor and new functions take GlobalRef by value

### ISSUE THREAD

**Issue by Michael03** [servo/servo#4164]
Code in 
components/script/dom/blob.rs
components/script/dom/event.rs
components/script/dom/formdata.rs
components/script/dom/canvasrenderingcontext2d.rs
components/script/dom/progressevent.rs
components/script/dom/urlsearchparams.rs
components/script/dom/websocket.rs
components/script/dom/worker.rs 
components/script/dom/xmlhttprequest.rs

**Comment by mattnenterprise** [comment]
@jdm @Michael03  I have done this for the ones listed above, and I had to change a part in the generated code to pass by value instead. I have a problem where other classes are generated using the part that I changed. It fails to compile because those constructors don't take the GlobalRef by value. Should I change them to also take it by value or what?
Heres the list I am having problems with compiling:
dom/bindings/codegen/Bindings/CommentBinding.rs
dom/bindings/codegen/Bindings/CustomEventBinding.rs
dom/bindings/codegen/Bindings/DOMParserBinding
dom/bindings/codegen/Bindings/DocumentBinding.rs
dom/bindings/codegen/Bindings/DocumentFragmentBinding.rs
dom/bindings/codegen/Bindings/ErrorEventBinding.rs
dom/bindings/codegen/Bindings/KeyboardEventBinding.rs
dom/bindings/codegen/Bindings/MessageEventBinding.rs
dom/bindings/codegen/Bindings/MouseEventBinding.rs
dom/bindings/codegen/Bindings/RangeBinding.rs
dom/bindings/codegen/Bindings/TextBinding.rs
dom/bindings/codegen/Bindings/UIEventBinding.rs

**Comment by jdm** [comment]
Yes, those should be changed too.
