### ISSUE TITLE
Add view-source protocol

### ISSUE THREAD

**Issue by jdm** [servo/servo#4181]
Make a handler that delegates to the HTTP loader then sets the Content-Type header to text/plain!

**Comment by doublec** [comment]
Is anyone working on this? If not, I'd be keen to try.

**Comment by jdm** [comment]
You're welcome to it!

**Comment by doublec** [comment]
I've implemented the suggested approach of having a view-source handler, and modifying the content type to be text/plain if that is used. It's in doublec/servo@a788bcc3.

The content doesn't render as text/plain though as, I assume from issue #3649, it is not treated specially for rendering. Requesting text/plain content formats it as HTML.

Should I pull request this as is? Or look at implementing text/plain beforehand?

**Comment by jdm** [comment]
If you're willing, implementing text/plain would be great! That check probably belongs in ScriptTask::load for now.

**Comment by doublec** [comment]
No worries, I'll get on to text/plain support!

**Comment by doublec** [comment]
Is the a spec or a pointer to the way Gecko does text/plain display? Taking your ScriptTask pointer I hacked in a simple "wrap the text in a <pre> element with '<' escaped" to get something working. This lets me at test that the view-source changes I made work. I've put that in doublec/servo@d953da. The following works:

    ./mach run http://cd.pn/x.txt
    ./mach run view-source:http://tinyvid.tv/

For a better text/plain solution would it be better to build the document up manually in ScriptTask::load instead of parse_html? And is the "put it in a <pre>" approach ok, or is there a better way of building up the document for plain text?

**Comment by SimonSapin** [comment]
Dealing with `text/plain` is specified here: https://html.spec.whatwg.org/multipage/browsers.html#read-text

In particular, the HTML tokenizer has a `PLAINTEXT` mode where it just emits the input as text data and never switches mode again.

**Comment by doublec** [comment]
Aha, thanks, that clears things up.
