### ISSUE TITLE
Implement CSSStyleDeclaration.cssText

### ISSUE THREAD

**Issue by jdm** [servo/servo#4431]
Spec: http://dev.w3.org/csswg/cssom/#dom-cssstyledeclaration-csstext, http://dev.w3.org/csswg/cssom/#serialize-a-css-declaration-block
Code: components/script/dom/cssstyledeclaration.rs, components/script/dom/webidls/CSSStyleDecarlation.webidl

No tests until #4085 merges.

**Comment by jdm** [comment]
Any news, @iterion?

**Comment by iterion** [comment]
So sorry, I got started on this then was swamped with work. Please unassign me - hopefully somebody can finish it faster than I can.

I ran into difficulties getting the cssText to show the original properties, i.e. if border was specified `cssText` would output border-left, border-right, border-top, and border-bottom.

**Comment by yodalee** [comment]
I think I can handle this one.
Just make sure that: Does serialize a declaration already been implemented? something like `serialize_value` function.

**Comment by jdm** [comment]
In this case step 2 means clearing the inline style declarations of the parent element. And yes, step 3 means parsing a declaration block, and you should use the APIs available in `components/style` for that.

**Comment by yodalee** [comment]
Is step 2 means that I should call function `remove_inline_style_property` to every properties get from `get_inline_style_property()` of the element.

**Comment by yodalee** [comment]
So step 2 means that I should call function `remove_inline_style_property(property)` to every properties in the `owner`.

**Comment by jdm** [comment]
Yep!

**Comment by yodalee** [comment]
Is the implementation of `serialize_list()` in the `cssstyledeclaration.rs` same to `serialize-a-css-declaration-block` in spec?
http://dev.w3.org/csswg/cssom/#serialize-a-css-declaration-block

**Comment by jdm** [comment]
serialize_list corresponds to http://dev.w3.org/csswg/cssom/#serialize-a-whitespace_separated-list . I expect you want to implement the ToCss trait for the PropertyDeclarationBlock type in style/properties.rs.mako to match the spec.

**Comment by yodalee** [comment]
Here is some question I met during implementation, and I wanna make sure:
http://dev.w3.org/csswg/cssom/#serialize-a-css-declaration-block
In step 3.3: what does `maps to one or more shorthand properties` means? Since the `PropertyDeclaration` define in seems only map to one property in mod.rs. So property will be one property only.

**Comment by yodalee** [comment]
http://dev.w3.org/csswg/cssom/#serialize-a-css-declaration-block
I wanna ask some question:
1. In steps 3.3, is `property maps to one or more shorthand properties`. I don't get this, since each declaration will map to one css properties, right?
2. Is the description in step 3.3.1: `have a property name that maps to one of the shorthand properties in shorthands.` related to function `longhands_from_shorthand` here?
https://github.com/servo/servo/blob/master/components/style/properties.mako.rs#L5521
3. Steps 3.3.2.4: Does it means that only if we got `current longhands` all important or all normal, then we go to next step 3.3.2.5. Otherwise go back 3.3.2.

***************************
I will explain the steps by my current understanding:
1. If declaration map to single `shorthands` or single `longhand`, serialize it, save it, and record that we have serialize it.
2. If declaration map to multiple `shorthands` (related to question 1), get all the `longhand` property that map to one `shorthands`(related to question 2) and have not been serialized, put into a collection <i>longhands</i>
3. Test each `shorthands`, collect its related `longhand` to collection <i>current longhands</i>.
4. Related to Question 3, if the related <i>current longhands</i> is all important or all normal, then for each  `longhand` in <i>current longhands</i>, serialize it, save it, and record we have serialize it, then go back step 3.

**Comment by yodalee** [comment]
Oh, god this is a long question OAO.

**Comment by jdm** [comment]
1. `border` is a shorthand for `border-color`, `border-width`, `border-style`, etc. Those are all shorthands for `border-top-color`, `border-left-width`, `border-bottom-style`, etc. Does that make sense?
2. Yes.
3. Yes, that is the way I read it.

**Comment by yodalee** [comment]
So declaration.name() will give `border`, and we first convert it to shorthands property `border-color`, `border-width`. In in Step 3.3.1, expand them to longhands property by function `longhands_from_shorthand`.
So the expand is like: `border` ->  `border-color`, `border-width`, and `border-color` -> `border-top-color`, `border-right-color`, `border-bottom-color`, `border-left-color`

**Comment by jdm** [comment]
Yep!

**Comment by yodalee** [comment]
I will transfer this to @Shinglyu due to military training.

**Comment by glennw** [comment]
There is a work in progress branch I started here - it contains enough support to make several sites that rely on cssText work, but it's not spec complete enough to land yet.

https://github.com/glennw/servo/tree/csstext

**Comment by jdm** [comment]
@glennw I see the following bits are incomplete:
* the cssText getter doesn't expand shorthand properties
* the cssText setter iterates over normal twice, rather than normal/important (oops!)
* the cssText setter doesn't append rules in specified order

Is there anything else I'm missing?

**Comment by jdm** [comment]
Note: the specified order problem is a limitation of the current design of the CSS parser as far as I know.

**Comment by glennw** [comment]
@jdm I haven't taken a really detailed look at the spec, but that sounds correct to me. Thanks for looking over it!

**Comment by glennw** [comment]
@jdm I pushed a slightly modified branch, that contains the fix suggested by @SimonSapin and therefore fixes issue (2) you listed above.

In regards to (1) it does expand shorthand properties - in that the existing parsing code results in the declarations block containing longhands only (e.g. style.cssText = "background: red;" results in a declarations block with 8 entries in it, one for each longhand).

However, if I'm understanding the spec correctly, the behaviour above is a problem - we need to maintain the original information about whether a shorthand or longhand was provided in order to follow the spec serialization steps. Does that sound right to you? I will have another read of the spec too - perhaps I'm missing something obvious?

**Comment by jdm** [comment]
You're correct that my original comment is incorrect. However, I don't believe we need to retain any information about expansions that occurred previously. The serialization steps at https://drafts.csswg.org/cssom/#serialize-a-css-declaration-block explain it thus:
* for each longhand property encountered, make a list of all shorthand properties that it is part of
* for each such shorthand property, if all related longhand properties are present, serialize the values of each longhand property such that a conforming longhand property results and can be serialized
* serialize any longhand properties that are not dealt with by previous steps

**Comment by g-k** [comment]
I can give this a shot if no one else is working on it.

**Comment by jdm** [comment]
Go for it! Please ask questions about anything that's unclear :)

**Comment by jdm** [comment]
At least one test you can run is `./mach test-css tests/wpt/css-tests/cssom-1_dev/html/cssom-cssText-serialize.htm`. Another is `./mach test-css tests/wpt/css-tests/cssom-1_dev/html/index-001.htm`. Looks like `./mach test-css tests/wpt/css-tests/cssom-1_dev/html/` may be useful in general.

**Comment by g-k** [comment]
OK I rebased Glenn's branch (https://github.com/servo/servo/pull/5597 doesn't look related) and got started here: https://github.com/servo/servo/compare/master...g-k:csstext?expand=1

I think the CSS property name shortening is more or less correct for normal CSSStyleDeclarations though I need to clean the code up.

I'm seeing test failures for `color: RED;` vs. color: red;`, `font-size: 10pt` vs. `font-size: 13.333333px`, `font-weight: bold` vs. `font-weight: 700` and things like that.  

* Are css property grammars exposed anywhere (specifically whether a property is whitespace vs. comma separated and what default values it uses)?
* Does `PropertyDeclaration::value` and `value.to_css_string` implement https://drafts.csswg.org/cssom/#serialize-a-css-component-value or is `cssText` more of a pretty print?
* Should I try to change ToCSS implementations? Would that break layout (I have a few crashing tests as it is)?

**Comment by nox** [comment]
Staaahp. Isn't that the same thing as #9410? :/

Cc @craftytrickster.

**Comment by g-k** [comment]
oh noes!  I suppose this built character or something.  : |

Once #9410 lands I guess I can just add bindings for the cssText getter and setter.

**Comment by jdm** [comment]
#9410 merged (via #11377), so what's left to do here?
