### ISSUE TITLE
Implement the Fetch specification: infrastructure.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4576]
<https://fetch.spec.whatwg.org/>, excluding the `fetch()` API.

**Comment by KiChjang** [comment]
Is anyone working on this? I'd like to try this one out if not.

I'm guessing I will have to refactor `script/cors.rs` into a new file called `fetch.rs`, along with new `fetch` functionality, yes?

**Comment by jdm** [comment]
@KiChjang This would be a great project for you to take on :) @Manishearth has the details, since he did the initial work, but he has a million other things to work on.

**Comment by Manishearth** [comment]
Yeah, you can work on this :) I really wanted to work on this but as Josh said I have a million other things to do.

I personally would wait for @jdm's async net changes to land, but you can incrementally implement most of Fetch beforehand, especially the little bits and pieces like `is_simple_method()`, `is_simple_header()` (and all of the stuff like redirect handling, etc). You can also just go ahead and implement it with the intention to make it work with async net changes later. Either works.

Just to give a broad overview of what a completed version:

 - Most of fetch.spec.whatwg.org to be implemented in the fetch module in `net`. It should be structured similar to how the spec is structured, so that updates to the spec can be reflected easily.
 - Extremely little CORS code in script. `cors.rs` should die
 - Extremely little Fetch code in script. XHR should contain all the stuff on xhr.spec.whatwg.org, and whenever it says "Fetch foo", that should just be implemented as a call into `net::fetch` or something. Of course, post the async net changes it might be slightly more complicated than that, but basically we want very little net code in script.
 - Ideally the Fetch API would be generic -- so features of the API which XHR (our only consumer of fetch right now) doesn't use should still be implemented as much as possible. Eventually stuff like `img` and `iframe` will be using Fetch (as well as `fetch()`) spec-wise, so we want them to be able to reuse the same code. 


Mostly it is straightforward, since the spec is pretty clear cut. Spec questions can go to annevk in #whatwg (on Freenode). The hard part is figuring out how to make it interface with the rest of the code -- XHR and other things need to be able to consume the data as it comes in, so we need some sort of pipelining. The resource task already provides channels on which to listen to for bits of data, so we could use the same design, but again, jdm's async changes provide a better (but more confusing) API so you should probably use that.

Feel free to ask any further questions!

**Comment by Manishearth** [comment]
(Oh, also, you can reuse the existing code in `net::fetch`, or just rewrite it, either works :) )

**Comment by gobengo** [comment]
Cool to see recent activity on this, I was just wondering about it today.

Maybe silly question. The origin post on this PR says 'excluding the fetch() API'. Why wouldn't servo also implement the fetch() API? Is that the role of another layer of a browser engine?

**Comment by jdm** [comment]
The `fetch` API relies on Promise values, which Servo doesn't support yet.

**Comment by KiChjang** [comment]
Okay, I'm now moving on to implement `main_fetch`, and I see that in `net/fetch/response.rs`, there's code that implements rudimentary features of asynchronicity (`ResponseLoader`, `ResponseMsg`). How am I to integrate this to the `fetch` methods that require parallel processing? Also, should the `fetch`/`main_fetch` methods return a `Response` or `ResponseLoader`, or something else altogether? Should these `fetch` methods also take in an additional callback method as a parameter?

**Comment by Manishearth** [comment]
You probably should rewrite the skeleton Fetch code which I wrote ages ago.

We should probably use http://doc.servo.org/net_traits/index.html, specifically by feeding to http://doc.servo.org/net_traits/trait.AsyncResponseListener.html and friends.

https://github.com/servo/servo/pull/5156 is the PR that introduced those, you might want to quickly go through that to figure out how these can be used. Feel free to ask me/Josh for clarifications!

**Comment by KiChjang** [comment]
Wow, the spec has changed since I last worked on this. Some flavors of fetch are outdated.

Either way, should I copy the style in #7275 for async fetch requests going forward?

**Comment by KiChjang** [comment]
Also, there's a line left by @Manishearth [here](https://github.com/servo/servo/blob/master/components/net/fetch/request.rs#L98) that purposely avoids cross-referencing the script's `GlobalRef` object. I've been using a hack to get around this problem in `http_fetch`, by adding an additional parameter and field called `is_service_worker_global_scope`, but it would be advantageous to address this issue now, since other `fetch`es are quite dependent on `client` being an actual [environment settings object](https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object).

**Comment by jdm** [comment]
The way to address it is to pass any contextual information that is required. We explicitly do not want to (and can't!) make the net crate depend on the script crate, so let's just be explicit about the actual data we need.

**Comment by jdm** [comment]
If need be we can design a trait that provide the interface to communicate with a relevant script event loop on an as-needed basis.

**Comment by jdm** [comment]
This exists now, as demonstrated by XHR using said infrastructure.
