### ISSUE TITLE
Yell loudly when Cargo.toml dependencies don't match the list of extern crates

### ISSUE THREAD

**Issue by jdm** [servo/servo#4644]
Cargo's great as long as your declared dependencies in Cargo.toml actually reflect reality. There should be some way of preventing us from doing this wrong. Maybe it belongs in Cargo, maybe it belongs in tidy.py?

**Comment by Manishearth** [comment]
I'm tempted to hook tidy up with `espeak`/`say` here :stuck_out_tongue: 

Another option is to pluginify it -- use the same toml parser Cargo uses to parse the `Cargo.toml` and then just inspect the view item (this would be something that Cargo itself could optionally include via `-Z extra-plugin`).

Though this should probably be easier to do with `tidy` since python has everything.

**Comment by jdm** [comment]
Cargo's much better about this now. There are other issues filed about ensuring that we don't declare needless dependencies, but otherwise the situation is fine.
