### ISSUE TITLE
tabs in <pre> not shown

### ISSUE THREAD

**Issue by benwaffle** [servo/servo#4651]
something like this (but with a `\t`)
```html
<html><body><pre>		test</pre></body></html>
```

**Comment by jdm** [comment]
This is likely the `TODO: set "has tab" flag` in `transform_text` in `gfx/text/util.rs`.

**Comment by mskrzypkows** [comment]
I've checked that adding space to output_text in util.rs where jdm mentioned, causes adding indention, so that's the place which causes missing tabs. Now, to fix this I have to add flags as in: http://mxr.mozilla.org/mozilla-central/source/layout/generic/nsTextFrameUtils.cpp#69 but I didn't find any apropriate flags enum, so do I need to implement such an enum, in which module than?

**Comment by jdm** [comment]
No concrete answers yet; I've been looking at the equivalent Gecko code and found that the flag from http://mxr.mozilla.org/mozilla-central/source/layout/generic/nsTextFrame.cpp#2009 is used later at http://mxr.mozilla.org/mozilla-central/source/layout/generic/nsTextFrame.cpp#2069, and this new flag is used in places like http://mxr.mozilla.org/mozilla-central/source/gfx/thebes/gfxTextRun.cpp#287 (and others in that file). So we presumably would need to return certain flags from `transform_text` that get propagated to our text run creation code, which can then use it in places like http://mxr.mozilla.org/servo/source/components/gfx/text/text_run.rs#212 (presumably). Maybe @pcwalton has more specific suggestions?
