### ISSUE TITLE
android build fails to run due to missing symbol X509_gmtime_adj

### ISSUE THREAD

**Issue by glennw** [servo/servo#4700]

**Comment by mbrubeck** [comment]
This is still happening post-rustup.  `X509_gmtime_adj` is an OpenSSL function, so this must be a problem with how we are building and linking OpenSSL.

**Comment by mbrubeck** [comment]
This is fixed by sfackler/rust-openssl#153, but we need to upgrade Rust before we can use a version of rust-openssl with that fix (or fork rust-openssl and packages that depend on it, in order to backport the fix).

Alternately we might be able to work around for now by setting flags in our `.cargo/config` as suggested in sfackler/rust-openssl#107.

**Comment by jdm** [comment]
Is this still a problem?

**Comment by mbrubeck** [comment]
Fixed during the latest Rust upgrade.
