### ISSUE TITLE
Don't rebuild all of the tests when we're just running the reftests

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#4892]
```
1:28 PM <@mbrubeck> larsberg: The test-ref command calls ensure_built_tests, which runs `cargo test --no-run` to build *all* the tests.
1:29 PM <@mbrubeck> https://github.com/servo/servo/blob/master/python/servo/testing_commands.py#L143
1:29 PM <Manishearth> mbrubeck: we really shouldn't be using cargo for non-unit tests
1:29 PM <@mbrubeck> https://github.com/servo/servo/blob/master/python/servo/build_commands.py#L148
1:29 PM <@mbrubeck> I agree
1:29 PM <Manishearth> That's sort of the point of mach vs makefiles
```

Should just be a change to the python files listed in the above conversation.

**Comment by mbrubeck** [comment]
One solution would be to make the reftest harness a separate Cargo crate with its own Cargo.toml, and build it by running `cargo build` in the tests/ref directory.

Whatever we do for test_ref should also be usable for test_content.

**Comment by gilles-leblanc** [comment]
I'd like to work on this please.

**Comment by gilles-leblanc** [comment]
I have started working on this and I have a problem which I'm not sure how to solve. 

While creating a crate for reftest I added the rust-png dependency in the Cargo.toml file. The problem is rust-png itselfs depends on gcc-rs and the version locked by Cargo of gcc-rs (0.2.1) doesn't build with our version of Rust. 

If I check in the .lock files of the other servo crates that depend on png, the version locked is 0.1.7. 

Since the .lock file is auto-generated, I'm not sure what to do. I noticed that there was a change in servo/rust-png to point to the upstream gcc-rs rather than the servo one. 

Should I make a change to rust-png to have it require version 0.1.7 of gcc-rs ?

**Comment by jdm** [comment]
If necessary, you should be able to hand-edit the Cargo.lock file to use the version you require.

**Comment by mbrubeck** [comment]
Hmm, I just realized this means that we are rebuilding *all* the dependencies again just for the reftest harness.  This cure might be worse than the disease, at least until rust-lang/cargo#482 is fixed. :(

**Comment by gilles-leblanc** [comment]
Then, I'll put it on hold until we can get target directory sharing from Cargo.

**Comment by jdm** [comment]
The above-mentioned Cargo issue is fixed, so this may be worth looking into once more.

**Comment by SimonSapin** [comment]
Reftests with our custom harness are slowly moving into WPT, so this is becoming less important IMO.

**Comment by jdm** [comment]
Yeah, this isn't worth spending time on.
