### ISSUE TITLE
Move body of ScriptTask::dispatch_key_event into a method on Document

### ISSUE THREAD

**Issue by jdm** [servo/servo#4982]
The vast majority of the method has nothing to do with the script task and everything to do with the document that is the target of the event. It will be a little bit tricky because of the `self.compositor.borrow_mut().send_key_event(key, state, modifiers);` line, but that can just be passed as an argument to the new method for now (`RefMut<Box<ScriptListener+'static>>`, probably).

**Comment by KiChjang** [comment]
Let me try this `RefMut<Box<ScriptListener+'static>>` thing.

**Comment by KiChjang** [comment]
Not as simple as thought, whenever I tried to simply pass `self.compositor.borrow_mut()` to `dispatch_key_event` located in `document.rs` and use it as `compositor.send_key_event(key, state, modifiers)`, the compiler gives me an error `cannot borrow immutable local variable 'compositor' as mutable`... but it clearly is mutable at this point because `compositor` is being passed as a `RefMut`!

**Comment by jdm** [comment]
You can make the argument mut - `mut foo: Foo` is valid.
