### ISSUE TITLE
Shim localStorage using a separate SessionStorage instance

### ISSUE THREAD

**Issue by jdm** [servo/servo#5195]
Since localStorage and sessionStorage are both Storage instances, we can easily support localStorage for now by just creating a new Storage instance for it.

Code: http://mxr.mozilla.org/servo/source/components/script/dom/webidls/Window.webidl#131, http://mxr.mozilla.org/servo/source/components/script/dom/window.rs

**Comment by zslayton** [comment]
I'd like to work on this.

**Comment by jdm** [comment]
Go for it!

**Comment by zslayton** [comment]
@jdm, taking an initial look through this it would appear that any instance of `Storage` would send its `StorageTaskMsg`s to that window's lone `StorageTask` instance, e.g:

```rust
self.get_storage_task().send(StorageTaskMsg::Length(sender, self.get_url())).unwrap();
```
 If that's the case, I believe we would need to have a separate `StorageTask` for each of `sessionStorage` and `localStorage`, otherwise all of the values stored would be in a common instance of `StorageManager::data`. Does that sound accurate?

**Comment by jdm** [comment]
@zslayton Instead of a separate task, it probably is clearer to add an extra parameter to the messages indicating which type of storage should be used, and have multiple hashmaps in the storage task.

**Comment by zslayton** [comment]
@jdm Thanks, I'll do that! This is my first attempt at a non-cleanup patch and I'm not sure I fully grasp how Storage is being instantiated. If I were to create an enum to indicate which storage type to use for each method:
```rust
enum StorageType {
  Local,
  Session
}
```
, how could I get an instance of the appropriate variant into each instance of the Storage class that the Window creates? (Sorry to post this here rather than on IRC, I have to run and wanted to get the question out.)

**Comment by jdm** [comment]
You would add it as an argument to the Storage::new constructor, and store it in a field inside Storage::new_inherited. Then you can pass it as part of each request to the storage task.
