### ISSUE TITLE
Make PipelineId a pair of PipelineId and Option<SubpageId> 

### ISSUE THREAD

**Issue by jdm** [servo/servo#5235]
This would conceivably allow us to move all subpage-related modification out of script and into the constellation, where it arguably belongs.

**Comment by jdm** [comment]
Blocks #5235.

**Comment by frewsxcv** [comment]
I'll take a stab at this right now

**Comment by glennw** [comment]
I was thinking something like:

```
struct PipelineId {
    window_id: WindowId,
    subpage_id: SubpageId,
};
```

And then have the HTMLIFrameElement code be the one that generates the unique pipeline id, since that would simplify a number of other things in the future.

@jdm does that sound reasonable to you? It might hit an unforeseen roadblock, but it sounds like that could work.

**Comment by jdm** [comment]
@glennw So the iframe would get the window id from the window, and create the new subpage id? That sounds reasonable to me.

**Comment by glennw** [comment]
Yes, the window_id would be set once on each window creation, and the window would contain the subpage counter (as it does now) which the iframe would query/increment.

**Comment by frewsxcv** [comment]
FYI, I didn't feel I have the knowledge to complete this right now, so I'm no longer working on it

**Comment by KiChjang** [comment]
I can take a look at this one.

**Comment by KiChjang** [comment]
I just took a look at the previous PR, and I came across with the usage of the new `WindowId` struct. How and where is it going to be used and created?

**Comment by benschulz** [comment]
In its current form this issue seems to contradict #5241.

As far as @KiChjang's question is concerned, my interpretation is as follows. The constellation manages a (bijective) mapping from `PipelineId` to `WindowId` by incrementing a counter for each new `PipelineId` it receives from `ScriptLoadedURLInIFrame` messages. Then it sends the generated `WindowId` as part of the `AttachLayout` message. However, I'm not 100% certain that's right.

Assuming you get an answer to your question, will you continue working on this, @KiChjang?

**Comment by KiChjang** [comment]
You can go ahead and work on this issue, I have plenty of other stuff on my plate right now.

**Comment by glennw** [comment]
This is handled a different way now - iframes are able to generate their own PipelineId.
