### ISSUE TITLE
Address wpt expectation: instead of crash, expect an Exception 

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5467]
== How to reproduce ==

a) Execute location interface wpt tests: 
./mach test-wpt --include html/browsers/history/the-location-interface/

b) Inspect the output for security_location_0.sub.htm
(or look in tests/wpt/metadata/html/browsers/history/the-location-interface/security_location_0.sub.htm.ini)

The output will be:  
0:03.14 CRASH: Thread-TestrunnerManager-5 pid:53240. Test:None. Minidump anaylsed:False. Signature:[/html/browsers/history/the-location-interface/security_location_0.sub.htm]

== Expected result ==

The test should execute and return, as the relevant spec (https://html.spec.whatwg.org/multipage/browsers.html#security-location) requires the UA to raise an exception (i.e. SecurityError, see: https://html.spec.whatwg.org/multipage/infrastructure.html#securityerror).

The current behavior in servo is to panic/crash, which is non conforming to the spec.

**Comment by Adenilson** [comment]
@jdm and @jgraham FYI.

**Comment by jdm** [comment]
I don't think there's much point in opening this issue right now. The panic occurs right now because we don't like fetching URLs that don't resolve to a valid HTTP connection. The SecurityError described comes from a totally different part of the test. There's a totally different issue, which is that this test shouldn't be causing us to make an invalid HTTP connection - that's an issue in Servo, not the test, however.
