### ISSUE TITLE
Scroll speed too low

### ISSUE THREAD

**Issue by narfg** [servo/servo#5660]
Commit 9f3b3083817c2ac5b2aaf683c9ebe85c03571f82 made scrolling with the mouse wheel annoyingly slow. To be specific, this is not a performance problem but the scroll step size is too low.
I use Linux so this issue may be dependent on the OS.

**Comment by jdm** [comment]
cc @glennw and @pcwalton

**Comment by jdm** [comment]
Perhaps this is something that should be normalized in glutin, so we don't need to postprocess the received scroll events?

**Comment by pcwalton** [comment]
Agreed with @jdm. As of now we do no munging of the scroll distance in Servo--we treat the events as describing pixels--so any fixes should be on glutin's side.

**Comment by frewsxcv** [comment]
Related to scrolling speed #5320

**Comment by robertknight** [comment]
Brief notes on Qt/Gtk+/Chromium behaviors:

* Glutin currently sends a scroll wheel event with delta values of +/-1 for each event on Linux, whereas the Windows/Mac implementations use the delta values from the Cocoa / WinAPI event.
* Qt uses a fixed value of +/- 120 as the delta for each event
* Chromium uses a fixed value of +/- 53 as the delta (see https://code.google.com/p/chromium/codesearch#chromium/src/ui/events/x/events_x.cc&l=33) with a note that this was taken from Gtk+ , but uses device-provided values from XInput the device supports it.
* Current Gtk+ appears to do the proper thing and read it from Xinput, so it looks like that should return the data reported by `xinput list-props <mouse/touchpad device ID>`

**Comment by nnethercote** [comment]
I just hit this. I would have guess it was 100x slower than before but looking at commit `9f3b308` I guess that's a 3.33x overestimate :)

**Comment by mrobinson** [comment]
I think the issue is that there are two kinds of mouse wheel movements. There are "ticks," which is what mice traditionally send. Ticks are essentially the height of a line. Different toolkits and browser interpret these in different ways. Apple mice and some XInput devices may also have a precise value which is an absolute number of pixels to move. The core of the problem seems to be glutin cannot detect the precise events and sends a naked number when the number may either refer to ticks or absolute pixels. Thus, Servo doesn't know how to interpret the number in the wheel event.

**Comment by mrobinson** [comment]
There is more information here: https://github.com/tomaka/glutin/pull/451
