### ISSUE TITLE
Create a gfx_traits crate for shared types

### ISSUE THREAD

**Issue by jdm** [servo/servo#5698]
In particular, gfx::color is a big offender. The canvas crate depends on it, which causes script to be rebuilt when gfx is modified. If we move it to gfx_traits instead, that will help a lot. See #5465 for a similar effort.

**Comment by boghison** [comment]
What exactly are the shared types that need to be moved?

**Comment by jdm** [comment]
Types/functions that are used by other crates. An easy way to find these is searching for "use gfx::": http://mxr.mozilla.org/servo/search?string=use%20gfx%3A%3A

**Comment by boghison** [comment]
I'll take this, I guess

**Comment by boghison** [comment]
BTW, where's the debug macro from?

**Comment by boghison** [comment]
How could I solve the "includes itself" issue?

**Comment by jdm** [comment]
Could you be more specific? :)

**Comment by boghison** [comment]
Well, for example, I need to use gfx_traits::color in gfx/paint_context, but I can't add gfx_traits as a dependency in gfx, because gfx_traits depends on gfx (for example buffer_map).

**Comment by jdm** [comment]
Oh, that dependency is the wrong way round. gfx should depend on gfx_traits.

**Comment by boghison** [comment]
But what about the code that gfx_traits needs, I don't even understand the point of splitting gfx

**Comment by jdm** [comment]
Here's the point - today, if you change code in gfx/ we have to rebuild a lot of other crates that depend on it. In an ideal world, every crate (including gfx) that needs types/methods from gfx would depend on gfx_traits, where they would be defined. That would mean that any non-public changes to the gfx code do not require rebuilding every other crate. Right now, we can improve the situation by making a few crates (like canvas) depend on gfx_traits instead. Does that make sense? gfx_traits should be as close to standalone as possible, like script_traits, net_traits, etc.

**Comment by boghison** [comment]
@jdm Yes, that does make sense, but it still raises issues because of dependencies. If gfx is dependent on gfx_traits, the code in gfx_traits can't access the code in gfx, which means that the code that isn't public still needs to be copied or moved into it's own crate for the public types in gfx_traits to be able to use it. Again, the same example: gfx needs gfx_traits::color, which is fine, since gfx is dependent on gfx_traits, but gfx_traits::paint_task::PaintTask needs the BufferMap from gfx, so how does one deal with this?

**Comment by jdm** [comment]
@boghison I see what you mean. In this case, I would suggest moving the definition of the PaintRequest and BufferMap types to gfx_traits.

**Comment by boghison** [comment]
@jdm I think this is just too much work, could you please remove the label so that someone else would take the issue?

**Comment by boghison** [comment]
Also, to whomever might take this issue, feel free to use [this](https://github.com/boghison/servo/commit/47bfca4058f578b48a575ddc688923b4301704d5) commit as a head start :)

**Comment by ktt3ja** [comment]
I spent some time working on this, but dividing this crate up isn't very straightforward.

Since the `canvas`, `compositing`, and `servo` crates only depend on `gfx::color`, `gfx::paint_task`, and `gfx::font_cache_task`, I started by moving types in those files. However, I ended up having to move everything in `gfx::font_cache_task` over, which makes me bring in things from `font_template` and the `platform` module. Then `platform::font` in turn requires bringing things from `text` module over. 

At this point it feels like the number of things that have to be moved over to `gfx_traits` maybe too many, which defeats the purpose of creating this crate.

**Comment by boghison** [comment]
@ktt3ja Yes, I stumbled upon that as well

**Comment by jdm** [comment]
Yes, I suggest starting with just fixing `canvas` since it's the biggest problem here. `servo` definitely should not be changed, since it's the top-level crate.

**Comment by jdm** [comment]
That being said, it's looks like at least FontCacheTask could be moved into gfx_traits without much effort - the `Command` enum only uses a small number of other types that need to be moved as well.

**Comment by ktt3ja** [comment]
`FontCacheTask` impl uses `FontCache`, though, which is what's pulling in all these dependencies.

I think the only dependency I know how resolve is from `canvas`, but then this `gfx_traits` crate would only have `color`. :P

**Comment by jdm** [comment]
Oh, I see what you mean now. If you define a FontCacheTaskHelpers trait in gfx_traits which has the methods in the FontCacheTask impl, you can leave the actual implementation in gfx and break the dependency on FontCache that way.

**Comment by jdm** [comment]
This has turned out to be the opposite of easy in #6685.
