### ISSUE TITLE
Inexplicable unrooting ordering error

### ISSUE THREAD

**Issue by nox** [servo/servo#5720]
In the following code, if we remove the next_sibling binding and root the value directly where it's used, Servo crashes with an unrooting ordering error.

``` rust
    // https://dom.spec.whatwg.org/#dom-childnode-after
    fn after(self, nodes: Vec<NodeOrString>) -> ErrorResult {
        match self.parent_node().root() {
            None => {
                // Step 1.
                Ok(())
            },
            Some(ref parent_node) => {
                // Step 2.
                let doc = self.owner_doc().root();
                let node = try!(doc.r().node_from_nodes_and_strings(nodes)).root();
                // Step 3.
                let next_sibling = self.next_sibling().root();
                Node::pre_insert(node.r(), parent_node.r(),
                                 next_sibling.r()).map(|_| ())
            },
        }
    }
```

**Comment by nox** [comment]
Removing the ref pattern in `ref parent_node` also makes the code fail and should probably be detected in a lint pass.

**Comment by nox** [comment]
See https://github.com/servo/servo/pull/5721.

**Comment by jdm** [comment]
https://github.com/servo/servo/issues/5720#issuecomment-93809245 is covered by #5724.

**Comment by Manishearth** [comment]
Okay, I still can't figure out why this happens. I bet a debugger would give some insight, but for now I'll focus on improving rvalue checks in tenacious. Clearly ignoring rvalue moves is bad (we had figured this out yesterday but thought it wouldn't be a big issue). I'm considering linting on all rvalue moves *except* for those of the type `let foo = generate_root()`. That might be a tad overzealous, but it should also fix our rooting order problems completely, because AFAICT rvalues are the only case where destructors don't run in RAII order. (e.g. `let x = generate_root().func().generate_more_root()`)

**Comment by frewsxcv** [comment]
Worth mentioning that the code originally pasted above is now removed (#6800)

**Comment by michaelwu** [comment]
DOM roots no longer need to be unrooted in order, so I don't think this is a problem anymore.
