### ISSUE TITLE
Investigate if the check for '/' in step 7 for Cookie::new_wrapped is correct

### ISSUE THREAD

**Issue by jdm** [servo/servo#5944]
```
    If the cookie-attribute-list contains an attribute with an
    attribute-name of "Path", set the cookie's path to attribute-
    value of the last attribute in the cookie-attribute-list with an
    attribute-name of "Path". Otherwise, set the cookie's path to
    the default-path of the request-uri.
```

This warrants further investigation.

**Comment by frewsxcv** [comment]
[Link to the line in question](https://github.com/servo/servo/blob/db2eb36e19581eee83247160bbb03e2a671d0479/components/net/cookie.rs#L70)

**Comment by nox** [comment]
The check is [correct](https://tools.ietf.org/html/rfc6265#section-5.2.4), but maybe misplaced, or maybe the attribute is ignored altogether in the cookie crate itself.

**Comment by nox** [comment]
AFAICT the cookie crate doesn't do it itself. Should the parser ignore `Path` attributes that don't start with a `/`, @alexcrichton?

**Comment by alexcrichton** [comment]
cc @SergioBenitez

**Comment by SergioBenitez** [comment]
@nox The `cookie` parser should _not_ ignore `Path` values that do not begin with '/'. The grammar for `path-value` does not require a '/' as the first character ([RFC6265 4.1.1](https://tools.ietf.org/html/rfc6265#section-4.1.1)). The `cookie` crate cannot default the cookie attribute value to `default-path` since it obviously lacks this context. As such, I believe the best thing to do is to forward the information upward so that the dependent library (here, servo) can make an informed decision.

**Comment by nox** [comment]
Ok, I see, so that step is correct, and the cookie crate shouldn't do anything different.
