### ISSUE TITLE
Build for Adroid Failing - tenacious

### ISSUE THREAD

**Issue by JasonWeathersby** [servo/servo#5984]
I am getting this error will using ./mach build --android

error: extern location for tenacious does not exist: /Users/jweathersby/servo/servo/components/servo/target/debug/deps/libtenacious-77ae4415b1d0cf4d.so
/Users/jweathersby/servo/servo/components/plugins/lib.rs:22:1: 22:24 error: can't find crate for `tenacious`
/Users/jweathersby/servo/servo/components/plugins/lib.rs:22 extern crate tenacious;

**Comment by larsbergstrom** [comment]
What platform are you on (OSX or Linux)?

Also, are you on master up to this commit - https://github.com/servo/servo/commit/02cf89f4d3fb991a27ecbaf8d3cafe5722750cc6
?

OSX->Android was broken until that landed. Linux->Android should be working because we have a build machine that tests it.

Also also, if you have an existing build, you make need to `./mach clean` between android and non-android builds. Sorry for the inconvenience!

**Comment by Manishearth** [comment]
It's a .so file so he should be on Linux? We did land the Tenacious fixes on osx so that should be fixed.

**Comment by larsbergstrom** [comment]
@Manishearth cargo (the version we have) was looking for a .so file even on OSX due to that dylib thing, which is part of what was breaking us, if I understand all of alex's fixes correctly...

**Comment by JasonWeathersby** [comment]
That worked to get me past that issue. I get the note: Missing Tool `/opt/ndk_standalone/bin/arm-linux-androideabi-gcc`! option now :)

**Comment by larsbergstrom** [comment]
Great, thanks!
