### ISSUE TITLE
embedding: pointers being set wrongly

### ISSUE THREAD

**Issue by zmike** [servo/servo#5998]
In ServoCefBrowserExtensions::init(), there is the line self.downcast().host.set_browser((*self).clone()); which is supposed to set the browser object into the browser_host object. What actually happens is that it sets a block of zeroed/filled memory as the browser_host's browser object; something to do with how we're setting/passing the browser object here. I imagine there are similar cases.

This crashes any embedding application which tries to access the related object.

@pcwalton @jdm

**Comment by pcwalton** [comment]
I don't know what is happening off the top of my head.

**Comment by jdm** [comment]
I took a look and am at a loss.

**Comment by larsbergstrom** [comment]
Mike informs me that it's filled with not zeros, but 0x1D. I suspect that the value is being dropped too early, since that's the filling_drop value:
https://github.com/rust-lang/rust/blob/7132092ce6e954eb58d490fa886d0865c5cfba38/src/libcore/mem.rs#L375


Also, the relevant code is this line: 
https://github.com/servo/servo/blob/c42c2ae9b57b5960ce617e5b4c0ab75959e46957/ports/cef/browser.rs#L139

**Comment by zmike** [comment]
Ughhhh this ended up being a lifetime thing where the object was getting destroyed in one of the interface functions with no errors in rustc.
