### ISSUE TITLE
714M of test data?

### ISSUE THREAD

**Issue by Earnestly** [servo/servo#6051]
In this repo instead of somewhere else?

Thanks.

**Comment by jdm** [comment]
This was a deliberate decision to make it easier to submit new tests. We previously used a submodule. @jgraham were there any other motivating factors here?

**Comment by jgraham** [comment]
For web-platform-tests it is indeed because the update process is designed around having things in-tree. This is shared with gecko where submodules aren't an option (and I think is rather convenient compared to submodules in terms of the development process). The CSS tests then use the same setup for consistency although we can't upstream changes there in the same way.

If we did put the data in some other repo you would still need it to develop Servo, so I don't see that would be a substantial win.

**Comment by Earnestly** [comment]
> If we did put the data in some other repo you would still need it to develop
> Servo, so I don't see that would be a substantial win.

If you put it in another repo, people who wanted all of this data duplicated
from another engine, could still get it while those who didn't, didn't have to
be burdened with it.

Not all of us have fiber and 1TB SSDs, you've done nothing but remove the
choice for no actual gain over what servo developers apparently already do.

**Comment by SimonSapin** [comment]
Closing. While this is space usage is unfortunate, there isn’t an actionable proposal for an alternative with an update process.
