### ISSUE TITLE
Don't sync submodules unless needed

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#6122]
We don't need submodules for anything but Android now.

We shouldn't enforce submodules unless someone is doing an Android build.

(Submodule sync needs an updated git, which not everyone has)

**Comment by Manishearth** [comment]
This isn't so easy; without the submodule Cargo fails

```
22:59 < BenB> another one: Downloading Cargo nightly... Cargo ready. Could not find `Cargo.toml` in `/mnt/compile/mozilla/servo/servo/support/android-rs-glue/glue'. This is while building on Linux 64bit with Linux as target, not 
              Android.
```

**Comment by benbucksch** [comment]
That's actually Issue #6123 . Android deps should NOT download, if I'm not building Android.

For the time being, if you DO want to download android-rs-glue, this bug could be fixed by fetching this, instead of doing --recursive.
I think that's the right solution long-term, even when #6123 is fixed, because in order to be selective, you need to be specific first.

**Comment by frewsxcv** [comment]
Presumably, at the time of writing, Servo was using git submodules. This, AFAICT, is no longer the case.
