### ISSUE TITLE
Share Script Threads by eTLD+1, not by parent origin

### ISSUE THREAD

**Issue by jdm** [servo/servo#633]
This will allow separate tabs to execute independently, which is good. This will also allow us to sidestep problems where an iframe changes document.domain to either become cross-origin or same-origin but is part of the parent's TLD (eg. images.yahoo.com and yahoo.com). Any iframe that's part of the parent's TLD should use the parent's script task, and any that is not should get its own.

**Comment by asajeffrey** [comment]
Just discovered this very old issue! I think it should be eTLD+1 rather than eTLD, but otherwise yes.

**Comment by asajeffrey** [comment]
IRC chat at http://logs.glob.uno/?c=mozilla%23servo&s=21+Sep+2016&e=21+Sep+2016#c526896

**Comment by asajeffrey** [comment]
In that IRC chat, Ms2ger pointed out that you can use `window.open` to enable communication between same-origin documents in different tabs. For example:
```html
<html>
  <body></body>
  <script>
    let new_win = window.open("dummy.html", "same_target");
  </script>
</html>  
```
If you open that document twice in two separate tabs, after they've both loaded, they share a `new_win` object, and can communicate, e.g. with `new_win.document.body.setAttribute()` and `...getAttribute()`. This behaviour exists in FF.

The upshot is we should share script threads by eTLD+1, not by tab-and-eTLD+1.

**Comment by asajeffrey** [comment]
The easiest way to do this would be to include a hash map in the constellation which maps eTLD+1 to script channels. When a new pipeline is created, we should look up the eTLD+1 in the hash map, and use that to decide whether or not to recycle a script thread.

This does mean we need to think about how to freeze/thaw pipelines, since a script thread may contain some pipelines that are frozen, and some which are thawed.

Also, this may impact debugging (cc @ejpbruel) since different tabs are considered as different debugging targets.

**Comment by metajack** [comment]
Doesn't this mean that the case where I have N google docs tabs open means they all share the same script thread? That seems bad.

**Comment by asajeffrey** [comment]
@metajack indeed it does, and yes this is bad. The only way round this I can see is to make DOM objects shareable between threads, which also seems bad.

**Comment by metajack** [comment]
Another option is to deal with that stuff via message passing, and take the performance penalty. It may be worth trading poor performance in this (assumedly rare) setup than trading away baseline performance for multiple tabs.

Do e10s Firefox and Chromium make sure all eTLD+1 tabs are in the same content process?

**Comment by jdm** [comment]
I am concerned about the complexity of transparent, synchronous, cross-thread DOM objects. We already need something like that for XOWs, but that was at least going to be a very limited set of operations that would need to be proxied.

**Comment by asajeffrey** [comment]
OK, here are two ideas:

1. Script thread merging: make sure script threads for the same eTLD+1 are at least in the same process, but not the same thread. If we ever discover sharing happening, we merge the two script threads. I'm not sure if SM allows this, though, since this probably requires heap merging, which the SM GC may not be too happy about.

2. Lock merging: give each script thread a lock for it's DOM, then when we discover sharing between T1 and T2, we replace T2's lock by T1's lock. Again, not sure if SM will be very happy about this, we'd need to make sure T1 and T2 were sharing an SM instance.

I suspect lock merging would be easier than script thread merging. Both of these would allow separate gdocs to run concurrently, assuming that gdoc doesn't do horrible DOM sharing.

Note that all of these also apply to the descendant iframe case, or to the case where document.domain is set late in the day.

**Comment by metajack** [comment]
I asked @tschneidereit if SpiderMonkey could migrate compartments, and he says this isn't possible currently and is probably not something the SM team would want to do.

**Comment by tschneidereit** [comment]
I just talked to billm and he says that the Gecko team decided to break this functionality for multi-content process FF. He didn't know what other browsers are doing here.

**Comment by asajeffrey** [comment]
Unsurprisingly, script thread migration is out, but lock migration should still be okay shouldn't it? Does SM use thread affinity (e.g TLS) for anything?

**Comment by metajack** [comment]
If Firefox broke this, we certainly can :) But let's figure out what Chrome does before we decide.

**Comment by asajeffrey** [comment]
OK, tried in under Chrome. Calling window.open("same_target") from two different tabs opens two new tabs. So Chrome has switched off this back channel too. So if we wanted to, we could use the same interpretation of the spec, and go back to the original idea of sharing script threads per tab-and-eTLD+1.

**Comment by metajack** [comment]
That sounds like the right plan then. Thanks for testing this.

**Comment by asajeffrey** [comment]
IRC chat with @jdm: http://logs.glob.uno/?c=mozilla%23servo&s=28+Sep+2016&e=28+Sep+2016#c531104

Summary: sandboxes should be treated like tabs.

**Comment by asajeffrey** [comment]
More IRC chat with @jdm: http://logs.glob.uno/?c=mozilla%23servo&s=28+Sep+2016&e=28+Sep+2016#c531137

Summary: it looks like the spec at https://html.spec.whatwg.org/multipage/browsers.html#concept-origin says that if you have documents A, B and C, all from example.com, with A containing a sandboxed iframe B, and B containing an unsandboxed iframe C, then A and C have origin example.com, and B has an opaque origin. The upshot of this is that A and C are same-origin, and so C has access to A, even though it was created by B. This seems like a potential security vulnerability to me.

**Comment by asajeffrey** [comment]
Oh yes, and the security vulnerability isn't one, because sandboxing is inherited. In the example. A sandboxed B, so C inherits the sandboxing, so C is sandboxed from both A and B.

**Comment by asajeffrey** [comment]
The XOW issue: #2382.

**Comment by asajeffrey** [comment]
IRC chat with @avadacatavra, @jdm and @Ms2ger: http://logs.glob.uno/?c=mozilla%23servo&s=5+Oct+2016&e=5+Oct+2016#c535703

TL;DR: Window objects are per-pipeline, but WindowProxy/BrowsingContext objects have to be shared among Window objects in the same script thread. Also: #5238.

**Comment by asajeffrey** [comment]
More IRC, this time on jsapi: http://logs.glob.uno/?c=mozilla%23jsapi&s=5+Oct+2016&e=5+Oct+2016#c799430

TL;DR: http://searchfox.org/mozilla-central/source/js/src/jsapi.cpp#822 JS_TransplantObject is in our future.

**Comment by asajeffrey** [comment]
Epic IRC with @bholley: http://logs.glob.uno/?c=mozilla%23servo&s=5+Oct+2016&e=5+Oct+2016#c536033

Not entirely sure there is a TL;DR for this one.

**Comment by asajeffrey** [comment]
Must remember only to mention an issue in a PR summary if the PR closes the issue!
