### ISSUE TITLE
Worker ids aren't unique

### ISSUE THREAD

**Issue by jdm** [servo/servo#6631]
The devtools-related code for notifying when new worker globals are created won't work correctly in the presence of subworkers. Each WorkerGlobalScope/Window has its own next_worker_id field, so it's easy to end up with overlapping ids for independent workers.

**Comment by fabrizio8** [comment]
Is this still an issue?

**Comment by jdm** [comment]
Yep!

**Comment by jdm** [comment]
We should probably just have each worker id be a UUID.

**Comment by fabrizio8** [comment]
Ok, so I see that  `/servo/components/script/dom/globalscope.rs` defines the worker ID generation.
- `/servo/components/script/dom/worker.rs`

and - `/servo/components/devtools_traits/lib.rs` defines `WorkerId` as a u32. 

I can work on implementing using UUIDs instead of next_worker_id.
Should any of the related uses of the struct be refactored to something like WorkerUUID or is it okay to leave them as is?

**Comment by jdm** [comment]
Sorry for not answering this question sooner! I don't think it's necessary to rename the struct.

**Comment by kunalmohan** [comment]
Hi! I would like to work on this issue if it's still open.
This would be my first contribution. Anything I should keep in mind?

**Comment by fabrizio8** [comment]
You should be good to go!
I would just double check that the files and paths I mentioned in my last post are still relevant.

**Comment by kunalmohan** [comment]
@jdm will it be better to keep worker_id as UUID or generate a UUID and store it as a string? Because accordingly I'll have to see for the traits implemented for struct `WorkerId`.
