### ISSUE TITLE
Move websocket network connection creation to the resource task

### ISSUE THREAD

**Issue by jdm** [servo/servo#6638]
In the multiprocess world we can't initiate connections from the content process. Additionally, we need the initial websocket upgrade request to include things like cookies, etc. We need to add a new network protocol handler that takes care of all of this. The first step here is to simply move the connection creation out of the WebSocket constructor; we can leave the integration with the HTTP code for another time.

Code: components/script/dom/websocket.rs, components/net/resource_task.rs

**Comment by samfoo** [comment]
I'm willing to pick this up since I've hacked a bit on `resource_task.rs` already, but I'm not sure I understand what you're suggesting. Is the suggestion to move/recreate `establish_a_websocket_connection` in components/net/resource_task.rs, then pass that as an argument to the WebSocket constructor?

**Comment by Ms2ger** [comment]
Please don't pick it up just yet; I'm still working on that code.

**Comment by metajack** [comment]
We can't allow network connections from the content sandbox? It seems a bit weird to proxy all this through some other process, although I guess if Gecko is single threaded for i/o this isn't much different to that.

**Comment by jdm** [comment]
Gecko does the same. It's also important for things like network cache coherence, cookies, etc.

**Comment by metajack** [comment]
Won't this prevent anyone from writing any high performance websocket code? That's a lot of data copying to go from JS to outside JS to another process and then into the final socket buffer and then all the way back for the reply.

**Comment by jdm** [comment]
We may be able to send the socket descriptors to the content process after the connection is initiated. I haven't looked closely at what Gecko does for websockets in particular.

**Comment by metajack** [comment]
That sounds satisfactory.

**Comment by nfallen** [comment]
I can work on this!

**Comment by jdm** [comment]
For those following along at home, this is the plan I proposed to @nfallen:
```
1) Extract the websocket networking code (ie. making a connection, receiving data, and sending data) out of components/script/dom/websocket.rs and into components/net/websocket_loader.rs (which doesn't exist). This will require communicating with the resource task (components/net/resource_task.rs) to instruct it to initiate a new websocket connection, and providing an API that allows receiving feedback about this process (and subsequently sending and receiving data)
* I imagine this requiring a new message in the ControlMsg enum in components/net_traits/lib.rs similar to the existing Load message
* The new message should take an `IpcSender` argument that would allow the DOM websocket code to listen for the result of the connection

2) Extract the code in `load` in http_loader.rs that specifically deals with modifying the headers for a request into a separate function. Similarly, extract the code that deals with processing the headers for a response into a separate function.

3) Use the new methods on the `headers` fields in the Request and Response types that exist in the websocket network connection code that now lives in websocket_loader.rs
```

**Comment by nfallen** [comment]
I am working on Part 2 first and I have a few clarifying questions:

1) In order to test that my changes don't break any functionality, will running the XMLHttpRequest web platform tests be sufficient? Are there other tests I should run?

2) For the function that deals with processing the headers for the request, I extracted out logging the headers, setting the cookies, and updating the strict transport security list. Is this what you had in mind?

**Comment by jdm** [comment]
1) I think the XHR tests you mentioned should be sufficient.
2) Yes, that looks right to me!

**Comment by KiChjang** [comment]
Fixed by #8303.

**Comment by jdm** [comment]
Nope, that was only one part of it.

**Comment by nfallen** [comment]
In my current design, when the websocket connection is being established in the resource task, the DOM websocket code is sent an IpcReceiver that accepts an enum specifying an event that occurred on the network side. This allows the DOM code to queue the tasks to give feedback from the protocol. 

My question is: how should the DOM code wait for these events without blocking the DOM process? Should a thread be created that loops and calls recv() on the IpcReceiver? Or is there a way to register a listener on an IpcReceiver to respond to events?

I also wanted to make sure that I am on the right track given @metajack's concerns further back on this thread about performance. In my current design all incoming and outgoing message data will be passed between the two processes. However, it doesn't seem possible to pass the socket descriptors because they are not serializable. Will the performance tradeoffs be forgivable?

**Comment by jdm** [comment]
With respect to the question of performance, I'm in favour of doing the straightforward implementation and measuring before trying to optimize it.

As to your other question, that's a good one, and I feel silly for not considering it before. I'm in favour of creating a thread that receives the event notifications and enqueues a runnable that dispatches the DOM event (ie. just adapting the existing code at http://mxr.mozilla.org/servo/source/components/script/dom/websocket.rs#266). This is another case where we can measure the effects of this and attempt to optimize it if necessary at a later time.

**Comment by nfallen** [comment]
Sounds good! Since the websocket_loader code in the resource task will have to listen for both outgoing messages from the DOM and incoming messages from the socket, I was thinking of creating a thread for each of those tasks as well. Does that make sense?

**Comment by jdm** [comment]
Yep!

**Comment by nfallen** [comment]
I am running the tests in wpt/web-platform-tests/websockets now. When they are run all together, one test times out every time, but when I run smaller subsets of the tests they all pass. Do you think this is just because of the decrease in performance of this implementation? Are there any other tests I should be running before creating a pull request?

**Comment by jdm** [comment]
Huh, that's really interesting. Easiest way to figure it out is to run the tests against a revision without your changes and see if there's a change in behaviour. You can also try build with `--release` and running the tests with `--release` to see if there's a difference.

**Comment by jdm** [comment]
And no, those WPT tests should be all that's necessary.

**Comment by nfallen** [comment]
Yep, I tried those things! The build from master did not time out, but the release build from my branch still had the same issue.

**Comment by jdm** [comment]
It's quite interesting that the test doesn't time out when run in the group. Which one is it?

**Comment by nfallen** [comment]
A different test timed out each time that I ran ./mach test-wpt websockets. However, the most recent time I ran the tests, they all passed. Must be dependent on the CPU usage of my OS as I'm running the tests or something?

**Comment by jdm** [comment]
Plausible! If you think the work's ready, please make a pull request so we can start reviewing! If not, but you'd like another set of eyes to look at this timing out thing, please push your code to a branch of your fork and link it here.

**Comment by KiChjang** [comment]
Is this still pending on the extraction of websocket connection algorithms out of websocket.rs and into websocket_loader.rs?

**Comment by jdm** [comment]
I'll file new issues for any remaining pieces.
