### ISSUE TITLE
Add a unit test that ensures that hsts_preload.json can be decoded and is non-empty

### ISSUE THREAD

**Issue by jdm** [servo/servo#6789]
This should be a new test added to `tests/unit/net/hsts.rs` that calls `preload_hsts_domains` from `components/net/hsts.rs` and checks the return value.

**Comment by notriddle** [comment]
:hand: I'd like to try.

**Comment by jdm** [comment]
It's yours!

**Comment by RoboMantis** [comment]
this is my first time with bugs ahoy, I've learned a little rust over the course of the week and read the manual and completed some of the rustbyexample.com 
however I am doing this from a public library and may not be able to download anything(unless my buddy brings my computer back)  so how can I help?
and will play.rust-lang.com be enough. 
I plan on making a very dedicated effort here maybe 1 to 3 hours a day on weekdays.

**Comment by jdm** [comment]
Sorry @RoboMantis, any code-based contributions to Servo will require downloading the Servo source code and associated other tools (like our custom Rust compiler).

**Comment by RoboMantis** [comment]
ah ha, thats alright I should get my computer back next week, I can do. for now I'll be watching https://air.mozilla.org/the-joy-of-coding-mconley-livehacks-on-firefox-episode-19/

**Comment by RoboMantis** [comment]
https://koding.com
This is a startup that lets you use a linux vm in the web browser, and can even start servers and everything, so I guess I can still go now?!! !!! because I can download to this place I followed the link through coindesk.com yay! all from the browser haha. 
I'm ready to get started, is it kinda like whoever has the answer just plugs it in huh? is most of the work about searching for operators of the language in libraries or ...?

**Comment by jdm** [comment]
Yes, you can just choose any issue that isn't already assigned and give it a try. This one has the "C-assigned" label, so you'll need to find a different one.
