### ISSUE TITLE
Explore the minimum requirements for writing DOM unit tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#6813]
At minimum we need to initialize a JS runtime, create a Window and a Document. Creating a Window is in itself a fun process: http://mxr.mozilla.org/servo/source/components/script/dom/window.rs#984

One could argue that the easiest way forward is just to create a ScriptTask: http://mxr.mozilla.org/servo/source/components/script/script_task.rs#390 in order to reduce any potential duplication and ensure correctness.

I'm not entirely convinced that the resulting test harness will yield a useful environment for tests in comparison to a regular webpage, but it would be valuable to know that for sure!

**Comment by samfoo** [comment]
I've taken a brief look at this, and I'm wondering why wouldn't we make `Window` and `Document` traits, and allow mocking them in tests? None of the struct fields on either are public, which at least means this should be possible.

There's clearly a lot of work to do this, but it seems to me like most of the things we would want to test when doing this shouldn't need a full `ScriptTask` itself. Rather they interact with the `Document`/`Window` in some way, or change the state of the element itself.

Thoughts? If this makes sense, I'll try to put together a proof-of-concept.

**Comment by Ms2ger** [comment]
I'm generally not in favour of creating tests that can't be reused by other browsers.

**Comment by samfoo** [comment]
I see the value of these tests as faster feedback for the component-level logic of the servo specific implementation. 

Consider a (fictional) test like...

```rust
#[test]
fn test_anchor_tag_default_activation_behaviour_is_to_follow_link() {
    // Obviously made up syntax...
    let window = mock_window!();
    let document = mock_document_with_window!(window);

    let a = HTMLAnchorElement::new("a", None, document);
    let e = Event::new(/* ... */);
    let target = EventTarget::new(/* ... */);

    a.activation_behavior(&event, &target);

    assert_eq!(window.url, "http://whatever-the-url-was");
}
```

The main advantage being that this test runs in microseconds, rather than seconds like the WPT tests. If you're not convinced by the anchor tag, consider how code that requires user input (e.g. `maxLength` on `textarea` or `input`)? At present there's no way to synthesize a test for this other than manual WPT, which is terribly subpar.

I'm certainly not saying that we shouldn't also have platform tests, but the faster feedback is super valuable while developing since I don't have to wait minutes for WPT to fail as an initial indicator that things might be broken due to a change.

**Comment by samfoo** [comment]
So I spent a bit of time spiking out what it would take to turn `Document` and `Window` into traits, and then have anything that contains them be generic over the implementation. This would have allowed mocking either `Document` or `Window`.

The biggest problem with this approach is that the codegen isn't architected and since we generate a ton of code for elements that must contain a document element (e.g. `Node`, and then anything that uses that, etc, etc) it starts to look like a very large piece of work.

I still think that this kind of approach has merit, but the time sink is pretty substantial, and without a great investment in making the mocking really easy, might not be that useful anyway.

I might try spiking out @jdm's original idea of creating a script task, and see what some of the costs/benefits are.

[For the interested, current progress on trait-ifying.](https://github.com/samfoo/servo/tree/document-trait-spike)

**Comment by nox** [comment]
@jdm Do we still want this? I personally would want to see *less* unit tests in general.

**Comment by jdm** [comment]
Yeah, I don't see this exploration going anywhere useful.
