### ISSUE TITLE
Mousing over the root flow can cause selector matching to rerun for the whole document

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#6942]
This is because we don't know whether there might be a selector `body:hover X { ... }` for all nodes X, and so we conservatively rerun selector matching for the whole document even if the body's style didn't change. This is very slow!

It seems like a general problem. How does Gecko deal with it?

**Comment by heycam** [comment]
This is a kind of problem we are [just fixing now](https://bugzilla.mozilla.org/show_bug.cgi?id=1180118) in Gecko.  Although the patches I have there won't work for :hover state matching changes, it should extend easily to that.

Selectors in Gecko are represented by lists of [`nsCSSSelector`](https://dxr.allizom.org/mozilla-central/rev/1d4f44ee51668865945db95c5fbd898e71955a33/layout/style/StyleRule.h#124) objects.  Each `nsCSSSelector` is a [sequence of simple selectors](http://www.w3.org/TR/selectors/#sequence) in CSS 3 Selectors terminology, and has an `mNext` pointer to the `nsCSSSelector` object to its left. Let's change the example to `body.foo span`.  This selector would comprise two `nsCSSSelector` objects, where the rightmost one represents `span` and points to the next `nsCSSSelector` looking left for `body.foo`.  Each `nsCSSSelector` has an `mCombinator` for the combinator that appears to its right.

The result of cascading all of the style sheets in a document is an [object called the "rule cascade"](https://dxr.allizom.org/mozilla-central/rev/1d4f44ee51668865945db95c5fbd898e71955a33/layout/style/nsCSSRuleProcessor.cpp#850), which stores, among other things, hash tables that map class names, IDs, and attribute names, to all of the individual `nsCSSSelector` objects that use them.  So if the document only had the one `body.foo span` rule, we would have the `mClassSelectors` table mapping "foo" to the `body.foo` `nsCSSSelector`, and the other tables would be empty.

Currently, we handle dynamic updates to the document by looking up these tables in response to a change in the document, and determining whether we should (a) restyle just the element that had the change, (b) restyle the element that had the change and all of its descendants, (c) restyle the element that had the change, all of its descendants, and all of its later siblings and their descendants.  (This is an [nsRestyleHint](https://dxr.allizom.org/mozilla-central/rev/1d4f44ee51668865945db95c5fbd898e71955a33/layout/base/nsChangeHint.h#355).)  We make this decision [based on what the `mOperator` of the `nsCSSSelector` we just looked up was](https://dxr.allizom.org/mozilla-central/rev/1d4f44ee51668865945db95c5fbd898e71955a33/layout/style/nsCSSRuleProcessor.cpp#2577).

So if we toggle the "foo" class on the body, we look up the `mClassSelectors` table on the rule cascade to find one `nsCSSSelector`, the one for `body.foo`, look at its `mOperator` (it's `' '`, for the descendant combinator) and turn that into the "we need to restyle the element and its entire subtree" restyle hint, [eRestyle_Subtree](https://dxr.allizom.org/mozilla-central/rev/1d4f44ee51668865945db95c5fbd898e71955a33/layout/base/nsChangeHint.h#380).  This is using the same reasoning that it sounds like Servo is using — we know that there could be descendant elements that need to be restyled, since we have some stuff to the right of the `body.foo` selector, but we don't know which elements, so we just restyle the whole subtree underneath the body.

With the bug 1180118 patches, instead of just generating the eRestyle_Subtree restyle hint if we find an `nsCSSSelector` with a `' '` or `'>'` `mOperator`, we have a new hint eRestyle_SomeDescendants which means "look at this set of `nsCSSSelector` objects and restyle all descendants of the element that had the dynamic change on it that match one of them".  The list of `nsCSSSelector` objects consists of the rightmost `nsCSSSelector` object for the ones we just looked up in the rule cascade tables.  In our case, this would be the one for `span`.

Later, when we are processing the pending restyles for the document, as we traverse the tree we evaluate the current element against the `nsCSSSelector` objects if we weren't otherwise going to run selector matching on the element.  This evaluation only looks at that single `nsCSSSelector` object, which should be relatively cheap.  Also, if we decide that we can stop restyling at a given point (because say the only style change we got for an element was an non-inherited property and we recorded that no descendants explicitly inherited it or otherwise depended on it), then we switch to traversing descendants and just evaluating them against the `nsCSSSelector` objects, and not doing any of the other restyle processing that we normally do.

So overall we still visit every descendant of the element that had the dynamic change, but we can avoid doing the restyling (performing full selector matching, computing style data) on many of the elements in the subtree.

**Comment by dbaron** [comment]
Though @pcwalton said "there might be a selector", not "there is a selector", so it's not clear to me that he's saying that servo already has the equivalent of our HasStateDependentStyle and HasAttributeDependentStyle methods.  Those use data structures that store pointers into the middle of CSS selectors so that we know which (if any) restyle hints are necessary in response to attribute or state changes, by doing selector matching on only the partial selector (from our pointer going leftwards) to see if we have to do actual restyling, and determining the restyling that we do by the combinator rightwards.  In the case of attribute changes, we look at the selector both before and after the attribute change (in a way that I think is slightly conservative, but I forget exactly how).

**Comment by pcwalton** [comment]
Right, @dbaron is correct. Servo is missing the nsRestyleHint infrastructure entirely. So a quick summary of this bug might be "Servo needs an nsRestyleHint".

**Comment by bholley** [comment]
I'm going to take a look at this, at least the smaller issue that @dbaron mentioned.
