### ISSUE TITLE
Scrolling is broken on Android

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#7036]
I saw clicking on a link work once, but scrolling and pinch-zoom appear to be non-functional.

**Comment by mbrubeck** [comment]
Glutin translates touch input on Android into [mouse events](https://github.com/tomaka/glutin/blob/e90f377b9fbab23a140029e71ef57933b266c473/src/api/android/mod.rs#L73-L75).  Upstream Glutin master has a [touch event](https://github.com/tomaka/glutin/blob/e90f377b9fbab23a140029e71ef57933b266c473/src/events.rs#L51-L52) API, but this isn't yet used in the Android port.

We could easily change Servo's android port to make "mouse" movement scroll the page instead of sending DOM mouse events, but this would break the demos that use mousemove events for other purposes.

To make touch input usable for both scrolling and DOM events, we need to implement the [Touch Events](http://www.w3.org/TR/touch-events/) DOM API, and cancel scrolling if the web page calls preventDefault on the "touchstart" or "touchmove" event.

**Comment by mbrubeck** [comment]
If a temporary hack is needed for demo purposes, we could also provide a way for a web page to opt out of touch scrolling, for example by implementing a tiny subset of the ['touch-action'](http://www.w3.org/TR/pointerevents/#the-touch-action-css-property) CSS property.

**Comment by frewsxcv** [comment]
FWIW, at the time of writing, there are WPT tests we fail related to `TouchEvent` creation

https://github.com/servo/servo/blob/master/tests/wpt/metadata/dom/nodes/Document-createEvent.html.ini

**Comment by mbrubeck** [comment]
I started working on basic touch event support at https://github.com/mbrubeck/servo/commits/touchevent

**Comment by waddlesplash** [comment]
#7204 was merged.
