### ISSUE TITLE
Implement WebSocket#binaryType.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7098]
Blocks #6060 

* Spec: <https://html.spec.whatwg.org/multipage/#dom-websocket-binarytype>.
* Code: `components/script/dom/{websocket.rs,webidl/WebSocket.rs}`.
* Test: various under `tests/wpt/web-platform-tests/websockets/`, `tests/wpt/web-platform-tests/html/dom/interfaces.html`.

**Comment by tomjakubowski** [comment]
I can take a stab at this.

**Comment by jdm** [comment]
Please do!

**Comment by tomjakubowski** [comment]
I did the bare minimum and enabled the accessor in the IDL file and added the necessary fields and impl methods. See https://github.com/tomjakubowski/servo/commit/8d999de7df0aa587560d6c4291aa2d2a263967cf

It doesn't actually change the type of the data provided to the `message` callback, however, because I couldn't see an immediate and obvious safe way to create and return an `ArrayBuffer` (which should apparently land as part of https://github.com/servo/servo/pull/6779).
