### ISSUE TITLE
Build broken due to heartbeats

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7328]
```
failed to run custom build command for `hbs-pow-sys v0.1.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#4476aa6a)`
Process didn't exit successfully: `/target/debug/build/hbs-pow-sys-4f2a0dd8d72ac62e/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Unable to execute "cmake" "" "/heartbeats-simple-sys-203def3c271a26ee/master/hbs-pow-sys/heartbeats-simple"! No such file or directory (os error 2)', /heartbeats-simple-sys-203def3c271a26ee/master/hbs-pow-sys/build.rs:35
```

**Comment by connorimes** [comment]
This could be because the heartbeats-simple git submodule is not being init'd.  I'm not familiar enough with git to know why this works in some cases but not others.  Maybe different git versions behave differently w.r.t to checking out submodules when a repository is cloned?  I don't explicitly init submodules in the build script when attempting to compile the native dependency, but maybe I need to.  Seems dirty adding git commands to build scripts though.

**Comment by Ms2ger** [comment]
That didn't help, but installing cmake did
