### ISSUE TITLE
Document how to add a repo to homu

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7444]
CC @metajack @mbrubeck

**Comment by Ms2ger** [comment]
Cover travis vs buildbot CI.

**Comment by mbrubeck** [comment]
Current docs are at https://github.com/servo/saltfs/wiki/Adding-a-repo-to-Homu

**Comment by Ms2ger** [comment]
We should probably decide where to centralize those docs. CC @edunham @larsbergstrom

**Comment by edunham** [comment]
@Ms2ger, where had you expected these docs to be available (or what did you search before concluding that we didn't have the docs)? I ask because I'd like to make sure there are links to the docs in those places to save others from the trouble you ran into :)

**Comment by Ms2ger** [comment]
Same wiki as https://github.com/servo/servo/wiki/Buildbot-administration

**Comment by edunham** [comment]
You're right; having that page over on the saltfs wiki doesn't make much sense. I think I put the information there when I was quite new to the project and had some incorrect assumptions about how the wikis were used. Looking at it now, it makes much more sense to relocate the page over to the main wiki.

Closing since the docs now exist in a way that should enable people to find them: https://github.com/servo/servo/wiki/Adding-a-repo-to-Homu

**Comment by metajack** [comment]
Note that I've now expanded these docs and published a sanitized version of my helper scripts.
