### ISSUE TITLE
Implement channel messaging (MessageChannel and MessagePort)

### ISSUE THREAD

**Issue by jdm** [servo/servo#7457]
https://html.spec.whatwg.org/multipage/comms.html#channel-messaging

https://html.spec.whatwg.org/multipage/comms.html#messagechannel
https://html.spec.whatwg.org/multipage/comms.html#messageport

@mukilan has an old branch that does some of this and will link it here.

**Comment by ConnorGBrewster** [comment]
I am working on this one

**Comment by jdm** [comment]
@ConnorGBrewster This is something I would want to have significant upfront planning for before having someone implement it. I started a branch earlier this week for experimenting and discovered that the specification is significantly more intricate than I anticipated, making the implementation much more complex than I originally expected.

The biggest issue is that the queued messages need to be able to be transferred between script event loops if the associated message port is transferred, as this means that `postMessage` can't just send a message to the current target script thread. Implementing the spec's concept of an additional task source per message port also conveniently map to our use of `Select` in `ScriptThread`, which can't deal with variable message sources.

**Comment by ConnorGBrewster** [comment]
@jdm ok that make sense. I currently just have skeletons setup for the `MessageChannel` and `MessagePort` DOM structs with the WebIDL bindings. I haven't done any actual implementation yet, I will hold off on that until a plan is created.

**Comment by KiChjang** [comment]
I was reading the spec for this, and I feel like we may have chalked up the difficulty a bit too much on this one. I have in mind a preliminary version that may work and it goes like this:

1. We create and implement a new `TaskSource` called `PortMessageQueue` and make a new method in `GlobalScope` to return it. (Maybe have this TaskSource store the has-been-shipped flag and disabled flag as well?) 
2. Code in the `MessagePort` DOM APIs and fields according to its WebIDL file, and add in a field called `entangled_port` which is of type `DOMRefCell<Rc<MessagePort>>`
3. Create a new `Runnable` called `PortMessageRunnable`. This will be responsible for firing the event at the target MessagePort.

The entanglement operation would simply be accepting a new MessagePort object and creating a new Rc pointing to it, and then assigning this new Rc to the other MessagePort object's entangled_port field. `postMessage` would use the `entangled_port` field to get the GlobalScope for the entangled `MessagePort`, and transitively the `PortMessageQueue`. At this point, we now just need to create the `MessageEvent` and then queue it.

Am I missing something here? I'm going to try and code this in and see if there's anything that I'm missing.

**Comment by KiChjang** [comment]
Ah, of course I forgot -- the case where you need to transfer the `MessagePort`. In Gecko, they store an enum that represents the state of the `MessagePort` (i.e. whether it is being entangled or disentangled, or if it is closing, etc.). We could check for the state of the `MessagePort` in the methods `postMessage` and `start`, and when the port is in the disentangled or disentangling state, abort the algorithms completely, since they would be handled in a special way during transfer. Does that make sense?

**Comment by KiChjang** [comment]
That still doesn't address the issue where PortMessageRunnable are not supposed to be dropped when there is no corresponding PortMessageQueue. Perhaps we'll need to have the constellation store them temporarily, until the corresponding ScriptThread enables its PortMessageQueue. This would mean each individual Runnable will need to have a FrameId and registered domain name of its destination ScriptThread.

**Comment by gterzian** [comment]
I have a question on the transferring of MessagePort objects, can this cross "agent-cluster" boundaries? 

From reading https://html.spec.whatwg.org/multipage/web-messaging.html#ports-as-the-basis-of-an-object-capability-model-on-the-web it seems there is a strong cross-origin use-case, which implies message ports can indeed be transferred across agent-clusters(or I'm still not getting agent-clusters). 

Actually leaving agent-clusters aside, a MessagePort implementation that would allow for the example linked to above, would in Servo have to cross process boundaries, since the port would have to be transferred from one origin to another, hence from one script-thread/process to another. 

Is this making sense? 

I was looking at the current work in progress at https://github.com/servo/servo/pull/16622 and it seems to perhaps not support transfers across process boundaries, because [TRANSFERRED_MESSAGE_PORTS](https://github.com/servo/servo/pull/16622/files#diff-7a9812c344e5a2ce6252e367e0297530R34) is thread local and the various members of `MessagePortInternal` are `RefCell`? 

Also by using `StructuredCloneData` on the entire `MessagePortInternal`, I think you are also effectively restricting yourself to a single script-thread/process(given the pointer used to write and later read a `MessagePort`, I don't think that would work across process, right?)

**Comment by jdm** [comment]
Your proposed model matches my previous thoughts when reviewing the WIP pull request. I do think it would be valuable to adapt the current work in that direction.

**Comment by gterzian** [comment]
Ok, I'd be interested in giving it a try, re-using all the DOM side of things, and just trying a different take on the queuing. 

Lastly, I think a dual design where the constellation is used to "entangle", "ship" and "enable" ports and their queues, but with ports communicating directly via IPC script-to-script once fully up and running, is feasible and probably optimal(we don't want all messages being routed by the constellation, just the heavy duty setup work).

**Comment by gterzian** [comment]
Also had a look at the dedicated worker and their ["implicit port"](https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-dedicatedworkerglobalscope-interface:messageport).

Since those are implicit, they can't be manipulated directly by a script, and thus can never be "shipped". So I think out current use of "normal" channel should be just fine for now(we could just update the task source used), and using an actual message port only becomes interesting with shared workers(which we don't have yet, right?).

**Comment by jdm** [comment]
Agreed.

**Comment by gterzian** [comment]
(one exception might be `BroadcastChannel`, but even then, a script-thread matching a given origin for the broadcast could simply use the "normal" channel to the dedicated worker to do the broadcast)

**Comment by KiChjang** [comment]
@gterzian I'm currently in the process of rebasing my PR against master, and I'll expect it to be done tonight (PST), you may want to wait until then so that you have less merge conflicts to fix.

**Comment by gterzian** [comment]
@KiChjang Thanks!
