### ISSUE TITLE
Make SERVO_HEADLESS a command line option for `./mach build`

### ISSUE THREAD

**Issue by metajack** [servo/servo#7637]
Right now to get OSMesa and no X dependency on Linux we compile with the env var SERVO_HEADLESS set to 1. This really should be a command line option to `./mach build`.

See https://github.com/servo/servo/issues/7512#issuecomment-140409029 for reference.

**Comment by glennw** [comment]
@metajack I believe this can actually be changed now to be a runtime switch rather than compile time. Previously, glutin had to link against either libGL or libOSMesa at compile time. However, the lib is now loaded dynamically via dlopen(). That probably makes the task a bit more involved - but a much better result.

**Comment by jdm** [comment]
This is going to need more information if the easy tag is going to remain.

**Comment by jdm** [comment]
If we proceed with just adding a flag right now, the code lives in `python/servo/build_commands.py`.

**Comment by glennw** [comment]
This would also involve changing the buildbot scripts in saltfs that currently set this env var.

**Comment by metajack** [comment]
I assumed that the env var would be set by the build scripts, so saltfs changes don't need to gate this. But those changes would be super easy too.

@glennw Maybe file a new bug as E-less easy for your proposed flip to a runtime flag? I think this one is a reasonable first step even if the other solution is even better.

**Comment by nerith** [comment]
I'm working on this.
