### ISSUE TITLE
Create a simplified issue list for E-easy/E-less-easy

### ISSUE THREAD

**Issue by jdm** [servo/servo#7649]
It's great to link people to https://github.com/servo/servo/labels/E-easy, but the resulting list is not always that useful. Specifically, we use the `C-assigned` label to mean that an issue has been claimed by someone and is being worked on, but this clutters the view for everyone else. I propose a webpage that uses the github API to display the following:
```
Good first bugs for Servo
===================

Unclaimed:
* #1234 Issue title goes here
* #1230 Another title goes here

Possibly up for grabs:
* #1225 Title for some issue that has a last-touched date that is >2 weeks ago
```

We can also show the issue labels, since those are useful pieces of information, and this could aggregate E-less-easy issues too and make it clear which category issues fall under.

Stealing the github issue fetching code from https://github.com/jdm/bugsahoy/blob/master/magic.js#L578 and https://github.com/jdm/bugsahoy/blob/master/cgi-bin/githubapi.cgi is totally allowed, as is using a more convenient JS library to access github is also totally encouraged!

**Comment by samfoo** [comment]
Love it. I'll pick this up.

**Comment by jdm** [comment]
Yay!

**Comment by samfoo** [comment]
Took a first [swag at this](http://www.ifdown.net/servo-starters/) last night. It might make sense to transfer the [repository](https://github.com/samfoo/servo-starters) to be owned by the servo org? Otherwise, I'm happy to keep maintaining it.

A few things that could be improved/feature ideas:

* Design is pretty crap. Lots of noise with the labels. I don't have a great idea on this.
* Because it just uses the GitHub javascript API, unauthenticated requests are limited by IP. Could be much worse for some users, but it's much simpler to release a static page to start with. I could turn it into a node app and push it to heroku or something?
* Needs a spinner/loading indicator.
* Needs more information about what servo is or a link to the servo repo.
* Right now there's no paging logic at all. Maybe it doesn't even matter? There's only 37 total unclaimed easy/less-easy issues.
* A "I'm feeling lucky" button to pick a random open item.
* ...?

**Comment by jdm** [comment]
We could ask people to log in to github and use https://github.com/HenrikJoreteg/github-secret-keeper to allow it to remain a simple static app.

**Comment by jdm** [comment]
No wait, those are two separate ideas... we could use the secret-keeper if we wanted to use a particular github account for every user without having them log in.

**Comment by samfoo** [comment]
Yeah, I think it would make more sense just to push it on a VPS/heroku with a single authenticated account (ala how you did bugsahoy). It's not that big of a deal I don't think, but this was certainly the easiest approach to do without hassling with deployment, domains, etc.

**Comment by jdm** [comment]
And yeah, we'd be happy to accept the repository. This is great!

**Comment by samfoo** [comment]
Added a few things from the list above. Visible [here](http://www.ifdown.net/servo-starters/). I'll transfer the repo just now.

**Comment by samfoo** [comment]
D'oh! I can't transfer to servo unless I have admin rights. Silly github. Best approach is probably to clone/create a new repo, then I'll delete mine.

**Comment by jdm** [comment]
Forked!

**Comment by jdm** [comment]
Also that spinner is adorable.

**Comment by KiChjang** [comment]
@jdm can this be considered done?

**Comment by jdm** [comment]
Yep!
