### ISSUE TITLE
Can I open urls from the gui?

### ISSUE THREAD

**Issue by mcarifio** [servo/servo#7652]
There doesn't seem to be a window to type in urls. This is by design?

**Comment by jdm** [comment]
By default, yes. A GUI with a url bar can be used by running index.html from https://github.com/glennw/servo-shell instead of another URL at program launch.

**Comment by SimonSapin** [comment]
At the moment, Servo is a rendering engine rather than an "entire" browser.

There has been a couple experiments to add a UI on top of it (https://github.com/glennw/miniservo-gtk, https://github.com/pcwalton/miniservo-mac, https://github.com/glennw/servo-shell, possibly others) but I believe our current plan is to port https://github.com/mozilla/browser.html. See https://github.com/servo/servo/issues/5394

**Comment by samfoo** [comment]
[The README] says on Mac `Ctrl-L` will spawn a dialog that allows browsing to a new URL, but this doesn't seem to work for me. Removing this might result in less confusion?

**Comment by jdm** [comment]
#7655. Thanks!
