### ISSUE TITLE
border-width: 0.5px is painted as 1px border

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7665]
![0 5border](https://cloud.githubusercontent.com/assets/373579/9952837/b547a2aa-5dda-11e5-8455-ec8a14c5aa3e.png)

**Comment by mbrubeck** [comment]
This is caused by [this code](https://github.com/servo/servo/blob/83b364189c5c8f37d01cd3512d45d850f737800f/components/gfx/paint_context.rs#L1098) and many similar lines in this file that use the `to_nearest_azure_*` functions.  These incorrectly round to the nearest px.  They should instead round to the nearest device pixel.

**Comment by mbrubeck** [comment]
Note: I haven't tested this on an actual retina-style display, but I simulated it by zooming and by using `--device-pixel-ratio`.

Also, I forgot to add a test, which I'll do shortly.
