### ISSUE TITLE
Inline border does not enclose inline-block

### ISSUE THREAD

**Issue by notriddle** [servo/servo#7681]
``` html
<!DOCTYPE html>
<html>
<head>
<style>
    .outer {border:solid 1px}
    .inner {display:inline-block}
</style>
</head>
<body>
    <span class="outer">
        <span class="inner">text</span>
        next
    </span>
</body>
</html>
```

![screenshot from 2015-09-18 15-53-31](https://cloud.githubusercontent.com/assets/1593513/9972778/76340a16-5e1d-11e5-9ca9-a6f7683ad033.png)

**Comment by mbrubeck** [comment]
I think [this code](https://github.com/servo/servo/blob/8dd24fa783eb28f3c4f0beacae33ba1b947b1f36/components/layout/display_list_builder.rs#L1040-L1051) is supposed to draw the border when building the display list for `span#outer`, but is incorrectly using `node.style` from the child node, rather than `self.style`.

**Comment by notriddle** [comment]
Are you sure about that? As a reminder, `<span style="border:red"><span style="border:black">TEST</span></span>` is expected to work, too, even though there will only be one fragment (inline elements don't generate flows, and fragments are never nested). I'm pretty sure that's what the `inline_contexts.nodes` list is for.

**Comment by mbrubeck** [comment]
Oh yes, I misunderstood what that code was doing.

**Comment by notriddle** [comment]
I pretty much understand what the problem is: the inner block flow isn't drawing a border, because there's nothing that would make it do so, and the fragment isn't drawing a border because it's not a primary fragment.

If I remove the `is_primary_fragment` conditional, it draws the rest of the border... sort of. It's offset wrong, probably for the same reason (if you look closely) that the text is already off the baseline.

**Comment by nox** [comment]
This is still true.

**Comment by Loirooriol** [comment]
Fixed in layout 2020

 - Layout 2013:
   ![](https://github.com/user-attachments/assets/3c8a94a0-5c87-4102-b787-4032aa2f8127)
 - Layout 2020:
   ![](https://github.com/user-attachments/assets/392cb03b-fa96-440d-a09c-440abb1aced6)
 - Firefox:
   ![](https://github.com/user-attachments/assets/60973565-d4d6-46f9-9e0d-e6359fd54144)
