### ISSUE TITLE
Updating git repository stuck on skia

### ISSUE THREAD

**Issue by iostreamer-X** [servo/servo#7687]
I have been trying to build servo since last night but it simply refuses to progress. 
    Updating git repository `https://github.com/servo/skia`
is where the whole process stops. I have waited for approx 1 hour, deleted .cargo/git and restated but to no avail. Please help regarding this.

Thank you.

![screenshot from 2015-09-20 12 48 44](https://cloud.githubusercontent.com/assets/7972020/9979700/af4d8c1c-5f96-11e5-99fa-88ff02d394d8.png)

**Comment by jdm** [comment]
It's an extremely large repository, so this isn't particularly surprising depending on the speed of the internet connection in use.

**Comment by iostreamer-X** [comment]
Oh, I checked the speed and yes it was really low, 30KBps on average against usual 128KBps. Seems it is working fine in the background but any idea why such low speed?(Sorry of going off topic)

**Comment by Manishearth** [comment]
@jdm What are your thoughts on using a flattened (i.e., no git history) copy of Skia as a git dep? My Skia checkout is 1.1G, with 973M being the `.git` folder. The rest is large enough to not work on crates.io, but small enough to be cloneable without too much of a wait.

Cargo is basically never going to get shallow cloning capabilities since libgit2 is not planning on supporting it (something about shallow clones being incompatible with the rest of the library). The deep clone that we have to do now is very confusing to new contributors.

**Comment by jdm** [comment]
I'm strongly in favour of anything that improves the cloning performance of skia.

**Comment by iostreamer-X** [comment]
Sorry for bugging, I think this was not even an issue.
