### ISSUE TITLE
Don't interpret binary files as HTML

### ISSUE THREAD

**Issue by jdm** [servo/servo#7706]
We want to avoid interpreting streams of binary bytes as HTML, since that's silly and easily breaks our layout code that is unprepared for such things. In the code that receives the HTTP headers for a page (ParserContext::headers_available) we should check for the `Content-Type` header `application/octet-stream` and ignore the forthcoming response body if the header matches. We can replace it with an informative message in the same way that we create a special document for images in that method.

Testcase: firefox.com and press the download button
Code: components/script/dom/servohtmlparser.rs

**Comment by SimonSapin** [comment]
Rather than a black list with `application/octet-stream`, we might want a white list of supported MIME type (and possibly some [sniffing](https://mimesniff.spec.whatwg.org/). We know how to deal with `text/html`, `text/plain`, some image MIME type, etc, and everything unknown should be treated like `application/octet-stream`.

**Comment by s142857** [comment]
is it possible a n00b like me can fix it

**Comment by jdm** [comment]
@s142857 I think you should give it a shot :)

**Comment by s142857** [comment]
could you guide me

**Comment by jdm** [comment]
First step is to find the `headers_available` method of `ParserContext`. Next step is to get the `Content-Type` header from the headers in the metadata value. Final step is to check it's value and return a fake document if the content-type is not supported.

**Comment by jdm** [comment]
Fixed by #7956.
