### ISSUE TITLE
Only display text caret in focused inputs

### ISSUE THREAD

**Issue by jdm** [servo/servo#7757]
Right now the caret is always displayed, but we should build on #7756 to only return a caret position from `get_insertion_point_for_layout` when the node has focus (ie. check the IN_FOCUS_STATE flag).

Code: components/script/dom/htmlinputelement.rs

**Comment by j3parker** [comment]
I'll grab this one along with #7756 for now if that's cool

**Comment by jdm** [comment]
Makes sense!

**Comment by j3parker** [comment]
Ok, so following the suggestion is easy enough but I don't think this is 100% ready to get fixed. Here's what I have so far: https://github.com/servo/servo/compare/master...j3parker:input-caret-only-when-focused?expand=1

In the first commit I'm making `get_insertion_point_for_layout` return `None` when the input is not focused. This works initially: when you load a page with no focused input tags there will be no carets. When you click on one and move the caret everything is fine.

The trouble comes when you de-focus. Because the insertion point is "cached" on the fragment (still learning the terminology/control flow here) and we can't access the node when drawing the fragment (we only have an `OpaqueNode` handle) we're stuck.

It seems like we should be forcing a relayout when one of these nodes loses focus. It looks like `focusout` events are currently not supported: https://github.com/servo/servo/blob/96356a4b339af07831dec79e0084079328b43b53/components/script/dom/document.rs#L520

The next two commits in my branch are what I think should be done if `focusout` did exist.

Does that sound right? Should we open up an issue for implementing `focusout` (and friends)?

**Comment by jdm** [comment]
Seems like a sensible time to bite that bullet!

**Comment by jdm** [comment]
Filed #7981.

**Comment by Manishearth** [comment]
I accidentally fixed this in #8983 (didn't realize it was an e-easy). Should I un-fix it?

**Comment by KiChjang** [comment]
I think it's fine, #7985 has been hanging there for 2 months and an attempt to reach out to the original assignee has gone silent for almost 2 weeks.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/8983
