### ISSUE TITLE
Implement 'ask for a reset' algorithm for <select> elements

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7774]
https://html.spec.whatwg.org/multipage/#ask-for-a-reset

**Comment by frewsxcv** [comment]
[Relevant FIXME](https://github.com/servo/servo/blob/8547d132f9a6f5499c437572ea5648c6baf2f621/components/script/dom/htmloptionelement.rs#L149) which was added in #7745

**Comment by dagnir** [comment]
I'm completely new to servo (and any browser engine dev).  From looking at the spec, this seems relatively simple.  Is this appropriate for a newcomer?

**Comment by jdm** [comment]
I believe so! You'll probably want to implement `HTMLSelectElement`'s `size` attribute, followed by the `multiple` attribute, (both using appropriate macros from `macros.rs`) and then add a `ask_for_reset` method. Let us know if anything is unclear!

**Comment by jdm** [comment]
Looks like the `multiple` attribute already is implemented: http://mxr.mozilla.org/servo/source/components/script/dom/htmlselectelement.rs#82

**Comment by dagnir** [comment]
Thank you.  I'll get to work on it

**Comment by dagnir** [comment]
Hi @jdm, here is what I've put together so far https://github.com/dagnir/servo/commit/c6267df34dae9389b98566838b5667f4c765bc84.  Please let me know what things need fixing before I send a PR

**Comment by jdm** [comment]
A few useful changes:
* instead of calling Item in a loop, we should be using `traverse_preorder` and iterating through the results
* uses of `match` that only act on the `Some` branch can be written as `if let Some(` instead
* uses of `if something.is_some() { something.unwrap() }` can be written as `if let Some(` instead
* `first_enabled` and `last_selected` can probably be `Option<Root<HTMLOptionElement>>` instead of indexes
* unfortunately the `Disabled` method is not quite enough; we need to call `get_disabled_state` instead

Generally it's easier to make comments like these in our review tool; submitting PRs for early feedback is encouraged :)

**Comment by dagnir** [comment]
@jdm Thanks!  I'lll send PRs in the future
