### ISSUE TITLE
Text color is not updated when a class is toggled

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7814]
```html
<style>
  span {
    font-size: 30px;
    color: red;
  }

  span.selected {
    color: green;
  }
</style>

<body>
  <span class='selected'>A</span>
  <span>B</span>
  <span>C</span>
  <span>D</span>
  <pre></pre>
</body>

<script>
  var i = 0;
  setInterval(() => {
    document.querySelector('.selected').classList.remove('selected');
    var span = document.querySelectorAll('span')[i];
    span.classList.add('selected');
    document.querySelector('pre').textContent = span.textContent;
    i = (i + 1) % 4;
  }, 500);
</script>
```

In Firefox, text color changes from green to red. In Servo, nothing happen.

**Comment by jdm** [comment]
Out of curiosity, does it update if you resize the window or move the mouse over the text?

**Comment by paulrouget** [comment]
If I do something like `:hover{font-size: something}`, it updates the color.

**Comment by jdm** [comment]
I suspect this occurs because modifying the class attribute through the DOMSettableToken list doesn't end up marking the node as dirty. Modifying the class attribute directly goes through [this path](http://mxr.mozilla.org/servo/source/components/script/dom/element.rs#1465) instead, which would mark it dirty.

**Comment by jdm** [comment]
I suspect the DOMSettableToken methods that mutate attributes should explicitly mark the relevant element as dirty.

**Comment by Ms2ger** [comment]
That makes no sense. The attribute changing code should handle this; there's even code in `Element::attribute_mutated` that should.

**Comment by mbrubeck** [comment]
Yes, I verified that the node is correctly marked dirty.  Also, changing to use `.setAttribute("class", ...)` or `.className = ...` does fix the behavior.  The behavior depends on which style property is changed.  `color` and `background` don't work, but `font-size` does.  Maybe the problem is that we're not triggering the correct sort of incremental layout, or the incremental layout logic is buggy for these properties.

**Comment by mbrubeck** [comment]
Debugging shows that style recalc runs as expected, and `repair_if_possible` is called, and correctly repairs the text fragments, but the display list still ends up with the old colors for some reason.

`background-color` updates correctly on block elements, but not on inline elements. Maybe this is related to `Flow::repair_style` which is a no-op for `InlineFlow`.

Disabling incremental layout makes the test case work correctly.

**Comment by mbrubeck** [comment]
The problem is that `repair_if_possible` repairs the original UnscannedText fragments from the node's ConstructionResult, rather than the InlineFlow and its ScannedText fragments.

I think [this case](https://github.com/servo/servo/blob/ba2714f4f607da77bd7200f88cfa16c1d10da9cd/components/layout/construct.rs#L1379-L1383) should just `return false;` because we can't repair the correct fragment(s) here.
