### ISSUE TITLE
Don't ignore errors when sending data over websockets

### ISSUE THREAD

**Issue by jdm** [servo/servo#7861]
In `WebSocket::send` we ignore the result of actually sending the data over the network. That causes us to fail tests, funnily enough :) Following the [spec](https://tools.ietf.org/html/rfc6455#section-10.7) for dealing with invalid data, we should be dispatching a `CloseTask` to ensure that the connection is terminated, and additionally for certain cases of errors we should be implementing the `fail the websocket connection` algorithm which causes the `close the websocket connection` to dispatch an `error` event at the `WebSocket` object. One example is when there are [errors processing UTF-8 data](https://tools.ietf.org/html/rfc6455#section-8.1), which corresponds to a case in the [error result](http://doc.servo.org/websocket/result/enum.WebSocketError.html) from calling send!

Test: `./mach test-wpt tests/wpt/web-platform-tests/websockets/interfaces/WebSocket/events/018.html`
Code: components/script/dom/websocket.rs

**Comment by jimberlage** [comment]
I'll take this on if you want.

**Comment by jdm** [comment]
That would be great!

**Comment by jimberlage** [comment]
So I'm wondering whether we need to be considering invalid input of the type specified in the test.  It seems that if we send an invalid opcode, or bad UTF-8 data, the server would then be responsible for handling the error by calling `_fail_the_websocket_connection_`.  We need to validate dataframes on our own, but it seems like that will happen in the onMessage handler.

That said, we certainly need to do something about errors in `WebSocket::send()`.  Looking through the rust-websocket code, it looks like the possible errors returned by `send_message` are `WebSocketError::DataFrameError` and `WebSocketError::IoError`.  The bulk of the errors are raised when calling the underlying `std::net::TcpStream::write()`, which should likely be handled according to https://tools.ietf.org/html/rfc6455#section-7.2.1 and https://html.spec.whatwg.org/multipage/comms.html#dom-websocket-send.  The `WebSocketError::DataFrameError` result happens when an invalid opcode is used in the dataframe being sent.  By using the `Message` type provided by the rust-websocket library, we are never responsible for setting the opcode.  So while we should handle this case, we should probably treat it like other unexpected errors.

That also makes me wonder whether the test in tests/wpt/web-platform-tests/websockets/interfaces/WebSocket/events/018.html should actually fail.  `WebSocket::send()` shouldn't treat any of the values as opcodes, instead dealing with the entire string as part of the payload.

I'm interested to hear your input; I'm not extremely familiar with the spec by any means, so if I'm misreading things please let me know.

**Comment by jdm** [comment]
You make an excellent point; the strings sent should not cause send errors, but rather errors while receiving since the socket is echoing back the raw bytes that it receives in the payload. Looks like the actual issue here is that we just silently terminate the thread when an `Err` value is received from `incoming_messages`!

**Comment by Wafflespeanut** [comment]
@jimberlage any news on progress?

**Comment by jimberlage** [comment]
Sorry, I've been neglecting this.  If someone else is interested in taking this on, that's fine; otherwise, I'll try to get to it this week.

**Comment by samfoo** [comment]
I'm interested in picking this up.

**Comment by KiChjang** [comment]
It's yours!
