### ISSUE TITLE
Intermittent failure in /_mozilla/css/border_collapse_simple_a.html

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#8120]
https://github.com/servo/servo/pull/8119#issuecomment-149806757

```
/_mozilla/css/border_collapse_simple_a.html 77802e92a2da4dd031b24c4be665f39f9062e055
/_mozilla/css/border_collapse_simple_ref.html 95a8130381addac71d77940ba243397b634e1a43
```

**Comment by jdm** [comment]
There's a one pixel difference in the output. Looks like a layout problem to me.
<img width="819" alt="screen shot 2015-10-21 at 9 39 33 am" src="https://cloud.githubusercontent.com/assets/27658/10638200/aea06808-77d7-11e5-83d5-52159b9dee55.png">

**Comment by nox** [comment]
Cc @mbrubeck 

This is again an incremental layout bug.

Layout is first done with only the first and second rows, resulting in a bottom border of 4px. The other rows are then parsed and laid out, but the bottom border of the second row isn't updated to 2px.

**Comment by mbrubeck** [comment]
Part of the issue is that inserting a row into a table dynamically can lead to a flow tree like this:

```html
    <table>
      <tbody>
        <tr><td></td></tr>
      </tbody>
      <tr><td></td></tr>
    </table>
```

The border-collapse code in Servo has a bug that prevents it from traversing this flow tree correctly.  Fixing that bug fixes the border width.  I haven't submitted that fix yet because some other bug that's causing the *position* of the border to be off by 1px in my test case.  Investigating that now.

**Comment by nox** [comment]
@mbrubeck Oh nice!
