### ISSUE TITLE
Benchmark the Piston `image` crate against libpng, libjpeg-turbo

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#8271]
It would be useful to have some benchmarks comparing decoding speed on a variety of real-world images, in the [image](https://crates.io/crates/image) crate versus popular C libraries like libpng and libjpeg-turbo, so that we can track how much optimization is needed to get to performance parity with other browsers.

**Comment by LifeIsStrange** [comment]
Why not use the popular images library instead of reinventing the wheel ? Recreate an image decoding and encoding library is a waste of time no ? Maybe you want use new paradigm for outperform the actuals popular images library but if it is the case why not Improve this popular library instead of recreate from scratch ? Coding a library Just to make it in rust is something useless. 
Sorry for my poor english and sorry If say something of stupid.

**Comment by jdm** [comment]
The goal of writing image decoders in Rust is to avoid security vulnerabilities due to memory unsafety (eg. https://bugzilla.mozilla.org/show_bug.cgi?id=251381, https://bugzilla.mozilla.org/show_bug.cgi?id=727401, https://bugzilla.mozilla.org/show_bug.cgi?id=155222, https://bugzilla.mozilla.org/show_bug.cgi?id=823071, etc.)

**Comment by LifeIsStrange** [comment]
Ok sorry for my ignorance.

**Comment by Oktosha** [comment]
I'd like to do it

**Comment by jdm** [comment]
@Oktosha I would recommend looking for existing benchmarks for image decoding and using their source images as a starting point :)

**Comment by Oktosha** [comment]
@jdm I've created a [repo](https://github.com/Oktosha/servo-image-benchmark) for this task and added links to sample images to [README](https://github.com/Oktosha/servo-image-benchmark/blob/master/README.md). Also I've written a [TODO](https://github.com/Oktosha/servo-image-benchmark/blob/master/TODO.md) I'm going to follow.

**Comment by gkbrk** [comment]
[Here](https://github.com/gkbrk/ImageBench)'s a small script I wrote for this purpose. I might try adding some graphs/plots maybe.

**Comment by gkbrk** [comment]
Here's an example plot from my benchmark.
![Benchmark Plot](https://i.imgur.com/zjBqsFw.jpg)

**Comment by mbrubeck** [comment]
This is good stuff. Thanks!

**Comment by drbo** [comment]
libjpeg-turbo uses hand-written vector assembly code for many operations, which may explain the large difference.

**Comment by gkbrk** [comment]
Here's another plot after updating the image crate to v0.5.4.

![Rust-Image Benchmark Plot](https://imageupload.co.uk/images/2015/12/04/graph.jpg)

**Comment by jdm** [comment]
@gkbrk Just to confirm, is that using a release build?

**Comment by gkbrk** [comment]
@jdm Yep. I'm not sure if I wrote the rust code in an optimal way though.

**Comment by jdm** [comment]
As written, we don't have an end-state in which we can say we're done. I'm getting rid of the E-easy tag until that changes.

**Comment by nox** [comment]
We use image now.
