### ISSUE TITLE
Add Windows support for the new WPT test runner UI

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#8313]
It currently uses escape codes that probably do not work in Windows terminals.

**Comment by camlorn** [comment]
I'm looking into this because of #17392.

Per an IRC discussion with @retep998, It appears that ANSI can be made to work in Windows 10 well enough for what we're doing.  I've hard-coded the line width.

Python terminal support for earlier versions of Windows is an epic train wreck.  I don't think there's a cross-platform Python package for it, but haven't researched it heavily.

**Comment by mrobinson** [comment]
@camlorn Just looking through some of my old bugs and wanted to check in with you about this: Can we close this bug now since it seems that your changes allow the WPT UI to run on Windows? If not, what's a good description for this bug to encapsulate the current work remaining to do?

**Comment by camlorn** [comment]
@mrobinson 
It does run, but the UI might be awful.  I had to hack around assumptions that we'd be in a Linux terminal.  There weren't good Python libs for Windows.

It's been too long for me to remember specifics, but I'd suggest closing this and waiting for someone to open another ticket if there's still a problem.

**Comment by mrobinson** [comment]
Thanks!
