### ISSUE TITLE
ACID 2 does not render eyes correctly on dual GPU Intel+GeForce 610M

### ISSUE THREAD

**Issue by MikkCZ** [servo/servo#8319]
![acid2-screenshot](https://cloud.githubusercontent.com/assets/3941344/10920662/a8632ac6-8271-11e5-884f-6c632fe1d263.png)
![system-information-screenshot](https://cloud.githubusercontent.com/assets/3941344/10920661/a8603d7a-8271-11e5-9eae-cbbe2d1f2c3a.png)

**Comment by SimonSapin** [comment]
Are you on a "retina" display? Acid 2 is know to only render correctly when CSS `1px` is one device pixel.

**Comment by SimonSapin** [comment]
http://www.webstandards.org/action/acid2/guide/
> For user agents that support font zooming, it [Acid2] also assumes a zoom factor of 100%.

(This was written before high-density display where a thing. High-density is effectively a zoom.)

**Comment by glennw** [comment]
This is also occurring on my (non retina) screen. However, it is fine when using -o to output a screnshot (which is why the reftest is still passing). This is occuring with CPU rendering, so the GPU should be irrelevant here. However, if I run with -i mode, the bug doesn't occur - so it looks to be a bug related to incremental layout and/or reflow.

**Comment by mrobinson** [comment]
I'm pretty sure this is a duplicate of https://github.com/servo/servo/issues/7722.

**Comment by SimonSapin** [comment]
Closing as duplicate.
