### ISSUE TITLE
Determine binary path also taking into account --target flag

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8349]
In the function `get_binary_path` (https://github.com/servo/servo/blob/master/python/servo/command_base.py#L147), it is assumed that the binary is either in the debug or release subfolders of the target folder. In the case where there is a `--target` argument provided to mach (or where it is implicit, because of `--android`), however, the file will be in a folder similar to `target/arm-linux-androideabi/debug`.

The work here is to fix that up so that the command_base code knows how to properly determine the target path and then to replace the hacky-y code in post_build_commands for packaging (https://github.com/servo/servo/blob/master/python/servo/post_build_commands.py#L182) to no longer build that path itself.

Testing the packaging command will require building for Android: https://github.com/servo/servo/wiki/Building-for-Android

**Comment by yanirs** [comment]
Hey, I'm new to the project and thought this might be a good place to start :)

Looking at the code, I was thinking that the way to go may be making `get_binary_path()` consider whether it's an Android build (by looking at `config["build"]["android"]` or accepting a boolean `android` argument). Then, `package()` can set `config["build"]["android"]` to `True` (or call `get_binary_path()` with `android=True`), and call `get_binary_path()` to obtain the correct path.

Is this what you had in mind? It still feels pretty hacky... Ideally, there shouldn't be many checks for Android scattered around the code. Am I missing something?

**Comment by larsbergstrom** [comment]
@yanirs 

That sounds like a good approach! I was mainly hoping to reduce the number of places where we are separately determining and assembling the binary path. 

Now that I'm looking at the code a second time, we might also be able to store the `--target` argument into a build configuration space (it's set for Android to the appropriate triple) and use that. Then, the binary path code would also be future-proofed against other cross targets, like ARM linux! Does that make sense?

Thanks for picking this up!

**Comment by yanirs** [comment]
@larsbergstrom Thanks!

I'm not sure what you mean by storing the `--target` argument into a build configuration space. I was actually wondering about that flag because it's set twice in the `build()` command (https://github.com/servo/servo/blob/master/python/servo/build_commands.py#L195 and https://github.com/servo/servo/blob/master/python/servo/build_commands.py#L201). Do you mean adding a `--target` argument to `package()`?

By the way, I've noticed that some of the `CommandArgument` decorators are duplicated several times (like `--dev` and `--release`). Have you thought of reducing this duplication? It'd probably be better to address it in a separate issue, though :)

**Comment by larsbergstrom** [comment]
@yanirs Sorry for the delay!

I was wondering if it would be possible to store it into the hashmap like many of the other settings (e.g., as `self.config["build"]["target"] = "arm-linux-androideabi"` instead of checking in a more ad-hock manner (or requiring the `--android` flag). Does that make sense? Sorry if I'm using poor terminology - your python is likely better than mine, as I'm pretty new to it!

Anything that reduces duplication would be a very welcome change! We've grown a lot of these scripts by "editor-based-inheritance" so there's a ton of duplication. Suggestions to clean that up would be awesome.

**Comment by yanirs** [comment]
@larsbergstrom No worries :)

I added `arm-linux-androideabi` as the default value of `self.config["android"]["target"]` because it's an Android-specific target. I don't think it's possible to get rid of flags completely because the pattern seems to be that the flags override the `self.config` dictionary (which is desirable when building in different modes for multiple platforms). It may make sense to merge some of the flags as a step towards reducing duplication, e.g., `--dev` and `--release` could be merged into `--mode`, and `--android` could be merged into `--target`.

**Comment by Wafflespeanut** [comment]
#8596 closes this.
