### ISSUE TITLE
Handle generic font-family names

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#8371]
https://drafts.csswg.org/css-fonts/#propdef-font-family
https://drafts.csswg.org/css-fonts/#generic-font-families

In the `font-family` property, the `serif`, `sans-serif`, `cursive`, `fantasy`, and `monospace` keywords represent generic families when they’re not in quotes.
- Uncomment [this code](https://github.com/servo/servo/blob/9fea6d2e46dd917f16a5f1ec0f6484e8164c7a3a/components/style/properties.mako.rs#L1734-L1738) and [this code](https://github.com/servo/servo/blob/9fea6d2e46dd917f16a5f1ec0f6484e8164c7a3a/components/style/properties.mako.rs#L1785-L1792) in `components/style/properties.mako.rs`
- Change [`get_initial_value()`](https://github.com/servo/servo/blob/9fea6d2e46dd917f16a5f1ec0f6484e8164c7a3a/components/style/properties.mako.rs#L1772) to return `FontFamily::Serif`
- Handle the new variants in `components/gfx/font_context.rs`. (I have no idea what this involves.)

**Comment by SimonSapin** [comment]
See also occurrences of "generic" in `components/gfx/font_cache_task`. Since there is a fixed set of generic families, maybe the hash map in `FontCache::generic_fonts` should be replaced with a `match` expression on the style crate’s `FontFamily` enum.

**Comment by SimonSapin** [comment]
CC @Ms2ger @pcwalton @glennw for winning the `git shortlog -sn components/gfx/font*` lottery.

**Comment by craftytrickster** [comment]
If possible, I would like to attempt this.

**Comment by eefriedman** [comment]
Okay; feel free to ask if you have any questions.

**Comment by craftytrickster** [comment]
@eefriedman Thank you.
@SimonSapin Thank you for the explanation of the issue. I have made some preliminary changes which I will put in a pull request.

As for handling the variants in `components/gfx/font_context.rs`, I am not sure anything needs to be done there, since it is not directly interacting with the FontFamily enum. 

As for the modifying `components/gfx/font_cache_task`, I did replace the plain string instances with instances of the FontFamily enum, however, I did not remove the HashMap. My reasoning is because when `transform_family` is called, if we did not use the HashMap we would have to calculate the mapped family every time instead of doing it one time upfront during hashmap population.
