### ISSUE TITLE
Spaces in path break virtualenv creation

### ISSUE THREAD

**Issue by schumannd** [servo/servo#8390]
`./mach build --dev` fails with `Pip failed to execute properly.` which comes from l.135 in `python/mach_bootstrap.py`

This is due to:
`subprocess.check_call([pip, "install", "-q", "-r", req_path])`
where `pip` contains the path to pip in the newly created virtual environment, but without escaped spaces.

To reproduce just try to set up rust in a folder which contains a space in its name.

**Comment by zwn** [comment]
I think the fix in #8394 (4ff8d3ad9cea) is not correct (meaning it does not help in any way) and in addition it breaks windows build for me. Does windows build work for anyone else from a clean checkout?

Doing 
```python
>>> from pipes import quote
>>> quote('windows\\path')
"'windows\\path'"
>>>
```
creates a quoted path that is good for shell but not for `__file__`.  Inside `activate_this.py` it is used to adjust the PATH but it fails:
```python
>>> os.getcwd()
'C:\\software\\git'
>>> os.path.abspath(__file__)
"C:\\software\\git\\'windows\\path'"
>>>
```
Please note how the 'windows\\path' gets embedded literately to make nonexisting path.

Also according to https://docs.python.org/2/library/subprocess.html#subprocess.check_call by default shell is not involved so shell quoting is not needed. The original problem must have been caused by something else.

**Comment by frewsxcv** [comment]
@zwn Can you open a new issue for that? This issue was (implicitly) about OSX/Linux, so if there's an issue with spaces in filepaths on Windows, we should probably create a new issue. You can just copy and paste what you just wrote into the body of the issue

**Comment by zwn** [comment]
Done so in #10595.
