### ISSUE TITLE
Should Document::invalidate_stylesheets really call get_html_element?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8409]
It means we won't mark the document element dirty if it's not an `html` element.

**Comment by mbrubeck** [comment]
This could by fixed by changing [this code] to call `self.GetDocumentElement()` instead of `self.get_html_element()`.

It looks like there are several other calls to `get_html_element` that could also be changed in this way.

[1]: https://github.com/servo/servo/blob/e4fe0db8fd5f0b5431ba3856b4931613a96e924e/components/script/dom/document.rs#L1238-L1240

**Comment by djc** [comment]
I would like to take this.

**Comment by jdm** [comment]
Please do!
