### ISSUE TITLE
Resizing browser window doesn't redraw webpage with new viewport bounds

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8443]
I can reproduce this with https://news.ycombinator.com and https://wikipedia.org

![](https://cloud.githubusercontent.com/assets/416575/11052607/8bca03c0-8727-11e5-99d6-e6c948747db9.gif)

I did a `git bisect` and traced the issue back to this commit: https://github.com/servo/servo/commit/f1b6c7cc99d0804daa52753d02368927176b6c05

**Comment by SimonSapin** [comment]
I’ve reduced the (manual) test case to:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<p style="border: solid">Test
```

On to messing with iframes.

**Comment by notriddle** [comment]
@SimonSapin Didn't realize you were working on this; once you've got a test case built, do you have a fixed version of Servo also or should I make a pull request of b46f641.

**Comment by SimonSapin** [comment]
Oh, nice! I just finished the test case but haven’t started looking into the fix yet.

tests/wpt/mozilla/tests/css/meta_viewport_resize_iframe.html
```html
<meta name="viewport" content="initial-scale=1.0">
<body style="margin: 0">
Test
```

tests/wpt/mozilla/tests/css/meta_viewport_resize.html
```html
<!doctype html>
<meta charset=utf-8>
<title>Resizing the initial containing block dynamically with &lt;meta name="viewport">
       https://github.com/servo/servo/issues/8443</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script>
setup({ "explicit_done": true });
function run() {
    test(function() {
        var iframe = document.getElementsByTagName("iframe")[0];
        var body_style = iframe.contentWindow.getComputedStyle(iframe.contentDocument.body);

        assert_equals(body_style.width, "400px");
        iframe.width = 500;
        window.setTimeout(function() {
            test(function() {
                console.log(body_style.width);
                assert_equals(body_style.width, "500px");
            }, "<body>’s width inside <iframe> update dynamically with <iframe>’s width");
            done();
        }, 200);
    }, "<body> inside <iframe> has the <iframe>’s width");
}
</script>
<iframe src="meta_viewport_resize_iframe.html" onload="run()" width=400></iframe>
```

This passes in Firefox and Chromium, but in addition to the bug I was looking to reproduce (the width is unchanged in the second assert) there’s an other bug: `<meta name="viewport" content="initial-scale=1.0">` causes `body_style.width` to be 800px instead of 400px. I don’t understand why.

**Comment by SimonSapin** [comment]
@notriddle Do you want to make a PR with that test? Do you have an idea about the 800px bug?

**Comment by notriddle** [comment]
The test passes in my branch, anyway, so I went ahead and opened the PR. I suspect the reason it was doing 800px was that it was starting out with the device's size set to initial_window_size (which has an 800px width) and, since it was never changing the device's size, it was never changing, even with the initial resize event that is carefully sent before the script could observe it.
