### ISSUE TITLE
Web assembly support

### ISSUE THREAD

**Issue by runvnc** [servo/servo#8448]
Just wondering if servo supports web assembly in any way or if there is an effort ongoing related to that.

**Comment by Ms2ger** [comment]
This is mostly going to happen in SpiderMonkey, so we'll pick it up when Firefox gets it.

Metabug: https://bugzilla.mozilla.org/show_bug.cgi?id=1188259

**Comment by LifeIsStrange** [comment]
And what about shumway support ? =)

**Comment by metajack** [comment]
@tschneidereit Can give you more info on what is needed for Shumway as he did some investigation of that several months back.

**Comment by tschneidereit** [comment]
Shumway support is blocked by many small things, not any major missing
feature. Instead of hacking Shumway to get it working *somehow*, I'm slowly
working through the blockers as I encounter them. Right now, that means
some small CSSOM stuff. #7979 and #8039 were results of that, and I'm
making good progress on building on those to actually support some CSSOM
APIs.

Then there's the issue of `SVGMatrix` not being supported. I *think* we
might actually get away with never implementing that, and going with
`DOMMatrix` instead. Implementing that isn't trivial, either, though. #7415
and #6683 were preparatory work.

Once the DOM API blockers are all out of the way, it's going to be all
about Canvas2D. From what I was told, various issues should be expected,
because the implementation has major holes, apparently. I haven't looked
into that part at all, though.

**Comment by Ms2ger** [comment]
Shumway is #6097, for future reference

**Comment by LifeIsStrange** [comment]
Ok sorry and thanks !

**Comment by frewsxcv** [comment]
Going to close in favor of #9232 since there is more up-to-date info there
