### ISSUE TITLE
Rename conversion routines, again.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8473]
In b290a3161d8ac85c7bcc3f9d7c0ae5a6fa379607, @nox renamed a bunch of conversion routines in a way that is almost diametrically opposed to [the standard terminology we use](http://doc.servo.org/servo/script/dom/index.html#a-dom-object-and-its-reflector). In particular, an object that implements `Reflectable` is a "DOM object", and a `JSObject` for a DOM object is its "reflector". We should correct these names.

**Comment by nox** [comment]
So why would "reflector" refer to JSObject, when we have an actual Rust structure called Reflector and nothing named Object anywhere? We should probably rename again everything, but we need a new term somewhere.

**Comment by nox** [comment]
In the documentation you point out, I would rename **DOM object** to **DOM structure**, and **reflector** to **object**.

**Comment by Ms2ger** [comment]
CC @bholley

**Comment by bholley** [comment]
"Object Reflection" is the standard term that I'm aware of for mirroring objects across language runtimes. Of those two words, the "reflect" part is much less ambiguous than the "object" part, which is why "reflector" is a better name than "object".

It is unfortunate that Rust has also recently introduced a trait called "Reflect". However, I still think that in there are, in total, several orders of magnitude more meanings of the term "object" than there are of the term "reflector", and that the former would be extremely confusing, especially in the case where a given Rust DOM object holds onto other JS objects in addition to its reflector.

**Comment by jdm** [comment]
Rust introduced a Reflect trait?

**Comment by metajack** [comment]
This was news to me too:
https://doc.rust-lang.org/stable/std/marker/trait.Reflect.html

**Comment by bholley** [comment]
FWIW the naming of "Reflectable" rather than "Reflect" was my fault, since I was a rust n00b at the time (several years ago). I sorta figured it would get fixed at some point.

**Comment by nox** [comment]
What about global_root_from_reflectable, instead of global_root_from_reflector?

**Comment by Ms2ger** [comment]
I think I'd prefer renaming `Reflectable` to `DOMObject`.

**Comment by bholley** [comment]
> I think I'd prefer renaming Reflectable to DOMObject.

That sounds reasonable to me.

**Comment by frewsxcv** [comment]
> I think I'd prefer renaming `Reflectable` to `DOMObject`.

Is this change still desired? If so, I can make the change.

**Comment by nox** [comment]
Seems ok with me too.

**Comment by frewsxcv** [comment]
PR opened: https://github.com/servo/servo/pull/14495.

🖌 🚲 🏠
