### ISSUE TITLE
Format our code with rustfmt

### ISSUE THREAD

**Issue by saneyuki** [servo/servo#8553]
I think we should do this.

**Comment by saneyuki** [comment]
cc: @Manishearth ?

**Comment by Manishearth** [comment]
It's not ready yet. I periodically try running it on Servo.

**Comment by frewsxcv** [comment]
Anyone know how Go projects incorporate gofmt (or Rust w/ rustfmt) into project workflows? Require that it get used pre-commit and checked via CI? Have the build system automatically format upon check-in (which sounds scary)? Something else?

**Comment by saneyuki** [comment]
I think it would be better to check in CI the commited files as tidy which we're running. It's not enough?

**Comment by Manishearth** [comment]
Checked via CI I think. Similar to how clippy checks update_lints or how servo checks lockfile_changed.

I'd rather not gate CI on rustfmt though. I'm slightly more okay with it if we use circleci or something for tidy+fmt to get separate and immediate status icons from the long build.

**Comment by Manishearth** [comment]
So I've been poking around, and rustfmt seems to be much more stable now.

The following toml config is pretty nice for servo

```rust
reorder_imports = true
reorder_imported_names = true
max_width = 120
ideal_width = 80
normalize_comments = false
```

`normalize_comments` prevents the license comment from being reformatted to use line comments instead of block comments. We might want to do that anyway, but it's nice to reduce the impact of the first run.

rustfmt currently doesn't reorder `extern crate`s. Furthermore, it reformats `#[attr] extern crate foo;` into two lines, which breaks tidy (tidy only asks for the sorting of extern crate lines which do not have attributes, since the ones with attributes usually have special requirements for ordering). We'll need to change this a bit and/or add extern crate sorting to rustfmt.

I would like to reformat everything and slowly make rustfmt part of CI checks. Perhaps removing the corresponding tidy checks.

Thoughts? @jdm @Ms2ger @Wafflespeanut

**Comment by jdm** [comment]
I'm open to that plan. I think adding extern crate reordering to rustfmt makes the most sense.

**Comment by Wafflespeanut** [comment]
It'd be wonderful to have rustfmt in tree. Also, tidy's sorting isn't that great right now (#9259). We can improve it in tidy, but rustfmt should do this better. I never imagined that rustfmt could be integrated so easily :smile:

**Comment by pyfisch** [comment]
:tada: rustfmt now works well on servo with this config:

```
match_block_trailing_comma = true
binop_separator = "Back"
error_on_line_overflow = false
```

It can be installed with `rustup install rustfmt-preview` for servo and run with `cargo fmt --package layout` for individual packages like `layout`.

The formatting works with `./mach test-tidy` but the long (>100 character) imports need to be formatted by hand.

**Comment by atouchet** [comment]
Is this done now?

**Comment by CYBAI** [comment]
Done by #22126 !
