### ISSUE TITLE
Null compositor does not assign sizes for subpages

### ISSUE THREAD

**Issue by notriddle** [servo/servo#8573]
The non-headless compositor is assigning the size based on the size of the iframe's corresponding layer, which the headless one never creates.

Why isn't layout doing this job? After all, it always exists.

**Comment by jdm** [comment]
@glennw do you know the answer to this question?

**Comment by glennw** [comment]
This is probably more a question for @pcwalton - I can't quite recall the details (although I can probably dig into the code and find out if pcwalton doesn't know). On a tangent - what purpose does the null compositor actually serve these days? Since we're able to run the normal compositor in headless mode without any X dependencies, do we need to keep the null compositor?

**Comment by notriddle** [comment]
The null compositor is used when nothing needs to be drawn, like with
script tests.

**Comment by glennw** [comment]
Sure, but given that it adds an extra maintenance burden, perhaps it's simpler just to run the script tests with the normal compositor running in headless mode?

**Comment by Ms2ger** [comment]
If that works just as well, I guess that would be fine.

**Comment by jdm** [comment]
This is not the first time we've been bitten by different behaviour between the compositor implementations. We should kill it if we can.
