### ISSUE TITLE
Remove the `wrap_fn` argument from `reflect_dom_object`.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8576]
It should be possible to derive it from the type. Maybe `FooBinding::Wrap` should be `<Foo as ConcreteDOMObject>::wrap`? (Name of the trait up for bikeshedding.)

**Comment by nox** [comment]
This obviously exclude global interfaces, which don't have the same wrap signature. Maybe we should also have a reflect_dom_global function with that other wrap?

**Comment by Ms2ger** [comment]
Orthogonal to this issue, but that sounds like something we could do, yes.

**Comment by kjhyung** [comment]
@jdm hi can i try this issue?

**Comment by jdm** [comment]
@kjhyung Of course!

**Comment by jdm** [comment]
@kjhyung Have you made any progress on this task?

**Comment by lyuyuan** [comment]
@jdm May I have a try on this if no one is working on it now?

**Comment by jdm** [comment]
@lyuyuan Sure! I think the easiest way to proceed is to:
* add an associated const to the DomObject trait which is a function pointer to the general wrap function type (https://doc.servo.org/script/dom/bindings/codegen/Bindings/ANGLEInstancedArraysBinding/ANGLEInstancedArraysBinding/fn.Wrap.html, using `Self` instead of `ANGLEInstancedArrays`)
* modify the output of `#[dom_struct]` (https://github.com/servo/servo/blob/master/components/dom_struct/lib.rs) to produce an implementation of DomObject that includes the new associated constant (using `crate::dom::codegen::Bindings::[name]Bindings::Wrap` for a type named `[name]`)
* remove the `wrap_fn` argument from [reflect_dom_object](https://github.com/servo/servo/blob/master/components/script/dom/bindings/reflector.rs#L17) and use `T::WRAP` instead (assuming the new associated constant is called WRAP)

Does that make sense?

**Comment by lyuyuan** [comment]
@jdm Sounds good! Thanks for the tip!

**Comment by lyuyuan** [comment]
@jdm It seems that `DomObject` trait cannot contain associated constants ([E0038](https://doc.rust-lang.org/error-index.html#E0038)) because it is [`FormControl`](https://github.com/servo/servo/blob/1b7223a284cd8f780d2856a50747ffc97beffd23/components/script/dom/htmlformelement.rs#L1320)'s supertrait and `FormControl` is used in a trait object [here](https://github.com/servo/servo/blob/1b7223a284cd8f780d2856a50747ffc97beffd23/components/script/dom/htmlformelement.rs#L1535-L1577).
If I understand the [workaround ](https://doc.rust-lang.org/error-index.html#the-trait-cannot-contain-associated-constants)correctly, I need to add a helper method in `DomObject` which returns the WRAP function pointer. Does this sounds correct? Thanks!

**Comment by jdm** [comment]
I think we can get away with a different solution:
```trait DomObjectWrap {
    const WRAP: ...
}
```
And edit https://github.com/servo/servo/blob/master/components/dom_struct/lib.rs#L42-L53 to implement the DomObjectWrap trait, and make reflect_dom_object take `T: DomObject + DomObjectWrap`.
