### ISSUE TITLE
Add HSTS pinning

### ISSUE THREAD

**Issue by alex** [servo/servo#8580]
Pages such as https://subdomain.preloaded-hsts.badssl.com/ should be disallowed from loading.

**Comment by samfoo** [comment]
"HSTS pinning" doesn't make any sense to me. I just checked and when servo navigates to...

[**http**://subdomain.preloaded-hsts.badssl.com/](http://subdomain.preloaded-hsts.badssl.com/)

...it correctly sees that the subdomain requires secure loading and upgrades the connection to [**https**://subdomain.preloaded-hsts.badssl.com/](https://subdomain.preloaded-hsts.badssl.com/)

The current HSTS preload includes:

```
        ...
        {
            "host": "preloaded-hsts.badssl.com", 
            "include_subdomains": true
        }, 
        ...
```
---

The problem is that the certificate is invalid for that subdomain. The wildcard cert `*.badssl.com` should not match `subdomain.preloaded-hsts.badssl.com` as per [RFC](https://tools.ietf.org/html/rfc2818#section-3.1) 

Specifically:

    Matching is performed using the matching rules specified by
    [RFC2459].  If more than one identity of a given type is present in
    the certificate (e.g., more than one dNSName name, a match in any one
    of the set is considered acceptable.) Names may contain the wildcard
    character * which is considered to match any single domain name
    component or component fragment. E.g., *.a.com matches foo.a.com but
    not bar.foo.a.com. f*.com matches foo.com but not bar.com.

Right now servo & hyper don't do any validation on TLS hostnames. I believe this is already documented as a problem in hyperium/hyper#472 and servo/servo#4954

**Comment by alex** [comment]
Bleh, you're right not sure why I typed HSTS pinning.

As for the wildcard bit, it's not clear to me whether it's correct or not for HSTS to use the wildcard rule there, it's clear that Chrome treats the wildcard as matching multiple path components.

**Comment by nox** [comment]
Pretty sure we support HSTS now.
