### ISSUE TITLE
servo.org should be https-only

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8585]
As mentioned by @jruderman (https://twitter.com/jruderman/status/666954504366067712), since it has commands to type into a terminal and soon links to nightly builds, we should be serving it only over https.

@edunham, do you know how to set that up?

**Comment by Manishearth** [comment]
Github pages can't handle HTTPS+custom domains.

We will need to proxy it through nginx or move it off GH-hosted GH pages entirely.

**Comment by frewsxcv** [comment]
Relevant issue: #7262

> HTTPS+custom domains

[Yes it can](https://github.com/servo/servo/issues/7262#issuecomment-132436142)

**Comment by Manishearth** [comment]
Ooooo nice

**Comment by larsbergstrom** [comment]
@frewsxcv That is fantastic news - thanks for passing that info on!

**Comment by edunham** [comment]
servo.org now redirects to https://servo.org/, as does www.servo.org. 

blog.servo.org does not have HTTPS yet because it doesn't display right on https://servo.github.io/blog.servo.org (https://github.com/servo/blog.servo.org/issues/45). Distributing the site over HTTP from github to cloudflare then HTTPS from cloudflare to the user would be deceptive.

**Comment by frewsxcv** [comment]
:confetti_ball:
