### ISSUE TITLE
Implement "input" event for <input> elements

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8613]
https://html.spec.whatwg.org/multipage/forms.html#event-input-input

**Comment by jdm** [comment]
We actually have code that is supposed to do this already in HTMLInputElement::handle_event. Do you have a testcase showing that this doesn't work?

**Comment by Manishearth** [comment]
So we already sort of support them, though `.onsubmit` won't work (attaching event handlers will work).

https://github.com/servo/servo/blob/master/components/script/dom/htmlinputelement.rs#L797

We don't support them for text boxes because text boxes don't seem to have activation behavior (?). I can't find where in the spec we're supposed to catch changes to text boxes, will look deeper in a bit.

**Comment by Manishearth** [comment]
> For input elements without a defined activation behaviour, but to which these events apply, and for which the user interface involves both interactive manipulation and an explicit commit action, then when the user changes the element's value, the user agent must queue a task to fire a simple event that bubbles named input at the input element, and any time the user commits the change, the user agent must queue a task to fire a simple event that bubbles named change at the input element.

It was right there :confounded:

**Comment by paulrouget** [comment]
Oh, I might have done something wrong.

I'll investigate.

Here is the code I've been using:

```html
<!DOCTYPE html>
<html>
<body>
  <input type="text">
  <pre></pre>
  <script>
    var i = document.querySelector("input");
    var pre = document.querySelector("pre")
    i.addEventListener("input", function(e) {
      pre.textContent += "> "  + e.target.value + "\n";
    });
  </script>  
</body>
</html>
```

**Comment by paulrouget** [comment]
fwiw, in browser.html, we will use the `keyup` event as a workaround until this get resolved.

**Comment by jdm** [comment]
Awkward! I was reading htmltextareaelement.rs somehow. We should do the exact same thing we do in HTMLTextAreaElement::handle_event - check for a trusted event and queue a runnable that causes the "input" event to be dispatched at the element.

Code: components/script/dom/htmlinputelement.rs

**Comment by wldcordeiro** [comment]
I'd like to try taking this issue.

**Comment by Manishearth** [comment]
Sure! Let us know if you need help!

**Comment by wldcordeiro** [comment]
Could I just get a run down of what parts of the source I'm most interested in for this and resources about how the input event should work? (That html spec link I assume is good to start with)

**Comment by Manishearth** [comment]
@wldcordeiro htmltextareaelement.rs and htmlinputelement.rs, basically

https://github.com/servo/servo/blob/master/components/script/dom/htmltextareaelement.rs#L336

You'll need to add a similar `value_changed` field if we don't have one already, and in the key handler dispatch a change event.

Might be worthwhile to move ChangeEventRunnable into htmlinputelement.rs somewhere and make it take an EventTarget instead of an HTMLTextAreaElement (just do the [upcast](https://github.com/servo/servo/blob/master/components/script/dom/htmltextareaelement.rs#L245) early)

**Comment by Manishearth** [comment]
@wldcordeiro any updates?

**Comment by frewsxcv** [comment]
Unassigning since we haven't heard from @wldcordeiro

**Comment by ckimes89** [comment]
I'd like to try taking this issue.

@Manishearth you mention that ChangeEventRunnable could be changed to use an EventTarget, but the Runnable impl for ChangeEventRunnable calls a method defined on HTMLTextAreaElement.

https://github.com/servo/servo/blob/master/components/script/dom/htmltextareaelement.rs#L363
https://github.com/servo/servo/blob/master/components/script/dom/htmltextareaelement.rs#L237

`dispatch_change_event` doesn't seem to be doing anything special that's particular to the HTMLTextAreaElement aside from getting the element's window. Is it possible to get the window from an EventTarget? I just get compiler errors trying to do it the naive way.

**Comment by jdm** [comment]
The easiest way to get the window from an eventtarget would be to downcast it to a Node and call `window_from_node`.

**Comment by Manishearth** [comment]
Actually, `dispatch_change_event` could take a `Node` instead (all Nodes are EventTargets, not all EventTargets are Nodes)
