### ISSUE TITLE
tidy.py check for cargo versions doesn't report multiple byteorder packages

### ISSUE THREAD

**Issue by jdm** [servo/servo#8691]
Noticed in review for #8446.

**Comment by Wafflespeanut** [comment]
Ah! `check_lock` only compares the versions of dependencies with that of the base packages it has collected along the way. Since both "byteorder" packages [exist as base packages](https://github.com/servo/servo/blob/dc0e467945e7fb8eaf93f9e40e7ebcb2d5f52b0c/components/servo/Cargo.lock#L142-L150), the old one's being replaced. This could be an easy issue :)

Code: `python/tidy.py`

**Comment by GuillaumeGomez** [comment]
Then I'll take this one. ;)
