### ISSUE TITLE
Make Fragment::debug_id only claim space in debug mode

### ISSUE THREAD

**Issue by burg** [servo/servo#87]
For debugging purposes, all flows/boxes are stamped with an int, to make debugging output readable. Somehow, we should only include this field for debug builds. (well, once there is more than one build mode...)

**Comment by frewsxcv** [comment]
Update: #420 has been closed

**Comment by mbrubeck** [comment]
This number is currently stored in [Fragment::debug_id][1].  This could be fixed by changing this field's type from `u16` to a new custom type `struct DebugId`.  Then use [conditional compilation] to make this struct contain a single `u16` field when `cfg(debug_assertions)` is enabled, or no fields otherwise (so it will take up zero space).

The new type will need to implement the Display trait.  In non-debug builds, it could display as an empty string, or maybe as its own address.

[1]: https://github.com/servo/servo/blob/ea38ccfdfe12c64d41ff460f358e21cafead8414/components/layout/fragment.rs#L120-L121
[conditional compilation]: http://doc.rust-lang.org/reference.html#conditional-compilation

**Comment by mitchhentges** [comment]
I bet I can take care of this

**Comment by mitchhentges** [comment]
I'm not sure what we want to return from [`debug_id()`](https://github.com/servo/servo/blob/master/components/layout/fragment.rs#L848-L850) if it doesn't exist, so I'll opt for `-1`. This will affect [fmt::Debug for Fragment](https://github.com/servo/servo/blob/master/components/layout/fragment.rs#L2627) and [`Encodable for Fragment`](https://github.com/servo/servo/blob/master/components/layout/fragment.rs#L132)

**Comment by mbrubeck** [comment]
You could change debug_id() to return a DebugId instead of u16.

**Comment by mitchhentges** [comment]
Hmm, that will just defer the I'd resolution, but I think I've got some ideas. Memory address sounds good, too
