### ISSUE TITLE
Support for CSS :link selector

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8720]
https://html.spec.whatwg.org/multipage/#selector-link

https://drafts.csswg.org/selectors/#link

**Comment by frewsxcv** [comment]
Depends on #8715

**Comment by salty-horse** [comment]
Seems implemented here: [components/script/dom/element.rs:1680](https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1680)

**Comment by SimonSapin** [comment]
`:link` is misnamed in CSS since it’s exclusive with `:visited`: it only matches links that are not visited. I’ve named the trait methods according to the pseudo-classes’ meaning rather than their syntax:

* Selector `:link` calls trait method `fn is_unvisited_link(&self) -> bool`
* Selector `:visited` calls trait method `fn is_visited_link()(&self) -> bool`
* Selector `:any-link` is equivalent to `:matches(:link, :visited)`, calls trait method `fn is_link()(&self) -> bool`

https://github.com/servo/rust-selectors/blob/74a3ff5228/src/parser.rs#L620-L622
https://github.com/servo/rust-selectors/blob/74a3ff5228/src/matching.rs#L657-L666

`:link` is already implemented, but at the moment it is identical to `:any-link` for reasons explained in https://github.com/servo/servo/issues/8718#issuecomment-160323338.

Closing this issue in favor of #8718, since it’s really the same thing.
