### ISSUE TITLE
Move PaintListener to gfx_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#8834]
This trait is only used by `gfx/` and `compositing/`, so it's an easy candidate to move out of the grab-bag `msg/` crate.

Code: `components/msg/compositor_msg.rs`, `components/gfx_traits/lib.rs`, `components/gfx/paint_task.rs`

**Comment by cnaj** [comment]
I've taken a quick look into it; it seems that `PaintListener` depends on `msg::constellation_msg::PipelineId` (which should stay in `msg`, I guess). `msg::constellation_msg::ScriptMsg` depends on `canvas_traits::CanvasMsg`, and `canvas_traits` in turn depends on `gfx_traits`, where we would have a circular dependency.

Do I see it right that the dependency from `msg` crate to `canvas_traits` is the problematic dependency (i.e. which pulls in graphics into messages)?

I'm still evaluating if I can work on this because it's my first contact to servo.

**Comment by KiChjang** [comment]
Does `PaintListener` depend upon `msg::constellation_msg::ScriptMsg`? If not, there shouldn't be any issue in moving `PaintListener` to `gfx_traits`.

**Comment by jdm** [comment]
Oh, so `msg` depends on `gfx_traits` via `canvas_traits`? That's... unfortunate.

**Comment by jdm** [comment]
We might be able to fix that problem by fixing #8833 first.

**Comment by KiChjang** [comment]
#8833 has been resolved.

**Comment by cnaj** [comment]
Started to work on this.
