### ISSUE TITLE
Set the canvas state properly when using pattern arguments for setStrokeStyle/setFillStyle

### ISSUE THREAD

**Issue by jdm** [servo/servo#9081]
The test added in #9080 has two cases that don't pass, and they both involve pattern objects. If we compare the branches in `CanvasRenderingContext2d::SetFillStyle`/`SetStrokeStyle`, we see that the strong and gradient paths set the `state` field, while the pattern ones don't, which is why the getters don't retrieve the pattern object as expected.

Code: `components/script/dom/canvasrenderingcontext2d.rs`
Test: `./mach test-wpt tests/wpt/mozilla/tests/mozilla/canvas/fill_and_stroke_getters_setters.html`

**Comment by Ms2ger** [comment]
Note the line
```

**Comment by jdm** [comment]
That is changed in #9080.

**Comment by iszak** [comment]
Since this doesn't have the label C-assigned I am assuming it's still open and would like to try it.

By looking at the [specification](http://www.w3.org/TR/2dcontext/#fill-and-stroke-styles) it seems we need to store the CanvasPattern object in state so that it can be retrieved via fillStyle/strokeStyle and that should fix the test.
