### ISSUE TITLE
Only set clip for background image when required.

### ISSUE THREAD

**Issue by glennw** [servo/servo#9154]
See https://github.com/servo/servo/blob/master/components/layout/display_list_builder.rs#L427

Setting unnecessary clips works fine on WR, but it can introduce batch breaks when using GPU clipping, so there is a performance win by avoiding unnecessary clip rects.

This appears to be the only place in the code that causes a lot of unnecessary clip rects on real world pages I have tested on.

**Comment by pcwalton** [comment]
cc me

**Comment by glennw** [comment]
@pcwalton Did the fix for this land?

**Comment by mrobinson** [comment]
I'm pretty sure this is no longer an issue after https://github.com/servo/servo/pull/17694. For the non-LocalClip case this isn't as easy to fix in Servo, because the rounded clips are stored in the ClipScrollTree. In any case, this optimization should probably be done in WebRender, so it can be shared by all types of items.
