### ISSUE TITLE
Refactor WebGLPaintTask to prevent creating extra IPC channels

### ISSUE THREAD

**Issue by ecoal95** [servo/servo#9228]
Right now we create an IPC channel when we create a `WebGLPaintTask`. 

When the context creation fails, this channel is not returned and thus created in vain.

The mspc channel is necessary, since the task makes use of it, but it should be easy to wait until we know the task has succeeded to create the IPC channel.

Code: https://github.com/servo/servo/blob/master/components/canvas/webgl_paint_task.rs#L188-L234

**Comment by coder543** [comment]
I'm thinking about contributing to Servo, so I was looking at the code section highlighted. Is it normal for Servo code to just be seat-of-the-pants `unwrap`-ing everything? That seems pretty dangerous, but I'm not going to claim to be a Rust expert at this point.

**Comment by KiChjang** [comment]
If you don't expect an error to happen at all, it's ok to use `.unwrap()`. Are you currently working on this issue?

**Comment by ecoal95** [comment]
Hi Josh.

Generally if the corresponding failure is fatal, and there's no
way to recover from the error, there's no problem unwrapping it.

E.g.: If a `send()` or `recv()` message fails, we've lost communication
with the outer thread, and there's no way to guarantee that the program
execution will continue as expected, so IMO it's preferrable to crash
instead of, for example, get locked waiting to receive something.

Unwrap is just syntax suggar to avoid writing a ton of `panic!`s on
unrecoverable errors.

**Comment by coder543** [comment]
Hello,

Those responses make sense. Thanks!

And right now I'm studying the issue to see if I understand it. What I'm seeing right now is that lines 190 to 192 need to stay where they are so that their variables can be accessed from line 233. Nothing can really change there. But, line 193 could be moved to right after line 205 with no ill effects, I think. If that's all there is to this bug, then all I would need to do is make that change, test that it still compiles, and then submit a pull request? Or is there a set of unit tests I need to run? The "Hacking Quickstart" indicates that a PR won't be accepted unless there's a test, but I'm not sure how this change would be tested.

**Comment by ecoal95** [comment]
The idea will be to move lines 190 and 193 (those which make use of the ipc channel,
which is more expensive to create) as far to the bottom as possible, and don't execute
them if the `result_port` receives an `Err` value.

**Comment by coder543** [comment]
Alright, I'm working on this issue now. I tested out my initial idea of moving line 193 into the closure, but I had overlooked how the closure would then take ownership of in_process_chan. I could always create an `in_process_chan_clone = in_process_chan.clone()` that the closure would be allowed to take ownership of, but I'm currently playing with moving lines 190 and 193 down below the closure entirely. The reason I initially didn't want to do that was because I was afraid that any messages sent before the `ROUTER.route` call would be lost, effectively defeating the purpose. It looks like that isn't the case though. I moved line 193 below the closure and ran `./mach run tests/html/test_webgl_triangle.html` and the triangle seemed to be rendered into the viewport perfectly, so it seems that the messages in the channel are still routed correctly, I suppose. Now I moved line 190 below the closure and I'm waiting on it to build again.

What kind of test should I write for this?

**Comment by ecoal95** [comment]
You can't write a teat for this, since these are implementation details.
Its fine if it builds and passes the existing tests :-)

The approach looks good to me so far. The Router line position won't affect
anything, since it just means something like: "I want to proxy all the
messages that arrive to this IPC channel to this in-process channel", and
no message will be sent before exiting that function.
