### ISSUE TITLE
Re-export IDL union typedefs instead of using type aliasing

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9511]
#9419 introduced type aliasing for IDL typedefs. However, due to rust-lang/rust#26264, we cannot use enum variants with aliased enums. We will instead need to change the type aliasing into re-exports, something of the form `pub use Foo as TypeDefBar`.

Code: `components/script/dom/bindings/codegen/codegen.py`

**Comment by KiChjang** [comment]
@Tycheon claimed in IRC.

**Comment by Tycheon** [comment]
I've been looking over the relevant code (components/script/dom/webidls/XMLHttpRequest.webidl, and components/script/dom/bindings/codegen and the associated commit: https://github.com/servo/servo/commit/d6df844ae532b45905ed616118d0d70903c0b84d )

If I'm reading your issue ( https://github.com/rust-lang/rust/issues/31355 ), and the .webidl correctly, it looks like the issue is that typedef'ing an enum doesn't allow you to access the variants directly (a la typedef::variant ).

Blob and BodyInit seem to just be typedefs for the underlying XMLHttpRequestResponseType enum in XMLHttpRequest.webidl (I'm not sure how to get the python code to build those files so that I can see what the final product looks like), so trying to make another alias to export is just going to give the same issue we have now.

I've been trying to pull this apart to see if there's another way of tackling it, but the only thing I can come up with is to export the underlying enum as BodyInit (ie. use dom::bindings::codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestResponseType as BodyInit). However, that will fail, as the underlying enum is private, so it would need to be marked pub.

Is that the solution being sought here?

**Comment by jdm** [comment]
Yes, that sounds like what we're looking for.

**Comment by Tycheon** [comment]
For all such cases? Or just this specific one? And I'm assuming through the CodeGenRust.py file, and not just a second entry in the .rs file for the blocked PR (xmlhttprequest.rs)?

**Comment by jdm** [comment]
Right, we want this to happen automatically for every union type defined in WebIDL files.

**Comment by jdm** [comment]
This is being solved in #9691.
