### ISSUE TITLE
Extract the document response algorithm out of the XHR Response method

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9553]
And perhaps name the new method `document_response`.

Code: `components/script/dom/xmlhttprequest.rs`
Spec: https://xhr.spec.whatwg.org/#the-response-attribute

**Comment by liviuba** [comment]
Can I give it a try?

**Comment by jdm** [comment]
Please do!

**Comment by jdm** [comment]
@KiChjang Did you have something specific in mind? There already is a `document_response` method, and the code in `Response` that deals with documents is already quite small.

**Comment by KiChjang** [comment]
Yes, @Msger commented on my PR [here](https://github.com/servo/servo/pull/9383#issuecomment-179783236) and he specifically said that he'd like to move the functionality out of the match arm and into a function of its own.

I haven't actually looked into it, but it seems like the current code is wrong as well. We should really NOT be calling `GetResponseXML()` and instead call `document_response`.

**Comment by Ms2ger** [comment]
Looks like we already have a `fn document_response`, but the caching is handled in `fn GetResponseXML`. The thing I'd like to change here is to move the caching into `document_response`, so that it more closely aligns with [the spec](https://xhr.spec.whatwg.org/#document-response). This would allow us to change the call to `GetResponseXML` in `fn Response` to use `document_response` directly, and avoid the error checking.
