### ISSUE TITLE
No load blocker created when iframe.reload() is used

### ISSUE THREAD

**Issue by jdm** [servo/servo#9592]
There's no URL present, so we can't create a load blocker. We should fix this by making sure the iframe is always aware of the url of the currently framed document.
#6677

**Comment by cbrewster** [comment]
@asajeffrey is it possible to do this now? or do we need to manually track the current url?

**Comment by atouchet** [comment]
@gterzian did #23368 address this?

**Comment by gterzian** [comment]
> @gterzian did #23368 address this?

Not that I'm aware of.

Could also relate to https://github.com/servo/servo/issues/23760

**Comment by gterzian** [comment]
Hang-on, somehow it either did or I removed the comment in error at https://github.com/servo/servo/pull/23368/files#diff-498ce74d806ab54484e768d9237a53b1L149

**Comment by gterzian** [comment]
Ok so yes the `LoadData` is not optional anymore, so this is "fixed" https://github.com/servo/servo/pull/23368/files#diff-498ce74d806ab54484e768d9237a53b1R112

So I removed with `Option` around `LoadData`, and that's because it was never called with `None`. So it seems like the comment was invalid, and this issue fixed in an earlier change, since it was about dealing with the now non-existent `None` case. 

Unless I'm missing something...

**Comment by gterzian** [comment]
This was the historical case where `None` was used:

https://github.com/jdm/servo/blob/c5fe8f74010a872e1b0a2f5d7f956c679fc08855/components/script/dom/htmliframeelement.rs#L459

**Comment by jdm** [comment]
As written, the problem described in this issue looks fixed, in that case.
