### ISSUE TITLE
Implement `word-break: keep-all'

### ISSUE THREAD

**Issue by nhirata** [servo/servo#9673]
1.  ./mach run http://people.mozilla.org/~nhirata/html_tp/wordbreak.html
2. adjust the window

- Expected: last line doesn't break
- Actual: last line breaks

**Comment by mbrubeck** [comment]
Spec: https://drafts.csswg.org/css-text-3/#valdef-word-break-keep-all

Relevant code:
* [Fragment::calculate_split_position](https://github.com/servo/servo/blob/e4fe0db8fd5f0b5431ba3856b4931613a96e924e/components/layout/fragment.rs#L1556-L1576)
* [Existing iterators for word and character breaking](https://github.com/servo/servo/blob/e4fe0db8fd5f0b5431ba3856b4931613a96e924e/components/gfx/text/text_run.rs#L61-L179)

Adding support for `keep-all` will require a new iterator that acts like NaturalWordSliceIterator except that sequences of consecutive letters (Unicode general category = Letter or Number) are always joined into a single slice.

**Comment by pierrechevalier83** [comment]
I would be interested to give it a try if no-one is on it (?)

**Comment by KiChjang** [comment]
Certainly! Please find us on `irc.mozilla.org` at `#servo` if you have any questions!

**Comment by pierrechevalier83** [comment]
Hi guys,

It's been almost a week now since I've said I would take this one. I have started looking at it, but it turns out it's not as simple as I thought. I also don't have as much time as I thought I would to spend on this.

If someone else is itching to try this out, please don't let me block you.

**Comment by jdm** [comment]
Ok!

**Comment by g-k** [comment]
shotgun?

**Comment by jdm** [comment]
@g-k Go for it :)

**Comment by g-k** [comment]
I'm getting a 404 from the test page: http://people.mozilla.org/~nhirata/html_tp/wordbreak.html

But it's in the web archive at: https://web.archive.org/web/20150905231452/http://people.mozilla.org/~nhirata/html_tp/wordbreak.html

I started on this branch: https://github.com/servo/servo/compare/master...g-k:word-break-keep-all?expand=1 but still need to finish the iterator.

**Comment by KiChjang** [comment]
@g-k How's this progressing so far?

**Comment by g-k** [comment]
@KiChjang No progress!  I got stuck then distracted and forgot about it.

I think I want the iterator to be something like [this](https://is.gd/vXUyDu) but with ranges over glyphs?  Can I use [is_alphanumeric](https://doc.rust-lang.org/1.0.0/unicode/primitive.char.html#method.is_alphanumeric) on glyphs?

I need to read the code and spec for `NaturalWordSliceIterator` again and look at `range/lib.rs` and `gfx/text/glyph.rs` again.

It'd be nice to finish this myself, but if someone else wants to finish it that'd be fine too.


Also, I thought it was interesting that Gecko and Webkit break on the space after パ but not the [Unicode Character 'IDEOGRAPHIC COMMA' (U+3001)](http://www.fileformat.info/info/unicode/char/3001/index.htm) and Blink does the opposite.  I guess the spec allows for that where it says: "breaks are prohibited between pairs of letters ... except where opportunities exist due to dictionary-based breaking."

FF 47.0.1

<img width="669" alt="screen shot 2016-07-08 at 10 51 14 pm" src="https://cloud.githubusercontent.com/assets/226605/16705667/94dba6d0-455e-11e6-9cdf-7c7eaa164c70.png"> 

Safari 9.1.1 (10601.6.17)

<img width="694" alt="screen shot 2016-07-08 at 11 00 39 pm" src="https://cloud.githubusercontent.com/assets/226605/16705705/dae3826e-455f-11e6-8292-af53ccb9fcd4.png">

Chrome 51.0.2704.106

<img width="848" alt="screen shot 2016-07-08 at 10 54 47 pm" src="https://cloud.githubusercontent.com/assets/226605/16705681/1c436b9e-455f-11e6-9cbd-7d1896d58934.png">

**Comment by emilio** [comment]
@g-k Hi!

So I'm totally not a layout expert here, but it seems that if you need an iterator for alphanumeric glyphs you could do something like what we do to flag glyph entries that are spaces: https://github.com/servo/servo/blob/master/components/gfx/text/glyph.rs#L501. With that, I guess you could do that sort of easily :)

That being said, I don't know how hot is that code, and whether doing that check there is going to affect performance in a significant way. I don't think that its going to be significant, but anyway, I'd say its better to do the easy thing first, and then improve on that.

**Comment by KiChjang** [comment]
@g-k Are you still working on this?

**Comment by g-k** [comment]
No, I haven't looked at it in awhile.  Someone else can pick it up.

**Comment by flacerdk** [comment]
Hi, I would like to give this a try.

**Comment by flacerdk** [comment]
I have been reading the code and I have some ideas on how this could go. But right now I'm a bit confused about how fragments work.

`reflow_fragment` in `layout/inline.rs` tries to push fragments until it runs out of space, then it tries to split the line. However it looks like fragments don't necessarily end on a word boundary (at least for non-ASCII; for ASCII, they always seem to end on words). I don't know if this is the desired behavior, but at any rate, it makes `reflow_fragment` a bit greedy since it just keeps pushing fragments regardless of whether they're words or not. In particular for the Japanese text, it seems to be creating one fragment per glyph.

So there are a few options:

- Coalesce fragments so that they only contain full words (as defined
  [here](http://www.unicode.org/reports/tr29/tr29-9.html#Word_Boundaries)),
  before sending them to `reflow_fragment`. Looks like the cleanest option to
  me, but I don't know if `ScannedText`s are supposed to have this property.
- Write an iterator for splitting fragments that looks into the text already
  pushed by `reflow_fragment` to determine whether it can be split. I assume
  this could be done by looking at the text run, but it could get messy since
  we'd still have to remove some of the text pushed, in case it could not get
  split.
- Keep `reflow_fragment`'s greedy behavior, but then refuse to split words that
  `keep-all` doesn't allow to split. In this case we'd still have to look into
  fragments that were already pushed, but at least we wouldn't have to undo
  anything. Also, this will likely produce a lot of overflow.

Any thoughts?

**Comment by flacerdk** [comment]
I've done a lot more digging and now I have a better idea of what's going on.

Initially I was trying to write a slice iterator whose slices can span more than one glyph run. This was to overcome the fact that text runs contain glyph runs that are produced by `break_and_shape` in `text_run.rs`. This function outputs glyph runs that correspond to _natural words_, which is too liberal for `word-break: keep-all`. (For example, マージャ would be split into two glyph runs マー and ジャ, but UAX#29 doesn't allow a split there).

However, it seems like slices aren't supposed to have more than one glyph run. In particular, the `TextRun` functions for computing metrics and advances (used by `calculate_split_position_using_breaking_strategy` in `fragment.rs`) act on individual glyph runs (or rather, individual glyph stores, which doesn't make the task any easier as far as I can see).

The alternative I found is to build longer glyph runs, dividing them according to UAX#29 instead of natural words. With these, we can even use `NaturalWordSliceIterator` and the rest of the code doesn't change. The drawback is having to carry these longer glyph runs in the `TextRun` struct. They are only to be used with `keep-all`, so this is probably a bit wasteful. I don't know if this is sensible, but it seems to work.

**Comment by jdm** [comment]
I don't know anything about the code or the work involved, and I also can't can't if you have any specific questions yet. If you do, please holler and I'll be sure to poke people who can answer them!
