### ISSUE TITLE
Build script doesn't allow downloading of Rust compiler

### ISSUE THREAD

**Issue by sydbarrett74** [servo/servo#9761]
At the stage in the build script where the Rust compiler should be downloaded, I get this error:
----------------------------------------
Downloading Rust compiler...
Download failed (403): Forbidden - https://static-rust-lang-org.s3.amazonaws.com/dist/2016-02-22/rustc-nightly-x86_64-unknown.tar.gz

**Comment by jdm** [comment]
cc @larsbergstrom

**Comment by Manishearth** [comment]
Could you open a python shell and try

```python
import platform
platform.system().lower()
platform.machine().lower()
```

?

**Comment by sydbarrett74** [comment]
'windows' and 'amd64', respectively

**Comment by larsbergstrom** [comment]
This usually happens when the shell window is not a MINGW64 environment window. You can check by doing `echo $MSYSTEM`, which should say `MINGW64`. We should probably add some hardening to mach for this, but honestly we've been hoping we could just get the build working in more build environments (at least `MSYS`).

**Comment by sydbarrett74** [comment]
I entered the above command and verified that my environment is indeed MINGW64.

**Comment by Jayflux** [comment]
@sydbarrett74  That's odd, this issue got fixed and merged into master from https://github.com/servo/servo/pull/9624

**Comment by sydbarrett74** [comment]
I grabbed the latest nightly build, and no longer have the problem. Closing this bug.

**Comment by larsbergstrom** [comment]
@sydbarrett74 Thanks for following up - much appreciated!
