### ISSUE TITLE
form + HTTP post doesn't work (or at least doesn't redirect)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9829]
Affects: **github.com** (can't log in).

Test case:
```html
<form action="http://localhost:6060/b.html" method="post">
  <input value="click" type="submit">
</form>
```

Clicking on the button should load b.html. It doesn't.

**Comment by paulrouget** [comment]
This prevents logging in Github.

**Comment by paulrouget** [comment]
Using GET instead appears to work.
It also works if I use `file://` instead of `http://`.

**Comment by KiChjang** [comment]
This is because [submit body](https://html.spec.whatwg.org/multipage/forms.html#submit-body) for [planned navigation](https://html.spec.whatwg.org/multipage/forms.html#planned-navigation) hasn't been implemented yet. I think it's dependent on the encoding for multipart/form-data.

@psdh are you currently working on this? Or is it ok for someone else to work on it?

**Comment by KiChjang** [comment]
The relevant PR for encoding is #9198. I can fix the navigation problem after it lands.

**Comment by paulrouget** [comment]
> I can fix the navigation problem after it lands.

That would be great!

**Comment by Manishearth** [comment]
@KiChjang you implemented planned navigation recently. Is this done, or is there still work left?

Also, I guess this bug is why github's comment button doesn't work?

**Comment by jdm** [comment]
See the comment two before yours.

**Comment by pcwalton** [comment]
Suspected to be affecting Twitter login as well.
