### ISSUE TITLE
High CPU usage during a RAF loop

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9844]
Something as simple at that:

```html
<script>
  function foo() {
    requestAnimationFrame(foo);
  }
</script>

<button onclick="foo()">Start rAF</button>
```

… shows a 30% to 50% CPU usage on my macbook.

**Comment by paulrouget** [comment]
This is a lot better since https://github.com/servo/servo/pull/9858

**Comment by paulrouget** [comment]
Still around ~15% here. Compared to Gecko: ~3%.

**Comment by pcwalton** [comment]
Yeah, so this is another case of Servo's design currently making it impossible to catch up to other browsers here. Safari, Gecko, and Chrome all use `CVDisplayLink` instead of actually synchronizing `requestAnimationFrame()` to `CGLFlushDrawable()` calls. We use `CGLFlushDrawable()` with a swap interval of 1, which means we have to actually redraw the picture every frame on the OS main thread and communicate that info to the background threads. All of that adds overhead. The good news is that this is significantly amortized if you're actually drawing something in your `requestAnimationFrame` loop, since the optimization of not drawing the picture only applies if you aren't actually animating anything. :)

**Comment by paulrouget** [comment]
This test shows that there's an actual overhead even when drawing: https://gist.github.com/paulrouget/99442585974f6661b7c5

25% CPU without rAF, 55% CPU with rAF.

**Comment by pcwalton** [comment]
OK, *that* is suspicious. Event handling is expected to be somewhat expensive, but not *that* expensive.

**Comment by pcwalton** [comment]
It is true that we drop a few frames with `setTimeout()`, but not enough that it explains the difference. The profile doesn't look that different either. Strange…

**Comment by paulrouget** [comment]
@pcwalton any idea what's going on here?

**Comment by pcwalton** [comment]
Here's something interesting I found (feel free to confirm, @paulrouget): The CPU usage between rAF and non-rAF seems nearly-identical (about 21%) for me if the window is in the background. But if the window is in the foreground, then the CPU usage of rAF jumps up.

**Comment by paulrouget** [comment]
I can't reproduce. Do you use the test from the first comment? Is anything being drawn in your loop?

**Comment by pcwalton** [comment]
Yes, I'm using the test from the first comment. By not being able to repro, do you mean that the rAF usage is always high and the setTimeout is low, or that both are low?

**Comment by paulrouget** [comment]
I'm using the test from the first comment. With rAF, I get ~20% with window in the background and foreground. With setTimeout instead, I get around ~5% with window in the background and foreground.

**Comment by pcwalton** [comment]
Interesting. I get 20% for both rAF and setTimeout with the window in the background.

**Comment by paulrouget** [comment]
This is the code I use for `setTimeout`:

```html
<script>
  var x = 0;
  window.requestAnimationFrame = c => setTimeout(c, 16);
  setInterval(() => {
    console.log(x);
    x = 0;
  }, 1000);
  function foo() {
    x++;
    requestAnimationFrame(foo);
  }
</script>

<button onclick="foo()">Start rAF</button>
```

**Comment by pcwalton** [comment]
So this is at least part of it: When using setTimeout(), we get 53 FPS. When using rAF, we get 60 FPS. More FPS == more frames painted == more CPU.

**Comment by pcwalton** [comment]
BTW, some of the difference between Gecko is probably that we do invalidation in Gecko but don't in Servo. I'd like to hold off on implementing invalidation just for this though…

**Comment by pcwalton** [comment]
@paulrouget Can you try this patch? It reduces the amount of CompositorProxy traffic and wakeups and seems to improve things for me. https://gist.github.com/pcwalton/b8e36e05101fe049d610d55943664eef

**Comment by paulrouget** [comment]
With this patch, rAF is called once and then is never called again.

**Comment by tschneidereit** [comment]
I'm seeing 27% with `setTimeout` and 31% with `rAF` with @paulrouget's current Homebrew servo distribution. That seems perfectly in line with the difference in FPS that @pcwalton (and that I'm seeing, too.)

@paulrouget, your 5% CPU usage when using `setTimeout` seems suspiciously low. What kinds of results do you see when you pass `-w -Z wr-stats`?

**Comment by tschneidereit** [comment]
Tested on my 2015 Macbook, too, with different results: using `setTimeout` I get the same 27% CPU usage as on my 2012 Macbook Pro (which is somewhat surprising given that the latter's CPU should be quite a bit more powerful.) Using `rAF`, though, I get 54% CPU usage, so pretty exactly twice as much. And that's with roughly the same FPS.

**Comment by paulrouget** [comment]
Describing my protocol:

- this code: https://github.com/servo/servo/issues/9844#issuecomment-207078279
- latest master with `-w -b` *without* `-Z wr-stats` (does that actually take CPU to draw?)
- keep window in foreground
- activity monitor in background

Results my macbook 2015:
- with rAF, ~11% CPU, 60 FPS
- without, ~3% CPU, ~54 FPS

**Comment by tschneidereit** [comment]
> Results with my macbook 2015:
> 
>     with rAF, ~11% CPU, 60 FPS
>     without, ~3% CPU, ~54 FPS

Ok, when actually testing the right code (I was testing with [this](https://gist.github.com/paulrouget/99442585974f6661b7c5)), I see roughly the same result. Only difference is that with rAF I have 14%-16% CPU usage.

**Comment by nox** [comment]
@paulrouget That doesn't seem to be true anymore since #11205.

**Comment by paulrouget** [comment]
@nox: https://github.com/servo/servo/issues/11260

**Comment by nox** [comment]
Just want to make sure, you are using latest master right?

**Comment by paulrouget** [comment]
> Just want to make sure, you are using latest master right?

Yes.

**Comment by paulrouget** [comment]
So now that https://github.com/servo/servo/issues/11260 appears to not be a problem anymore, here are the latest results on my macbook:

* with rAF, ~8.5% CPU, 60 FPS
* without, ~2% CPU, ~54 FPS

**Comment by nox** [comment]
@paulrouget Should we consider it fixed?

**Comment by paulrouget** [comment]
> @paulrouget Should we consider it fixed?

Good enough to run browserhtml. Divided by 2 the initial overhead.

I still don't understand why it takes more CPU than `setTimeout(16)`.

**Comment by nox** [comment]
@paulrouget @pcwalton says that's the necessary cost to vsync.

**Comment by pcwalton** [comment]
@paulrouget I'll explain the issue. `setTimeout(16)` does not have to sync to the [vertical blanking interval](https://en.wikipedia.org/wiki/Vertical_blanking_interval) (VBLANK) of the display. However, `requestAnimationFrame()` does—or, at least, it should, as that is its intended use.

The ways to do that are limited. On the Mac and iOS, Apple recommends a class called [CVDisplayLink](https://developer.apple.com/library/mac/documentation/QuartzCore/Reference/CVDisplayLinkRef/). This is what Safari and Firefox use. When I used it, however, I got tearing if the swap interval was not set to 1, which is unexpected. Investigating further, I found that CVDisplayLink simply queries the refresh rate of the screen and sets up a timer for that interval—effectively, it just does a glorified `setTimeout(16)`. This is not adequate: the exact moment of VBLANK is what we care about, not simply the interval.

The other, cross-platform method is through [glXSwapBuffers](https://www.opengl.org/sdk/docs/man2/xhtml/glXSwapBuffers.xml) on X11 and [CGLFlushDrawable](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGL_OpenGL/#//apple_ref/c/func/CGLFlushDrawable) on the Mac, with the *swap interval* set to 1. The swap interval can be configured with [glXSwapIntervalEXT](https://www.opengl.org/registry/specs/EXT/swap_control.txt) on X11 and [kCGLPFASwapInterval](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGL_OpenGL/#//apple_ref/c/tdef/CGLContextParameter) on the Mac. This causes glXSwapBuffers/CGLFlushDrawable to finish rendering, block until the next VBLANK, swap, and then return. This is the most reliable way to actually get the correct VBLANK timing—it has to be, or else tearing would occur. So this is the method we use.

Now note that glXSwapBuffers/CGLFlushDrawable do *two* things: they swap the front and back buffer, *and* they block until the next VBLANK. In the case in which there is no rendering to be done, this is a waste: we don't want to swap buffers, but we do want to block until the nearest VBLANK. However, the API fuses both operations. So we actually have to paint the frame and perform the buffer swap. This uses a significant amount of CPU and GPU time, both in preparing the rendering commands and in the driver.

As mentioned before, Safari and Firefox dodge this by using CVDisplayLink on the Mac, which only performs VBLANK notifications, which is why you see them use less CPU in this test case. But those VBLANK notifications are not as accurate as the ones we get from swapping buffers, at least according to my investigation. So there's a tradeoff: more CPU usage (though note that there's using not much if any more CPU in the case of actual rendering) versus more accurate timing. I made the latter choice.
