### ISSUE TITLE
CSS: parse_non_custom_with_var does not consume leading whitespace

### ISSUE THREAD

**Issue by craftytrickster** [servo/servo#9978]
A css property may look like the following:
`color: green; display: inline;`

When the css parser parses the above statement, it understands the the color is "green" not " green" with a leading space. However, when dealing with var properties, such as `display: var(--a) 1px;`, it does not understand that the leading space should be ignored. This appears to be causing the test failures on https://github.com/servo/servo/pull/9410.

**Comment by SimonSapin** [comment]
What’s going on is that most properties are parsed into abstract data structures. For example colors are (R, G, B, A) tuples of floating point numbers, and `display` is an enum with one variant for each keyword. Whitespace is irrelevant there, and serialization adds one after `:` after the property name because it looks nice.

When a value contains `var(--a)` however, it is left "unparsed", with whitespace as-is, until the value of `--a` can be known. I’m not convinced leading whitespace should be trimmed there, since per the [css-variables](https://drafts.csswg.org/css-variables/) spec it’s kinda part of the value. Instead, serialization can opt to only add a space after `:` for other values. See my comment in https://github.com/servo/servo/pull/9410#issuecomment-199929959
